import { createClient } from 'npm:@supabase/supabase-js@2.115.0'

const SUPABASE_URL=Deno.env.get('SUPABASE_URL')!
const ANON_KEY=Deno.env.get('SUPABASE_ANON_KEY')!
const SERVICE_KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
const SLUG='cozinha360-pagbank-payments-v60'
const VERSION='6.0.0'
const PROVIDER='pagbank'
const anon=createClient(SUPABASE_URL,ANON_KEY,{auth:{persistSession:false,autoRefreshToken:false}})
const admin=createClient(SUPABASE_URL,SERVICE_KEY,{auth:{persistSession:false,autoRefreshToken:false}})
const enc=new TextEncoder(),dec=new TextDecoder()
const now=()=>new Date().toISOString()
const env=(name:string)=>(Deno.env.get(name)||'').trim()
const clean=(value:unknown,max=500)=>String(value??'').trim().slice(0,max)
const environment=()=>env('PAGBANK_ENV').toLowerCase()==='sandbox'?'sandbox':'production'
const apiBase=()=>environment()==='sandbox'?'https://sandbox.api.pagseguro.com':'https://api.pagseguro.com'
const configured=()=>Boolean(env('PAGBANK_APP_TOKEN')&&env('PAGBANK_CLIENT_ID')&&env('PAGBANK_CLIENT_SECRET'))
const homologated=()=>environment()==='sandbox'||env('PAGBANK_HOMOLOGATED').toLowerCase()==='true'
const platformReady=()=>configured()&&homologated()

function routePath(req:Request){const p=new URL(req.url).pathname,m=`/${SLUG}`,i=p.indexOf(m);return i>=0?(p.slice(i+m.length)||'/'):p}
function cors(req:Request){const origin=req.headers.get('origin')||'',allowed=/^https:\/\/([a-z0-9-]+\.)?(cozinha-360-os\.netlify\.app|onrender\.com)$/i.test(origin)||/^http:\/\/(localhost|127\.0\.0\.1):\d+$/i.test(origin);return{'Access-Control-Allow-Origin':allowed?origin:'https://cozinha-360-os.netlify.app','Access-Control-Allow-Headers':'authorization, apikey, content-type, x-client-info','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Max-Age':'86400','Vary':'Origin','Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}}
const j=(req:Request,data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:cors(req)})
const fail=(req:Request,detail:string,status=400,extra:Record<string,unknown>={})=>j(req,{detail,...extra},status)
const parse=async(req:Request)=>{try{return await req.json()}catch{return{}}}
function b64(bytes:Uint8Array){let raw='';for(const b of bytes)raw+=String.fromCharCode(b);return btoa(raw).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function unb64(value:string){let v=value.replace(/-/g,'+').replace(/_/g,'/');while(v.length%4)v+='=';return Uint8Array.from(atob(v),c=>c.charCodeAt(0))}
async function rootBytes(){const seed=env('C360_INTEGRATION_KEY')||`${SERVICE_KEY}:c360-integrations-v29`;return new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(seed)))}
async function aesKey(){return crypto.subtle.importKey('raw',await rootBytes(),{name:'AES-GCM'},false,['encrypt','decrypt'])}
async function seal(value:unknown){const iv=crypto.getRandomValues(new Uint8Array(12)),ct=await crypto.subtle.encrypt({name:'AES-GCM',iv},await aesKey(),enc.encode(JSON.stringify(value)));return{ciphertext:b64(new Uint8Array(ct)),iv:b64(iv)}}
async function openSecret(row:any){const pt=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(row.iv)},await aesKey(),unb64(row.ciphertext));return JSON.parse(dec.decode(pt))}

async function auth(req:Request){const h=req.headers.get('authorization')||'',token=h.startsWith('Bearer ')?h.slice(7):'';if(!token)return null;if(token===SERVICE_KEY)return{service:true,id:0};const{data,error}=await anon.auth.getUser(token);if(error||!data.user)return null;let p=(await admin.from('users').select('id,email,full_name').eq('auth_user_id',data.user.id).maybeSingle()).data;if(!p&&data.user.email)p=(await admin.from('users').select('id,email,full_name').ilike('email',data.user.email).maybeSingle()).data;return p||null}
async function member(userId:number,businessId:number){const r=await admin.from('memberships').select('role').eq('user_id',userId).eq('business_id',businessId).maybeSingle();return r.data||null}
async function authorize(req:Request,businessId:number){const who:any=await auth(req);if(!who)return null;if(who.service)return who;if(!await member(Number(who.id),businessId))return null;return who}

async function connection(businessId:number){const r=await admin.from('integration_connections').select('*').eq('business_id',businessId).eq('provider',PROVIDER).eq('status','active').order('id',{ascending:true}).limit(1).maybeSingle();if(r.error)throw r.error;return r.data}
async function credential(connectionId:number){const r=await admin.from('integration_credentials').select('*').eq('connection_id',connectionId).eq('provider',PROVIDER).maybeSingle();if(r.error)throw r.error;if(!r.data)return null;return{row:r.data,secret:await openSecret(r.data),metadata:typeof r.data.metadata_json==='string'?JSON.parse(r.data.metadata_json||'{}'):r.data.metadata_json||{},scopes:typeof r.data.scopes_json==='string'?JSON.parse(r.data.scopes_json||'[]'):r.data.scopes_json||[]}}
function platformHeaders(extra:Record<string,string>={}){return{accept:'application/json',authorization:`Bearer ${env('PAGBANK_APP_TOKEN')}`,'x-client-id':env('PAGBANK_CLIENT_ID'),'x-client-secret':env('PAGBANK_CLIENT_SECRET'),...extra}}
function sellerHeaders(accessToken:string,extra:Record<string,string>={}){return{accept:'application/json',authorization:`Bearer ${env('PAGBANK_APP_TOKEN')}`,'x-client-token':accessToken,...extra}}
async function jsonApi(url:string,init:RequestInit,label:string){const r=await fetch(url,init),x=await r.json().catch(()=>({}));if(!r.ok){const message=clean(x?.error_messages?.[0]?.description||x?.message||x?.error_description||x?.error?.message||x?.error||`${label} recusou a solicitação`,800);const e:any=new Error(message);e.status=r.status;e.body=x;throw e}return x}
async function refresh(secret:any){if(!secret.refresh_token)throw new Error('PagBank exige nova autorização');return jsonApi(`${apiBase()}/oauth2/refresh`,{method:'POST',headers:platformHeaders({'content-type':'application/json'}),body:JSON.stringify({grant_type:'refresh_token',refresh_token:secret.refresh_token})},'PagBank refresh')}
const expiry=(secret:any)=>Number(secret.expires_in||0)?new Date(Date.now()+Number(secret.expires_in)*1000).toISOString():null
async function saveFresh(current:any,next:any){const encrypted=await seal(next),expiresAt=expiry(next),updatedAt=now(),r=await admin.from('integration_credentials').update({ciphertext:encrypted.ciphertext,iv:encrypted.iv,expires_at:expiresAt,metadata_json:JSON.stringify({...current.metadata,refreshed_at:updatedAt}),updated_at:updatedAt}).eq('connection_id',current.row.connection_id).eq('updated_at',current.row.updated_at).select('*').maybeSingle();if(r.error)throw r.error;if(r.data)return{row:r.data,secret:next,metadata:{...current.metadata,refreshed_at:updatedAt},scopes:current.scopes};return credential(current.row.connection_id)}
async function fresh(conn:any,current:any){const exp=current.row.expires_at?Date.parse(current.row.expires_at):0;if(!exp||exp>Date.now()+300000)return current;try{const next=await refresh(current.secret),saved=await saveFresh(current,next);if(saved)return saved}catch(error){const latest=await credential(conn.id),latestExp=latest?.row.expires_at?Date.parse(latest.row.expires_at):0;if(latest&&(!latestExp||latestExp>Date.now()+300000))return latest;throw error}throw new Error('Não foi possível renovar a autorização PagBank')}
async function sellerContext(businessId:number){if(!platformReady())throw Object.assign(new Error('PagBank ainda aguarda configuração ou homologação da plataforma.'),{code:'platform_setup_required'});const conn=await connection(businessId);if(!conn)throw Object.assign(new Error('Conecte sua conta PagBank antes de gerar o Pix.'),{code:'connection_required'});let current=await credential(conn.id);if(!current)throw Object.assign(new Error('A autorização PagBank precisa ser refeita.'),{code:'credential_missing'});current=await fresh(conn,current);if(!current?.secret?.access_token)throw Object.assign(new Error('A autorização PagBank precisa ser refeita.'),{code:'credential_missing'});return{conn,current,accessToken:String(current.secret.access_token)}}

function digits(value:unknown){return String(value??'').replace(/\D/g,'')}
function validTaxId(value:string){return value.length===11||value.length===14}
function validEmail(value:string){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value)}
function phoneNode(value:unknown){const d=digits(value);if(d.length===11&&d.slice(2,3)==='9')return[{country:'55',area:d.slice(0,2),number:d.slice(2),type:'MOBILE'}];return undefined}
function safeIntent(row:any){return{token:row.public_token,provider:PROVIDER,status:row.status,status_detail:row.status_detail,paid:row.status==='processed',amount_cents:Number(row.amount_cents),qr_code:row.status==='processed'?null:row.qr_code,qr_code_base64:row.status==='processed'?null:row.qr_code_base64,ticket_url:row.status==='processed'?null:row.ticket_url,expires_at:row.expires_at,updated_at:row.updated_at}}
function mappedStatus(remote:string){const s=String(remote||'').toUpperCase();if(s==='PAID')return'processed';if(['DECLINED','DENIED'].includes(s))return'failed';if(['CANCELED','CANCELLED'].includes(s))return'canceled';if(s==='EXPIRED')return'expired';if(['REFUNDED','REFUND'].includes(s))return'refunded';if(['CHARGED_BACK','CHARGEBACK'].includes(s))return'charged_back';if(['WAITING','IN_ANALYSIS','AUTHORIZED','PROCESSING'].includes(s))return'processing';return'processing'}
function firstCharge(remote:any){return Array.isArray(remote?.charges)?remote.charges[0]||null:null}
function chargeLink(charge:any,rel:string){return clean((charge?.links||[]).find((x:any)=>String(x?.rel||'').toUpperCase()===rel)?.href,1000)||null}
function trustedQrUrl(value:string|null){if(!value)return null;try{const u=new URL(value),allowed=environment()==='sandbox'?'sandbox.api.pagseguro.com':'api.pagseguro.com';return u.protocol==='https:'&&u.hostname===allowed?u.toString():null}catch{return null}}
async function qrBase64(charge:any,accessToken:string){const url=trustedQrUrl(chargeLink(charge,'QRCODE.BASE64'));if(!url)return null;try{const r=await fetch(url,{headers:sellerHeaders(accessToken,{accept:'text/plain'})});if(!r.ok)return null;const value=(await r.text()).trim();return value.length<2_000_000?value:null}catch{return null}}

async function syncRemote(intent:any,ctx:any,remote:any){if(clean(remote?.reference_id,120)!==String(intent.external_reference))throw new Error('Referência PagBank não corresponde à cobrança local');const charge=firstCharge(remote),remoteAmount=Number(charge?.amount?.value||0);if(remoteAmount&&remoteAmount!==Number(intent.amount_cents))throw new Error('Valor PagBank diverge do pedido local');const status=mappedStatus(charge?.status),detail=clean(charge?.status,80)||null,paid=status==='processed',qr=clean(charge?.qr_code?.text,5000)||null,png=trustedQrUrl(chargeLink(charge,'QRCODE.PNG')),base64=paid?null:await qrBase64(charge,ctx.accessToken),patch={external_order_id:clean(remote?.id,180)||intent.external_order_id,status,status_detail:detail,qr_code:paid?null:qr,qr_code_base64:paid?null:(base64||intent.qr_code_base64||null),ticket_url:paid?null:(png||intent.ticket_url||null),last_event_at:now(),last_error:null,updated_at:now()};const u=await admin.from('payment_intents').update(patch).eq('id',intent.id).select('*').single();if(u.error)throw u.error;const ou=await admin.from('orders').update({paid,updated_at:now(),...(paid?{error_flag:false}:{})}).eq('id',intent.order_id).eq('business_id',intent.business_id);if(ou.error)throw ou.error;await admin.from('integration_connections').update({last_success_at:now(),last_error:null,updated_at:now()}).eq('id',ctx.conn.id);return u.data}
async function remoteOrder(ctx:any,orderId:string){return jsonApi(`${apiBase()}/orders/${encodeURIComponent(orderId)}`,{headers:sellerHeaders(ctx.accessToken)},'PagBank Order')}

async function createPix(req:Request,businessId:number,orderId:number){if(!await authorize(req,businessId))return fail(req,'Sem acesso',401);const body:any=await parse(req),taxId=digits(body.payer_tax_id);if(!validTaxId(taxId))return fail(req,'Informe um CPF ou CNPJ válido para gerar o Pix.',422,{code:'payer_tax_id_required'});const orderR=await admin.from('orders').select('id,business_id,customer_id,total_cents,paid,status').eq('id',orderId).eq('business_id',businessId).maybeSingle();if(orderR.error)throw orderR.error;const order=orderR.data;if(!order)return fail(req,'Pedido não encontrado',404);if(Number(order.total_cents)<=0)return fail(req,'Pedido sem valor para cobrança',409);let customer:any=null;if(order.customer_id){const c=await admin.from('customers').select('name,email,phone').eq('id',order.customer_id).eq('business_id',businessId).maybeSingle();if(c.error)throw c.error;customer=c.data}const payerName=clean(body.payer_name||customer?.name,120),payerEmail=clean(body.payer_email||customer?.email,120).toLowerCase();if(payerName.length<2)return fail(req,'Informe o nome do pagador.',422,{code:'payer_name_required'});if(!validEmail(payerEmail))return fail(req,'Informe um e-mail válido para gerar o Pix.',422,{code:'payer_email_required'});let ctx:any;try{ctx=await sellerContext(businessId)}catch(e:any){return fail(req,clean(e?.message,500),409,{code:e?.code||'connection_error'})}
 let intentR=await admin.from('payment_intents').select('*').eq('business_id',businessId).eq('order_id',orderId).eq('provider',PROVIDER).eq('method','pix').maybeSingle();if(intentR.error)throw intentR.error;let intent=intentR.data
 if(intent?.external_order_id){try{const remote=await remoteOrder(ctx,String(intent.external_order_id)),synced=await syncRemote(intent,ctx,remote);if(['processing','processed','action_required','created'].includes(String(synced.status)))return j(req,{ok:true,reused:true,payment:safeIntent(synced)})}catch(e){await admin.from('payment_intents').update({last_error:clean((e as any)?.message,800),updated_at:now()}).eq('id',intent.id)}}
 if(intent&&['failed','canceled','expired','refunded','charged_back'].includes(String(intent.status))){const reset=await admin.from('payment_intents').update({idempotency_key:crypto.randomUUID(),external_order_id:null,status:'created',status_detail:null,qr_code:null,qr_code_base64:null,ticket_url:null,expires_at:null,last_error:null,updated_at:now()}).eq('id',intent.id).select('*').single();if(reset.error)throw reset.error;intent=reset.data}
 if(!intent){const externalReference=`c360-pb:${businessId}:${orderId}`,ins=await admin.from('payment_intents').insert({business_id:businessId,order_id:orderId,connection_id:ctx.conn.id,provider:PROVIDER,method:'pix',external_reference:externalReference,amount_cents:Number(order.total_cents)}).select('*').single();if(ins.error)throw ins.error;intent=ins.data}
 const expiresAt=new Date(Date.now()+30*60_000).toISOString(),phones=phoneNode(customer?.phone),payload:any={reference_id:intent.external_reference,customer:{name:payerName,email:payerEmail,tax_id:taxId,...(phones?{phones}:{})},items:[{reference_id:`order-${orderId}`,name:`Pedido Cozinha 360 #${orderId}`,quantity:1,unit_amount:Number(order.total_cents)}],charges:[{reference_id:`charge-${intent.id}`,description:`Pedido Cozinha 360 #${orderId}`,amount:{value:Number(order.total_cents),currency:'BRL'},payment_method:{type:'PIX',pix:{expiration_date:expiresAt}}}]}
 try{const remote=await jsonApi(`${apiBase()}/orders`,{method:'POST',headers:sellerHeaders(ctx.accessToken,{'content-type':'application/json','x-idempotency-key':String(intent.idempotency_key).replace(/-/g,'')}),body:JSON.stringify(payload)},'PagBank Pix'),synced=await syncRemote({...intent,expires_at:expiresAt},ctx,remote),u=await admin.from('payment_intents').update({expires_at:expiresAt}).eq('id',intent.id).select('*').single();if(u.error)throw u.error;return j(req,{ok:true,reused:false,payment:safeIntent({...synced,expires_at:expiresAt})},201)}catch(e:any){const message=clean(e?.message||e,800);await admin.from('payment_intents').update({last_error:message,updated_at:now()}).eq('id',intent.id);await admin.from('integration_connections').update({last_error:message,last_error_at:now(),updated_at:now()}).eq('id',ctx.conn.id);return fail(req,message,e?.status&&e.status<500?422:502,{code:'pagbank_rejected'})}}

async function syncIntent(req:Request,intent:any,allowPublic=false){let ctx:any;try{ctx=await sellerContext(Number(intent.business_id))}catch(e:any){if(allowPublic)return j(req,{ok:true,payment:safeIntent(intent),sync:'temporarily_unavailable'});throw e}if(!intent.external_order_id||['processed','failed','canceled','expired','refunded','charged_back'].includes(String(intent.status)))return j(req,{ok:true,payment:safeIntent(intent)});try{const remote=await remoteOrder(ctx,String(intent.external_order_id)),synced=await syncRemote(intent,ctx,remote);return j(req,{ok:true,payment:safeIntent(synced),sync:'remote'})}catch(e:any){await admin.from('payment_intents').update({last_error:clean(e?.message,800),updated_at:now()}).eq('id',intent.id);if(allowPublic)return j(req,{ok:true,payment:safeIntent(intent),sync:'last_known'});throw e}}
async function syncByOrder(req:Request,businessId:number,orderId:number){if(!await authorize(req,businessId))return fail(req,'Sem acesso',401);const r=await admin.from('payment_intents').select('*').eq('business_id',businessId).eq('order_id',orderId).eq('provider',PROVIDER).eq('method','pix').maybeSingle();if(r.error)throw r.error;if(!r.data)return fail(req,'Cobrança não encontrada',404);return syncIntent(req,r.data)}
async function publicStatus(req:Request,token:string){const r=await admin.from('payment_intents').select('*').eq('public_token',token).eq('provider',PROVIDER).eq('method','pix').maybeSingle();if(r.error)throw r.error;if(!r.data)return fail(req,'Cobrança não encontrada',404);return syncIntent(req,r.data,true)}

Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(req)});const path=routePath(req);try{if(req.method==='GET'&&path==='/health')return j(req,{ok:true,service:SLUG,version:VERSION,provider:PROVIDER,environment:environment(),platform_ready:platformReady(),capabilities:{pix_create:true,pix_status:true,remote_reconciliation:true,webhook:false},privacy:{payer_tax_id:'transient_not_stored'}});let m=path.match(/^\/businesses\/(\d+)\/orders\/(\d+)\/pix$/);if(req.method==='POST'&&m)return await createPix(req,Number(m[1]),Number(m[2]));m=path.match(/^\/businesses\/(\d+)\/orders\/(\d+)\/pix\/sync$/);if(req.method==='POST'&&m)return await syncByOrder(req,Number(m[1]),Number(m[2]));m=path.match(/^\/pix\/([0-9a-f-]{36})$/i);if(req.method==='GET'&&m)return await publicStatus(req,m[1]);return fail(req,'Rota não encontrada',404)}catch(e){return fail(req,clean((e as any)?.message||e,800),500)}})
