import React, { useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Activity, ArrowRight, BadgeCheck, BarChart3, CheckCircle2, CircleAlert, Database, Gauge, Globe2, Radar, ShieldCheck, Sparkles, TriangleAlert, Zap } from 'lucide-react';
import './ranking-site-v2.css';

const API='https://npgheuzpnkwtxopswpqy.supabase.co/functions/v1/sac-ranking-site-api';
async function api(body){const r=await fetch(API,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data?.error||`HTTP ${r.status}`);return data;}
const n=v=>Number(v||0);const fmt=v=>new Intl.NumberFormat('pt-BR',{maximumFractionDigits:1}).format(n(v));const pct=v=>`${Math.max(0,Math.min(100,n(v))).toFixed(n(v)>=10?0:1)}%`;
const humanStatus=s=>({queued:'Na fila',processing:'Analisando',completed:'Concluído',failed:'Falhou'})[s]||s||'Preparando';
const tone=s=>['pass','healthy','completed'].includes(s)?'good':['fail','critical','failed'].includes(s)?'bad':['warning','attention','insufficient_coverage'].includes(s)?'warn':'neutral';
function Mini({label,value,note}){return <div className="rv-mini"><span>{label}</span><strong>{value}</strong>{note&&<small>{note}</small>}</div>}
function App(){
 const query=new URLSearchParams(location.search), initial=query.get('scan')||'';
 const [url,setUrl]=useState('');const [token,setToken]=useState(initial);const [busy,setBusy]=useState(Boolean(initial));const [result,setResult]=useState(null);const [error,setError]=useState('');const timer=useRef(null);
 const evidence=result?.evidence_dashboard||{};const caps=evidence?.metric_capabilities||{};const cov=evidence?.metric_coverage||{};const layers=Array.isArray(evidence?.conversion_layers)?evidence.conversion_layers:[];const priorities=Array.isArray(result?.priority_actions)?result.priority_actions:[];const bench=result?.benchmark_comparison||evidence?.benchmark_comparison||{};const benchRows=Array.isArray(bench?.comparison)?bench.comparison:[];const active=n(caps?.autonomous_implemented), observed=n(cov?.observed_distinct);const operationalCoverage=active?Math.min(100,(observed/active)*100):0;
 const score=useMemo(()=>{if(result?.preview_score!=null)return {label:'Score preliminar',value:Math.round(n(result.preview_score))};if(layers.length){const a=layers.map(x=>n(x.evidence_readiness)).filter(Number.isFinite);if(a.length)return{label:'Cobertura de evidência',value:Math.round((a.reduce((x,y)=>x+y,0)/a.length)*100)}}return{label:'Cobertura operacional',value:Math.round(operationalCoverage)}},[result,layers,operationalCoverage]);
 async function poll(t){try{const d=await api({action:'status',token:t});const r=d?.result||null;setResult(r);setError('');if(r?.status==='completed'||r?.status==='failed'){setBusy(false);return}timer.current=setTimeout(()=>poll(t),2400)}catch(e){setError('Falha ao consultar a análise.');setBusy(false)}}
 useEffect(()=>{document.title='Ranking Site · Plutyx SAC';if(initial)poll(initial);return()=>timer.current&&clearTimeout(timer.current)},[]);
 async function start(e){e.preventDefault();setError('');setResult(null);setBusy(true);try{const d=await api({action:'start',url});if(!d?.token)throw new Error('scan_token_missing');setToken(d.token);history.replaceState(null,'',`${location.pathname}?scan=${encodeURIComponent(d.token)}`);poll(d.token)}catch(e){setBusy(false);const m={invalid_url:'Digite uma URL válida.',daily_preview_limit:'O limite diário desta conexão foi atingido.',scanner_busy:'Os coletores estão ocupados neste instante.'};setError(m[e.message]||'Não foi possível iniciar a análise agora.')}}
 const status=result?.status||(busy?'processing':'');const limited=result?.error_code==='access_limited'||result?.access?.limited===true;
 return <main className="rv-page"><div className="rv-glow a"/><div className="rv-glow b"/>
  <header className="rv-header"><a href="https://plutyx.com" className="rv-logo"><div><Gauge size={18}/></div><span><b>PLUTYX</b><small>SAC · Site Intelligence</small></span></a><div className="rv-health"><i/>autonomous collectors online</div></header>
  <section className="rv-hero"><div className="rv-eyebrow"><Radar size={13}/> AUDITORIA AUTÔNOMA POR EVIDÊNCIA</div><h1>Uma URL entra.<br/><em>O site vira dados.</em></h1><p>Performance, SEO, acessibilidade, segurança, arquitetura, UX, CRO e sinais técnicos coletados pelo próprio SAC. O que não pode ser medido de forma real não entra como aprovação.</p>
   <form className="rv-search" onSubmit={start}><div><Globe2 size={18}/><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="seusite.com.br" aria-label="URL do site"/></div><button disabled={busy||!url.trim()}>{busy?<><Activity size={16}/> Analisando</>:<>Analisar site <ArrowRight size={16}/></>}</button></form>
   <div className="rv-chips"><span>HTTP + DOM</span><span>Chromium</span><span>PageSpeed + CrUX</span><span>WCAG</span><span>Security</span><span>Benchmark próprio</span></div>{error&&<div className="rv-error"><TriangleAlert size={15}/>{error}</div>}
  </section>
  {(busy||result)&&<section className="rv-console"><div className="rv-console-head"><div><span className={`rv-status ${tone(status)}`}><i/>{humanStatus(status)}</span><h2>{result?.url||url||'Preparando domínio'}</h2></div>{token&&<code>{token.slice(0,8)}…</code>}</div><div className="rv-flow">{['Descoberta','HTTP / DOM','Performance','Browser / WCAG','Evidência / Benchmark'].map((x,i)=><div className={result?.status==='completed'||i<(busy?2:5)?'on':''} key={x}><b>{String(i+1).padStart(2,'0')}</b><span>{x}</span></div>)}</div>{busy&&!result?.evidence_dashboard&&<div className="rv-scan"><i/></div>}{limited&&<div className="rv-note"><ShieldCheck size={16}/>O origin limitou coleta direta. Páginas de desafio não recebem nota como se fossem o site; qualquer fallback permanece identificado pela fonte.</div>}</section>}
  {result?.status==='completed'&&<>
   <section className="rv-overview"><div className="rv-score"><div className="rv-ring" style={{'--fill':`${score.value*3.6}deg`}}><div><strong>{score.value}</strong><span>/100</span></div></div><div><span>{score.label}</span><h2>{result?.official_score?'Score oficial':'Leitura condicionada à evidência'}</h2><p>Sem evidência suficiente, o SAC mantém a camada sem nota. Ausência nunca vira “pass”.</p></div></div><div className="rv-kpis"><Mini label="Coletores autônomos" value={active||'—'} note="ativos no motor"/><Mini label="Métricas observadas" value={observed||'—'} note="neste scan"/><Mini label="Checks aprovados" value={evidence?.atomic_status?.pass??'—'}/><Mini label="Falhas reais" value={evidence?.atomic_status?.fail??'—'}/></div></section>
   <section className="rv-section"><Title icon={Zap} eyebrow="N0 → N∞" title="Camadas de conversão" text="Cobertura mínima antes de qualquer nota."/><div className="rv-layers">{layers.map(l=>{const ready=n(l.evidence_readiness)*100;return <article key={l.layer_code}><div className="rv-layer-top"><b>{l.layer_code}</b><span className={tone(l.status)}>{l.score_10!=null?`${fmt(l.score_10)}/10`:l.status==='pending_evidence'?'evidência pendente':'cobertura insuficiente'}</span></div><h3>{l.label}</h3><p>{l.description}</p><div className="rv-bar"><i style={{width:pct(ready)}}/></div><small>{pct(ready)} · {l.checks?.verified||0} verificações comprovadas</small></article>})}</div></section>
   {priorities.length>0&&<section className="rv-section"><Title icon={CircleAlert} eyebrow="PRIORIDADE AUTOMÁTICA" title="Corrija primeiro o que tem maior evidência" text="Severidade × impacto × confiança; esforço não é inventado sem conhecer a stack."/><div className="rv-actions">{priorities.slice(0,8).map((a,i)=><article key={`${a.check_code}-${i}`}><div className="rv-rank">{String(i+1).padStart(2,'0')}</div><div className="rv-action-copy"><div><span className={`rv-pill ${tone(a.status)}`}>{a.status}</span><span>{a.engine}</span></div><h3>{a.title}</h3><p>{a.explanation||a.recommendation||'Evidência técnica observada.'}</p><small>Confiança {pct(n(a.confidence)*100)} · fonte {a.evidence_tier||a.source_kind||'observada'}</small></div><strong>{fmt(a.evidence_priority)}</strong></article>)}</div></section>}
   {benchRows.length>0&&<section className="rv-section"><Title icon={BarChart3} eyebrow="BENCHMARK PRÓPRIO" title="Seu site contra o corpus técnico" text="Prevalência técnica comparável; não é previsão de venda ou ranking."/><div className="rv-benchmark">{benchRows.slice(0,12).map(b=><div className="rv-bench" key={b.metric}><div><strong>{String(b.metric).replaceAll('_',' ')}</strong><span>{fmt(b.site_percent)}% no site</span></div><div className="rv-dual"><i style={{width:pct(b.benchmark_percent)}}/><b style={{width:pct(b.site_percent)}}/></div><em className={n(b.delta_pp)>=0?'good':'bad'}>{n(b.delta_pp)>=0?'+':''}{fmt(b.delta_pp)} p.p.</em></div>)}</div></section>}
   <section className="rv-section"><Title icon={Database} eyebrow="EVIDENCE OS" title="O que foi realmente coletado" text="A página pública mostra somente observações que chegaram de um coletor ou dataset identificado."/><div className="rv-evidence">{Object.entries(cov?.by_evidence_class||{}).map(([k,v])=><div key={k}><span>{k.replaceAll('_',' ')}</span><strong>{v?.observed||0}</strong><small>observadas</small></div>)}</div><div className="rv-integrity"><BadgeCheck size={16}/> Métricas privadas, experimentais ou de comportamento real não são tratadas como coletadas só porque existem no catálogo metodológico.</div></section>
  </>}
  <footer className="rv-footer"><span>Plutyx · SAC</span><span>Evidence-first autonomous website intelligence · 2026</span></footer>
 </main>
}
function Title({icon:Icon,eyebrow,title,text}){return <div className="rv-title"><div><span><Icon size={13}/>{eyebrow}</span><h2>{title}</h2></div><p>{text}</p></div>}
createRoot(document.getElementById('root')).render(<React.StrictMode><App/></React.StrictMode>);
