import React,{useEffect,useMemo,useRef,useState}from'react';
import{createRoot}from'react-dom/client';
import{Activity,ArrowRight,Award,BadgeCheck,BarChart3,BookOpen,Check,ChevronDown,CircleAlert,Clock3,Database,ExternalLink,FileSearch,Filter,Gauge,Globe2,Layers3,LineChart,Medal,Menu,Search,ShieldCheck,Sparkles,Target,Trophy,TriangleAlert,Users,WalletCards,X,Zap}from'lucide-react';
import'./ranking-site-v2.css';

const API='https://npgheuzpnkwtxopswpqy.supabase.co/functions/v1/sac-ranking-site-api';
async function api(body){const r=await fetch(API,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data?.error||`HTTP ${r.status}`);return data}
const n=v=>Number(v||0);const pct=v=>`${Math.max(0,Math.min(100,n(v))).toFixed(n(v)>=10?0:1)}%`;const num=(v,d=1)=>new Intl.NumberFormat('pt-BR',{maximumFractionDigits:d}).format(n(v));
const statusTone=s=>['pass','healthy','completed','ready','eligible'].includes(s)?'good':['fail','critical','failed'].includes(s)?'bad':['warning','attention','insufficient_coverage'].includes(s)?'warn':'neutral';
const statusPt=s=>({queued:'Na fila',processing:'Analisando',completed:'Concluído',failed:'Falhou',pass:'Aprovado',fail:'Falha',warning:'Atenção',not_applicable:'Não aplicável',not_verifiable:'Sem evidência',eligible:'Elegível',insufficient_coverage:'Cobertura insuficiente',ready:'Pronto',pending_evidence:'Evidência pendente'})[s]||String(s||'—').replaceAll('_',' ');
const dimLabels={accessibility:'Acessibilidade',animations_transitions:'Animações',content:'Conteúdo',conversion_readiness:'Prontidão de conversão',creativity:'Criatividade',design:'Design',developer_overall:'Developer',experience_overall:'Experiência',markup_metadata:'Markup & Metadata',responsive_design:'Responsividade',semantics_seo:'SEO & Semântica',site_experience_index:'Site Experience',usability:'Usabilidade',wpo:'Performance / WPO'};
const engineLabels={performance:'Performance',accessibility:'Acessibilidade',security:'Segurança',seo:'SEO',seo_onpage:'SEO On-page',crawl_indexability:'Crawl & Indexação',structured_data:'Dados estruturados',analytics_tracking:'Tracking',social_sharing:'Social',image_intelligence:'Imagens',frontend_network:'Frontend / Rede',conversion_architecture:'Conversão',ux:'UX',forms:'Formulários',privacy:'Privacidade'};
function metricValue(m){const v=m?.numeric_value;if(v==null)return m?.text_value||'—';const u=m?.unit||'';if(u==='ms')return v>=1000?`${num(v/1000,2)} s`:`${num(v,0)} ms`;if(u==='bytes'){if(v>=1048576)return`${num(v/1048576,2)} MB`;if(v>=1024)return`${num(v/1024,1)} KB`;return`${num(v,0)} B`}if(u==='boolean')return v? 'Sim':'Não';if(u==='percent')return`${num(v,1)}%`;if(u==='score_0_100')return`${num(v<=1?v*100:v,0)}/100`;if(u==='score_0_1')return`${num(v*100,0)}%`;return`${num(v,2)}${u?` ${u}`:''}`}
function Mini({label,value,note,tone}){return <div className={`s3-mini ${tone||''}`}><span>{label}</span><strong>{value}</strong>{note&&<small>{note}</small>}</div>}
function SectionTitle({icon:Icon,eyebrow,title,text,action}){return <div className="s3-title"><div><span><Icon size={13}/>{eyebrow}</span><h2>{title}</h2></div><div className="s3-title-side">{text&&<p>{text}</p>}{action}</div></div>}
function Progress({value,tone='green'}){return <div className={`s3-progress ${tone}`}><i style={{width:pct(value)}}/></div>}
function Pill({children,tone='neutral'}){return <span className={`s3-pill ${tone}`}>{children}</span>}

function App(){
 const initial=new URLSearchParams(location.search).get('scan')||'';
 const[url,setUrl]=useState('');const[token,setToken]=useState(initial);const[busy,setBusy]=useState(Boolean(initial));const[status,setStatus]=useState(null);const[report,setReport]=useState(null);const[home,setHome]=useState(null);const[error,setError]=useState('');const[tab,setTab]=useState('overview');const[issueFilter,setIssueFilter]=useState('all');const[metricSearch,setMetricSearch]=useState('');const[navOpen,setNavOpen]=useState(false);const timer=useRef(null);const homeTimer=useRef(null);
 async function loadHome(){try{const d=await api({action:'home',limit:25});setHome(d?.result||null)}catch{}}
 async function loadReport(t){try{const d=await api({action:'report',token:t});if(d?.result?.found){setReport(d.result);setBusy(false);loadHome()}}catch(e){setError('A análise terminou, mas o relatório detalhado ainda está sendo materializado. Atualize em alguns segundos.');setBusy(false)}}
 async function poll(t){try{const d=await api({action:'status',token:t});const r=d?.result||null;setStatus(r);setError('');if(r?.status==='completed'){await loadReport(t);return}if(r?.status==='failed'){setBusy(false);return}timer.current=setTimeout(()=>poll(t),2200)}catch{setError('Falha ao consultar a análise.');setBusy(false)}}
 useEffect(()=>{document.title='Sites de Alta Conversão · Plutyx SAC';loadHome();homeTimer.current=setInterval(loadHome,30000);if(initial)poll(initial);return()=>{timer.current&&clearTimeout(timer.current);homeTimer.current&&clearInterval(homeTimer.current)}},[]);
 async function start(e,forced){e?.preventDefault?.();const raw=forced||url;if(!raw.trim())return;setError('');setReport(null);setStatus(null);setBusy(true);setTab('overview');try{const d=await api({action:'start',url:raw});if(!d?.token)throw new Error('scan_token_missing');setToken(d.token);history.replaceState(null,'',`${location.pathname}?scan=${encodeURIComponent(d.token)}`);poll(d.token)}catch(e){setBusy(false);const m={invalid_url:'Digite uma URL válida.',daily_preview_limit:'Você atingiu o limite diário de análises desta conexão.',scanner_busy:'Os coletores estão ocupados neste instante.'};setError(m[e.message]||'Não foi possível iniciar a análise agora.')}}
 const ranking=home?.ranking||[];const recent=home?.recent_analyzed||[];const awardsCatalog=home?.awards_catalog||[];const marketHome=home?.market?.listings||[];const stats=home?.stats||{};
 const issues=report?.issues||[];const metrics=report?.metrics||[];const pages=report?.pages||[];const dimensions=report?.dimensions||[];const rank=report?.ranking||null;const summary=report?.status_summary||{};const evidence=report?.evidence_dashboard||status?.evidence_dashboard||{};const priorities=report?.priority_actions||status?.priority_actions||[];const bench=evidence?.benchmark_comparison?.comparison||[];
 const filteredIssues=useMemo(()=>issues.filter(i=>issueFilter==='all'||i.status===issueFilter),[issues,issueFilter]);
 const filteredMetrics=useMemo(()=>{const q=metricSearch.trim().toLowerCase();return q?metrics.filter(m=>`${m.name} ${m.metric_code} ${m.engine} ${m.source_kind}`.toLowerCase().includes(q)):metrics},[metrics,metricSearch]);
 const primaryScore=rank?.score_100??(dimensions.find(x=>x.dimension_code==='site_experience_index')?.preliminary_score_10?dimensions.find(x=>x.dimension_code==='site_experience_index').preliminary_score_10*10:null);
 const scanning=busy||(['queued','processing'].includes(status?.status));
 return <main className="s3-page"><div className="s3-aurora a"/><div className="s3-aurora b"/>
  <header className="s3-header"><a className="s3-brand" href="/ranking-site/"><div><Gauge size={19}/></div><span><b>PLUTYX</b><small>SITES DE ALTA CONVERSÃO</small></span></a><nav className={navOpen?'open':''}><a href="#ranking" onClick={()=>setNavOpen(false)}>Ranking</a><a href="#como-funciona" onClick={()=>setNavOpen(false)}>Como funciona</a><a href="#awards" onClick={()=>setNavOpen(false)}>Awards</a><a href="#community" onClick={()=>setNavOpen(false)}>Comunidade</a><a href="#market" onClick={()=>setNavOpen(false)}>Market</a></nav><div className="s3-live"><i/>ranking atualiza automaticamente</div><button className="s3-menu" onClick={()=>setNavOpen(!navOpen)}>{navOpen?<X/>:<Menu/>}</button></header>

  <section className="s3-hero"><div className="s3-kicker"><Trophy size={13}/> RANKING AUTÔNOMO · EVIDÊNCIA REAL</div><h1>Qual posição o seu site<br/><em>merece ocupar?</em></h1><p>Cole uma URL. O SAC rastreia até 10 páginas, executa laboratório, browser, acessibilidade, segurança, SEO, UX e CRO, compara com benchmarks e transforma a evidência em um relatório investigável — sem inventar tráfego ou vendas.</p><form className="s3-search" onSubmit={start}><div><Globe2/><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://seusite.com.br" aria-label="URL do site"/></div><button disabled={busy||!url.trim()}>{busy?<><Activity size={16}/> Analisando</>:<>Descobrir minha posição <ArrowRight size={16}/></>}</button></form><div className="s3-proof"><span><BadgeCheck/>140 coletores públicos ativos</span><span><FileSearch/>até 10 páginas por scan</span><span><ShieldCheck/>ausência de evidência ≠ aprovação</span></div>{error&&<div className="s3-error"><TriangleAlert size={15}/>{error}</div>}</section>

  {!report&&!scanning&&<>
   <section className="s3-stats"><Mini label="Sites no ranking" value={stats.ranked_sites??'—'} note="cobertura mínima atingida"/><Mini label="Sites analisados" value={stats.analyzed_sites??'—'} note="dados atuais"/><Mini label="Métricas autônomas" value={stats.active_public_metrics??'—'} note="coletores implementados"/><Mini label="Awards emitidos" value={stats.awards_issued??0} note="somente critérios comprovados"/><Mini label="Avaliações da comunidade" value={stats.community_ratings??0} note="separadas do score técnico"/></section>
   <section id="ranking" className="s3-section"><SectionTitle icon={Trophy} eyebrow="SITES DE ALTA CONVERSÃO" title="Ranking Autônomo" text="Apenas sites com cobertura ≥60% entram na classificação. Readiness não é taxa de conversão real."/><RankingTable rows={ranking} onAnalyze={u=>{setUrl(`https://${u}`);start(null,`https://${u}`)}}/><div className="s3-method"><ShieldCheck size={16}/><div><b>Dois níveis de verdade.</b><span>Este ranking mede prontidão autônoma. O selo Verified High Conversion ficará reservado a sites que conectarem telemetria first-party e comprovarem conversão real.</span></div></div></section>
   <section className="s3-section"><SectionTitle icon={Clock3} eyebrow="NOVAS ANÁLISES" title="Quem acabou de entrar no radar" text="Sites com cobertura insuficiente aparecem aqui, mas ainda não ocupam posição."/><div className="s3-recent">{recent.map((r,i)=><article key={`${r.normalized_domain}-${i}`}><div className="s3-site-icon">{String(r.normalized_domain||'?').slice(0,1).toUpperCase()}</div><div><h3>{r.normalized_domain}</h3><p>{r.detected_archetype?.replaceAll('_',' ')||'arquétipo em análise'}</p></div><strong>{r.score_100?num(r.score_100,1):'—'}</strong><div><span>{pct(n(r.metric_coverage)*100)} cobertura</span><Progress value={n(r.metric_coverage)*100} tone={r.eligibility_status==='eligible'?'green':'amber'}/></div><Pill tone={statusTone(r.eligibility_status)}>{statusPt(r.eligibility_status)}</Pill></article>)}</div></section>
   <section id="awards" className="s3-section"><SectionTitle icon={Award} eyebrow="RECONHECIMENTO VERIFICÁVEL" title="SAC Awards" text="Selos são liberados por score + cobertura. Não existe compra de posição."/><div className="s3-awards">{awardsCatalog.slice(0,8).map(a=><AwardCard key={a.award_code} award={a}/>)}</div></section>
   <section id="community" className="s3-community"><div><span><Users size={14}/> COMMUNITY LAYER</span><h2>O score técnico não é concurso de popularidade.</h2><p>A comunidade avalia Design, Usabilidade, Criatividade e Conteúdo em uma camada separada. Opinião humana enriquece o perfil — mas nunca altera silenciosamente a evidência técnica.</p></div><div className="s3-community-grid"><Mini label="Design" value="—" note="community score"/><Mini label="Usabilidade" value="—" note="community score"/><Mini label="Criatividade" value="—" note="community score"/><Mini label="Conteúdo" value="—" note="community score"/></div><div className="s3-zero"><Users/><b>Comunidade em abertura</b><span>{stats.community_ratings||0} avaliações públicas registradas até agora. A interface já preserva a separação entre Community Choice e SAC Score.</span></div></section>
   <section id="market" className="s3-section"><SectionTitle icon={WalletCards} eyebrow="CURATED CONVERSION MARKET" title="Melhorar é a próxima etapa" text="O Market conhece os motores do SAC. Depois do scan, as soluções são reordenadas pelas lacunas comprovadas."/><MarketGrid rows={marketHome}/></section>
   <section id="como-funciona" className="s3-section"><SectionTitle icon={Layers3} eyebrow="UMA URL → UM SISTEMA" title="O SaaS faz o resto" text="A experiência foi desenhada para educar enquanto analisa, sem pedir um briefing antes de entregar valor."/><div className="s3-steps">{[['01','Descobrir','URL, DNS, páginas, headers e estrutura.'],['02','Medir','Chromium, Lighthouse, PageSpeed, CrUX, axe e probes.'],['03','Explicar','Issues, páginas afetadas, benchmark e evidência.'],['04','Competir','Readiness score, cobertura e posição no ranking.'],['05','Melhorar','Plano priorizado + Market + reauditoria.']].map(x=><article key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
  </>}

  {(scanning||status)&&!report&&<ScanConsole status={status} url={url} token={token}/>} 

  {report&&<Report report={report} tab={tab} setTab={setTab} primaryScore={primaryScore} summary={summary} rank={rank} dimensions={dimensions} issues={filteredIssues} rawIssues={issues} issueFilter={issueFilter} setIssueFilter={setIssueFilter} metrics={filteredMetrics} metricSearch={metricSearch} setMetricSearch={setMetricSearch} pages={pages} priorities={priorities} bench={bench}/>} 

  <footer className="s3-footer"><span>Plutyx · Sites de Alta Conversão · SAC 2026</span><span>Observed ≠ Estimated ≠ Verified first-party</span></footer>
 </main>
}

function RankingTable({rows,onAnalyze}){if(!rows.length)return <div className="s3-empty"><Trophy/><b>O ranking está começando com dados reais.</b><span>Sites só aparecem depois de atingir a cobertura metodológica mínima.</span></div>;return <div className="s3-ranking"><div className="head"><span>#</span><span>Site</span><span>Score</span><span>Cobertura</span><span>Confiança</span><span>Tier</span><span></span></div>{rows.map(r=><div className="row" key={r.normalized_domain}><strong className={r.overall_rank<=3?'podium':''}>{r.overall_rank===1?'🥇':r.overall_rank===2?'🥈':r.overall_rank===3?'🥉':`#${r.overall_rank}`}</strong><div className="site"><i>{r.normalized_domain?.[0]?.toUpperCase()}</i><div><b>{r.company_name||r.normalized_domain}</b><small>{r.detected_archetype?.replaceAll('_',' ')||r.category||'site analisado'}</small></div></div><b className="score">{num(r.score_100,1)}</b><div><span>{pct(n(r.metric_coverage)*100)}</span><Progress value={n(r.metric_coverage)*100}/></div><span>{pct(n(r.evidence_confidence)*100)}</span><Pill tone="good">{r.tier}</Pill><button onClick={()=>onAnalyze(r.normalized_domain)}>Reanalisar <ArrowRight size={12}/></button></div>)}</div>}
function AwardCard({award,progress}){const measured=progress?.measured_score;const coverage=progress?.measured_coverage;const threshold=n(progress?.threshold??award.threshold);const minCov=n(progress?.minimum_coverage??award.minimum_coverage);const scoreOk=measured!=null&&(!threshold||n(measured)>=threshold);const covOk=coverage!=null&&n(coverage)>=minCov;const hit=progress?.issued||(scoreOk&&covOk&&!progress?.requires_official_score);return <article className={`s3-award ${hit?'hit':''}`}><div className="medal"><Medal/></div><span>{award.award_family||progress?.award_family}</span><h3>{award.label||progress?.label}</h3><p>{award.description||progress?.description}</p>{progress&&<><div className="s3-award-progress"><small>Score {measured!=null?num(measured,2):'—'}{threshold?` / ${threshold}`:''}</small><Progress value={threshold&&measured!=null?Math.min(100,n(measured)/threshold*100):0}/></div><div className="s3-award-progress"><small>Cobertura {coverage!=null?pct(n(coverage)*100):'—'} / {pct(minCov*100)}</small><Progress value={coverage!=null?Math.min(100,n(coverage)/Math.max(minCov,.01)*100):0} tone="cyan"/></div><Pill tone={hit?'good':'neutral'}>{progress.issued?'Emitido':progress.requires_official_score?'score oficial necessário':hit?'critério atingido':'em progresso'}</Pill></>}</article>}
function MarketGrid({rows=[]}){if(!rows.length)return <div className="s3-empty"><WalletCards/><b>Catálogo disponível, sem oferta aplicável nesta visão.</b></div>;return <div className="s3-market">{rows.map((m,i)=><article key={m.slug||i}><div><Pill tone="neutral">{m.category}</Pill>{m.featured&&<Sparkles size={13}/>}</div><h3>{m.title}</h3><p>{m.summary}</p>{m.matched_gaps!=null&&<div className="s3-match"><b>{m.matched_gaps}</b><span>lacunas relacionadas</span><strong>{num(m.match_points,1)} match</strong></div>}<small>{(m.platforms||[]).join(' · ')||m.pricing_model}</small>{m.checkout_url?<a href={m.checkout_url} target="_blank" rel="noreferrer">Ver solução <ExternalLink size={12}/></a>:<button disabled>Configuração guiada</button>}</article>)}</div>}
function ScanConsole({status,url,token}){const st=status?.status||'processing';return <section className="s3-scanbox"><div className="s3-scanhead"><div><Pill tone={statusTone(st)}>{statusPt(st)}</Pill><h2>{status?.url||url||'Preparando domínio'}</h2><p>{status?.mode==='lighthouse_full'?'Auditoria profunda · até 10 páginas':'Construindo a auditoria e distribuindo coletores auxiliares'}</p></div>{token&&<code>{token.slice(0,8)}…</code>}</div><div className="s3-pipeline">{[['01','Descoberta'],['02','Crawl + DOM'],['03','Lab + CWV'],['04','Browser + WCAG'],['05','SEO + Security'],['06','Evidence OS'],['07','Ranking']].map((x,i)=><div className={st==='completed'||i<3?'on':''} key={x[0]}><b>{x[0]}</b><span>{x[1]}</span></div>)}</div><div className="s3-scanline"><i/></div><div className="s3-scanfacts"><span><Activity/> coletores executam em paralelo</span><span><Database/> evidências são materializadas com proveniência</span><span><Trophy/> posição só aparece com cobertura suficiente</span></div></section>}

function Report({report,tab,setTab,primaryScore,summary,rank,dimensions,issues,rawIssues,issueFilter,setIssueFilter,metrics,metricSearch,setMetricSearch,pages,priorities,bench}){
 const domain=report.domain||{};const community=report.community||{};const awards=report.awards||[];const market=report.market?.recommendations||[];const evidence=report.evidence_dashboard||{};const cov=evidence.metric_coverage||{};const active=evidence.metric_capabilities?.autonomous_implemented||0;const observed=cov.observed_distinct||0;
 const tabs=[['overview','Overview',Gauge],['issues',`Problemas (${rawIssues.length})`,CircleAlert],['metrics',`Métricas (${report.metrics?.length||0})`,Database],['pages',`Páginas (${pages.length})`,FileSearch],['awards','Awards',Award],['market','Soluções',WalletCards],['evidence','Evidência',ShieldCheck]];
 return <div className="s3-report"><section className="s3-report-hero"><div className="s3-report-domain"><div className="s3-domainmark">{domain.normalized_domain?.[0]?.toUpperCase()||'S'}</div><div><span>AUDITORIA AUTÔNOMA</span><h2>{domain.company_name||domain.normalized_domain}</h2><p>{domain.detected_archetype?.replaceAll('_',' ')||'Site intelligence profile'} · {report.audit?.audit_type} · {pages.length} página(s)</p></div></div><div className="s3-report-score"><div><strong>{primaryScore!=null?num(primaryScore,1):'—'}</strong><span>/100</span></div><p>{rank?.eligibility_status==='eligible'?'Autonomous Readiness Score':'Score preliminar condicionado à cobertura'}</p></div><div className="s3-rankbox"><span>Posição</span><strong>{rank?.overall_rank?`#${rank.overall_rank}`:'—'}</strong><small>{rank?.eligibility_status==='eligible'?`${pct(n(rank.percentile))} percentile`:`faltam ${Math.max(0,60-n(rank?.metric_coverage)*100).toFixed(0)} p.p. de cobertura`}</small></div></section>
  <section className="s3-report-kpis"><Mini label="Cobertura de métricas" value={pct(active?observed/active*100:0)} note={`${observed}/${active} observadas`}/><Mini label="Confiança da evidência" value={rank?.evidence_confidence?pct(n(rank.evidence_confidence)*100):'—'} note="média ponderada"/><Mini label="Falhas" value={summary.fail??0} note="verificadas" tone="bad"/><Mini label="Atenções" value={summary.warning??0} note="verificadas" tone="warn"/><Mini label="Aprovados" value={summary.pass??0} note="com evidência" tone="good"/><Mini label="Sem evidência" value={summary.not_verifiable??0} note="não viram pass"/></section>
  <div className="s3-tabs">{tabs.map(([id,label,Icon])=><button className={tab===id?'active':''} key={id} onClick={()=>setTab(id)}><Icon size={14}/>{label}</button>)}</div>
  {tab==='overview'&&<Overview dimensions={dimensions} priorities={priorities} bench={bench} community={community} awards={awards} rank={rank}/>} 
  {tab==='issues'&&<Issues rows={issues} all={rawIssues} filter={issueFilter} setFilter={setIssueFilter}/>} 
  {tab==='metrics'&&<Metrics rows={metrics} search={metricSearch} setSearch={setMetricSearch}/>} 
  {tab==='pages'&&<Pages rows={pages}/>} 
  {tab==='awards'&&<section className="s3-section in-report"><SectionTitle icon={Award} eyebrow="PROGRESSO PARA SELOS" title="Awards & reconhecimento" text="Score alto sem cobertura suficiente não libera selo."/><div className="s3-awards">{awards.map(a=><AwardCard key={a.award_code} award={a} progress={a}/>)}</div></section>}
  {tab==='market'&&<section className="s3-section in-report"><SectionTitle icon={Target} eyebrow="O QUE FAZ SENTIDO RESOLVER" title="Market personalizado pelo diagnóstico" text="Match técnico vem das lacunas do audit. Pontos só mudam após reauditoria."/><MarketGrid rows={market}/></section>}
  {tab==='evidence'&&<Evidence report={report}/>} 
 </div>}
function Overview({dimensions,priorities,bench,community,awards,rank}){return <>
 <section className="s3-section in-report"><SectionTitle icon={BarChart3} eyebrow="SCORECARD" title="Onde o site está forte — e onde ainda é cedo para concluir" text="Cada dimensão mostra score preliminar, cobertura e confiança separadamente."/><div className="s3-dimensions">{dimensions.filter(d=>!['developer_overall','experience_overall','site_experience_index'].includes(d.dimension_code)).map(d=>{const score=d.score_10??d.preliminary_score_10;return <article key={d.dimension_code}><div><span>{dimLabels[d.dimension_code]||d.dimension_code}</span><b>{score!=null?num(score,2):'—'}<small>/10</small></b></div><Progress value={score!=null?n(score)*10:0} tone={d.status==='ready'?'green':'cyan'}/><footer><span>{pct(n(d.evidence_coverage)*100)} cobertura</span><span>{pct(n(d.effective_confidence)*100)} confiança</span><Pill tone={statusTone(d.status)}>{d.status==='ready'?'oficial na dimensão':'preliminar'}</Pill></footer></article>})}</div></section>
 {priorities.length>0&&<section className="s3-section in-report"><SectionTitle icon={Zap} eyebrow="PRIORIDADE AUTOMÁTICA" title="Comece por aqui" text="Impacto/status × confiança. Esforço de implementação só entra quando a stack é conhecida."/><div className="s3-priority">{priorities.slice(0,8).map((a,i)=><article key={`${a.check_code}-${i}`}><b>{String(i+1).padStart(2,'0')}</b><div><div><Pill tone={statusTone(a.status)}>{statusPt(a.status)}</Pill><span>{engineLabels[a.engine]||a.engine}</span></div><h3>{a.title}</h3><p>{a.explanation||a.recommendation||'Evidência técnica observada.'}</p><small>Confiança {pct(n(a.confidence)*100)} · {a.evidence_tier||a.source_kind}</small></div><strong>{num(a.evidence_priority,2)}</strong></article>)}</div></section>}
 {bench.length>0&&<section className="s3-section in-report"><SectionTitle icon={LineChart} eyebrow="BENCHMARK TÉCNICO" title="Site vs corpus público" text="Prevalência técnica, não previsão de vendas."/><div className="s3-bench">{bench.slice(0,14).map(b=><article key={b.metric}><div><b>{String(b.metric).replaceAll('_',' ')}</b><span>{num(b.site_percent,0)}% site · {num(b.benchmark_percent,0)}% benchmark</span></div><div className="bars"><i style={{width:pct(b.benchmark_percent)}}/><b style={{width:pct(b.site_percent)}}/></div><em className={n(b.delta_pp)>=0?'good':'bad'}>{n(b.delta_pp)>=0?'+':''}{num(b.delta_pp,1)} p.p.</em></article>)}</div></section>}
 <section className="s3-grid2"><div className="s3-section in-report"><SectionTitle icon={Users} eyebrow="COMMUNITY" title="Leitura humana" text="Separada do score técnico."/><div className="s3-community-score"><strong>{community.ratings_count||0}</strong><span>avaliações</span></div><div className="s3-community-mini">{['design','usability','creativity','content'].map(k=><div key={k}><span>{k}</span><b>{community[k]!=null?num(community[k],1):'—'}</b></div>)}</div></div><div className="s3-section in-report"><SectionTitle icon={Trophy} eyebrow="RANKING" title="Prontidão competitiva" text="Entrada exige cobertura global."/><div className="s3-rank-detail"><strong>{rank?.overall_rank?`#${rank.overall_rank}`:'Ainda fora'}</strong><p>{rank?.eligibility_status==='eligible'?`Score ${num(rank.score_100,1)} · ${pct(n(rank.metric_coverage)*100)} de cobertura`:`O score ${num(rank?.score_100,1)} é informativo, mas a cobertura ${pct(n(rank?.metric_coverage)*100)} ainda não habilita posição.`}</p></div></div></section>
 </>}
function Issues({rows,all,filter,setFilter}){const counts={fail:all.filter(x=>x.status==='fail').length,warning:all.filter(x=>x.status==='warning').length};return <section className="s3-section in-report"><SectionTitle icon={CircleAlert} eyebrow="ISSUE EXPLORER" title="Problemas investigáveis" text="Abra um item para ver páginas afetadas, fonte e evidência." action={<div className="s3-filters"><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}>Todos {all.length}</button><button className={filter==='fail'?'active bad':''} onClick={()=>setFilter('fail')}>Falhas {counts.fail}</button><button className={filter==='warning'?'active warn':''} onClick={()=>setFilter('warning')}>Atenções {counts.warning}</button></div>}/><div className="s3-issues">{rows.map(i=><details key={i.check_code}><summary><div className={`s3-severity ${i.status}`}>{i.status==='fail'?'!':'△'}</div><div><span>{engineLabels[i.engine]||i.engine} · {i.check_code}</span><h3>{i.title}</h3><p>{i.explanation||'Evidência observada pelo coletor.'}</p></div><div className="s3-issue-meta"><b>{i.affected_pages_count||0}</b><span>página(s)</span><small>{pct(n(i.confidence)*100)} conf.</small></div><ChevronDown/></summary><div className="s3-issue-body"><div><h4>O que encontramos</h4><p>{i.explanation||'Resultado observado.'}</p>{i.recommendation&&<><h4>Como corrigir</h4><p>{i.recommendation}</p></>}</div><div><h4>Páginas afetadas</h4>{i.affected_pages?.length?<ul>{i.affected_pages.map(u=><li key={u}>{u}</li>)}</ul>:<p>Issue consolidado no nível do domínio ou sem page_id individual.</p>}<h4>Fonte</h4><code>{i.source_kind}</code></div><details className="s3-evidence-raw"><summary>Evidência técnica</summary><pre>{JSON.stringify(i.evidence,null,2)}</pre></details></div></details>)}</div></section>}
function Metrics({rows,search,setSearch}){return <section className="s3-section in-report"><SectionTitle icon={Database} eyebrow="OBSERVED METRICS" title="Métricas realmente coletadas" text="Cada linha preserva unidade, classe de evidência, fonte e confiança." action={<label className="s3-inline-search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar métrica, engine ou fonte"/></label>}/><div className="s3-metrics"><div className="head"><span>Métrica</span><span>Valor</span><span>Classe</span><span>Confiança</span><span>Fonte</span></div>{rows.map(m=><div className="row" key={m.metric_code}><div><b>{m.name}</b><small>{m.metric_code} · {engineLabels[m.engine]||m.engine}</small></div><strong>{metricValue(m)}</strong><Pill tone={m.evidence_class==='public_dataset'?'cyan':m.evidence_class==='lab'?'warn':'neutral'}>{m.evidence_class}</Pill><span>{pct(n(m.confidence)*100)}</span><code>{m.source_kind}</code></div>)}</div></section>}
function Pages({rows}){return <section className="s3-section in-report"><SectionTitle icon={FileSearch} eyebrow="CRAWL SAMPLE" title="Páginas analisadas" text="A contagem de issues mostra o que foi associado a cada URL do scan."/><div className="s3-pages">{rows.map(p=><article key={p.id}><div className="s3-page-status"><b>{p.http_status||'—'}</b><span>{p.page_type||'page'}</span></div><div><h3>{p.title||p.normalized_url}</h3><p>{p.normalized_url}</p><small>{p.word_count||0} palavras · {p.images_count||0} imagens · {p.forms_count||0} formulário(s) · {p.internal_links||0} links internos</small></div><div className="s3-page-issues"><span className="bad">{p.errors||0} falhas</span><span className="warn">{p.warnings||0} atenções</span></div></article>)}</div></section>}
function Evidence({report}){const e=report.evidence_dashboard||{};const cov=e.metric_coverage||{};return <section className="s3-section in-report"><SectionTitle icon={ShieldCheck} eyebrow="EVIDENCE OS" title="De onde veio cada conclusão" text="O SAC mantém lab, browser, HTTP, dataset público e first-party semanticamente separados."/><div className="s3-evidence-grid">{Object.entries(cov.by_evidence_class||{}).map(([k,v])=><article key={k}><span>{k.replaceAll('_',' ')}</span><strong>{v.observed}<small>/{v.registered}</small></strong><Progress value={v.registered?v.observed/v.registered*100:0}/></article>)}</div><div className="s3-policy">{Object.entries(report.methodology_disclosure||{}).map(([k,v])=><div key={k}>{v===true?<Check/>:<CircleAlert/>}<span>{k.replaceAll('_',' ')}</span></div>)}</div><div className="s3-method"><ShieldCheck/><div><b>Regra central</b><span>Ausência de evidência não vira aprovação. Readiness autônomo não é taxa de conversão, tráfego ou receita. Dados comportamentais reais só entram quando observados por telemetria própria/first-party.</span></div></div></section>}

createRoot(document.getElementById('root')).render(<React.StrictMode><App/></React.StrictMode>);