import { diagnosticContext, diagnosticScore, diagnosticPercent } from './diagnostic-semantics.js';
import './diagnostic-semantics.css';
import React,{useEffect,useMemo,useRef,useState}from'react';
import{createRoot}from'react-dom/client';
import{Activity,ArrowRight,Award,BadgeCheck,BarChart3,Check,ChevronDown,CircleAlert,Clock3,Crown,Database,ExternalLink,FileSearch,Gauge,Globe2,Layers3,LineChart,LockKeyhole,Medal,Menu,Search,ShieldCheck,Sparkles,Target,Trophy,TriangleAlert,Users,WalletCards,X,Zap}from'lucide-react';
import'./ranking-site-v2.css';
import'./ranking-site-v4.css';

const API='https://npgheuzpnkwtxopswpqy.supabase.co/functions/v1/sac-ranking-site-api';
async function api(body){const r=await fetch(API,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const data=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(data?.error||`HTTP ${r.status}`);e.status=r.status;throw e}return data}
const n=v=>Number(v||0);const pct=v=>`${Math.max(0,Math.min(100,n(v))).toFixed(n(v)>=10?0:1)}%`;const num=(v,d=1)=>new Intl.NumberFormat('pt-BR',{maximumFractionDigits:d}).format(n(v));const brl=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(n(v));
const statusTone=s=>['pass','healthy','completed','ready','eligible'].includes(s)?'good':['fail','critical','failed'].includes(s)?'bad':['warning','attention','insufficient_coverage'].includes(s)?'warn':'neutral';
const statusPt=s=>({queued:'Na fila',processing:'Analisando',completed:'Concluído',failed:'Falhou',pass:'Aprovado',fail:'Falha',warning:'Atenção',not_applicable:'Não aplicável',not_verifiable:'Sem evidência',eligible:'Elegível',insufficient_coverage:'Cobertura insuficiente',ready:'Pronto',pending_evidence:'Evidência pendente'})[s]||String(s||'—').replaceAll('_',' ');
const dimLabels={accessibility:'Acessibilidade',animations_transitions:'Animações',content:'Conteúdo',conversion_readiness:'Prontidão de conversão',creativity:'Criatividade',design:'Design',markup_metadata:'Markup & Metadata',responsive_design:'Responsividade',semantics_seo:'SEO & Semântica',usability:'Usabilidade',wpo:'Performance / WPO'};
const engineLabels={performance:'Performance',accessibility:'Acessibilidade',security:'Segurança',seo:'SEO',seo_onpage:'SEO On-page',crawl_indexability:'Crawl & Indexação',structured_data:'Dados estruturados',analytics_tracking:'Tracking',social_sharing:'Social',image_intelligence:'Imagens',frontend_network:'Frontend / Rede',conversion_architecture:'Conversão',ux:'UX',forms:'Formulários',privacy:'Privacidade'};
function metricValue(m){const v=m?.numeric_value;if(v==null)return m?.text_value||'—';const u=m?.unit||'';if(u==='ms')return v>=1000?`${num(v/1000,2)} s`:`${num(v,0)} ms`;if(u==='bytes'){if(v>=1048576)return`${num(v/1048576,2)} MB`;if(v>=1024)return`${num(v/1024,1)} KB`;return`${num(v,0)} B`}if(u==='boolean')return v?'Sim':'Não';if(u==='percent')return`${num(v,1)}%`;if(u==='score_0_100')return`${num(v<=1?v*100:v,0)}/100`;if(u==='score_0_1')return`${num(v*100,0)}%`;return`${num(v,2)}${u?` ${u}`:''}`}
function Mini({label,value,note,tone}){return <div className={`s3-mini ${tone||''}`}><span>{label}</span><strong>{value}</strong>{note&&<small>{note}</small>}</div>}
function SectionTitle({icon:Icon,eyebrow,title,text,action}){return <div className="s3-title"><div><span><Icon size={13}/>{eyebrow}</span><h2>{title}</h2></div><div className="s3-title-side">{text&&<p>{text}</p>}{action}</div></div>}
function Progress({value,tone='green'}){return <div className={`s3-progress ${tone}`}><i style={{width:pct(value)}}/></div>}
function Pill({children,tone='neutral'}){return <span className={`s3-pill ${tone}`}>{children}</span>}

function App(){
 const initial=new URLSearchParams(location.search).get('scan')||'';
 const[url,setUrl]=useState('');const[token,setToken]=useState(initial);const[busy,setBusy]=useState(Boolean(initial));const[status,setStatus]=useState(null);const[report,setReport]=useState(null);const[home,setHome]=useState(null);const[qualification,setQualification]=useState(null);const[error,setError]=useState('');const[tab,setTab]=useState('overview');const[issueFilter,setIssueFilter]=useState('all');const[metricSearch,setMetricSearch]=useState('');const[navOpen,setNavOpen]=useState(false);const timer=useRef(null);const homeTimer=useRef(null);
 async function loadHome(){try{const d=await api({action:'home',limit:25});setHome(d?.result||null)}catch{}}
 async function loadReport(t){try{const d=await api({action:'report',token:t});if(d?.result?.found){setReport(d.result);setBusy(false);loadHome()}}catch{setError('A análise terminou, mas o relatório detalhado ainda está sendo materializado.');setBusy(false)}}
 async function poll(t){try{const d=await api({action:'status',token:t});const r=d?.result||null;setStatus(r);setError('');if(r?.status==='completed'){await loadReport(t);return}if(r?.status==='failed'){setBusy(false);return}timer.current=setTimeout(()=>poll(t),2200)}catch{setError('Falha ao consultar a análise.');setBusy(false)}}
 useEffect(()=>{document.title='Ranking Sites de Alta Conversão · SAC';loadHome();homeTimer.current=setInterval(loadHome,30000);if(initial)poll(initial);return()=>{timer.current&&clearTimeout(timer.current);homeTimer.current&&clearInterval(homeTimer.current)}},[]);
 async function qualify(e,forced){e?.preventDefault?.();const raw=forced||url;if(!raw.trim())return;setError('');setQualification(null);try{const d=await api({action:'qualify',url:raw});setQualification(d?.result||null);setUrl(d?.result?.url||raw);setTimeout(()=>document.getElementById('challenge-gate')?.scrollIntoView({behavior:'smooth',block:'center'}),60)}catch(e){setError(e.message==='invalid_url'?'Digite uma URL válida.':'Não foi possível preparar o desafio agora.')}}
 async function startPaid(){if(!qualification?.intent_token)return;setBusy(true);setError('');try{const d=await api({action:'start',intent_token:qualification.intent_token});if(!d?.token)throw new Error('scan_token_missing');setToken(d.token);history.replaceState(null,'',`${location.pathname}?scan=${encodeURIComponent(d.token)}`);poll(d.token)}catch(e){setBusy(false);if(e.message==='payment_required')setError('O Raio-X só entra na fila depois da confirmação do pagamento.');else setError('Não foi possível iniciar a análise paga agora.')}}
 const ranking=home?.ranking||[];const recent=home?.recent_analyzed||[];const awardsCatalog=home?.awards_catalog||[];const marketHome=home?.market?.listings||[];const stats=home?.stats||{};const offers=home?.offers||{};const story=home?.benchmark_story||{};
 const issues=report?.issues||[];const metrics=report?.metrics||[];const pages=report?.pages||[];const dimensions=report?.dimensions||[];const rank=report?.ranking||null;const summary=report?.status_summary||{};const evidence=report?.evidence_dashboard||status?.evidence_dashboard||{};const priorities=report?.priority_actions||status?.priority_actions||[];const bench=evidence?.benchmark_comparison?.comparison||[];
 const filteredIssues=useMemo(()=>issues.filter(i=>issueFilter==='all'||i.status===issueFilter),[issues,issueFilter]);const filteredMetrics=useMemo(()=>{const q=metricSearch.trim().toLowerCase();return q?metrics.filter(m=>`${m.name} ${m.metric_code} ${m.engine} ${m.source_kind}`.toLowerCase().includes(q)):metrics},[metrics,metricSearch]);
 const primaryScore=rank?.score_100??(dimensions.find(x=>x.dimension_code==='site_experience_index')?.preliminary_score_10?dimensions.find(x=>x.dimension_code==='site_experience_index').preliminary_score_10*10:null);const scanning=busy||(['queued','processing'].includes(status?.status));
 return <main className="s3-page s4-page"><div className="s3-aurora a"/><div className="s3-aurora b"/>
  <header className="s3-header"><a className="s3-brand" href="/ranking-site/"><div><Trophy size={19}/></div><span><b>SAC</b><small>SITES DE ALTA CONVERSÃO</small></span></a><nav className={navOpen?'open':''}><a href="#ranking">Ranking</a><a href="#awards">Awards</a><a href="#community">Comunidade</a><a href="#planos">Participar</a><a href="#market">Aumentar pontos</a></nav><div className="s3-live"><i/> temporada 2026 ativa</div><button className="s3-menu" onClick={()=>setNavOpen(!navOpen)}>{navOpen?<X/>:<Menu/>}</button></header>

  <section className="s3-hero s4-hero"><div className="s3-kicker"><Crown size={13}/> RANKING GLOBAL · SITES DE ALTA CONVERSÃO</div><h1>Até onde o seu site<br/><em>consegue chegar?</em></h1><p>Empresas e profissionais competem por uma posição no ranking que mede a prontidão real de seus sites para converter melhor. O SAC cruza engenharia, UX, psicologia aplicada, comportamento, acessibilidade, SEO, confiança, dados e arquitetura de vendas — e mostra onde você está hoje.</p><div className="s4-storyline"><span><Database/> {story.claim_10k_success_ready?'10.000+ auditorias concluídas':`${num(story.urls_processed||stats.benchmark_urls_processed,0)} URLs processadas`}</span><span><Gauge/> {stats.active_public_metrics||140} métricas autônomas ativas</span><span><Trophy/> ranking por evidência, não por popularidade</span></div><form className="s3-search" onSubmit={qualify}><div><Globe2/><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://seusite.com.br" aria-label="URL do site"/></div><button disabled={!url.trim()}>Quero descobrir minha pontuação <ArrowRight size={16}/></button></form><div className="s4-pricehint"><LockKeyhole size={13}/> A análise completa é paga. Colar a URL apenas prepara o seu desafio — nenhum scan profundo é executado antes do pagamento.</div>{error&&<div className="s3-error"><TriangleAlert size={15}/>{error}</div>}</section>

  {qualification&&!scanning&&!report&&<ChallengeGate q={qualification} offers={offers} onStart={startPaid}/>} 

  {!report&&!scanning&&<>
   <section className="s3-stats s4-stats"><Mini label="Sites classificados" value={stats.ranked_sites??'—'} note="posição ativa"/><Mini label="URLs no benchmark" value={stats.benchmark_urls_processed??'—'} note={`${stats.benchmark_successful_audits??'—'} concluídas com sucesso`}/><Mini label="Métricas públicas" value={stats.active_public_metrics??'—'} note="coleta autônoma"/><Mini label="Awards da temporada" value={awardsCatalog.length||'—'} note="categorias verificáveis"/><Mini label="Comunidade" value={stats.community_ratings??0} note="avaliações separadas do score"/></section>
   <section id="ranking" className="s3-section s4-ranking-section"><SectionTitle icon={Trophy} eyebrow="PLACAR ATUAL" title="Sites de Alta Conversão" text="A posição não é comprada. A assinatura mantém o perfil no ecossistema; o lugar no placar depende da evidência técnica e da cobertura do scan."/><RankingTable rows={ranking} onAnalyze={u=>{setUrl(`https://${u}`);qualify(null,`https://${u}`)}}/><div className="s4-ranking-cta"><div><Crown/><span><b>Seu concorrente pode estar aqui antes de você.</b><small>Descubra a sua pontuação, entre na temporada e acompanhe a evolução do seu site.</small></span></div><a href="#planos">Ver como participar <ArrowRight/></a></div></section>

   <section className="s4-origin"><div><span>POR QUE ESTE RANKING EXISTE</span><h2>Não é um concurso de site bonito. É uma competição por maturidade de conversão.</h2><p>O motor observa sinais técnicos que qualquer crawler pode provar e separa aquilo que exige telemetria real. A camada metodológica agrega performance, UX, acessibilidade, SEO, segurança, confiança, estrutura de oferta, copy, fricção, comportamento, dados e experimentação.</p></div><div className="s4-pillars">{[[Gauge,'Engenharia','Velocidade, estabilidade, rede, scripts, mobile e infraestrutura.'],[Users,'Comportamento','Fricção, navegação, formulários e sinais first-party quando conectados.'],[Sparkles,'Psicologia & UX','Clareza, atenção, hierarquia, confiança e redução de ansiedade.'],[Target,'Vendas','Oferta, CTA, tracking, funil, prova, checkout e prontidão comercial.']].map(([I,t,p])=><article key={t}><I/><h3>{t}</h3><p>{p}</p></article>)}</div></section>

   <section id="planos" className="s3-section"><SectionTitle icon={Crown} eyebrow="ENTRE NO JOGO" title="Você escolhe até onde quer participar" text="A análise é a porta de entrada. Ranking, Comunidade e Awards são produtos diferentes porque entregam valores diferentes."/><Pricing offers={offers} onAnalyze={()=>document.querySelector('.s3-search input')?.focus()}/></section>

   <section id="awards" className="s3-section"><SectionTitle icon={Award} eyebrow="SAC AWARDS · TEMPORADA 2026" title="Reconhecimento que precisa ser conquistado" text="A inscrição coloca o site na temporada; não garante prêmio. Awards são emitidos por score, cobertura, ranking e critérios específicos."/><div className="s3-awards">{awardsCatalog.slice(0,8).map(a=><AwardCard key={a.award_code} award={a}/>)}</div><div className="s4-awards-foot"><div><Medal/><span><b>Inscrição Awards</b><small>{brl(offers?.awards?.price||297)} por site / temporada</small></span></div><div><Clock3/><span><b>Annual Awards</b><small>fechamento anual + destaques recorrentes da temporada</small></span></div></div></section>

   <section id="community" className="s3-community s4-community"><div><span><Users size={14}/> CÍRCULO DE EVOLUÇÃO</span><h2>Uma comunidade de empresas que tratam o site como ativo de vendas.</h2><p>Discussões, missões, benchmarks, votos, casos e evolução de score. A camada humana cria pertencimento e reputação sem contaminar a nota técnica.</p></div><div className="s4-community-benefits">{['Perfil profissional e histórico','Votos e Community Choice','Missões para subir no ranking','Benchmarks e estudos aplicados','Discussões entre empresários','Novos critérios e tendências'].map(x=><span key={x}><Check/>{x}</span>)}</div><div className="s4-community-price"><small>a partir de</small><strong>{brl(offers?.community?.price||39)}<em>/mês</em></strong><a href="#planos">Ver planos</a></div></section>

   <section id="market" className="s3-section"><SectionTitle icon={Zap} eyebrow="AQUI ESTÁ O PRINCIPAL NEGÓCIO" title="Suba no ranking melhorando o que realmente importa" text="Depois do diagnóstico, o SAC reorganiza soluções pelas lacunas do seu site. Cada projeto mostra os critérios que pode resolver; pontos só entram depois da reauditoria."/><MarketGrid rows={marketHome}/></section>

   <section className="s3-section"><SectionTitle icon={Layers3} eyebrow="JORNADA COMPLETA" title="Curiosidade → competição → evolução" text="O produto usa status, comparação, progresso, pertencimento e ambição comercial sem falsificar escassez ou resultado."/><div className="s3-steps s4-steps">{[['01','Cole a URL','Prepare seu desafio sem gastar processamento.'],['02','Compre o Raio-X','O scan profundo mede e explica a pontuação.'],['03','Entre no Ranking','Mantenha perfil, posição, histórico e selo de participante.'],['04','Entre na Comunidade','Compare, aprenda, vote e acompanhe a evolução.'],['05','Dispute os Awards','Inscreva o site na temporada anual.'],['06','Aumente seus pontos','Contrate correções e reaudite para comprovar a evolução.']].map(x=><article key={x[0]}><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
  </>}

  {(scanning||status)&&!report&&<ScanConsole status={status} url={url} token={token}/>} 
  {report&&<Report report={report} offers={offers} tab={tab} setTab={setTab} primaryScore={primaryScore} summary={summary} rank={rank} dimensions={dimensions} issues={filteredIssues} rawIssues={issues} issueFilter={issueFilter} setIssueFilter={setIssueFilter} metrics={filteredMetrics} metricSearch={metricSearch} setMetricSearch={setMetricSearch} pages={pages} priorities={priorities} bench={bench}/>} 
  <footer className="s3-footer"><span>SAC · Sites de Alta Conversão · Temporada 2026</span><span>Posição é conquistada. Compra não altera score.</span></footer>
 </main>
}

function ChallengeGate({q,offers,onStart}){const o=q.offer||offers.analysis||{};return <section id="challenge-gate" className="s4-gate"><div className="s4-gate-main"><Pill tone="good">DESAFIO PREPARADO</Pill><span className="domain"><Globe2/>{q.domain}</span><h2>Agora o SAC pode descobrir onde este site realmente fica no ranking.</h2><p>O pagamento libera a auditoria profunda, o scorecard completo, os problemas priorizados, as métricas observadas e o plano de evolução. Entrar no ranking público continua sendo uma decisão separada.</p><div className="s4-gate-proof"><span><Database/><b>{q.benchmark?.urls_processed||'—'}</b> URLs de benchmark</span><span><BadgeCheck/><b>{q.benchmark?.successful_audits||'—'}</b> auditorias concluídas</span><span><ShieldCheck/><b>Evidence OS</b> sem transformar ausência em aprovação</span></div></div><aside><span>RAIO-X SAC</span><strong>{brl(o.price||97)}</strong><small>pagamento único por análise</small><ul><li><Check/>até 10 páginas</li><li><Check/>métricas + issues + evidências</li><li><Check/>pontuação e prontidão para ranking</li><li><Check/>plano para aumentar score</li></ul>{o.checkout_ready?<a href={o.checkout_url} target="_blank" rel="noreferrer">Liberar minha análise <ArrowRight/></a>:<button onClick={onStart}>Liberar após pagamento <LockKeyhole/></button>}<em>{o.checkout_ready?'Checkout conectado. O scan é liberado após confirmação.':'Infraestrutura de pagamento preparada; checkout externo ainda precisa ser conectado.'}</em></aside></section>}

function Pricing({offers,onAnalyze}){const plans=[
 {key:'analysis',icon:Gauge,label:'Descobrir',name:'Raio-X SAC',price:offers?.analysis?.price||97,interval:'único',text:'Descubra sua pontuação e todas as lacunas que impedem o site de subir.',items:['Auditoria profunda','Scorecard + evidências','Plano de evolução'],cta:'Analisar meu site'},
 {key:'ranking',icon:Trophy,label:'Competir',name:'Ranking',price:offers?.ranking?.price||59,interval:'/mês',text:'Perfil público, posição, histórico e selo de participante enquanto a assinatura estiver ativa.',items:['Perfil no ecossistema','Histórico de posição','Share card + badge'],cta:'Entrar no ranking'},
 {key:'community',icon:Users,label:'Pertencer',name:'Comunidade',price:offers?.community?.price||39,interval:'/mês',text:'Conteúdo, votos, discussões, benchmarks e missões com empresas que querem vender melhor.',items:['Community Choice','Missões e benchmarks','Networking aplicado'],cta:'Entrar na comunidade'},
 {key:'club',icon:Crown,label:'Mais escolhido',name:'Ranking + Comunidade',price:offers?.club?.price||79,interval:'/mês',text:'A competição e a comunidade no mesmo plano recorrente.',items:['Tudo do Ranking','Tudo da Comunidade','Evolução contínua'],cta:'Quero o clube',featured:true},
 ];
 return <><div className="s4-pricegrid">{plans.map(p=>{const I=p.icon;const cfg=offers?.[p.key]||{};return <article className={p.featured?'featured':''} key={p.key}>{p.featured&&<b className="popular">RECOMENDADO</b>}<I/><span>{p.label}</span><h3>{p.name}</h3><p>{p.text}</p><div className="price"><strong>{brl(p.price)}</strong><small>{p.interval}</small></div><ul>{p.items.map(x=><li key={x}><Check/>{x}</li>)}</ul>{p.key==='analysis'?<button onClick={onAnalyze}>{p.cta}</button>:cfg.checkout_ready?<a href={cfg.checkout_url} target="_blank" rel="noreferrer">{p.cta}<ArrowRight/></a>:<button disabled>{p.cta}</button>}</article>})}</div><div className="s4-complete"><div><Crown/><span><b>Complete Pass 2026</b><small>Raio-X + inscrição Awards agora; Ranking + Comunidade enquanto quiser permanecer no ecossistema.</small></span></div><div className="s4-complete-price"><strong>{brl(offers?.complete?.entry?.price||349)}</strong><span>entrada</span><i>+</i><strong>{brl(offers?.complete?.recurring?.price||79)}</strong><span>/mês</span></div><button disabled>Escolher Complete Pass</button></div><p className="s4-pricing-note">A inscrição no Awards não garante prêmio. A assinatura do Ranking não compra posição. Serviços não compram pontos: qualquer mudança de score precisa ser comprovada por uma nova auditoria.</p></>}

function RankingTable({rows,onAnalyze}){if(!rows.length)return <div className="s3-empty"><Trophy/><b>O ranking está começando com dados reais.</b><span>Sites só aparecem depois de atingir cobertura metodológica suficiente.</span></div>;return <div className="s3-ranking"><div className="head"><span>#</span><span>Site</span><span>Score</span><span>Cobertura</span><span>Confiança</span><span>Tier</span><span></span></div>{rows.map(r=><div className="row" key={r.normalized_domain}><strong className={r.overall_rank<=3?'podium':''}>{r.overall_rank===1?'🥇':r.overall_rank===2?'🥈':r.overall_rank===3?'🥉':`#${r.overall_rank}`}</strong><div className="site"><i>{r.normalized_domain?.[0]?.toUpperCase()}</i><div><b>{r.company_name||r.normalized_domain}</b><small>{r.detected_archetype?.replaceAll('_',' ')||r.category||'site classificado'}</small></div></div><b className="score">{num(r.score_100,1)}</b><div><span>{pct(n(r.metric_coverage)*100)}</span><Progress value={n(r.metric_coverage)*100}/></div><span>{pct(n(r.evidence_confidence)*100)}</span><Pill tone="good">{r.tier}</Pill><button onClick={()=>onAnalyze(r.normalized_domain)}>Desafiar <ArrowRight size={12}/></button></div>)}</div>}
function AwardCard({award,progress}){const measured=progress?.measured_score;const coverage=progress?.measured_coverage;const threshold=n(progress?.threshold??award.threshold);const minCov=n(progress?.minimum_coverage??award.minimum_coverage);const scoreOk=measured!=null&&(!threshold||n(measured)>=threshold);const covOk=coverage!=null&&n(coverage)>=minCov;const hit=progress?.issued||(scoreOk&&covOk&&!progress?.requires_official_score);return <article className={`s3-award ${hit?'hit':''}`}><div className="medal"><Medal/></div><span>{award.award_family||progress?.award_family}</span><h3>{award.label||progress?.label}</h3><p>{award.description||progress?.description}</p>{progress&&<><div className="s3-award-progress"><small>Score {measured!=null?num(measured,2):'—'}{threshold?` / ${threshold}`:''}</small><Progress value={threshold&&measured!=null?Math.min(100,n(measured)/threshold*100):0}/></div><div className="s3-award-progress"><small>Cobertura {coverage!=null?pct(n(coverage)*100):'—'} / {pct(minCov*100)}</small><Progress value={coverage!=null?Math.min(100,n(coverage)/Math.max(minCov,.01)*100):0} tone="cyan"/></div><Pill tone={hit?'good':'neutral'}>{progress.issued?'Emitido':progress.requires_official_score?'score oficial necessário':hit?'critério atingido':'em progresso'}</Pill></>}</article>}
function MarketGrid({rows=[]}){if(!rows.length)return <div className="s3-empty"><WalletCards/><b>Catálogo disponível, sem oferta aplicável nesta visão.</b></div>;return <div className="s3-market">{rows.map((m,i)=><article key={m.slug||i}><div><Pill tone="neutral">{m.category}</Pill>{m.featured&&<Sparkles size={13}/>}</div><h3>{m.title}</h3><p>{m.summary}</p>{m.matched_gaps!=null&&<div className="s3-match"><b>{m.matched_gaps}</b><span>lacunas que esta solução pode atacar</span><strong>{num(m.match_points,1)} sinal de impacto</strong></div>}<div className="s4-point-rule"><Target/> Potencial de pontos só é calculado por simulação e confirmado após reauditoria.</div><small>{(m.platforms||[]).join(' · ')||m.pricing_model}</small>{m.checkout_url?<a href={m.checkout_url} target="_blank" rel="noreferrer">Ver solução <ExternalLink size={12}/></a>:<button disabled>Configuração guiada</button>}</article>)}</div>}
function ScanConsole({status,url,token}){const st=status?.status||'processing';return <section className="s3-scanbox"><div className="s3-scanhead"><div><Pill tone={statusTone(st)}>{statusPt(st)}</Pill><h2>{status?.url||url||'Preparando domínio'}</h2><p>Auditoria profunda · até 10 páginas · Evidence OS · Ranking</p></div>{token&&<code>{token.slice(0,8)}…</code>}</div><div className="s3-pipeline">{[['01','Descoberta'],['02','Crawl + DOM'],['03','Lab + CWV'],['04','Browser + WCAG'],['05','SEO + Security'],['06','Evidence OS'],['07','Ranking']].map((x,i)=><div className={st==='completed'||i<3?'on':''} key={x[0]}><b>{x[0]}</b><span>{x[1]}</span></div>)}</div><div className="s3-scanline"><i/></div><div className="s3-scanfacts"><span><Activity/> coletores executam em paralelo</span><span><Database/> evidências preservam proveniência</span><span><Trophy/> posição só aparece com cobertura suficiente</span></div></section>}

function Report({report,offers,tab,setTab,primaryScore,summary,rank,dimensions,issues,rawIssues,issueFilter,setIssueFilter,metrics,metricSearch,setMetricSearch,pages,priorities,bench}){
 const domain=report.domain||{};const community=report.community||{};const awards=report.awards||[];const market=report.market?.recommendations||[];const evidence=report.evidence_dashboard||{};const cov=evidence.metric_coverage||{};const active=evidence.metric_capabilities?.autonomous_implemented||0;const observed=cov.observed_distinct||0;
 const truth=diagnosticContext(report);
 const tabs=[['overview','Overview',Gauge],['issues',`Problemas (${rawIssues.length})`,CircleAlert],['metrics',`Métricas (${report.metrics?.length||0})`,Database],['pages',`Páginas (${pages.length})`,FileSearch],['awards','Awards',Award],['market','Aumentar pontos',Zap],['evidence','Evidência',ShieldCheck]];
 return <div className="s3-report"><section className="s3-report-hero"><div className="s3-report-domain"><div className="s3-domainmark">{domain.normalized_domain?.[0]?.toUpperCase()||'S'}</div><div><span>{truth.label.toUpperCase()}</span><h2>{domain.company_name||domain.normalized_domain}</h2><p>{domain.detected_archetype?.replaceAll('_',' ')||'perfil de inteligência do site'} · {pages.length} página(s)</p></div></div><div className="s3-report-score"><div><strong>{diagnosticScore(primaryScore,truth.provisional)}</strong><span>/100</span></div><p>{truth.label}</p></div><div className="s3-rankbox"><span>Competição oficial</span><strong>{truth.position?`#${truth.position}`:'Sem posição'}</strong><small>{truth.official?'Participação elegível':'Diagnóstico fora da classificação oficial'}</small></div></section>
  <section className={`gcl-diagnostic ${truth.official?'official':''}`} aria-label="Como interpretar este diagnóstico"><header><strong>{truth.label}</strong><span>{truth.preliminaryAxes?`${truth.preliminaryAxes} eixos preliminares`:'Evidência observada nesta análise'}</span></header><p>{truth.official?'A pontuação atende aos critérios de elegibilidade informados nesta análise.':'A pontuação resume a evidência disponível e pode mudar com novas coletas. Ela não comprova taxa de conversão, participação ou colocação na competição oficial.'}</p><div className="gcl-diagnostic-grid"><div><span>Verificações com evidência</span><b>{diagnosticPercent(truth.coverage)}</b><div className="gcl-diagnostic-meter"><i style={{width:`${(truth.coverage??0)*100}%`}}/></div><small>{truth.observed??'—'} de {truth.total??'—'} verificações classificadas como aprovado, atenção ou falha.</small></div><div><span>Sinais coletados</span><b>{diagnosticPercent(truth.collectorCoverage)}</b><small>Disponibilidade dos sinais do coletor. Este percentual usa outra base e não representa cobertura da avaliação.</small></div></div><details><summary>Por que alguns valores são aproximados?</summary><p>Os eixos preliminares aparecem arredondados com ≈. A coleta ausente permanece sem evidência; não vira nota zero, aprovação ou penalidade. Cada eixo mostra sua própria cobertura.</p></details></section><section className="s4-postscore"><div><Trophy/><span><b>Use o diagnóstico para orientar sua próxima melhoria.</b><small>Ranking, comunidade e Awards transformam uma auditoria isolada em uma jornada contínua de evolução.</small></span></div><div><strong>{brl(offers?.club?.price||79)}<em>/mês</em></strong><button disabled>Entrar no Ranking + Comunidade</button></div></section>
  <section className="s3-report-kpis"><Mini label="Verificações com evidência" value={diagnosticPercent(truth.coverage)} note={`${truth.observed??'—'}/${truth.total??'—'} verificadas`}/><Mini label="Confiança" value={rank?.evidence_confidence?pct(n(rank.evidence_confidence)*100):'—'} note="evidência ponderada"/><Mini label="Falhas" value={summary.fail??0} note="verificadas" tone="bad"/><Mini label="Atenções" value={summary.warning??0} note="verificadas" tone="warn"/><Mini label="Aprovados" value={summary.pass??0} note="com evidência" tone="good"/><Mini label="Sem evidência" value={summary.not_verifiable??0} note="não viram pass"/></section>
  <div className="s3-tabs">{tabs.map(([id,label,Icon])=><button className={tab===id?'active':''} key={id} onClick={()=>setTab(id)}><Icon size={14}/>{label}</button>)}</div>
  {tab==='overview'&&<Overview dimensions={dimensions} priorities={priorities} bench={bench} community={community} rank={rank}/>} 
  {tab==='issues'&&<Issues rows={issues} all={rawIssues} filter={issueFilter} setFilter={setIssueFilter}/>} 
  {tab==='metrics'&&<Metrics rows={metrics} search={metricSearch} setSearch={setMetricSearch}/>} 
  {tab==='pages'&&<Pages rows={pages}/>} 
  {tab==='awards'&&<section className="s3-section in-report"><SectionTitle icon={Award} eyebrow="TEMPORADA 2026" title="O que este site ainda precisa para conquistar um Award" text="Inscrição habilita a candidatura; score e cobertura continuam decidindo o resultado."/><div className="s3-awards">{awards.map(a=><AwardCard key={a.award_code} award={a} progress={a}/>)}</div></section>}
  {tab==='market'&&<section className="s3-section in-report"><SectionTitle icon={Zap} eyebrow="SUBIR NO RANKING" title="Soluções ligadas aos seus gaps reais" text="O SAC conecta cada solução às lacunas observadas. A reauditoria é quem confirma qualquer ganho."/><MarketGrid rows={market}/></section>}
  {tab==='evidence'&&<Evidence report={report}/>} 
 </div>}
function Overview({dimensions,priorities,bench,community,rank}){return <>
 <section className="s3-section in-report"><SectionTitle icon={BarChart3} eyebrow="SCORECARD" title="Onde você ganha e perde terreno" text="Score, cobertura e confiança ficam separados para não esconder incerteza."/><div className="s3-dimensions">{dimensions.filter(d=>!['developer_overall','experience_overall','site_experience_index'].includes(d.dimension_code)).map(d=>{const score=d.score_10??d.preliminary_score_10;return <article key={d.dimension_code}><div><span>{dimLabels[d.dimension_code]||d.dimension_code}</span><b>{diagnosticScore(score,d.status!=='ready')}<small>/10</small></b></div><Progress value={score!=null?n(score)*10:0} tone={d.status==='ready'?'green':'cyan'}/><footer><span>{pct(n(d.evidence_coverage)*100)} cobertura</span><span>{pct(n(d.effective_confidence)*100)} confiança</span><Pill tone={statusTone(d.status)}>{d.status==='ready'?'evidência suficiente':'preliminar'}</Pill></footer></article>})}</div></section>
 {priorities.length>0&&<section className="s3-section in-report"><SectionTitle icon={Zap} eyebrow="ONDE RECUPERAR TERRENO" title="Prioridades automáticas" text="Impacto/status × confiança. Não é promessa de faturamento."/><div className="s3-priority">{priorities.slice(0,8).map((a,i)=><article key={`${a.check_code}-${i}`}><b>{String(i+1).padStart(2,'0')}</b><div><div><Pill tone={statusTone(a.status)}>{statusPt(a.status)}</Pill><span>{engineLabels[a.engine]||a.engine}</span></div><h3>{a.title}</h3><p>{a.explanation||a.recommendation||'Evidência técnica observada.'}</p><small>Confiança {pct(n(a.confidence)*100)} · {a.evidence_tier||a.source_kind}</small></div><strong>{num(a.evidence_priority,2)}</strong></article>)}</div></section>}
 {bench.length>0&&<section className="s3-section in-report"><SectionTitle icon={LineChart} eyebrow="BENCHMARK" title="Seu site vs corpus público" text="Prevalência técnica, não previsão de vendas."/><div className="s3-bench">{bench.slice(0,14).map(b=><article key={b.metric}><div><b>{String(b.metric).replaceAll('_',' ')}</b><span>{num(b.site_percent,0)}% site · {num(b.benchmark_percent,0)}% benchmark</span></div><div className="bars"><i style={{width:pct(b.benchmark_percent)}}/><b style={{width:pct(b.site_percent)}}/></div><em className={n(b.delta_pp)>=0?'good':'bad'}>{n(b.delta_pp)>=0?'+':''}{num(b.delta_pp,1)} p.p.</em></article>)}</div></section>}
 <section className="s3-grid2"><div className="s3-section in-report"><SectionTitle icon={Users} eyebrow="COMUNIDADE" title="Reputação humana" text="Separada do score técnico."/><div className="s3-community-score"><strong>{community.ratings_count||0}</strong><span>avaliações</span></div><div className="s3-community-mini">{['design','usability','creativity','content'].map(k=><div key={k}><span>{k}</span><b>{community[k]!=null?num(community[k],1):'—'}</b></div>)}</div></div><div className="s3-section in-report"><SectionTitle icon={Trophy} eyebrow="RANKING" title="Prontidão competitiva" text="Posição exige cobertura global."/><div className="s3-rank-detail"><strong>{diagnosticContext(rank||{}).position?`#${diagnosticContext(rank).position}`:'Sem posição oficial'}</strong><p>{diagnosticContext(rank||{}).official?'Classificação liberada pelos critérios da competição.':'Este diagnóstico é provisório. Participação oficial exige domínio verificado, inscrição válida e evidência suficiente.'}</p></div></div></section>
 </>}
function Issues({rows,all,filter,setFilter}){const counts={fail:all.filter(x=>x.status==='fail').length,warning:all.filter(x=>x.status==='warning').length};return <section className="s3-section in-report"><SectionTitle icon={CircleAlert} eyebrow="ISSUE EXPLORER" title="O que está segurando sua pontuação" text="Abra um item para ver página, fonte e evidência." action={<div className="s3-filters"><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}>Todos {all.length}</button><button className={filter==='fail'?'active bad':''} onClick={()=>setFilter('fail')}>Falhas {counts.fail}</button><button className={filter==='warning'?'active warn':''} onClick={()=>setFilter('warning')}>Atenções {counts.warning}</button></div>}/><div className="s3-issues">{rows.map(i=><details key={i.check_code}><summary><div className={`s3-severity ${i.status}`}>{i.status==='fail'?'!':'△'}</div><div><span>{engineLabels[i.engine]||i.engine} · {i.check_code}</span><h3>{i.title}</h3><p>{i.explanation||'Evidência observada pelo coletor.'}</p></div><div className="s3-issue-meta"><b>{i.affected_pages_count||0}</b><span>página(s)</span><small>{pct(n(i.confidence)*100)} conf.</small></div><ChevronDown/></summary><div className="s3-issue-body"><div><h4>O que encontramos</h4><p>{i.explanation||'Resultado observado.'}</p>{i.recommendation&&<><h4>Como corrigir</h4><p>{i.recommendation}</p></>}</div><div><h4>Páginas afetadas</h4>{i.affected_pages?.length?<ul>{i.affected_pages.map(u=><li key={u}>{u}</li>)}</ul>:<p>Issue consolidado no domínio ou sem page_id individual.</p>}<h4>Fonte</h4><code>{i.source_kind}</code></div><details className="s3-evidence-raw"><summary>Evidência técnica</summary><pre>{JSON.stringify(i.evidence,null,2)}</pre></details></div></details>)}</div></section>}
function Metrics({rows,search,setSearch}){return <section className="s3-section in-report"><SectionTitle icon={Database} eyebrow="OBSERVED METRICS" title="Tudo o que foi realmente coletado" text="Cada linha preserva unidade, classe, fonte e confiança." action={<label className="s3-inline-search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar métrica, engine ou fonte"/></label>}/><div className="s3-metrics"><div className="head"><span>Métrica</span><span>Valor</span><span>Classe</span><span>Confiança</span><span>Fonte</span></div>{rows.map(m=><div className="row" key={m.metric_code}><div><b>{m.name}</b><small>{m.metric_code} · {engineLabels[m.engine]||m.engine}</small></div><strong>{metricValue(m)}</strong><Pill tone={m.evidence_class==='public_dataset'?'cyan':m.evidence_class==='lab'?'warn':'neutral'}>{m.evidence_class}</Pill><span>{pct(n(m.confidence)*100)}</span><code>{m.source_kind}</code></div>)}</div></section>}
function Pages({rows}){return <section className="s3-section in-report"><SectionTitle icon={FileSearch} eyebrow="CRAWL" title="Páginas analisadas" text="Issues permanecem ligadas ao que foi realmente observado."/><div className="s3-pages">{rows.map(p=><article key={p.id}><div className="s3-page-status"><b>{p.http_status||'—'}</b><span>{p.page_type||'page'}</span></div><div><h3>{p.title||p.normalized_url}</h3><p>{p.normalized_url}</p><small>{p.word_count||0} palavras · {p.images_count||0} imagens · {p.forms_count||0} formulário(s)</small></div><div className="s3-page-issues"><span className="bad">{p.errors||0} falhas</span><span className="warn">{p.warnings||0} atenções</span></div></article>)}</div></section>}
function Evidence({report}){const e=report.evidence_dashboard||{};const cov=e.metric_coverage||{};return <section className="s3-section in-report"><SectionTitle icon={ShieldCheck} eyebrow="EVIDENCE OS" title="De onde veio cada conclusão" text="Lab, browser, HTTP, dataset e first-party continuam semanticamente separados."/><div className="s3-evidence-grid">{Object.entries(cov.by_evidence_class||{}).map(([k,v])=><article key={k}><span>{k.replaceAll('_',' ')}</span><strong>{v.observed}<small>/{v.registered}</small></strong><Progress value={v.registered?v.observed/v.registered*100:0}/></article>)}</div><div className="s3-policy">{Object.entries(report.methodology_disclosure||{}).map(([k,v])=><div key={k}>{v===true?<Check/>:<CircleAlert/>}<span>{k.replaceAll('_',' ')}</span></div>)}</div><div className="s3-method"><ShieldCheck/><div><b>Regra central</b><span>Ausência de evidência não vira aprovação. Readiness autônomo não é taxa de conversão, tráfego ou receita. Compra não altera score.</span></div></div></section>}

createRoot(document.getElementById('root')).render(<React.StrictMode><App/></React.StrictMode>);