import { createClient } from 'npm:@supabase/supabase-js@2'

const SUPABASE_URL=Deno.env.get('SUPABASE_URL')!
const ANON_KEY=Deno.env.get('SUPABASE_ANON_KEY')!
const SERVICE_KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
const FUNCTION_SLUG='cozinha360-delivery-v40'
const PUBLIC_APP=(Deno.env.get('C360_PUBLIC_APP_URL')||'https://cozinha-360-os.netlify.app').replace(/\/$/,'')
const anon=createClient(SUPABASE_URL,ANON_KEY,{auth:{persistSession:false,autoRefreshToken:false}})
const admin=createClient(SUPABASE_URL,SERVICE_KEY,{auth:{persistSession:false,autoRefreshToken:false}})
const allowedOrigins=new Set([PUBLIC_APP,'http://localhost:5173','http://127.0.0.1:5173'])

function cors(req:Request){const origin=req.headers.get('origin')||'';return{'Access-Control-Allow-Origin':allowedOrigins.has(origin)?origin:PUBLIC_APP,'Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'GET,POST,PATCH,PUT,OPTIONS','Vary':'Origin','Content-Type':'application/json; charset=utf-8'}}
const reply=(req:Request,data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:cors(req)})
const fail=(req:Request,detail:string,status=400,extra:Record<string,unknown>={})=>reply(req,{detail,...extra},status)
const now=()=>new Date().toISOString()
const val=(value:unknown,max=180)=>String(value??'').trim().slice(0,max)
const num=(value:unknown,fallback=0)=>{const n=Number(value);return Number.isFinite(n)?Math.trunc(n):fallback}
const id=(value:unknown)=>Math.max(0,num(value))
const slug=(value:unknown)=>val(value,90).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,90)
const iso=(value:unknown)=>{if(!value)return null;const d=new Date(String(value));return Number.isNaN(d.getTime())?null:d.toISOString()}
async function json(req:Request){try{return await req.json()}catch{return{}}}
function routePath(req:Request){const p=new URL(req.url).pathname,marker='/'+FUNCTION_SLUG,i=p.indexOf(marker);return i>=0?(p.slice(i+marker.length)||'/'):p}

async function auth(req:Request){const h=req.headers.get('authorization')||'',token=h.startsWith('Bearer ')?h.slice(7):'';if(!token)return null;const {data,error}=await anon.auth.getUser(token);if(error||!data.user)return null;let profile=(await admin.from('users').select('id,email,full_name').eq('auth_user_id',data.user.id).maybeSingle()).data;if(!profile&&data.user.email)profile=(await admin.from('users').select('id,email,full_name').ilike('email',data.user.email).maybeSingle()).data;return profile||null}
async function membership(userId:number,businessId:number,write=false){const row=(await admin.from('memberships').select('id,role').eq('user_id',userId).eq('business_id',businessId).maybeSingle()).data;if(!row)return null;if(write&&!['owner','admin'].includes(row.role))return null;return row}
async function audit(businessId:number,userId:number,action:string,entityType:string,entityId:string,payload:unknown){await admin.from('audit_logs').insert({business_id:businessId,actor_user_id:userId,action,entity_type:entityType,entity_id:entityId,payload_json:JSON.stringify(payload??{})})}
async function validBrand(businessId:number,brandId:number|null){if(!brandId)return true;return Boolean((await admin.from('brands').select('id').eq('business_id',businessId).eq('id',brandId).eq('soft_deleted',false).maybeSingle()).data)}
async function validDriver(businessId:number,driverId:number|null){if(!driverId)return true;return Boolean((await admin.from('delivery_drivers').select('id').eq('business_id',businessId).eq('id',driverId).eq('active',true).maybeSingle()).data)}
async function validZone(businessId:number,zoneId:number|null){if(!zoneId)return true;return Boolean((await admin.from('delivery_zones').select('id').eq('business_id',businessId).eq('id',zoneId).eq('active',true).maybeSingle()).data)}

const brandLimits:Record<string,number>={start:1,pro:3,'360':10}
async function overview(req:Request,businessId:number){
  const [business,brands,channels,orders,items,customers,zones,drivers,deliveries,loyalty,promos,stores,connections,billing]=await Promise.all([
    admin.from('businesses').select('id,name,city,currency').eq('id',businessId).single(),
    admin.from('brands').select('id,business_id,name,active,soft_deleted,slug,primary_channel,sort_order').eq('business_id',businessId).eq('soft_deleted',false).order('sort_order').order('id'),
    admin.from('channels').select('id,name,fee_bps,fixed_fee_cents,delivery_cents,promo_cents,media_cents,traffic_active').eq('business_id',businessId).order('id'),
    admin.from('orders').select('id,brand_id,channel_id,customer_id,status,source,total_cents,variable_cost_cents,contribution_cents,paid,delayed,error_flag,version,created_at,updated_at').eq('business_id',businessId).order('created_at',{ascending:false}).limit(120),
    admin.from('order_items').select('id,order_id,product_id,quantity,unit_price_cents,unit_variable_cost_cents').eq('business_id',businessId).order('id'),
    admin.from('customers').select('id,name,phone,email,consent_marketing,opted_out_at,created_at').eq('business_id',businessId).order('id'),
    admin.from('delivery_zones').select('*').eq('business_id',businessId).order('active',{ascending:false}).order('id'),
    admin.from('delivery_drivers').select('*').eq('business_id',businessId).order('active',{ascending:false}).order('id'),
    admin.from('deliveries').select('*').eq('business_id',businessId).order('created_at',{ascending:false}).limit(120),
    admin.from('loyalty_programs').select('*').eq('business_id',businessId).maybeSingle(),
    admin.from('delivery_promos').select('*').eq('business_id',businessId).order('active',{ascending:false}).order('id'),
    admin.from('storefronts').select('id,business_id,brand_id,channel_id,slug,display_name,active').eq('business_id',businessId).order('id'),
    admin.from('integration_connections').select('id,provider,display_name,status,mode,last_success_at,last_error_at,last_error').eq('business_id',businessId).order('provider'),
    admin.from('business_billing_accounts').select('plan_key,status,current_period_end,cancel_at_period_end').eq('business_id',businessId).maybeSingle(),
  ])
  if(business.error)return fail(req,'Operação não encontrada',404)
  const failures=[brands.error,channels.error,orders.error,items.error,customers.error,zones.error,drivers.error,deliveries.error,promos.error,stores.error,connections.error].filter(Boolean)
  if(failures.length){console.error('delivery overview',failures);return fail(req,'Não foi possível montar o Delivery 360',500)}
  const brandRows=brands.data||[],channelRows=channels.data||[],orderRows=orders.data||[],itemRows=items.data||[],customerRows=customers.data||[],deliveryRows=deliveries.data||[]
  const itemMap=new Map<number,any[]>();for(const item of itemRows){const rows=itemMap.get(Number(item.order_id))||[];rows.push(item);itemMap.set(Number(item.order_id),rows)}
  const customerMap=new Map(customerRows.map(row=>[Number(row.id),row])),channelMap=new Map(channelRows.map(row=>[Number(row.id),row])),brandMap=new Map(brandRows.map(row=>[Number(row.id),row])),deliveryMap=new Map(deliveryRows.map(row=>[Number(row.order_id),row]))
  const enriched=orderRows.map(row=>({...row,items:itemMap.get(Number(row.id))||[],customer:row.customer_id?customerMap.get(Number(row.customer_id))||null:null,channel:row.channel_id?channelMap.get(Number(row.channel_id))||null:null,brand:row.brand_id?brandMap.get(Number(row.brand_id))||null:null,delivery:deliveryMap.get(Number(row.id))||null}))
  const active=new Set(['new','confirmed','production','checking','awaiting_delivery']),open=enriched.filter(row=>active.has(String(row.status))),paid=orderRows.filter(row=>row.paid)
  const brandStats=brandRows.map(brand=>{const rows=orderRows.filter(o=>Number(o.brand_id)===Number(brand.id)),done=rows.filter(o=>o.paid);return{brand_id:brand.id,orders:rows.length,open_orders:rows.filter(o=>active.has(String(o.status))).length,revenue_cents:done.reduce((s,o)=>s+num(o.total_cents),0),contribution_cents:done.reduce((s,o)=>s+num(o.contribution_cents),0)}})
  const plan=String(billing.data?.plan_key||'start').toLowerCase()
  return reply(req,{version:'4.0.0',business:business.data,summary:{open_orders:open.length,delayed_orders:open.filter(o=>o.delayed).length,paid_orders:paid.length,revenue_cents:paid.reduce((s,o)=>s+num(o.total_cents),0),contribution_cents:paid.reduce((s,o)=>s+num(o.contribution_cents),0),available_drivers:(drivers.data||[]).filter(d=>d.active&&d.status==='available').length,active_zones:(zones.data||[]).filter(z=>z.active).length},plan:{key:plan,status:billing.data?.status||'observe_only',brand_limit:brandLimits[plan]||1,current_period_end:billing.data?.current_period_end||null,cancel_at_period_end:Boolean(billing.data?.cancel_at_period_end)},brands:brandRows,brand_stats:brandStats,channels:channelRows,orders:enriched,zones:zones.data||[],drivers:drivers.data||[],deliveries:deliveryRows,loyalty:loyalty.data||{business_id:businessId,mode:'off',points_per_real:1,cashback_bps:0,redeem_threshold:0,active:false},promos:promos.data||[],storefronts:stores.data||[],connections:connections.data||[]})
}

async function createBrand(req:Request,businessId:number,userId:number,p:any){const name=val(p.name,120);if(name.length<2)return fail(req,'Informe o nome da marca');const brandSlug=slug(p.slug||name);if(!brandSlug)return fail(req,'Slug da marca inválido');const r=await admin.from('brands').insert({business_id:businessId,name,slug:brandSlug,primary_channel:val(p.primary_channel||'direct',32)||'direct',sort_order:num(p.sort_order),active:p.active!==false,soft_deleted:false}).select('*').single();if(r.error)return fail(req,r.error.code==='23505'?'Já existe uma marca com esse nome ou slug.':'Não foi possível criar a marca',r.error.code==='23505'?409:400);await audit(businessId,userId,'create','brand',String(r.data.id),{name:r.data.name,slug:r.data.slug});return reply(req,{brand:r.data},201)}
async function patchBrand(req:Request,businessId:number,userId:number,brandId:number,p:any){const current=(await admin.from('brands').select('*').eq('business_id',businessId).eq('id',brandId).eq('soft_deleted',false).maybeSingle()).data;if(!current)return fail(req,'Marca não encontrada',404);const patch:any={};if(p.name!==undefined){patch.name=val(p.name,120);if(patch.name.length<2)return fail(req,'Nome inválido')}if(p.slug!==undefined){patch.slug=slug(p.slug);if(!patch.slug)return fail(req,'Slug inválido')}if(p.active!==undefined)patch.active=Boolean(p.active);if(p.primary_channel!==undefined)patch.primary_channel=val(p.primary_channel,32)||'direct';if(p.sort_order!==undefined)patch.sort_order=num(p.sort_order);if(p.soft_deleted===true){patch.soft_deleted=true;patch.active=false}const r=await admin.from('brands').update(patch).eq('business_id',businessId).eq('id',brandId).select('*').single();if(r.error)return fail(req,r.error.code==='23505'?'Slug já utilizado.':'Não foi possível atualizar a marca',r.error.code==='23505'?409:400);await audit(businessId,userId,'update','brand',String(brandId),patch);return reply(req,{brand:r.data})}

async function createZone(req:Request,businessId:number,userId:number,p:any){const zoneType=val(p.zone_type||'neighborhood',24);if(!['radius','neighborhood','cep'].includes(zoneType))return fail(req,'Tipo de zona inválido');const brandId=id(p.brand_id)||null;if(!await validBrand(businessId,brandId))return fail(req,'Marca inválida',404);const row={business_id:businessId,brand_id:brandId,name:val(p.name,120),zone_type:zoneType,match_value:val(p.match_value,180),fee_cents:Math.max(0,num(p.fee_cents)),min_order_cents:Math.max(0,num(p.min_order_cents)),eta_min:Math.min(360,Math.max(5,num(p.eta_min,45))),active:p.active!==false,version:1};if(!row.name)return fail(req,'Informe o nome da zona');const r=await admin.from('delivery_zones').insert(row).select('*').single();if(r.error)return fail(req,'Não foi possível criar a zona',400);await audit(businessId,userId,'create','delivery_zone',String(r.data.id),row);return reply(req,{zone:r.data},201)}
async function patchZone(req:Request,businessId:number,userId:number,zoneId:number,p:any){const current=(await admin.from('delivery_zones').select('*').eq('business_id',businessId).eq('id',zoneId).maybeSingle()).data;if(!current)return fail(req,'Zona não encontrada',404);if(p.version!==undefined&&num(p.version)!==num(current.version))return fail(req,'Zona foi alterada em outra sessão.',409,{code:'VERSION_CONFLICT'});const patch:any={version:num(current.version)+1};if(p.name!==undefined)patch.name=val(p.name,120);if(p.zone_type!==undefined){const v=val(p.zone_type,24);if(!['radius','neighborhood','cep'].includes(v))return fail(req,'Tipo de zona inválido');patch.zone_type=v}if(p.match_value!==undefined)patch.match_value=val(p.match_value,180);if(p.fee_cents!==undefined)patch.fee_cents=Math.max(0,num(p.fee_cents));if(p.min_order_cents!==undefined)patch.min_order_cents=Math.max(0,num(p.min_order_cents));if(p.eta_min!==undefined)patch.eta_min=Math.min(360,Math.max(5,num(p.eta_min)));if(p.active!==undefined)patch.active=Boolean(p.active);if(p.brand_id!==undefined){const b=id(p.brand_id)||null;if(!await validBrand(businessId,b))return fail(req,'Marca inválida',404);patch.brand_id=b}const r=await admin.from('delivery_zones').update(patch).eq('business_id',businessId).eq('id',zoneId).eq('version',current.version).select('*').maybeSingle();if(r.error||!r.data)return fail(req,'Conflito ao salvar zona',409);await audit(businessId,userId,'update','delivery_zone',String(zoneId),patch);return reply(req,{zone:r.data})}

async function createDriver(req:Request,businessId:number,userId:number,p:any){const vehicle=val(p.vehicle||'moto',20),status=val(p.status||'offline',20);if(!['foot','bike','moto','car','utility'].includes(vehicle))return fail(req,'Veículo inválido');if(!['available','busy','offline'].includes(status))return fail(req,'Status inválido');const row={business_id:businessId,name:val(p.name,120),phone:val(p.phone,40),vehicle,status,active:p.active!==false,version:1};if(!row.name)return fail(req,'Informe o nome do entregador');const r=await admin.from('delivery_drivers').insert(row).select('*').single();if(r.error)return fail(req,'Não foi possível adicionar o entregador',400);await audit(businessId,userId,'create','delivery_driver',String(r.data.id),{name:r.data.name,vehicle:r.data.vehicle,status:r.data.status});return reply(req,{driver:r.data},201)}
async function patchDriver(req:Request,businessId:number,userId:number,driverId:number,p:any){const current=(await admin.from('delivery_drivers').select('*').eq('business_id',businessId).eq('id',driverId).maybeSingle()).data;if(!current)return fail(req,'Entregador não encontrado',404);if(p.version!==undefined&&num(p.version)!==num(current.version))return fail(req,'Entregador foi alterado em outra sessão.',409,{code:'VERSION_CONFLICT'});const patch:any={version:num(current.version)+1};if(p.name!==undefined)patch.name=val(p.name,120);if(p.phone!==undefined)patch.phone=val(p.phone,40);if(p.vehicle!==undefined){const v=val(p.vehicle,20);if(!['foot','bike','moto','car','utility'].includes(v))return fail(req,'Veículo inválido');patch.vehicle=v}if(p.status!==undefined){const v=val(p.status,20);if(!['available','busy','offline'].includes(v))return fail(req,'Status inválido');patch.status=v}if(p.active!==undefined)patch.active=Boolean(p.active);const r=await admin.from('delivery_drivers').update(patch).eq('business_id',businessId).eq('id',driverId).eq('version',current.version).select('*').maybeSingle();if(r.error||!r.data)return fail(req,'Conflito ao salvar entregador',409);await audit(businessId,userId,'update','delivery_driver',String(driverId),patch);return reply(req,{driver:r.data})}

async function saveDelivery(req:Request,businessId:number,userId:number,orderId:number,p:any){const order=(await admin.from('orders').select('id,status').eq('business_id',businessId).eq('id',orderId).maybeSingle()).data;if(!order)return fail(req,'Pedido não encontrado',404);const driverId=id(p.driver_id)||null,zoneId=id(p.zone_id)||null;if(!await validDriver(businessId,driverId))return fail(req,'Entregador inválido',404);if(!await validZone(businessId,zoneId))return fail(req,'Zona inválida',404);const status=val(p.status||(driverId?'assigned':'waiting'),24);if(!['waiting','assigned','picked_up','delivered','failed','cancelled'].includes(status))return fail(req,'Status de entrega inválido');const current=(await admin.from('deliveries').select('*').eq('business_id',businessId).eq('order_id',orderId).maybeSingle()).data;if(current&&p.version!==undefined&&num(p.version)!==num(current.version))return fail(req,'Entrega foi atualizada em outra sessão.',409,{code:'VERSION_CONFLICT'});const row:any={business_id:businessId,order_id:orderId,driver_id:driverId,zone_id:zoneId,status,fee_cents:Math.max(0,num(p.fee_cents,current?.fee_cents||0)),promised_at:p.promised_at!==undefined?iso(p.promised_at):(current?.promised_at||null),notes:val(p.notes??current?.notes??'',1000),version:current?num(current.version)+1:1};if(status==='picked_up'&&!current?.picked_up_at)row.picked_up_at=now();if(status==='delivered'&&!current?.delivered_at)row.delivered_at=now();let saved:any,error:any;if(current){const r=await admin.from('deliveries').update(row).eq('id',current.id).eq('business_id',businessId).eq('version',current.version).select('*').maybeSingle();saved=r.data;error=r.error}else{const r=await admin.from('deliveries').insert(row).select('*').single();saved=r.data;error=r.error}if(error||!saved)return fail(req,'Não foi possível salvar a entrega',current?409:400);if(driverId&&['assigned','picked_up','delivered'].includes(status)){const driver=(await admin.from('delivery_drivers').select('version').eq('business_id',businessId).eq('id',driverId).maybeSingle()).data;if(driver)await admin.from('delivery_drivers').update({status:status==='delivered'?'available':'busy',version:num(driver.version)+1}).eq('business_id',businessId).eq('id',driverId).eq('version',driver.version)}await audit(businessId,userId,current?'update':'create','delivery',String(saved.id),{order_id:orderId,driver_id:driverId,zone_id:zoneId,status,fee_cents:saved.fee_cents});return reply(req,{delivery:saved},current?200:201)}

async function saveLoyalty(req:Request,businessId:number,userId:number,p:any){const mode=val(p.mode||'off',20);if(!['off','points','cashback'].includes(mode))return fail(req,'Modo de fidelidade inválido');const points=Math.max(0,Number(p.points_per_real??1));if(!Number.isFinite(points))return fail(req,'Pontuação inválida');const row={business_id:businessId,mode,points_per_real:points,cashback_bps:Math.min(5000,Math.max(0,num(p.cashback_bps))),redeem_threshold:Math.max(0,num(p.redeem_threshold)),active:Boolean(p.active)&&mode!=='off',updated_by_user_id:userId,updated_at:now()};const r=await admin.from('loyalty_programs').upsert(row,{onConflict:'business_id'}).select('*').single();if(r.error)return fail(req,'Não foi possível salvar fidelidade',400);await audit(businessId,userId,'update','loyalty_program',String(businessId),row);return reply(req,{loyalty:r.data})}
async function createPromo(req:Request,businessId:number,userId:number,p:any){const discount=val(p.discount_type,24);if(!['percent','fixed','free_delivery'].includes(discount))return fail(req,'Tipo de cupom inválido');const brandId=id(p.brand_id)||null;if(!await validBrand(businessId,brandId))return fail(req,'Marca inválida',404);const code=val(p.code,40).toUpperCase().replace(/[^A-Z0-9_-]/g,'');if(code.length<3)return fail(req,'Código precisa ter ao menos 3 caracteres');const row={business_id:businessId,brand_id:brandId,code,discount_type:discount,value:Math.max(0,num(p.value)),min_order_cents:Math.max(0,num(p.min_order_cents)),max_uses:id(p.max_uses)||null,starts_at:iso(p.starts_at),ends_at:iso(p.ends_at),active:p.active!==false};const r=await admin.from('delivery_promos').insert(row).select('*').single();if(r.error)return fail(req,r.error.code==='23505'?'Cupom já existe.':'Não foi possível criar o cupom',r.error.code==='23505'?409:400);await audit(businessId,userId,'create','delivery_promo',String(r.data.id),{code:r.data.code,discount_type:r.data.discount_type,value:r.data.value});return reply(req,{promo:r.data},201)}

Deno.serve(async(req:Request)=>{
  if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(req)})
  const path=routePath(req),method=req.method
  if(path==='/health'&&method==='GET')return reply(req,{status:'ok',service:FUNCTION_SLUG,version:'4.0.0'})
  const user=await auth(req);if(!user)return fail(req,'Sessão inválida ou expirada',401)
  const match=path.match(/^\/businesses\/(\d+)(?:\/(.*))?$/);if(!match)return fail(req,'Rota não encontrada',404)
  const businessId=id(match[1]);if(!businessId)return fail(req,'Operação inválida',400)
  const rest=match[2]||'overview',write=method!=='GET',member=await membership(Number(user.id),businessId,write);if(!member)return fail(req,write?'Somente owner/admin pode alterar o Delivery 360.':'Você não participa desta operação.',403)
  const p=write?await json(req):{}
  try{
    if(method==='GET'&&rest==='overview')return await overview(req,businessId)
    if(method==='POST'&&rest==='brands')return await createBrand(req,businessId,Number(user.id),p)
    let m=rest.match(/^brands\/(\d+)$/);if(method==='PATCH'&&m)return await patchBrand(req,businessId,Number(user.id),id(m[1]),p)
    if(method==='POST'&&rest==='zones')return await createZone(req,businessId,Number(user.id),p)
    m=rest.match(/^zones\/(\d+)$/);if(method==='PATCH'&&m)return await patchZone(req,businessId,Number(user.id),id(m[1]),p)
    if(method==='POST'&&rest==='drivers')return await createDriver(req,businessId,Number(user.id),p)
    m=rest.match(/^drivers\/(\d+)$/);if(method==='PATCH'&&m)return await patchDriver(req,businessId,Number(user.id),id(m[1]),p)
    m=rest.match(/^deliveries\/(\d+)$/);if(method==='PUT'&&m)return await saveDelivery(req,businessId,Number(user.id),id(m[1]),p)
    if(method==='PUT'&&rest==='loyalty')return await saveLoyalty(req,businessId,Number(user.id),p)
    if(method==='POST'&&rest==='promos')return await createPromo(req,businessId,Number(user.id),p)
    return fail(req,'Rota não encontrada',404)
  }catch(error){console.error('delivery-v40',error);return fail(req,'Falha interna no Delivery 360',500)}
})
