import { createClient } from 'npm:@supabase/supabase-js@2'

const URL=Deno.env.get('SUPABASE_URL')!,ANON=Deno.env.get('SUPABASE_ANON_KEY')!,SERVICE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
const APP=(Deno.env.get('C360_PUBLIC_APP_URL')||'https://cozinha-360-os.netlify.app').replace(/\/$/,'')
const SLUG='cozinha360-direct-v17',anon=createClient(URL,ANON,{auth:{persistSession:false,autoRefreshToken:false}}),admin=createClient(URL,SERVICE,{auth:{persistSession:false,autoRefreshToken:false}})
const origins=new Set([APP,'http://localhost:5173','http://127.0.0.1:5173'])
function headers(req:Request){const o=req.headers.get('origin')||'';return{'Access-Control-Allow-Origin':origins.has(o)?o:APP,'Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'GET,POST,PATCH,OPTIONS','Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','Vary':'Origin','X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY'}}
const out=(req:Request,data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:headers(req)}),bad=(req:Request,detail:string,status=400)=>out(req,{detail},status)
const body=async(req:Request)=>{try{return await req.json()}catch{return{}}},txt=(v:unknown,max=160)=>String(v??'').trim().slice(0,max),digits=(v:unknown)=>txt(v,40).replace(/\D/g,'')
const norm=(v:unknown)=>txt(v,180).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\s+/g,' ').trim()
function pathOf(req:Request){const p=new URL(req.url).pathname,m='/'+SLUG,i=p.indexOf(m);return i>=0?(p.slice(i+m.length)||'/'):p}
function friendly(e:unknown){const raw=String((e as any)?.message||e),pairs:Record<string,string>={ITEMS_INVALID:'Itens inválidos.',PRODUCT_UNAVAILABLE:'Um produto não está mais disponível.',ZONE_NOT_FOUND:'Este endereço ainda está fora da área de entrega cadastrada.',DELIVERY_MIN_ORDER:'O pedido não atinge o mínimo desta região.',PROMO_INVALID:'Cupom inválido.',PROMO_NOT_STARTED:'Este cupom ainda não começou.',PROMO_EXPIRED:'Este cupom expirou.',PROMO_LIMIT_REACHED:'Este cupom atingiu o limite de usos.',PROMO_MIN_ORDER:'O pedido não atinge o mínimo do cupom.',SCHEDULE_DISABLED:'Esta cozinha não aceita pedidos agendados.',SCHEDULE_INVALID:'Escolha um horário futuro válido.',SCHEDULE_TOO_FAR:'O horário está além da janela de agendamento.',DELIVERY_ZONE_REQUIRED:'Selecione uma região de entrega válida.',DELIVERY_ZONE_INVALID:'A região não está mais disponível.',SCHEDULED_ORDER_DISABLED:'Esta cozinha não aceita pedidos agendados.',SCHEDULED_ORDER_PAST:'Escolha um horário futuro.',SCHEDULED_ORDER_TOO_FAR:'O horário está além da janela permitida.'};for(const [k,v] of Object.entries(pairs))if(raw.includes(k))return v;return raw}
async function user(req:Request){const h=req.headers.get('authorization')||'',t=h.startsWith('Bearer ')?h.slice(7):'';if(!t)return null;const r=await anon.auth.getUser(t);if(r.error||!r.data.user)return null;const a=r.data.user;let p=(await admin.from('users').select('id,email,full_name').eq('auth_user_id',a.id).maybeSingle()).data;if(!p&&a.email)p=(await admin.from('users').select('id,email,full_name').ilike('email',a.email).maybeSingle()).data;return p||null}
async function member(uid:number,bid:number,write=false){const r=(await admin.from('memberships').select('role').eq('user_id',uid).eq('business_id',bid).maybeSingle()).data;if(!r)return null;if(write&&!['owner','admin'].includes(r.role))return null;return r}

async function store(slug:string){const s=(await admin.from('storefronts').select('id,business_id,brand_id,channel_id,slug,display_name,active').ilike('slug',slug).eq('active',true).maybeSingle()).data;if(!s)return null;const [b,brand,ps,prices,settings,zones]=await Promise.all([admin.from('businesses').select('id,name,city,currency').eq('id',s.business_id).maybeSingle(),s.brand_id?admin.from('brands').select('id,name').eq('id',s.brand_id).maybeSingle():Promise.resolve({data:null}),admin.from('products').select('id,name,category,brand_id').eq('business_id',s.business_id).eq('soft_deleted',false).eq('active',true).order('name'),admin.from('product_channel_prices').select('product_id,sale_price_cents').eq('business_id',s.business_id).eq('channel_id',s.channel_id).gt('sale_price_cents',0),admin.from('delivery_settings').select('scheduled_orders_enabled,max_scheduled_days,default_eta_min,customer_tracking_enabled').eq('business_id',s.business_id).maybeSingle(),admin.from('delivery_zones').select('id').eq('business_id',s.business_id).eq('active',true)]);if(ps.error||prices.error)throw ps.error||prices.error;const pm=new Map((prices.data||[]).map((x:any)=>[Number(x.product_id),Number(x.sale_price_cents)])),products=(ps.data||[]).filter((p:any)=>(!s.brand_id||Number(p.brand_id)===Number(s.brand_id))&&pm.has(Number(p.id))).map((p:any)=>({...p,sale_price_cents:pm.get(Number(p.id))})),cfg=settings.data||{scheduled_orders_enabled:true,max_scheduled_days:7,default_eta_min:45,customer_tracking_enabled:false};return{storefront:s,business:b.data,brand:(brand as any).data||null,products,fulfillment:{pickup:true,delivery:(zones.data||[]).length>0,scheduled_orders:Boolean(cfg.scheduled_orders_enabled),max_scheduled_days:Number(cfg.max_scheduled_days||7),customer_tracking:Boolean(cfg.customer_tracking_enabled)}}}
function items(payload:any,s:any){const raw=Array.isArray(payload.items)?payload.items.slice(0,20):[],rows=raw.map((x:any)=>({product_id:Number(x.product_id),quantity:Number(x.quantity||1)}));if(!rows.length||rows.some((x:any)=>!Number.isInteger(x.product_id)||!Number.isInteger(x.quantity)||x.quantity<1||x.quantity>20))throw new Error('ITEMS_INVALID');const pm=new Map(s.products.map((p:any)=>[Number(p.id),p]));let subtotal=0;for(const row of rows){const p=pm.get(row.product_id);if(!p)throw new Error('PRODUCT_UNAVAILABLE');subtotal+=Number((p as any).sale_price_cents)*row.quantity}return{rows,subtotal}}
function km(a:number,b:number,c:number,d:number){const r=(x:number)=>x*Math.PI/180,R=6371,da=r(c-a),db=r(d-b),q=Math.sin(da/2)**2+Math.cos(r(a))*Math.cos(r(c))*Math.sin(db/2)**2;return 2*R*Math.asin(Math.sqrt(q))}
async function zoneFor(s:any,p:any){const r=await admin.from('delivery_zones').select('*').eq('business_id',s.storefront.business_id).eq('active',true);if(r.error)throw r.error;const rows=(r.data||[]).filter((z:any)=>z.brand_id==null||s.storefront.brand_id==null||Number(z.brand_id)===Number(s.storefront.brand_id)).sort((a:any,b:any)=>Number(Boolean(b.brand_id))-Number(Boolean(a.brand_id))),nb=norm(p.neighborhood),cep=digits(p.postal_code),lat=Number(p.latitude),lng=Number(p.longitude);for(const z of rows){if(z.zone_type==='neighborhood'&&nb&&norm(z.match_value)===nb)return z;if(z.zone_type==='cep'&&cep&&digits(z.match_value)&&cep.startsWith(digits(z.match_value)))return z;if(z.zone_type==='radius'&&Number.isFinite(lat)&&Number.isFinite(lng)&&z.center_lat!=null&&z.center_lng!=null&&z.radius_km!=null&&km(Number(z.center_lat),Number(z.center_lng),lat,lng)<=Number(z.radius_km))return z}return null}
async function promo(s:any,code:string,subtotal:number,fee:number){if(!code)return{row:null,discount:0};const r=await admin.from('delivery_promos').select('*').eq('business_id',s.storefront.business_id).eq('active',true).ilike('code',code).maybeSingle();if(r.error)throw r.error;const p=r.data;if(!p)throw new Error('PROMO_INVALID');if(p.brand_id!=null&&s.storefront.brand_id!=null&&Number(p.brand_id)!==Number(s.storefront.brand_id))throw new Error('PROMO_INVALID');const now=Date.now();if(p.starts_at&&new Date(p.starts_at).getTime()>now)throw new Error('PROMO_NOT_STARTED');if(p.ends_at&&new Date(p.ends_at).getTime()<now)throw new Error('PROMO_EXPIRED');if(p.max_uses!=null&&Number(p.used_count)>=Number(p.max_uses))throw new Error('PROMO_LIMIT_REACHED');if(subtotal<Number(p.min_order_cents||0))throw new Error('PROMO_MIN_ORDER');let d=0;if(p.discount_type==='percent')d=Math.min(subtotal,Math.round(subtotal*Math.min(Number(p.value||0),100)/100));else if(p.discount_type==='fixed')d=Math.min(subtotal,Number(p.value||0));else if(p.discount_type==='free_delivery')d=fee;return{row:p,discount:d}}
async function quote(s:any,p:any){const x=items(p,s),fulfillment=p.fulfillment==='delivery'?'delivery':'pickup';let z:any=null,base=0,fee=0;if(fulfillment==='delivery'){z=await zoneFor(s,p);if(!z)throw new Error('ZONE_NOT_FOUND');if(x.subtotal<Number(z.min_order_cents||0))throw new Error('DELIVERY_MIN_ORDER');base=Number(z.fee_cents||0);fee=Number(z.free_delivery_over_cents||0)>0&&x.subtotal>=Number(z.free_delivery_over_cents)?0:base}const scheduled=txt(p.scheduled_for,60);if(scheduled){if(!s.fulfillment.scheduled_orders)throw new Error('SCHEDULE_DISABLED');const t=new Date(scheduled).getTime();if(!Number.isFinite(t)||t<Date.now())throw new Error('SCHEDULE_INVALID');if(t>Date.now()+s.fulfillment.max_scheduled_days*86400000)throw new Error('SCHEDULE_TOO_FAR')}const pc=txt(p.promo_code,40).toUpperCase(),pr=await promo(s,pc,x.subtotal,fee),total=Math.max(0,x.subtotal+fee-pr.discount);return{items:x.rows,fulfillment,subtotal_cents:x.subtotal,zone:z?{id:z.id,name:z.name,eta_min:z.eta_min,fee_cents:Number(z.fee_cents||0),free_delivery_over_cents:Number(z.free_delivery_over_cents||0),min_order_cents:Number(z.min_order_cents||0)}:null,base_delivery_fee_cents:base,delivery_fee_cents:fee,discount_cents:pr.discount,promo:pr.row?{id:pr.row.id,code:pr.row.code,discount_type:pr.row.discount_type,value:pr.row.value}:null,total_cents:total,scheduled_for:scheduled||null}}

Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:headers(req)});const path=pathOf(req),method=req.method;try{
 if(path==='/livez'&&method==='GET')return out(req,{ok:true,service:SLUG,version:'1.8.0',delivery_checkout:'v40'});if(path==='/readyz'&&method==='GET'){const checks=await Promise.all([admin.from('storefronts').select('id',{head:true,count:'exact'}),admin.from('direct_order_checkouts').select('order_id',{head:true,count:'exact'})]);return checks.some(x=>x.error)?bad(req,'database_not_ready',503):out(req,{ok:true,database:'ready',delivery_checkout:'ready',version:'1.8.0'})}
 let m=path.match(/^\/track\/([0-9a-f-]{36})$/i);if(m&&method==='GET'){const d=(await admin.from('deliveries').select('tracking_token,status,promised_at,scheduled_for,ready_at,picked_up_at,delivered_at,tracking_enabled,order_id').eq('tracking_token',m[1]).maybeSingle()).data;if(!d||!d.tracking_enabled)return bad(req,'Rastreamento indisponível',404);const o=(await admin.from('orders').select('brand_id').eq('id',d.order_id).maybeSingle()).data,brand=o?.brand_id?(await admin.from('brands').select('name').eq('id',o.brand_id).maybeSingle()).data:null;return out(req,{status:d.status,promised_at:d.promised_at,scheduled_for:d.scheduled_for,ready_at:d.ready_at,picked_up_at:d.picked_up_at,delivered_at:d.delivered_at,order_id:d.order_id,brand:brand?.name||null})}
 m=path.match(/^\/store\/([a-z0-9-]{3,60})$/);if(m&&method==='GET'){const s=await store(m[1]);return s?out(req,s):bad(req,'Loja não encontrada',404)}
 const qm=path.match(/^\/store\/([a-z0-9-]{3,60})\/quote$/);if(qm&&method==='POST'){const s=await store(qm[1]);if(!s)return bad(req,'Loja não encontrada',404);try{return out(req,await quote(s,await body(req)))}catch(e){return bad(req,friendly(e),422)}}
 if(m&&method==='POST'){const s=await store(m[1]);if(!s)return bad(req,'Loja não encontrada',404);const p:any=await body(req);let q:any;try{q=await quote(s,p)}catch(e){return bad(req,friendly(e),422)}const key=txt(p.client_order_key,100);if(key.length<8)return bad(req,'Identificador do pedido inválido',422);const a=p.attribution||{},created=await admin.rpc('c360_create_direct_order',{p_slug:m[1],p_client_order_key:key,p_items:q.items,p_customer_name:txt(p.customer_name,160),p_phone:txt(p.phone,40),p_email:txt(p.email,320),p_consent_marketing:Boolean(p.consent_marketing),p_session_key:txt(a.session_key,120)||null,p_referrer:txt(a.referrer,500)||null,p_utm_source:txt(a.utm_source,120)||null,p_utm_medium:txt(a.utm_medium,120)||null,p_utm_campaign:txt(a.utm_campaign,160)||null,p_utm_content:txt(a.utm_content,160)||null,p_utm_term:txt(a.utm_term,160)||null,p_gclid:txt(a.gclid,220)||null,p_fbclid:txt(a.fbclid,220)||null,p_ttclid:txt(a.ttclid,220)||null});if(created.error){const x=String(created.error.message||'');if(x.includes('PRODUCT_PRICE'))return bad(req,'Preço indisponível',409);if(x.includes('PRODUCT_NOT'))return bad(req,'Produto indisponível',409);throw created.error}const final=await admin.rpc('c360_finalize_direct_order_v40',{p_order_id:Number(created.data.id),p_business_id:Number(s.storefront.business_id),p_zone_id:q.zone?.id||null,p_promo_code:q.promo?.code||null,p_fulfillment:q.fulfillment,p_address_line:txt(p.address_line,300)||null,p_neighborhood:txt(p.neighborhood,120)||null,p_postal_code:txt(p.postal_code,20)||null,p_address_reference:txt(p.address_reference,220)||null,p_latitude:Number.isFinite(Number(p.latitude))?Number(p.latitude):null,p_longitude:Number.isFinite(Number(p.longitude))?Number(p.longitude):null,p_scheduled_for:q.scheduled_for,p_brand_consent:Boolean(p.consent_marketing),p_quote_snapshot:q});if(final.error)return bad(req,friendly(final.error),422);let tracking_url:null|string=null;if(final.data?.delivery_id&&s.fulfillment.customer_tracking){const dr=(await admin.from('deliveries').select('tracking_token').eq('id',Number(final.data.delivery_id)).eq('business_id',s.storefront.business_id).maybeSingle()).data;if(dr?.tracking_token)tracking_url=`${APP}/?track=${encodeURIComponent(String(dr.tracking_token))}`}return out(req,{...final.data,tracking_url},201)}
 const u=await user(req);if(!u)return bad(req,'Sessão inválida',401);m=path.match(/^\/businesses\/(\d+)\/storefronts$/);if(m&&method==='GET'){const bid=Number(m[1]);if(!await member(Number(u.id),bid))return bad(req,'Sem acesso',403);const r=await admin.from('storefronts').select('*,brands(name),channels(name)').eq('business_id',bid).order('created_at');if(r.error)throw r.error;return out(req,r.data||[])}
 if(m&&method==='POST'){const bid=Number(m[1]);if(!await member(Number(u.id),bid,true))return bad(req,'Somente owner/admin',403);const p:any=await body(req),ss=txt(p.slug,60).toLowerCase(),name=txt(p.display_name,160);if(!/^[a-z0-9][a-z0-9-]{2,59}$/.test(ss))return bad(req,'Slug inválido',422);if(name.length<2)return bad(req,'Nome inválido',422);let channel=Number(p.channel_id||0);if(!channel){const e=(await admin.from('channels').select('id').eq('business_id',bid).ilike('name','Pedido direto').maybeSingle()).data;if(e)channel=Number(e.id);else{const c=await admin.from('channels').insert({business_id:bid,name:'Pedido direto',fee_bps:0,fixed_fee_cents:0,delivery_cents:0,promo_cents:0,media_cents:0,traffic_active:false}).select('id').single();if(c.error)throw c.error;channel=Number(c.data.id)}}const brand=p.brand_id?Number(p.brand_id):null;if(brand&&!((await admin.from('brands').select('id').eq('business_id',bid).eq('id',brand).eq('soft_deleted',false).maybeSingle()).data))return bad(req,'Marca inválida',422);const r=await admin.from('storefronts').insert({business_id:bid,brand_id:brand,channel_id:channel,slug:ss,display_name:name,active:p.active!==false}).select('*').single();if(r.error)return bad(req,String(r.error.message).toLowerCase().includes('duplicate')?'Esse endereço já está em uso':'Não foi possível criar a loja',String(r.error.message).toLowerCase().includes('duplicate')?409:400);await admin.from('audit_logs').insert({business_id:bid,actor_user_id:u.id,action:'storefront.created',entity_type:'storefront',entity_id:String(r.data.id),payload_json:JSON.stringify({slug:ss,brand_id:brand,channel_id:channel})});return out(req,r.data,201)}
 m=path.match(/^\/businesses\/(\d+)\/storefronts\/(\d+)$/);if(m&&method==='PATCH'){const bid=Number(m[1]),sid=Number(m[2]);if(!await member(Number(u.id),bid,true))return bad(req,'Somente owner/admin',403);const p:any=await body(req),patch:any={};if(p.display_name!==undefined)patch.display_name=txt(p.display_name,160);if(p.active!==undefined)patch.active=Boolean(p.active);if(p.slug!==undefined){const s=txt(p.slug,60).toLowerCase();if(!/^[a-z0-9][a-z0-9-]{2,59}$/.test(s))return bad(req,'Slug inválido',422);patch.slug=s}const r=await admin.from('storefronts').update(patch).eq('business_id',bid).eq('id',sid).select('*').maybeSingle();if(r.error)throw r.error;return r.data?out(req,r.data):bad(req,'Loja não encontrada',404)}
 m=path.match(/^\/businesses\/(\d+)\/attribution$/);if(m&&method==='GET'){const bid=Number(m[1]);if(!await member(Number(u.id),bid))return bad(req,'Sem acesso',403);const d=Math.max(1,Math.min(365,Math.trunc(Number(new URL(req.url).searchParams.get('days')||30)))),r=await admin.rpc('c360_campaign_attribution',{p_business_id:bid,p_days:d});if(r.error)throw r.error;const rows=r.data||[],summary={orders:rows.reduce((a:number,x:any)=>a+Number(x.orders||0),0),revenue_cents:rows.reduce((a:number,x:any)=>a+Number(x.revenue_cents||0),0),media_cost_cents:rows.reduce((a:number,x:any)=>a+Number(x.media_cost_cents||0),0),contribution_after_media_cents:rows.reduce((a:number,x:any)=>a+Number(x.contribution_after_media_cents||0),0)};return out(req,{days:d,summary,campaigns:rows})}
 return bad(req,'Rota não encontrada',404)
}catch(e){console.error('direct-market-v40',e);return bad(req,'Erro interno',500)}})
