create table if not exists sac.lead_capture_smoke_runs (
  id bigint generated by default as identity primary key,
  captured_at timestamptz not null default now(),
  edge_status integer not null,
  persisted boolean not null default false,
  cleanup_verified boolean not null default false,
  source text not null default 'production_edge_canary',
  evidence jsonb not null default '{}'::jsonb,
  constraint lead_capture_smoke_status_check check (edge_status between 100 and 599)
);

alter table sac.lead_capture_smoke_runs enable row level security;
revoke all on sac.lead_capture_smoke_runs from public, anon, authenticated;
grant select, insert on sac.lead_capture_smoke_runs to service_role;

drop function if exists sac.gcl_record_lead_capture_smoke(integer,boolean,boolean,jsonb);
create function sac.gcl_record_lead_capture_smoke(p_edge_status integer,p_persisted boolean,p_cleanup_verified boolean,p_evidence jsonb default '{}'::jsonb)
returns bigint
language plpgsql
security definer
set search_path to 'sac','public'
as $function$
declare v_id bigint;
begin
  if p_edge_status < 100 or p_edge_status > 599 then raise exception 'invalid_edge_status'; end if;
  insert into sac.lead_capture_smoke_runs(edge_status,persisted,cleanup_verified,evidence)
  values(p_edge_status,coalesce(p_persisted,false),coalesce(p_cleanup_verified,false),coalesce(p_evidence,'{}'::jsonb))
  returning id into v_id;
  return v_id;
end;$function$;
revoke all on function sac.gcl_record_lead_capture_smoke(integer,boolean,boolean,jsonb) from public,anon,authenticated;
grant execute on function sac.gcl_record_lead_capture_smoke(integer,boolean,boolean,jsonb) to service_role;

create or replace function public.gcl_public_health()
returns jsonb
language plpgsql
stable security definer
set search_path to 'public','sac'
as $function$
declare
  p jsonb;
  q jsonb;
  v_live_products int:=0;
  v_test_products int:=0;
  v_webhook_ok boolean:=false;
  v_ranking_ok boolean:=false;
  v_queue_open boolean:=false;
  v_machine_ready boolean:=false;
  v_machine_blockers jsonb:='[]'::jsonb;
  v_lead_smoke_at timestamptz;
  v_lead_status int;
  v_lead_persisted boolean:=false;
  v_lead_cleanup boolean:=false;
  v_lead_ready boolean:=false;
begin
  p:=sac.ops_health_payload();
  q:=public.gcl_scan_queue_health();

  select count(*) filter(where provider_environment='live' and checkout_url is not null and status='active')::int,
         count(*) filter(where provider_environment='test' and checkout_url is not null and status in('draft','active'))::int
  into v_live_products,v_test_products
  from sac.commercial_products;

  select captured_at,edge_status,persisted,cleanup_verified
  into v_lead_smoke_at,v_lead_status,v_lead_persisted,v_lead_cleanup
  from sac.lead_capture_smoke_runs
  order by captured_at desc limit 1;

  v_webhook_ok:=coalesce((p->'payments'->>'webhook_failed_15m')::int,0)=0;
  v_ranking_ok:=coalesce((p->'ranking'->>'cache_age_seconds')::numeric,999999)<=300;
  v_queue_open:=coalesce(q->>'admission_state','')='open';
  v_machine_ready:=v_live_products>0 and v_webhook_ok and v_ranking_ok and v_queue_open;
  v_lead_ready:=coalesce(v_lead_status between 200 and 299,false)
    and coalesce(v_lead_persisted,false)
    and coalesce(v_lead_cleanup,false)
    and v_lead_smoke_at>=now()-interval '24 hours'
    and v_queue_open;

  if v_live_products=0 then v_machine_blockers:=v_machine_blockers||jsonb_build_array('stripe_livemode'); end if;
  if not v_webhook_ok then v_machine_blockers:=v_machine_blockers||jsonb_build_array('payment_webhook_health'); end if;
  if not v_ranking_ok then v_machine_blockers:=v_machine_blockers||jsonb_build_array('ranking_cache_freshness'); end if;
  if not v_queue_open then v_machine_blockers:=v_machine_blockers||jsonb_build_array('analysis_admission_capacity'); end if;

  return jsonb_build_object(
    'status',p->>'status',
    'captured_at',p->'captured_at',
    'analysis_queue',q,
    'lead_capture_go_live',jsonb_build_object(
      'machine_checks_passed',v_lead_ready,
      'latest_canary_at',v_lead_smoke_at,
      'latest_edge_status',v_lead_status,
      'persisted',v_lead_persisted,
      'cleanup_verified',v_lead_cleanup,
      'checkout_required',false,
      'transactional_email_required',false,
      'disclosure','This attests the public contact-capture path only. It does not attest live checkout, transactional-email delivery, or readiness for paid acquisition.'
    ),
    'payments',jsonb_build_object(
      'operational',v_live_products>0 and v_webhook_ok,
      'live_ready',v_live_products>0,
      'sandbox_operational',v_test_products>0 and v_webhook_ok,
      'live_products',v_live_products,
      'test_products',v_test_products,
      'webhook_healthy',v_webhook_ok,
      'disclosure',case when v_live_products>0 then 'Live checkout is enabled for at least one active commercial product.' else 'Payment integration is healthy in sandbox, but no active live checkout product is enabled yet.' end
    ),
    'ranking',jsonb_build_object('operational',v_ranking_ok),
    'commercial_go_live',jsonb_build_object(
      'machine_checks_passed',v_machine_ready,
      'machine_blockers',v_machine_blockers,
      'external_attestation_required',true,
      'required_external_controls',jsonb_build_array('auth_leaked_password_protection','transactional_email_domain','real_device_e2e','heavy_worker_capacity','legal_review','incident_ownership'),
      'disclosure','Operational health is not a commercial go-live attestation. External P0 controls must also be verified before paid traffic.'
    )
  );
end;$function$;