import { createClient } from 'npm:@supabase/supabase-js@2.115.0'

const SUPABASE_URL=Deno.env.get('SUPABASE_URL')!
const ANON_KEY=Deno.env.get('SUPABASE_ANON_KEY')!
const SERVICE_KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
const SLUG='cozinha360-migration-v70'
const VERSION='7.0.1'
const TAKEAT='https://public-api.takeat.app'
const anon=createClient(SUPABASE_URL,ANON_KEY,{auth:{persistSession:false,autoRefreshToken:false}})
const admin=createClient(SUPABASE_URL,SERVICE_KEY,{auth:{persistSession:false,autoRefreshToken:false}})
const enc=new TextEncoder(),dec=new TextDecoder()
const now=()=>new Date().toISOString()
const clean=(v:unknown,max=500)=>String(v??'').trim().slice(0,max)
const wait=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms))
function numeric(v:unknown){const raw=String(v??'').trim().replace(',','.');if(!raw)return null;const n=Number(raw);return Number.isFinite(n)?n:null}

function routePath(req:Request){const p=new URL(req.url).pathname,m=`/${SLUG}`,i=p.indexOf(m);return i>=0?(p.slice(i+m.length)||'/'):p}
function origin(req:Request){const raw=req.headers.get('origin')||'';if(/^https:\/\/[a-z0-9.-]+\.onrender\.com$/i.test(raw)||/^https:\/\/[a-z0-9.-]+\.netlify\.app$/i.test(raw)||/^http:\/\/(localhost|127\.0\.0\.1):5173$/i.test(raw))return raw;return 'https://cozinha-360-os-v41.onrender.com'}
function cors(req:Request){return{'Access-Control-Allow-Origin':origin(req),'Access-Control-Allow-Headers':'authorization, apikey, content-type, x-client-info','Access-Control-Allow-Methods':'GET,POST,DELETE,OPTIONS','Access-Control-Max-Age':'86400','Vary':'Origin','Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}}
const j=(req:Request,data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:cors(req)})
const fail=(req:Request,detail:string,status=400,extra:Record<string,unknown>={})=>j(req,{detail,...extra},status)
const parse=async(req:Request)=>{try{return await req.json()}catch{return{}}}

async function auth(req:Request){const h=req.headers.get('authorization')||'',token=h.startsWith('Bearer ')?h.slice(7):'';if(!token)return null;const{data,error}=await anon.auth.getUser(token);if(error||!data.user)return null;let p=(await admin.from('users').select('id,email,full_name').eq('auth_user_id',data.user.id).maybeSingle()).data;if(!p&&data.user.email)p=(await admin.from('users').select('id,email,full_name').ilike('email',data.user.email).maybeSingle()).data;return p||null}
async function member(userId:number,businessId:number,write=false){const r=await admin.from('memberships').select('id,role').eq('user_id',userId).eq('business_id',businessId).maybeSingle();if(r.error||!r.data)return null;if(write&&!['owner','admin'].includes(r.data.role))return null;return r.data}
async function audit(businessId:number,userId:number,action:string,payload:unknown){try{await admin.from('audit_logs').insert({business_id:businessId,actor_user_id:userId,action,entity_type:'migration',entity_id:'takeat',payload_json:JSON.stringify(payload??{})})}catch{/* Telemetry must never break migration authorization or writes. */}}

function b64(bytes:Uint8Array){let raw='';for(const b of bytes)raw+=String.fromCharCode(b);return btoa(raw).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function unb64(value:string){let v=value.replace(/-/g,'+').replace(/_/g,'/');while(v.length%4)v+='=';return Uint8Array.from(atob(v),c=>c.charCodeAt(0))}
async function rootBytes(){const seed=(Deno.env.get('C360_INTEGRATION_KEY')||'').trim()||`${SERVICE_KEY}:c360-integrations-v29`;return new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(seed)))}
async function aesKey(){return crypto.subtle.importKey('raw',await rootBytes(),{name:'AES-GCM'},false,['encrypt','decrypt'])}
async function seal(value:unknown){const iv=crypto.getRandomValues(new Uint8Array(12)),ct=await crypto.subtle.encrypt({name:'AES-GCM',iv},await aesKey(),enc.encode(JSON.stringify(value)));return{ciphertext:b64(new Uint8Array(ct)),iv:b64(iv)}}
async function openSecret(row:any){const pt=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(row.iv)},await aesKey(),unb64(row.ciphertext));return JSON.parse(dec.decode(pt))}
function parseMetadata(value:any){if(typeof value==='string'){try{return JSON.parse(value||'{}')}catch{return{}}}return value||{}}
function parseScopes(value:any){if(typeof value==='string'){try{return JSON.parse(value||'[]')}catch{return[]}}return Array.isArray(value)?value:[]}

async function connection(businessId:number){const r=await admin.from('integration_connections').select('*').eq('business_id',businessId).eq('provider','takeat_import').order('id',{ascending:true}).limit(1).maybeSingle();if(r.error)throw r.error;return r.data}
async function ensureConnection(businessId:number,restaurantId:string|null){const current=await connection(businessId);if(current){const u=await admin.from('integration_connections').update({status:'connecting',mode:'polling',external_account_ref:restaurantId||current.external_account_ref||null,last_error:null,updated_at:now()}).eq('id',current.id).select('*').single();if(u.error)throw u.error;return u.data}const r=await admin.from('integration_connections').insert({business_id:businessId,provider:'takeat_import',mode:'polling',status:'connecting',external_account_ref:restaurantId||null,display_name:'Takeat · importação'}).select('*').single();if(r.error)throw r.error;return r.data}
async function credential(connectionId:number){const r=await admin.from('integration_credentials').select('*').eq('connection_id',connectionId).maybeSingle();if(r.error)throw r.error;return r.data?{row:r.data,secret:await openSecret(r.data),metadata:parseMetadata(r.data.metadata_json),scopes:parseScopes(r.data.scopes_json)}:null}
async function saveCredential(conn:any,secret:any,expiresAt:string|null,scopes:string[],metadata:any={}){const encrypted=await seal(secret),r=await admin.from('integration_credentials').upsert({connection_id:conn.id,business_id:conn.business_id,provider:'takeat_import',ciphertext:encrypted.ciphertext,iv:encrypted.iv,key_version:1,expires_at:expiresAt,scopes_json:JSON.stringify(scopes),metadata_json:JSON.stringify(metadata),updated_at:now()},{onConflict:'connection_id'});if(r.error)throw r.error}
const expiry=(token:any)=>Number(token?.expires_in||0)?new Date(Date.now()+Number(token.expires_in)*1000).toISOString():null

async function takeatToken(form:URLSearchParams){const r=await fetch(`${TAKEAT}/oauth/token`,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded',accept:'application/json'},body:form,signal:AbortSignal.timeout(12000)}),x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(clean(x?.error_description||x?.message||x?.error||'Takeat recusou a autorização',800));return x}
async function exchangeApiKey(apiKey:string){return takeatToken(new URLSearchParams({grant_type:'api_key',api_key:apiKey}))}
async function refreshToken(refreshTokenValue:string){return takeatToken(new URLSearchParams({grant_type:'refresh_token',refresh_token:refreshTokenValue}))}
function activeLease(metadata:any){const lease=metadata?.refresh_lease;return lease?.id&&Date.parse(String(lease.until||''))>Date.now()?lease:null}
async function acquireRefreshLease(current:any){const row=current?.row,baseUpdated=clean(row?.updated_at,80);if(!row?.id||!baseUpdated)throw new Error('Credencial sem versão para serializar o refresh.');const lease={id:crypto.randomUUID(),until:new Date(Date.now()+20000).toISOString()},metadata={...current.metadata,refresh_lease:lease},stamp=now();const r=await admin.from('integration_credentials').update({metadata_json:JSON.stringify(metadata),updated_at:stamp}).eq('id',row.id).eq('updated_at',baseUpdated).select('*').maybeSingle();if(r.error)throw r.error;return r.data?{lease,row:r.data,metadata}:null}
async function releaseRefreshLease(rowId:number,leaseId:string){try{const r=await admin.from('integration_credentials').select('id,metadata_json,updated_at').eq('id',rowId).maybeSingle();if(r.error||!r.data)return;const metadata=parseMetadata(r.data.metadata_json);if(metadata?.refresh_lease?.id!==leaseId)return;delete metadata.refresh_lease;await admin.from('integration_credentials').update({metadata_json:JSON.stringify(metadata),updated_at:now()}).eq('id',rowId).eq('updated_at',r.data.updated_at)}catch{/* Lease expires automatically; release is best effort. */}}
async function fresh(conn:any,current:any,attempt=0):Promise<any>{const exp=current?.row?.expires_at?Date.parse(current.row.expires_at):0;if(!exp||exp>Date.now()+180000)return current;if(!current?.secret?.refresh_token)throw new Error('A Takeat exige nova autorização.');if(attempt>10)throw new Error('A credencial Takeat está sendo atualizada por outra requisição. Tente novamente em alguns segundos.');if(activeLease(current.metadata)){await wait(220+attempt*45);const latest=await credential(conn.id);if(!latest)throw new Error('Credencial Takeat ausente durante atualização.');return fresh(conn,latest,attempt+1)}const locked=await acquireRefreshLease(current);if(!locked){await wait(180+attempt*45);const latest=await credential(conn.id);if(!latest)throw new Error('Credencial Takeat ausente durante atualização.');return fresh(conn,latest,attempt+1)}try{const next=await refreshToken(String(current.secret.refresh_token)),expiresAt=expiry(next),scopes=clean(next.scope||current.scopes.join(' '),1000).split(/\s+/).filter(Boolean),metadata={...current.metadata,refreshed_at:now()};delete metadata.refresh_lease;await saveCredential(conn,next,expiresAt,scopes,metadata);const latest=await credential(conn.id);return latest||{...current,secret:next,row:{...current.row,expires_at:expiresAt},scopes,metadata}}catch(e){await releaseRefreshLease(Number(current.row.id),locked.lease.id);throw e}}
function safeConnection(row:any){return row?{provider:'takeat_import',status:row.status,display_name:row.display_name||'Takeat · importação',external_account_ref:row.external_account_ref||null,last_success_at:row.last_success_at||null,last_error:row.last_error||null}:null}

function qRestaurant(metadata:any){const restaurantId=clean(metadata?.restaurant_id,40);return restaurantId?`restaurant_id=${encodeURIComponent(restaurantId)}`:''}
async function takeatGet(path:string,accessToken:string,metadata:any){const join=path.includes('?')?'&':'?',restaurant=qRestaurant(metadata),url=restaurant?`${TAKEAT}${path}${join}${restaurant}`:`${TAKEAT}${path}`;const r=await fetch(url,{headers:{authorization:`Bearer ${accessToken}`,accept:'application/json'},signal:AbortSignal.timeout(15000)}),x=await r.json().catch(()=>({}));if(!r.ok){const message=clean(x?.message||x?.error_description||x?.error||`Takeat ${r.status}`,700),err:any=new Error(message);err.status=r.status;throw err}return x}
async function resourceProbe(path:string,current:any){try{return{ok:true,data:await takeatGet(path,String(current.secret.access_token),current.metadata)}}catch(e){return{ok:false,error:clean((e as any)?.message||e,300),status:Number((e as any)?.status||0)}}}

async function allInputs(current:any,cap=500){const rows:any[]=[];let offset=0;while(rows.length<cap){const x=await takeatGet(`/v1/inputs?offset=${offset}`,String(current.secret.access_token),current.metadata);const page=Array.isArray(x?.inputs)?x.inputs:[];rows.push(...page);if(!page.length||Number(x?.remaining||0)<=0)break;offset+=Number(x?.limit||100)||100}return rows.slice(0,cap)}
async function allClients(current:any,cap=600){const rows:any[]=[];let page=1;while(rows.length<cap){const x=await takeatGet(`/v1/clube/clients?page=${page}&per_page=200`,String(current.secret.access_token),current.metadata);const part=Array.isArray(x?.clients)?x.clients:[];rows.push(...part);if(!part.length||page>=Number(x?.total_pages||page))break;page+=1}return rows.slice(0,cap)}
function flattenProducts(x:any){const categories=Array.isArray(x)?x:[];const out:any[]=[];for(const category of categories){for(const product of Array.isArray(category?.products)?category.products:[])out.push({...product,category_name:clean(category?.name,160)})}return out}
function normalizePhone(v:unknown){return clean(v,40).replace(/\D/g,'')}
function unitMapping(unitRaw:unknown){const raw=clean(unitRaw,20).toLowerCase();if(['kg','quilo','quilos'].includes(raw))return{unit:'g',factor:1000,packageQty:1000};if(['l','lt','litro','litros'].includes(raw))return{unit:'ml',factor:1000,packageQty:1000};if(['g','gr','grama','gramas'].includes(raw))return{unit:'g',factor:1,packageQty:1};if(['ml','mililitro','mililitros'].includes(raw))return{unit:'ml',factor:1,packageQty:1};return{unit:raw||'un',factor:1,packageQty:1}}
function toInt(v:number){return Math.max(0,Math.round(Number.isFinite(v)?v:0))}
function inputNumbers(row:any){const quantity=numeric(row?.quantidade),minimum=numeric(row?.minimum_stock),ideal=numeric(row?.ideal_stock),unitPrice=numeric(row?.unitary_price);return{quantity,minimum,ideal,unitPrice,valid:quantity!==null&&minimum!==null&&ideal!==null&&unitPrice!==null}}

async function previewData(businessId:number,current:any){const productResult=await resourceProbe('/v1/products',current);let inputs:any[]=[];let clients:any[]=[];let inputsError:string|null=null,clientsError:string|null=null;try{inputs=await allInputs(current)}catch(e){inputsError=clean((e as any)?.message||e,250)}try{clients=await allClients(current)}catch(e){clientsError=clean((e as any)?.message||e,250)}const products=productResult.ok?flattenProducts(productResult.data):[],invalidInputs=inputs.filter(row=>!inputNumbers(row).valid).length
 const [existingProducts,existingIngredients,existingCustomers]=await Promise.all([
  admin.from('products').select('name').eq('business_id',businessId).eq('soft_deleted',false),
  admin.from('ingredients').select('name').eq('business_id',businessId).eq('soft_deleted',false),
  admin.from('customers').select('name,phone,email').eq('business_id',businessId),
 ])
 const productNames=new Set((existingProducts.data||[]).map((x:any)=>clean(x.name,160).toLowerCase())),ingredientNames=new Set((existingIngredients.data||[]).map((x:any)=>clean(x.name,160).toLowerCase())),phones=new Set((existingCustomers.data||[]).map((x:any)=>normalizePhone(x.phone)).filter(Boolean))
 const warnings=['Produtos são importados como cadastro base; preços por canal permanecem para revisão no Cozinha 360.','Clientes importados começam sem consentimento de marketing.','Campos não equivalentes não são inventados nem sobrescritos.'];if(invalidInputs)warnings.push(`${invalidInputs} insumo(s) possuem número legado inválido e ficarão para revisão em vez de virar zero.`)
 return{
  resources:{
   products:{available:productResult.ok,count:products.length,conflicts:products.filter(x=>productNames.has(clean(x.name,160).toLowerCase())).length,error:productResult.ok?null:productResult.error},
   inputs:{available:!inputsError,count:inputs.length,conflicts:inputs.filter(x=>ingredientNames.has(clean(x.name,160).toLowerCase())).length,error:inputsError,review_required:invalidInputs},
   customers:{available:!clientsError,count:clients.length,conflicts:clients.filter(x=>{const p=normalizePhone(x.phone);return p&&phones.has(p)}).length,error:clientsError,consent_policy:'reset_false'},
  },
  samples:{products:products.slice(0,4).map(x=>({name:clean(x.name,160),category:clean(x.category_name,160),price:clean(x.price,40),delivery_price:clean(x.delivery_price,40)})),inputs:inputs.slice(0,4).map(x=>({name:clean(x.name,160),unit:clean(x.unidade,20),quantity:clean(x.quantidade,40),minimum_stock:clean(x.minimum_stock,40),ideal_stock:clean(x.ideal_stock,40),needs_review:!inputNumbers(x).valid})),customers:clients.slice(0,4).map(x=>({name:clean(x.name,160),visits:toInt(numeric(x.visits)||0),favorite_product:clean(x.favorite_product,160)}))},
  warnings
 }
}

async function connectTakeat(req:Request,businessId:number){const who:any=await auth(req);if(!who)return fail(req,'Sem acesso',401);if(!await member(Number(who.id),businessId,true))return fail(req,'Somente owner/admin pode iniciar uma migração.',403);const body:any=await parse(req),apiKey=clean(body.api_key,500),restaurantId=clean(body.restaurant_id,40)||null;if(!/^tk_(live|test)_[A-Za-z0-9._-]+$/.test(apiKey))return fail(req,'Use uma API key Takeat válida (tk_live_… ou tk_test_…).',422,{code:'invalid_takeat_api_key'});const conn=await ensureConnection(businessId,restaurantId);try{const token=await exchangeApiKey(apiKey),scopes=clean(token.scope,1000).split(/\s+/).filter(Boolean),metadata={restaurant_id:restaurantId,connected_at:now(),auth_mode:'api_key_exchange',api_key_discarded:true};await saveCredential(conn,token,expiry(token),scopes,metadata);const p=await resourceProbe('/v1/products',{secret:token,metadata});const status=p.ok?'active':'degraded',error=p.ok?null:p.error;const u=await admin.from('integration_connections').update({status,display_name:restaurantId?`Takeat · restaurante ${restaurantId}`:'Takeat · importação',last_success_at:p.ok?now():null,last_error:error,last_error_at:error?now():null,updated_at:now()}).eq('id',conn.id).select('*').single();if(u.error)throw u.error;await audit(businessId,Number(who.id),'migration.takeat.connected',{restaurant_id:restaurantId,scopes,api_key_discarded:true,probe:p.ok});return j(req,{ok:true,connection:safeConnection(u.data),scopes,api_key_stored:false,next:'preview'})}catch(e){const message=clean((e as any)?.message||e,800);await admin.from('integration_connections').update({status:'degraded',last_error:message,last_error_at:now(),updated_at:now()}).eq('id',conn.id);return fail(req,message,502,{code:'takeat_connect_failed'})}}
async function status(req:Request,businessId:number){const who:any=await auth(req);if(!who)return fail(req,'Sem acesso',401);if(!await member(Number(who.id),businessId))return fail(req,'Sem acesso',403);const conn=await connection(businessId);let scopes:string[]=[];if(conn){const c=await credential(conn.id);scopes=c?.scopes||[]}return j(req,{ok:true,version:VERSION,provider:'takeat_import',connection:safeConnection(conn),scopes,capabilities:{products:'products:read',inputs:'inputs:read',customers:'clube:read'},auth:{current:'api_key_exchange',recommended_for_saas:'oauth_pkce',client_id_configured:Boolean((Deno.env.get('TAKEAT_CLIENT_ID')||'').trim())},disconnect:{local_tokens_removed:true,remote_api_key_revoke:'takeat_ai_builders'}})}
async function preview(req:Request,businessId:number){const who:any=await auth(req);if(!who)return fail(req,'Sem acesso',401);if(!await member(Number(who.id),businessId))return fail(req,'Sem acesso',403);const conn=await connection(businessId);if(!conn)return fail(req,'Conecte a Takeat antes de pré-visualizar.',409,{code:'connection_required'});let current=await credential(conn.id);if(!current)return fail(req,'Credencial de migração ausente.',409,{code:'credential_missing'});try{current=await fresh(conn,current);const data=await previewData(businessId,current);await admin.from('integration_connections').update({status:'active',last_success_at:now(),last_error:null,updated_at:now()}).eq('id',conn.id);await audit(businessId,Number(who.id),'migration.takeat.previewed',{resources:data.resources});return j(req,{ok:true,...data})}catch(e){const message=clean((e as any)?.message||e,800);await admin.from('integration_connections').update({status:'degraded',last_error:message,last_error_at:now(),updated_at:now()}).eq('id',conn.id);return fail(req,message,502,{code:'takeat_preview_failed'})}}

async function applyImport(req:Request,businessId:number){const who:any=await auth(req);if(!who)return fail(req,'Sem acesso',401);if(!await member(Number(who.id),businessId,true))return fail(req,'Somente owner/admin pode importar cadastros.',403);const body:any=await parse(req),include={products:body.products!==false,inputs:body.inputs!==false,customers:body.customers===true};const conn=await connection(businessId);if(!conn)return fail(req,'Conecte a Takeat antes de importar.',409,{code:'connection_required'});let current=await credential(conn.id);if(!current)return fail(req,'Credencial de migração ausente.',409,{code:'credential_missing'});current=await fresh(conn,current)
 const result={products:{created:0,skipped:0},inputs:{created:0,skipped:0,review:0},customers:{created:0,skipped:0,consent_reset:0}}
 try{
  if(include.products){const x=await takeatGet('/v1/products',String(current.secret.access_token),current.metadata),rows=flattenProducts(x),existing=(await admin.from('products').select('name').eq('business_id',businessId).eq('soft_deleted',false)).data||[],names=new Set(existing.map((v:any)=>clean(v.name,160).toLowerCase())),create:any[]=[];for(const row of rows){const name=clean(row.name,160);if(!name||names.has(name.toLowerCase())){result.products.skipped++;continue}names.add(name.toLowerCase());create.push({business_id:businessId,name,units_per_batch:1,packaging_cents_per_unit:0,energy_cents_per_batch:0,labor_cents_per_batch:0,soft_deleted:false})}if(create.length){const r=await admin.from('products').insert(create);if(r.error)throw r.error;result.products.created=create.length}}
  if(include.inputs){const rows=await allInputs(current),existing=(await admin.from('ingredients').select('name').eq('business_id',businessId).eq('soft_deleted',false)).data||[],names=new Set(existing.map((v:any)=>clean(v.name,160).toLowerCase())),create:any[]=[];for(const row of rows){const name=clean(row.name,160);if(!name||names.has(name.toLowerCase())){result.inputs.skipped++;continue}const nums=inputNumbers(row);if(!nums.valid){result.inputs.review++;continue}names.add(name.toLowerCase());const m=unitMapping(row.unidade),quantity=toInt((nums.quantity as number)*m.factor),minimum=toInt((nums.minimum as number)*m.factor),ideal=Math.max(minimum,toInt((nums.ideal as number)*m.factor)),unitPrice=Math.max(0,Math.round((nums.unitPrice as number)*100));create.push({business_id:businessId,name,unit:m.unit,last_purchase_price_cents:unitPrice,last_purchase_qty_milliunits:m.packageQty,usable_qty_milliunits:m.packageQty,on_hand_milliunits:quantity,par_level_milliunits:minimum,reorder_target_milliunits:ideal,soft_deleted:false})}if(create.length){const r=await admin.from('ingredients').insert(create);if(r.error)throw r.error;result.inputs.created=create.length}}
  if(include.customers){const rows=await allClients(current),existing=(await admin.from('customers').select('phone,email').eq('business_id',businessId)).data||[],phones=new Set(existing.map((v:any)=>normalizePhone(v.phone)).filter(Boolean)),create:any[]=[];for(const row of rows){const phone=normalizePhone(row.phone),name=clean(row.name,160)||'Cliente importado';if(phone&&phones.has(phone)){result.customers.skipped++;continue}if(phone)phones.add(phone);create.push({business_id:businessId,name,phone:clean(row.phone,40),email:'',consent_marketing:false});result.customers.consent_reset++}if(create.length){const r=await admin.from('customers').insert(create);if(r.error)throw r.error;result.customers.created=create.length}}
  await admin.from('integration_connections').update({status:'active',last_success_at:now(),last_error:null,updated_at:now()}).eq('id',conn.id);await audit(businessId,Number(who.id),'migration.takeat.applied',{include,result,customer_consent:'false_by_default'});return j(req,{ok:true,result,review_required:{product_channel_prices:include.products,customer_marketing_consent:include.customers,invalid_input_numbers:result.inputs.review,unknown_fields_not_imported:true}})
 }catch(e){const message=clean((e as any)?.message||e,800);await admin.from('integration_connections').update({status:'degraded',last_error:message,last_error_at:now(),updated_at:now()}).eq('id',conn.id);await audit(businessId,Number(who.id),'migration.takeat.apply_failed',{include,message});return fail(req,message,500,{code:'takeat_apply_failed',partial_result:result})}}
async function disconnect(req:Request,businessId:number){const who:any=await auth(req);if(!who)return fail(req,'Sem acesso',401);if(!await member(Number(who.id),businessId,true))return fail(req,'Somente owner/admin pode encerrar a migração.',403);const conn=await connection(businessId);if(!conn)return j(req,{ok:true,already_disconnected:true,remote_revoke:{required:false}});const d=await admin.from('integration_credentials').delete().eq('connection_id',conn.id);if(d.error)throw d.error;const u=await admin.from('integration_connections').update({status:'inactive',external_account_ref:null,display_name:'Takeat · importação',last_error:null,updated_at:now()}).eq('id',conn.id);if(u.error)throw u.error;const remoteRevoke={required:true,action:'revoke_api_key_in_takeat_ai_builders',detail:'Revogue a API key no AI Builders da Takeat para encerrar todas as sessões emitidas por essa chave.'};await audit(businessId,Number(who.id),'migration.takeat.disconnected',{local_tokens_removed:true,remote_revoke:remoteRevoke.action});return j(req,{ok:true,connection:{provider:'takeat_import',status:'inactive'},local_tokens_removed:true,remote_revoke:remoteRevoke})}

Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(req)});const path=routePath(req);try{if(req.method==='GET'&&path==='/health')return j(req,{ok:true,service:SLUG,version:VERSION,takeat_api:TAKEAT,refresh_serialization:'optimistic_lease'});let m=path.match(/^\/businesses\/(\d+)\/takeat\/status$/);if(req.method==='GET'&&m)return await status(req,Number(m[1]));m=path.match(/^\/businesses\/(\d+)\/takeat\/connect$/);if(req.method==='POST'&&m)return await connectTakeat(req,Number(m[1]));m=path.match(/^\/businesses\/(\d+)\/takeat\/preview$/);if(req.method==='POST'&&m)return await preview(req,Number(m[1]));m=path.match(/^\/businesses\/(\d+)\/takeat\/apply$/);if(req.method==='POST'&&m)return await applyImport(req,Number(m[1]));m=path.match(/^\/businesses\/(\d+)\/takeat$/);if(req.method==='DELETE'&&m)return await disconnect(req,Number(m[1]));return fail(req,'Rota não encontrada',404)}catch(e){return fail(req,clean((e as any)?.message||e,800),500)}})
