import { createClient } from 'npm:@supabase/supabase-js@2'

const SUPABASE_URL=Deno.env.get('SUPABASE_URL')!
const ANON_KEY=Deno.env.get('SUPABASE_ANON_KEY')!
const SERVICE_KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
const SLUG='cozinha360-setup-v42'
const anon=createClient(SUPABASE_URL,ANON_KEY,{auth:{persistSession:false,autoRefreshToken:false}})
const admin=createClient(SUPABASE_URL,SERVICE_KEY,{auth:{persistSession:false,autoRefreshToken:false}})
const allowedOrigins=new Set(['https://cozinha-360-os-v41.onrender.com','https://cozinha-360-os.netlify.app','http://localhost:5173','http://127.0.0.1:5173','http://localhost:3000'])
const now=()=>new Date().toISOString()
const text=(v:unknown,max=180)=>String(v??'').trim().slice(0,max)
const int=(v:unknown)=>Math.max(0,Math.trunc(Number(v)||0))
const bool=(v:unknown,fallback=false)=>v===undefined?fallback:Boolean(v)
function cors(req:Request){const origin=req.headers.get('origin')||'';return{'Access-Control-Allow-Origin':allowedOrigins.has(origin)?origin:'https://cozinha-360-os-v41.onrender.com','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'GET,POST,PUT,PATCH,DELETE,OPTIONS','Access-Control-Max-Age':'86400','Vary':'Origin','Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}}
const reply=(req:Request,data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:cors(req)})
const fail=(req:Request,detail:string,status=400,extra:Record<string,unknown>={})=>reply(req,{detail,...extra},status)
async function body(req:Request){try{return await req.json()}catch{return{}}}
function route(req:Request){const p=new URL(req.url).pathname,marker='/'+SLUG,i=p.indexOf(marker);return i>=0?(p.slice(i+marker.length)||'/'):p}
async function auth(req:Request){const h=req.headers.get('authorization')||'',token=h.startsWith('Bearer ')?h.slice(7):'';if(!token)return null;const{data,error}=await anon.auth.getUser(token);if(error||!data.user)return null;let profile=(await admin.from('users').select('id,email,full_name').eq('auth_user_id',data.user.id).maybeSingle()).data;if(!profile&&data.user.email)profile=(await admin.from('users').select('id,email,full_name').ilike('email',data.user.email).maybeSingle()).data;return profile||null}
async function membership(userId:number,businessId:number,write=false){const row=(await admin.from('memberships').select('id,role').eq('user_id',userId).eq('business_id',businessId).maybeSingle()).data;if(!row)return null;if(write&&!['owner','admin'].includes(row.role))return null;return row}
async function audit(businessId:number,userId:number,action:string,entityType:string,entityId:string,payload:unknown){await admin.from('audit_logs').insert({business_id:businessId,actor_user_id:userId,action,entity_type:entityType,entity_id:entityId,payload_json:JSON.stringify(payload??{})})}

const providerCatalog=[
 {key:'direct',name:'Loja própria Cozinha 360',category:'Pedidos',kind:'native',setup:'ready',purpose:'Venda direta sem comissão do Cozinha 360.',recommended:true},
 {key:'whatsapp',name:'WhatsApp Business',category:'Pedidos & CRM',kind:'connection',setup:'oauth',purpose:'Atendimento, pedidos e recompra com consentimento.',recommended:true},
 {key:'mercadopago',name:'Mercado Pago / Pix',category:'Pagamento',kind:'connection',setup:'oauth',purpose:'Confirmação de pagamento e conciliação sem conferir Pix manualmente.',recommended:true},
 {key:'ifood',name:'iFood',category:'Marketplace',kind:'connection',setup:'device_code',purpose:'Importação de pedidos para a fila operacional.',recommended:true},
 {key:'google',name:'Google Business + Ads',category:'Aquisição',kind:'connection',setup:'oauth',purpose:'Presença local, avaliações e mídia.',recommended:false},
 {key:'meta_ads',name:'Meta Ads',category:'Aquisição',kind:'connection',setup:'oauth',purpose:'Campanhas e atribuição conectadas à margem.',recommended:false},
 {key:'99food',name:'99Food',category:'Marketplace',kind:'partner',setup:'partner_onboarding',purpose:'Estrutura preparada; ativar somente após credencial/API oficial da conta.',recommended:false},
 {key:'keeta',name:'Keeta',category:'Marketplace',kind:'partner',setup:'partner_onboarding',purpose:'Estrutura preparada; ativar somente após credencial/API oficial da conta.',recommended:false},
 {key:'maps_google',name:'Google Maps Routes',category:'Logística',kind:'server_key',setup:'platform_key',purpose:'ETA, distância e otimização de rotas quando a chave de servidor estiver habilitada.',recommended:false},
 {key:'mapbox',name:'Mapbox',category:'Logística',kind:'server_key',setup:'platform_key',purpose:'Alternativa provider-neutral para mapas e roteamento.',recommended:false},
]

async function getSetup(req:Request,businessId:number){
 const[brands,connections,bindings,fiscal,settings,channels,stores]=await Promise.all([
  admin.from('brands').select('id,name,slug,active,primary_channel,sort_order').eq('business_id',businessId).eq('soft_deleted',false).order('sort_order').order('id'),
  admin.from('integration_connections').select('id,provider,external_account_ref,display_name,status,mode,last_success_at,last_error_at,last_error,updated_at').eq('business_id',businessId).order('provider'),
  admin.from('brand_integration_bindings').select('*').eq('business_id',businessId).order('brand_id').order('provider'),
  admin.from('brand_fiscal_profiles').select('*').eq('business_id',businessId).order('brand_id'),
  admin.from('delivery_settings').select('*').eq('business_id',businessId).maybeSingle(),
  admin.from('channels').select('id,name,traffic_active').eq('business_id',businessId).order('id'),
  admin.from('storefronts').select('id,brand_id,slug,display_name,active').eq('business_id',businessId).order('id'),
 ])
 const err=[brands.error,connections.error,bindings.error,fiscal.error,channels.error,stores.error].filter(Boolean);if(err.length){console.error('setup-v42 overview',err);return fail(req,'Não foi possível carregar o assistente de conexões.',500)}
 const connByProvider=new Map((connections.data||[]).map(c=>[String(c.provider),c]))
 const providers=providerCatalog.map(p=>{const c=connByProvider.get(p.key)||null;let state='available';if(p.kind==='native')state='active';else if(c?.status==='active')state='active';else if(c?.status==='degraded')state='attention';else if(c?.status==='connecting')state='connecting';else if(p.kind==='partner')state='partner_onboarding';else if(p.kind==='server_key')state='platform_setup';else state='not_connected';return{...p,state,connection:c}})
 const cfg=settings.data||{business_id:businessId,route_provider:'manual',route_mode:'manual',route_optimization_enabled:false,customer_tracking_enabled:false,whatsapp_status_updates:false,scheduled_orders_enabled:true,brand_crm_isolation:true,prep_target_min:25,default_eta_min:45,sla_warning_minutes:10,max_scheduled_days:7}
 const activeConnections=(connections.data||[]).filter(c=>c.status==='active')
 const activeBrands=(brands.data||[]).filter(b=>b.active)
 const unbound=activeConnections.filter(c=>['ifood','whatsapp','mercadopago'].includes(String(c.provider))&&!activeBrands.every(b=>(bindings.data||[]).some(x=>Number(x.brand_id)===Number(b.id)&&String(x.provider)===String(c.provider)&&x.active)))
 return reply(req,{version:'4.2.0',business_id:businessId,brands:brands.data||[],connections:connections.data||[],providers,bindings:bindings.data||[],fiscal_profiles:fiscal.data||[],settings:cfg,channels:channels.data||[],storefronts:stores.data||[],summary:{active_brands:activeBrands.length,active_connections:activeConnections.length,unbound_connections:unbound.length,fiscal_configured:(fiscal.data||[]).filter(f=>f.tax_id||f.legal_name).length,route_mode:cfg.route_mode||'manual',route_provider:cfg.route_provider||'manual'},next_actions:[...(activeBrands.length===0?['create_brand']:[]),...(unbound.length?['bind_connections']:[]),...((cfg.route_mode||'manual')!=='manual'&&!(cfg.route_provider&&cfg.route_provider!=='manual')?['connect_route_provider']:[])]})
}

async function saveBinding(req:Request,businessId:number,userId:number,p:any){
 const brandId=int(p.brand_id),connectionId=int(p.connection_id),provider=text(p.provider,40).toLowerCase();if(!brandId||!connectionId||!provider)return fail(req,'Marca, conexão e provedor são obrigatórios.')
 const brand=(await admin.from('brands').select('id,name').eq('business_id',businessId).eq('id',brandId).eq('soft_deleted',false).maybeSingle()).data;if(!brand)return fail(req,'Marca não encontrada.',404)
 const connection=(await admin.from('integration_connections').select('*').eq('business_id',businessId).eq('id',connectionId).maybeSingle()).data;if(!connection)return fail(req,'Conexão não encontrada.',404);if(String(connection.provider).toLowerCase()!==provider)return fail(req,'O provedor não corresponde à conexão selecionada.',409);if(connection.status!=='active')return fail(req,'Valide a conexão antes de vinculá-la à marca.',409,{code:'CONNECTION_NOT_ACTIVE'})
 const channelId=int(p.channel_id)||null;if(channelId){const channel=(await admin.from('channels').select('id').eq('business_id',businessId).eq('id',channelId).maybeSingle()).data;if(!channel)return fail(req,'Canal inválido.',404)}
 const row={business_id:businessId,brand_id:brandId,connection_id:connectionId,channel_id:channelId,provider,external_store_ref:text(p.external_store_ref,180)||null,order_import_enabled:bool(p.order_import_enabled,true),menu_sync_enabled:bool(p.menu_sync_enabled,false),price_sync_enabled:bool(p.price_sync_enabled,false),availability_sync_enabled:bool(p.availability_sync_enabled,false),auto_accept_orders:bool(p.auto_accept_orders,false),active:p.active!==false,updated_at:now()}
 const r=await admin.from('brand_integration_bindings').upsert(row,{onConflict:'business_id,brand_id,provider'}).select('*').single();if(r.error){console.error(r.error);return fail(req,'Não foi possível vincular a integração à marca.',400)}await audit(businessId,userId,'upsert','brand_integration_binding',String(r.data.id),{brand_id:brandId,connection_id:connectionId,provider,channel_id:channelId});return reply(req,{binding:r.data,brand,connection})
}
async function deleteBinding(req:Request,businessId:number,userId:number,id:number){const row=(await admin.from('brand_integration_bindings').select('*').eq('business_id',businessId).eq('id',id).maybeSingle()).data;if(!row)return fail(req,'Vínculo não encontrado.',404);const r=await admin.from('brand_integration_bindings').delete().eq('business_id',businessId).eq('id',id);if(r.error)return fail(req,'Não foi possível remover o vínculo.',400);await audit(businessId,userId,'delete','brand_integration_binding',String(id),row);return reply(req,{ok:true})}

async function saveFiscal(req:Request,businessId:number,userId:number,brandId:number,p:any){const brand=(await admin.from('brands').select('id,name').eq('business_id',businessId).eq('id',brandId).eq('soft_deleted',false).maybeSingle()).data;if(!brand)return fail(req,'Marca não encontrada.',404);const regime=text(p.tax_regime||'unconfigured',24);if(!['unconfigured','mei','simples','presumed','real','other'].includes(regime))return fail(req,'Regime tributário inválido.');const issuance=Boolean(p.issuance_enabled);const provider=text(p.fiscal_provider,40)||null,profile=text(p.provider_profile_ref,180)||null;if(issuance&&(!provider||!profile))return fail(req,'Conecte um provedor fiscal e informe o perfil externo antes de ativar emissão.',409,{code:'FISCAL_PROVIDER_REQUIRED'});const row={brand_id:brandId,business_id:businessId,legal_name:text(p.legal_name,180)||null,tax_id:text(p.tax_id,20).replace(/[^0-9A-Za-z]/g,'')||null,state_registration:text(p.state_registration,40)||null,municipal_registration:text(p.municipal_registration,40)||null,tax_regime:regime,fiscal_provider:provider,provider_profile_ref:profile,issuance_enabled:issuance,active:p.active!==false,updated_at:now()};const r=await admin.from('brand_fiscal_profiles').upsert(row,{onConflict:'brand_id'}).select('*').single();if(r.error)return fail(req,'Não foi possível salvar o perfil fiscal.',400);await audit(businessId,userId,'upsert','brand_fiscal_profile',String(brandId),{tax_regime:regime,fiscal_provider:provider,issuance_enabled:issuance});return reply(req,{fiscal_profile:r.data,brand})}

async function saveRoute(req:Request,businessId:number,userId:number,p:any){const provider=text(p.route_provider||'manual',24).toLowerCase(),mode=text(p.route_mode||'manual',24).toLowerCase();if(!['manual','google','mapbox','external'].includes(provider))return fail(req,'Provedor de rota inválido.');if(!['manual','assisted','intelligent'].includes(mode))return fail(req,'Modo de rota inválido.');if(mode!=='manual'&&provider==='manual')return fail(req,'Escolha um provedor antes de ativar rota assistida ou inteligente.',409,{code:'ROUTE_PROVIDER_REQUIRED'});if(provider!=='manual'){const providerKeys=provider==='google'?['maps_google','google']:provider==='mapbox'?['mapbox']:['external'];const connection=(await admin.from('integration_connections').select('id,provider,status').eq('business_id',businessId).in('provider',providerKeys).eq('status','active').limit(1).maybeSingle()).data;if(!connection)return fail(req,'O provedor de mapas ainda não está validado para esta operação.',409,{code:'ROUTE_CONNECTION_REQUIRED',provider})}
 const current=(await admin.from('delivery_settings').select('*').eq('business_id',businessId).maybeSingle()).data||{};const row={...current,business_id:businessId,route_provider:provider,route_mode:mode,route_optimization_enabled:mode==='intelligent',customer_tracking_enabled:bool(p.customer_tracking_enabled,current.customer_tracking_enabled??false),whatsapp_status_updates:bool(p.whatsapp_status_updates,current.whatsapp_status_updates??false),scheduled_orders_enabled:current.scheduled_orders_enabled??true,auto_accept_direct_orders:current.auto_accept_direct_orders??false,brand_crm_isolation:current.brand_crm_isolation??true,prep_target_min:current.prep_target_min??25,default_eta_min:current.default_eta_min??45,sla_warning_minutes:current.sla_warning_minutes??10,max_scheduled_days:current.max_scheduled_days??7,updated_by_user_id:userId,updated_at:now()};delete (row as any).created_at;const r=await admin.from('delivery_settings').upsert(row,{onConflict:'business_id'}).select('*').single();if(r.error){console.error(r.error);return fail(req,'Não foi possível salvar o roteamento.',400)}await audit(businessId,userId,'update','delivery_route_setup',String(businessId),{route_provider:provider,route_mode:mode});return reply(req,{settings:r.data})}

async function autoConfigure(req:Request,businessId:number,userId:number){const[brands,connections,bindings]=await Promise.all([admin.from('brands').select('id,name').eq('business_id',businessId).eq('active',true).eq('soft_deleted',false),admin.from('integration_connections').select('*').eq('business_id',businessId).eq('status','active'),admin.from('brand_integration_bindings').select('*').eq('business_id',businessId)]);if(brands.error||connections.error||bindings.error)return fail(req,'Não foi possível calcular a configuração automática.',500);const candidates=(connections.data||[]).filter(c=>['ifood','whatsapp','mercadopago'].includes(String(c.provider)));const created:any[]=[];for(const b of brands.data||[]){for(const c of candidates){if((bindings.data||[]).some(x=>Number(x.brand_id)===Number(b.id)&&String(x.provider)===String(c.provider)&&x.active))continue;const r=await admin.from('brand_integration_bindings').upsert({business_id:businessId,brand_id:b.id,connection_id:c.id,provider:c.provider,order_import_enabled:['ifood','whatsapp'].includes(String(c.provider)),menu_sync_enabled:false,price_sync_enabled:false,availability_sync_enabled:false,auto_accept_orders:false,active:true,updated_at:now()},{onConflict:'business_id,brand_id,provider'}).select('*').single();if(!r.error)created.push(r.data)}}await audit(businessId,userId,'auto_configure','brand_integration_binding','bulk',{created:created.map(x=>x.id)});return reply(req,{ok:true,created_count:created.length,bindings:created})}

Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(req)});const path=route(req),method=req.method;if(path==='/health'&&method==='GET')return reply(req,{status:'ok',service:SLUG,version:'4.2.0',capabilities:['brand_bindings','fiscal_profiles','route_setup','auto_configure']});const user=await auth(req);if(!user)return fail(req,'Sessão inválida ou expirada.',401);const m=path.match(/^\/businesses\/(\d+)(?:\/(.*))?$/);if(!m)return fail(req,'Rota não encontrada.',404);const businessId=int(m[1]);if(!businessId)return fail(req,'Operação inválida.',400);const rest=m[2]||'setup',write=method!=='GET';if(!await membership(Number(user.id),businessId,write))return fail(req,write?'Somente owner/admin pode alterar esta configuração.':'Você não participa desta operação.',403);const p:any=write?await body(req):{};try{if(method==='GET'&&rest==='setup')return await getSetup(req,businessId);if(method==='POST'&&rest==='bindings')return await saveBinding(req,businessId,Number(user.id),p);let x=rest.match(/^bindings\/(\d+)$/);if(method==='DELETE'&&x)return await deleteBinding(req,businessId,Number(user.id),int(x[1]));x=rest.match(/^fiscal\/(\d+)$/);if(method==='PUT'&&x)return await saveFiscal(req,businessId,Number(user.id),int(x[1]),p);if(method==='PUT'&&rest==='route')return await saveRoute(req,businessId,Number(user.id),p);if(method==='POST'&&rest==='auto-configure')return await autoConfigure(req,businessId,Number(user.id));return fail(req,'Rota não encontrada.',404)}catch(error){console.error('setup-v42',error);return fail(req,'Falha interna no assistente de conexões.',500)}})
