import { createClient } from 'npm:@supabase/supabase-js@2.115.0'

const SUPABASE_URL=Deno.env.get('SUPABASE_URL')!
const ANON_KEY=Deno.env.get('SUPABASE_ANON_KEY')!
const SERVICE_KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
const SLUG='cozinha360-pagbank-v59'
const VERSION='5.9.0'
const RENDER='https://cozinha-360-os-v41.onrender.com'
const NETLIFY='https://cozinha-360-os.netlify.app'
const LOCAL='http://localhost:5173'
const anon=createClient(SUPABASE_URL,ANON_KEY,{auth:{persistSession:false,autoRefreshToken:false}})
const admin=createClient(SUPABASE_URL,SERVICE_KEY,{auth:{persistSession:false,autoRefreshToken:false}})
const enc=new TextEncoder(),dec=new TextDecoder()
const now=()=>new Date().toISOString()
const env=(n:string)=>(Deno.env.get(n)||'').trim()
const clean=(v:unknown,max=500)=>String(v??'').trim().slice(0,max)
const environment=()=>env('PAGBANK_ENV').toLowerCase()==='sandbox'?'sandbox':'production'
const apiBase=()=>environment()==='sandbox'?'https://sandbox.api.pagseguro.com':'https://api.pagseguro.com'
const connectBase=()=>environment()==='sandbox'?'https://connect.sandbox.pagbank.com.br/oauth2/authorize':'https://connect.pagbank.com.br/oauth2/authorize'
const configured=()=>Boolean(env('PAGBANK_APP_TOKEN')&&env('PAGBANK_CLIENT_ID')&&env('PAGBANK_CLIENT_SECRET'))
const homologated=()=>environment()==='sandbox'||env('PAGBANK_HOMOLOGATED').toLowerCase()==='true'
const ready=()=>configured()&&homologated()
function originOf(value:unknown){try{const o=new URL(String(value||'')).origin;if(o===NETLIFY)return NETLIFY;if(o===LOCAL||o==='http://127.0.0.1:5173')return LOCAL;return RENDER}catch{return RENDER}}
function originCode(origin:string){return origin===NETLIFY?'N':origin===LOCAL?'L':'R'}
function originFromCode(code:string){return code==='N'?NETLIFY:code==='L'?LOCAL:RENDER}
function routePath(req:Request){const p=new URL(req.url).pathname,m=`/${SLUG}`,i=p.indexOf(m);return i>=0?(p.slice(i+m.length)||'/'):p}
function callbackUrl(){return `${SUPABASE_URL}/functions/v1/${SLUG}/oauth/callback`}
function cors(req:Request){const origin=originOf(req.headers.get('origin'));return{'Access-Control-Allow-Origin':origin,'Access-Control-Allow-Headers':'authorization, apikey, content-type, x-client-info','Access-Control-Allow-Methods':'GET,POST,DELETE,OPTIONS','Access-Control-Max-Age':'86400','Vary':'Origin','Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}}
const j=(req:Request,data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:cors(req)})
const fail=(req:Request,detail:string,status=400,extra:Record<string,unknown>={})=>j(req,{detail,...extra},status)
const parse=async(req:Request)=>{try{return await req.json()}catch{return{}}}
function b64(bytes:Uint8Array){let raw='';for(const b of bytes)raw+=String.fromCharCode(b);return btoa(raw).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function unb64(value:string){let v=value.replace(/-/g,'+').replace(/_/g,'/');while(v.length%4)v+='=';return Uint8Array.from(atob(v),c=>c.charCodeAt(0))}
function hex(bytes:Uint8Array){return Array.from(bytes).map(x=>x.toString(16).padStart(2,'0')).join('')}

async function auth(req:Request){const h=req.headers.get('authorization')||'',token=h.startsWith('Bearer ')?h.slice(7):'';if(!token)return null;const{data,error}=await anon.auth.getUser(token);if(error||!data.user)return null;let p=(await admin.from('users').select('id,email,full_name').eq('auth_user_id',data.user.id).maybeSingle()).data;if(!p&&data.user.email)p=(await admin.from('users').select('id,email,full_name').ilike('email',data.user.email).maybeSingle()).data;return p||null}
async function member(userId:number,businessId:number,write=false){const r=await admin.from('memberships').select('id,role').eq('user_id',userId).eq('business_id',businessId).maybeSingle();if(r.error||!r.data)return null;if(write&&!['owner','admin'].includes(r.data.role))return null;return r.data}
async function audit(businessId:number,userId:number,action:string,payload:unknown){try{await admin.from('audit_logs').insert({business_id:businessId,actor_user_id:userId,action,entity_type:'integration_connection',entity_id:'pagbank',payload_json:JSON.stringify(payload??{})})}catch{/* Audit telemetry must not break authorization. */}}

async function rootBytes(){const seed=env('C360_INTEGRATION_KEY')||`${SERVICE_KEY}:c360-integrations-v29`;return new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(seed)))}
async function aesKey(){return crypto.subtle.importKey('raw',await rootBytes(),{name:'AES-GCM'},false,['encrypt','decrypt'])}
async function hmacKey(){return crypto.subtle.importKey('raw',await rootBytes(),{name:'HMAC',hash:'SHA-256'},false,['sign','verify'])}
async function seal(value:unknown){const iv=crypto.getRandomValues(new Uint8Array(12)),ct=await crypto.subtle.encrypt({name:'AES-GCM',iv},await aesKey(),enc.encode(JSON.stringify(value)));return{ciphertext:b64(new Uint8Array(ct)),iv:b64(iv)}}
async function openSecret(row:any){const pt=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(row.iv)},await aesKey(),unb64(row.ciphertext));return JSON.parse(dec.decode(pt))}
async function signState(businessId:number,userId:number,origin:string){const exp=Math.floor(Date.now()/1000)+600,nonce=hex(crypto.getRandomValues(new Uint8Array(6))),prefix=`B${businessId.toString(36)}U${userId.toString(36)}E${exp.toString(36)}O${originCode(origin)}N${nonce}S`,sig=new Uint8Array(await crypto.subtle.sign('HMAC',await hmacKey(),enc.encode(prefix)));return prefix+hex(sig.slice(0,16))}
async function verifyState(state:string){const m=state.match(/^B([0-9a-z]+)U([0-9a-z]+)E([0-9a-z]+)O([RNL])N([0-9a-f]{12})S([0-9a-f]{32})$/i);if(!m)return null;const prefix=state.slice(0,-32),sig=state.slice(-32),signed=new Uint8Array(await crypto.subtle.sign('HMAC',await hmacKey(),enc.encode(prefix)));if(hex(signed.slice(0,16)).toLowerCase()!==sig.toLowerCase())return null;const businessId=parseInt(m[1],36),userId=parseInt(m[2],36),exp=parseInt(m[3],36);if(!businessId||!userId||!exp||exp<Math.floor(Date.now()/1000))return null;return{businessId,userId,origin:originFromCode(m[4])}}

async function connection(businessId:number){const r=await admin.from('integration_connections').select('*').eq('business_id',businessId).eq('provider','pagbank').order('id',{ascending:true}).limit(1).maybeSingle();if(r.error)throw r.error;return r.data}
async function ensureConnection(businessId:number){const current=await connection(businessId);if(current){const u=await admin.from('integration_connections').update({status:'connecting',last_error:null,updated_at:now()}).eq('id',current.id).select('*').single();if(u.error)throw u.error;return u.data}const r=await admin.from('integration_connections').insert({business_id:businessId,provider:'pagbank',mode:'webhook',status:'connecting'}).select('*').single();if(r.error)throw r.error;return r.data}
async function credential(connectionId:number){const r=await admin.from('integration_credentials').select('*').eq('connection_id',connectionId).maybeSingle();if(r.error)throw r.error;return r.data?{row:r.data,secret:await openSecret(r.data),metadata:typeof r.data.metadata_json==='string'?JSON.parse(r.data.metadata_json||'{}'):r.data.metadata_json||{},scopes:typeof r.data.scopes_json==='string'?JSON.parse(r.data.scopes_json||'[]'):r.data.scopes_json||[]}:null}
async function saveCredential(conn:any,secret:any,expiresAt:string|null,scopes:string[],metadata:any={}){const encrypted=await seal(secret),r=await admin.from('integration_credentials').upsert({connection_id:conn.id,business_id:conn.business_id,provider:'pagbank',ciphertext:encrypted.ciphertext,iv:encrypted.iv,key_version:1,expires_at:expiresAt,scopes_json:JSON.stringify(scopes),metadata_json:JSON.stringify(metadata),updated_at:now()},{onConflict:'connection_id'});if(r.error)throw r.error}
const expiry=(secret:any)=>Number(secret.expires_in||0)?new Date(Date.now()+Number(secret.expires_in)*1000).toISOString():null

function platformHeaders(extra:Record<string,string>={}){return{accept:'application/json',authorization:`Bearer ${env('PAGBANK_APP_TOKEN')}`,'x-client-id':env('PAGBANK_CLIENT_ID'),'x-client-secret':env('PAGBANK_CLIENT_SECRET'),...extra}}
async function api(url:string,init:RequestInit,label:string){const r=await fetch(url,init),x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(clean(x?.message||x?.error_description||x?.error?.message||x?.error||`${label} recusou a solicitação`,800));return x}
async function exchange(code:string){return api(`${apiBase()}/oauth2/token`,{method:'POST',headers:platformHeaders({'content-type':'application/json'}),body:JSON.stringify({grant_type:'authorization_code',code,redirect_uri:callbackUrl()})},'PagBank OAuth')}
async function refresh(secret:any){if(!secret.refresh_token)throw new Error('PagBank exige nova autorização');return api(`${apiBase()}/oauth2/refresh`,{method:'POST',headers:platformHeaders({'content-type':'application/json'}),body:JSON.stringify({grant_type:'refresh_token',refresh_token:secret.refresh_token})},'PagBank refresh')}
async function revoke(token:string){return api(`${apiBase()}/oauth2/revoke`,{method:'POST',headers:platformHeaders({'content-type':'application/json'}),body:JSON.stringify({token_type_hint:'access_token',token})},'PagBank revoke')}
async function accountProbe(accountId:string,accessToken:string){return api(`${apiBase()}/accounts/${encodeURIComponent(accountId)}`,{headers:{accept:'application/json',authorization:`Bearer ${env('PAGBANK_APP_TOKEN')}`,'x-client-token':accessToken}},'PagBank account')}
async function fresh(conn:any,current:any){const exp=current.row.expires_at?Date.parse(current.row.expires_at):0;if(!exp||exp>Date.now()+300000)return current;const next=await refresh(current.secret),expiresAt=expiry(next),metadata={...current.metadata,refreshed_at:now()};await saveCredential(conn,next,expiresAt,current.scopes,metadata);return{...current,secret:next,row:{...current.row,expires_at:expiresAt},metadata}}
function readiness(){return{provider:'pagbank',environment:environment(),platform_ready:ready(),state:ready()?'ready_to_authorize':configured()?'partner_approval':'platform_setup_required',authorization:'PagBank Connect Authorization',user_action:ready()?'authorize_account':'none',configured:configured(),homologated:homologated(),homologation_required:environment()==='production',redirect_uri:callbackUrl()}}
function safeConnection(row:any){return row?{provider:'pagbank',status:row.status,display_name:row.display_name||null,external_account_ref:row.external_account_ref||null,last_success_at:row.last_success_at||null,last_error:row.last_error||null}:null}

async function status(req:Request,businessId:number){const who:any=await auth(req);if(!who)return fail(req,'Sem acesso',401);if(!await member(Number(who.id),businessId))return fail(req,'Sem acesso',403);return j(req,{ok:true,version:VERSION,readiness:readiness(),connection:safeConnection(await connection(businessId))})}
async function start(req:Request,businessId:number){const who:any=await auth(req);if(!who)return fail(req,'Sem acesso',401);if(!await member(Number(who.id),businessId,true))return fail(req,'Somente owner/admin pode conectar PagBank.',403);if(!configured())return fail(req,'PagBank ainda não foi habilitado pela plataforma.',503,{code:'platform_setup_required',readiness:readiness()});if(!homologated())return fail(req,'A integração PagBank aguarda homologação de produção.',503,{code:'partner_approval',readiness:readiness()});const body:any=await parse(req),origin=originOf(body.return_origin||req.headers.get('origin')),state=await signState(businessId,Number(who.id),origin),scope='payments.read payments.create accounts.read checkout.create checkout.view',q=new URLSearchParams({client_id:env('PAGBANK_CLIENT_ID'),response_type:'code',redirect_uri:callbackUrl(),scope,state});await ensureConnection(businessId);await audit(businessId,Number(who.id),'integration.pagbank.connect_started',{environment:environment(),scope});return j(req,{ok:true,provider:'pagbank',authorization_url:`${connectBase()}?${q.toString()}`,expires_in_seconds:600,readiness:readiness()})}
async function callback(req:Request){const url=new URL(req.url),state=await verifyState(clean(url.searchParams.get('state'),128));if(!state)return new Response('Estado de autorização inválido ou expirado.',{status:400,headers:{'Content-Type':'text/plain; charset=utf-8'}});const back=new URL(state.origin);back.searchParams.set('connections','1');const error=clean(url.searchParams.get('error'),200),code=clean(url.searchParams.get('code'),200);if(error){back.searchParams.set('pagbank','denied');return Response.redirect(back.toString(),302)}if(!code){back.searchParams.set('pagbank','missing_code');return Response.redirect(back.toString(),302)}if(!await member(state.userId,state.businessId,true)){back.searchParams.set('pagbank','membership_changed');return Response.redirect(back.toString(),302)}try{const token=await exchange(code),conn=await ensureConnection(state.businessId),accountId=clean(token.account_id||token.account?.id||'',100)||null,scopes=clean(token.scope,500).split(/[ +]/).filter(Boolean),expiresAt=expiry(token),metadata={environment:environment(),authorized_at:now(),account_id:accountId};await saveCredential(conn,token,expiresAt,scopes,metadata);let label='Conta PagBank autorizada';if(accountId&&token.access_token){try{const account=await accountProbe(accountId,String(token.access_token));label=clean(account?.company?.name||account?.person?.name||account?.name||account?.email,180)||label}catch{/* Enrichment is optional. */}}const u=await admin.from('integration_connections').update({status:'active',external_account_ref:accountId,display_name:label,last_success_at:now(),last_error:null,updated_at:now()}).eq('id',conn.id);if(u.error)throw u.error;await audit(state.businessId,state.userId,'integration.pagbank.connected',{environment:environment(),account_id:accountId,scopes});back.searchParams.set('pagbank','connected');return Response.redirect(back.toString(),302)}catch(e){const message=clean((e as any)?.message||e,800),conn=await connection(state.businessId);if(conn)await admin.from('integration_connections').update({status:'degraded',last_error:message,last_error_at:now(),updated_at:now()}).eq('id',conn.id);await audit(state.businessId,state.userId,'integration.pagbank.connect_failed',{message});back.searchParams.set('pagbank','error');return Response.redirect(back.toString(),302)}}
async function test(req:Request,businessId:number){const who:any=await auth(req);if(!who)return fail(req,'Sem acesso',401);if(!await member(Number(who.id),businessId))return fail(req,'Sem acesso',403);const conn=await connection(businessId);if(!conn)return fail(req,'PagBank ainda não está conectado.',409,{code:'connection_required'});let current=await credential(conn.id);if(!current)return fail(req,'Credencial PagBank ausente.',409,{code:'credential_missing'});try{current=await fresh(conn,current);const accountId=clean(current.metadata?.account_id||current.secret?.account_id||'',100);if(accountId&&current.secret?.access_token)await accountProbe(accountId,String(current.secret.access_token));const u=await admin.from('integration_connections').update({status:'active',last_success_at:now(),last_error:null,updated_at:now()}).eq('id',conn.id).select('*').single();if(u.error)throw u.error;await audit(businessId,Number(who.id),'integration.pagbank.tested',{probe:accountId?'account':'token_lifecycle'});return j(req,{ok:true,provider:'pagbank',probe:accountId?'account_lookup':'token_lifecycle',connection:safeConnection(u.data)})}catch(e){const message=clean((e as any)?.message||e,800);await admin.from('integration_connections').update({status:'degraded',last_error:message,last_error_at:now(),updated_at:now()}).eq('id',conn.id);return fail(req,message,502,{code:'provider_test_failed'})}}
async function disconnect(req:Request,businessId:number){const who:any=await auth(req);if(!who)return fail(req,'Sem acesso',401);if(!await member(Number(who.id),businessId,true))return fail(req,'Somente owner/admin pode desconectar PagBank.',403);const conn=await connection(businessId);if(!conn)return j(req,{ok:true,already_disconnected:true});const current=await credential(conn.id);if(current?.secret?.access_token){try{await revoke(String(current.secret.access_token))}catch(e){return fail(req,`O PagBank não confirmou a revogação: ${clean((e as any)?.message||e,300)}`,502,{code:'remote_revoke_failed'})}}const d=await admin.from('integration_credentials').delete().eq('connection_id',conn.id);if(d.error)throw d.error;const u=await admin.from('integration_connections').update({status:'inactive',external_account_ref:null,display_name:null,last_error:null,updated_at:now()}).eq('id',conn.id);if(u.error)throw u.error;await audit(businessId,Number(who.id),'integration.pagbank.disconnected',{});return j(req,{ok:true,connection:{provider:'pagbank',status:'inactive'}})}

Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(req)});const path=routePath(req);try{if(req.method==='GET'&&path==='/health')return j(req,{ok:true,service:SLUG,version:VERSION,readiness:readiness()});if(req.method==='GET'&&path==='/oauth/callback')return await callback(req);let m=path.match(/^\/businesses\/(\d+)\/status$/);if(req.method==='GET'&&m)return await status(req,Number(m[1]));m=path.match(/^\/businesses\/(\d+)\/connect$/);if(req.method==='POST'&&m)return await start(req,Number(m[1]));m=path.match(/^\/businesses\/(\d+)\/test$/);if(req.method==='POST'&&m)return await test(req,Number(m[1]));m=path.match(/^\/businesses\/(\d+)\/disconnect$/);if(req.method==='DELETE'&&m)return await disconnect(req,Number(m[1]));return fail(req,'Rota não encontrada',404)}catch(e){return fail(req,clean((e as any)?.message||e,800),500)}})
