import { createClient } from 'npm:@supabase/supabase-js@2.115.0'

const URL=Deno.env.get('SUPABASE_URL')||''
const SERVICE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||''
const SLUG='cozinha360-checkout-payments-v57'
const VERSION='5.7.7'
const CORE=`${URL}/functions/v1/cozinha360-payments-v56`
const admin=createClient(URL,SERVICE,{auth:{persistSession:false,autoRefreshToken:false}})
const productionOrigins=new Set(['https://cozinha-360-os.netlify.app','https://cozinha-360-os-v41.onrender.com'])

function corsHeaders(req:Request){const origin=req.headers.get('origin')||'';const local=origin.startsWith('http://localhost:')||origin.startsWith('http://127.0.0.1:');const allowed=productionOrigins.has(origin)||local;return{'Access-Control-Allow-Origin':allowed?origin:'https://cozinha-360-os.netlify.app','Access-Control-Allow-Headers':'content-type','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','Vary':'Origin','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer'}}
function out(req:Request,data:unknown,status=200){return new Response(JSON.stringify(data),{status,headers:corsHeaders(req)})}
function fail(req:Request,detail:string,status=400,extra:Record<string,unknown>={}){return out(req,{detail,...extra},status)}
function clean(value:unknown,max=320){return String(value??'').trim().slice(0,max)}
async function readBody(req:Request){try{return await req.json()}catch{return{}}}
function pending(status:string){return status==='created'||status==='action_required'||status==='processing'}

async function capability(businessId:number){const profile=await admin.from('integration_profiles').select('use_mercadopago').eq('business_id',businessId).maybeSingle();if(profile.error)throw profile.error;if(!profile.data?.use_mercadopago)return{available:false,reason:'disabled'};const connection=await admin.from('integration_connections').select('id').eq('business_id',businessId).eq('provider','mercadopago').eq('status','active').limit(1).maybeSingle();if(connection.error)throw connection.error;if(!connection.data)return{available:false,reason:'connection_required'};return{available:true,reason:'ready'}}

async function verifyDirectOrder(businessId:number,orderId:number,clientKey:string){if(clientKey.length<8)return null;const order=await admin.from('orders').select('id,business_id,customer_id,total_cents,paid,idempotency_key').eq('id',orderId).eq('business_id',businessId).maybeSingle();if(order.error)throw order.error;if(!order.data||String(order.data.idempotency_key)!==clientKey)return null;const checkout=await admin.from('direct_order_checkouts').select('order_id').eq('order_id',orderId).eq('business_id',businessId).maybeSingle();if(checkout.error)throw checkout.error;return checkout.data?order.data:null}

async function corePix(businessId:number,orderId:number,payerEmail:string){const response=await fetch(`${CORE}/businesses/${businessId}/orders/${orderId}/pix`,{method:'POST',headers:{authorization:`Bearer ${SERVICE}`,'content-type':'application/json'},body:JSON.stringify({payer_email:payerEmail})});const parsed=await response.json().catch(()=>({}));if(!response.ok){const code=typeof parsed.code==='string'?parsed.code:undefined;const detail=code==='payer_email_required'?'Informe um e-mail válido para gerar o Pix.':code==='connection_required'?'Pix ainda não está disponível nesta cozinha.':'Não foi possível gerar o Pix agora.';return{ok:false,status:response.status,detail,code}}return{ok:true,status:response.status,data:parsed}}

function safePayment(row:any){return{token:row.public_token,status:row.status,status_detail:row.status_detail,paid:row.status==='processed',amount_cents:Number(row.amount_cents),qr_code:row.status==='processed'?null:row.qr_code,qr_code_base64:row.status==='processed'?null:row.qr_code_base64,ticket_url:row.status==='processed'?null:row.ticket_url,expires_at:row.expires_at,updated_at:row.updated_at}}

async function createPix(req:Request){const payload:any=await readBody(req);const businessId=Number(payload.business_id),orderId=Number(payload.order_id),clientKey=clean(payload.client_order_key,120),payerEmail=clean(payload.payer_email,320).toLowerCase();if(!Number.isInteger(businessId)||!Number.isInteger(orderId))return fail(req,'Pedido inválido',422);const order=await verifyDirectOrder(businessId,orderId,clientKey);if(!order)return fail(req,'Este pedido não autoriza uma cobrança pública.',403);const cap=await capability(businessId);if(!cap.available)return fail(req,'Pix não está disponível nesta cozinha.',409,{code:cap.reason});if(order.paid)return out(req,{ok:true,already_paid:true,payment:{paid:true,status:'processed',amount_cents:Number(order.total_cents)}});const result=await corePix(businessId,orderId,payerEmail);if(!result.ok)return fail(req,result.detail,result.status,result.code?{code:result.code}:{});return out(req,result.data,result.status)}

async function publicStatus(req:Request,token:string){const result=await admin.from('payment_intents').select('*').eq('public_token',token).maybeSingle();if(result.error)throw result.error;if(!result.data)return fail(req,'Cobrança não encontrada',404);let intent=result.data;if(pending(String(intent.status))){try{const order=await admin.from('orders').select('customer_id').eq('id',intent.order_id).eq('business_id',intent.business_id).maybeSingle();let email='';if(order.data?.customer_id){const customer=await admin.from('customers').select('email').eq('id',order.data.customer_id).eq('business_id',intent.business_id).maybeSingle();email=clean(customer.data?.email,320).toLowerCase()}if(email.includes('@')){const refreshed=await corePix(Number(intent.business_id),Number(intent.order_id),email);if(refreshed.ok&&refreshed.data?.payment)return out(req,{payment:refreshed.data.payment})}}catch(error){console.error('pix status reconcile fallback',error)}const latest=await admin.from('payment_intents').select('*').eq('id',intent.id).maybeSingle();if(!latest.error&&latest.data)intent=latest.data}return out(req,{payment:safePayment(intent)})}

async function ready(req:Request){const [db,core]=await Promise.all([admin.from('payment_intents').select('id',{head:true,count:'exact'}).limit(1),fetch(`${CORE}/health`).then(async response=>({ok:response.ok,status:response.status})).catch(()=>({ok:false,status:0}))]);const ok=!db.error&&core.ok;return out(req,{ok,service:SLUG,version:VERSION,database:db.error?'error':'ready',payments_core:core.ok?'ready':'unavailable'},ok?200:503)}

Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:corsHeaders(req)});const route=req.url.split('?')[0];try{if(req.method==='GET'&&route.endsWith('/livez'))return out(req,{ok:true,service:SLUG,version:VERSION,public_checkout:true});if(req.method==='GET'&&route.endsWith('/readyz'))return await ready(req);const capMarker='/capability/';const capIndex=route.lastIndexOf(capMarker);if(req.method==='GET'&&capIndex>=0){const businessId=Number(route.slice(capIndex+capMarker.length));if(Number.isInteger(businessId))return out(req,{pix:await capability(businessId)})}if(req.method==='POST'&&route.endsWith('/pix'))return await createPix(req);const statusMarker='/status/';const statusIndex=route.lastIndexOf(statusMarker);if(req.method==='GET'&&statusIndex>=0){const token=route.slice(statusIndex+statusMarker.length);if(/^[0-9a-f-]{36}$/i.test(token))return await publicStatus(req,token)}return fail(req,'Rota não encontrada',404)}catch(error){console.error('checkout-payments-v57',error);return fail(req,'Não foi possível processar o pagamento agora.',500)}})
