import { createClient } from 'npm:@supabase/supabase-js@2.115.0'

const URL=Deno.env.get('SUPABASE_URL')!
const SERVICE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
const SLUG='cozinha360-checkout-payments-v57'
const VERSION='5.7.2'
const CORE=`${URL}/functions/v1/cozinha360-payments-v56`
const admin=createClient(URL,SERVICE,{auth:{persistSession:false,autoRefreshToken:false}})

function pathOf(req:Request){const path=new URL(req.url).pathname,marker=`/${SLUG}`,i=path.indexOf(marker);return i>=0?(path.slice(i+marker.length)||'/'):path}
function cors(req:Request){const origin=req.headers.get('origin')||'',allowed=/^https:\/\/([a-z0-9-]+\.)?(cozinha-360-os\.netlify\.app|onrender\.com)$/i.test(origin)||/^http:\/\/(localhost|127\.0\.0\.1):\d+$/i.test(origin);return{'Access-Control-Allow-Origin':allowed?origin:'https://cozinha-360-os.netlify.app','Access-Control-Allow-Headers':'content-type','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','Vary':'Origin','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer'}}
const out=(req:Request,data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:cors(req)})
const fail=(req:Request,detail:string,status=400,extra:Record<string,unknown>={})=>out(req,{detail,...extra},status)
const clean=(v:unknown,max=320)=>String(v??'').trim().slice(0,max)
const body=async(req:Request)=>{try{return await req.json()}catch{return{}}}

async function capability(businessId:number){const [profile,connection]=await Promise.all([admin.from('integration_profiles').select('use_mercadopago').eq('business_id',businessId).maybeSingle(),admin.from('integration_connections').select('id').eq('business_id',businessId).eq('provider','mercadopago').eq('status','active').limit(1).maybeSingle()]);if(profile.error)throw profile.error;if(connection.error)throw connection.error;if(!profile.data?.use_mercadopago)return{available:false,reason:'disabled'};if(!connection.data)return{available:false,reason:'connection_required'};return{available:true,reason:'ready'}}

async function verifyDirectOrder(businessId:number,orderId:number,clientKey:string){if(clientKey.length<8)return null;const [order,checkout]=await Promise.all([admin.from('orders').select('id,business_id,total_cents,paid,idempotency_key').eq('id',orderId).eq('business_id',businessId).maybeSingle(),admin.from('direct_order_checkouts').select('order_id').eq('order_id',orderId).eq('business_id',businessId).maybeSingle()]);if(order.error)throw order.error;if(checkout.error)throw checkout.error;if(!order.data||!checkout.data||String(order.data.idempotency_key)!==clientKey)return null;return order.data}

async function corePix(businessId:number,orderId:number,payerEmail:string){const response=await fetch(`${CORE}/businesses/${businessId}/orders/${orderId}/pix`,{method:'POST',headers:{authorization:`Bearer ${SERVICE}`,'content-type':'application/json'},body:JSON.stringify({payer_email:payerEmail})}),parsed=await response.json().catch(()=>({}));if(!response.ok){const code=typeof parsed.code==='string'?parsed.code:undefined,detail=code==='payer_email_required'?'Informe um e-mail válido para gerar o Pix.':code==='connection_required'?'Pix ainda não está disponível nesta cozinha.':'Não foi possível gerar o Pix agora.';return{ok:false,status:response.status,detail,code}}return{ok:true,status:response.status,data:parsed}}

function safePayment(row:any){return{token:row.public_token,status:row.status,status_detail:row.status_detail,paid:row.status==='processed',amount_cents:Number(row.amount_cents),qr_code:row.status==='processed'?null:row.qr_code,qr_code_base64:row.status==='processed'?null:row.qr_code_base64,ticket_url:row.status==='processed'?null:row.ticket_url,expires_at:row.expires_at,updated_at:row.updated_at}}

async function createPix(req:Request){const payload:any=await body(req),businessId=Number(payload.business_id),orderId=Number(payload.order_id),clientKey=clean(payload.client_order_key,120),payerEmail=clean(payload.payer_email,320).toLowerCase();if(!Number.isInteger(businessId)||!Number.isInteger(orderId))return fail(req,'Pedido inválido',422);const order=await verifyDirectOrder(businessId,orderId,clientKey);if(!order)return fail(req,'Este pedido não autoriza uma cobrança pública.',403);const cap=await capability(businessId);if(!cap.available)return fail(req,'Pix não está disponível nesta cozinha.',409,{code:cap.reason});if(order.paid)return out(req,{ok:true,already_paid:true,payment:{paid:true,status:'processed',amount_cents:Number(order.total_cents)}});const result=await corePix(businessId,orderId,payerEmail);if(!result.ok)return fail(req,result.detail,result.status,{...(result.code?{code:result.code}:{})});return out(req,result.data,result.status)}

async function status(req:Request,token:string){const result=await admin.from('payment_intents').select('*').eq('public_token',token).maybeSingle();if(result.error)throw result.error;if(!result.data)return fail(req,'Cobrança não encontrada',404);return out(req,{payment:safePayment(result.data)})}

Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(req)});const path=pathOf(req);try{if(path==='/livez'&&req.method==='GET')return out(req,{ok:true,service:SLUG,version:VERSION,core:'cozinha360-payments-v56',public_checkout:true,reconciliation:'server_cron_and_webhook_when_configured'});let match=path.match(/^\/capability\/(\d+)$/);if(match&&req.method==='GET')return out(req,{pix:await capability(Number(match[1]))});if(path==='/pix'&&req.method==='POST')return await createPix(req);match=path.match(/^\/status\/([0-9a-f-]{36})$/i);if(match&&req.method==='GET')return await status(req,match[1]);return fail(req,'Rota não encontrada',404)}catch(error){console.error('checkout-payments-v57',error);return fail(req,'Não foi possível processar o pagamento agora.',500)}})
