import { createClient } from 'npm:@supabase/supabase-js@2.115.0'

const URL=Deno.env.get('SUPABASE_URL')!
const SERVICE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
const CLIENT_ID=(Deno.env.get('MERCADOPAGO_CLIENT_ID')||'').trim()
const CLIENT_SECRET=(Deno.env.get('MERCADOPAGO_CLIENT_SECRET')||'').trim()
const SLUG='cozinha360-checkout-payments-v57'
const VERSION='5.7.1'
const admin=createClient(URL,SERVICE,{auth:{persistSession:false,autoRefreshToken:false}})
const enc=new TextEncoder(),dec=new TextDecoder()
const now=()=>new Date().toISOString()
const clean=(v:unknown,max=320)=>String(v??'').trim().slice(0,max)
const money=(cents:number)=>(Math.max(0,Math.trunc(cents))/100).toFixed(2)

function pathOf(req:Request){const p=new URL(req.url).pathname,m=`/${SLUG}`,i=p.indexOf(m);return i>=0?(p.slice(i+m.length)||'/'):p}
function cors(req:Request){const o=req.headers.get('origin')||'';const ok=/^https:\/\/([a-z0-9-]+\.)?(cozinha-360-os\.netlify\.app|onrender\.com)$/i.test(o)||/^http:\/\/(localhost|127\.0\.0\.1):\d+$/i.test(o);return{'Access-Control-Allow-Origin':ok?o:'https://cozinha-360-os.netlify.app','Access-Control-Allow-Headers':'content-type','Access-Control-Allow-Methods':'GET,POST,OPTIONS','Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','Vary':'Origin','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer'}}
const out=(req:Request,data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:cors(req)})
const fail=(req:Request,detail:string,status=400,extra:Record<string,unknown>={})=>out(req,{detail,...extra},status)
const body=async(req:Request)=>{try{return await req.json()}catch{return{}}}

function b64(bytes:Uint8Array){let raw='';for(const b of bytes)raw+=String.fromCharCode(b);return btoa(raw).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function unb64(value:string){let v=value.replace(/-/g,'+').replace(/_/g,'/');while(v.length%4)v+='=';return Uint8Array.from(atob(v),c=>c.charCodeAt(0))}
async function rootBytes(){const seed=(Deno.env.get('C360_INTEGRATION_KEY')||'').trim()||`${SERVICE}:c360-integrations-v29`;return new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(seed)))}
async function aesKey(){return crypto.subtle.importKey('raw',await rootBytes(),{name:'AES-GCM'},false,['encrypt','decrypt'])}
async function openSecret(row:any){const pt=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(row.iv)},await aesKey(),unb64(row.ciphertext));return JSON.parse(dec.decode(pt))}
async function seal(value:unknown){const iv=crypto.getRandomValues(new Uint8Array(12)),ct=await crypto.subtle.encrypt({name:'AES-GCM',iv},await aesKey(),enc.encode(JSON.stringify(value)));return{ciphertext:b64(new Uint8Array(ct)),iv:b64(iv)}}

async function credential(connection:any){const r=await admin.from('integration_credentials').select('*').eq('connection_id',connection.id).maybeSingle();if(r.error)throw r.error;if(!r.data)return null;return{row:r.data,secret:await openSecret(r.data),metadata:typeof r.data.metadata_json==='string'?JSON.parse(r.data.metadata_json||'{}'):r.data.metadata_json||{}}}
async function fresh(connection:any,current:any){const exp=current.row.expires_at?Date.parse(current.row.expires_at):0;if(!exp||exp>Date.now()+5*60_000)return current;if(!current.secret.refresh_token)throw new Error('Mercado Pago exige nova autorização');const r=await fetch('https://api.mercadopago.com/oauth/token',{method:'POST',headers:{accept:'application/json','content-type':'application/json'},body:JSON.stringify({client_id:CLIENT_ID,client_secret:CLIENT_SECRET,grant_type:'refresh_token',refresh_token:current.secret.refresh_token})}),x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(String(x?.message||x?.error_description||x?.error||'Falha ao renovar Mercado Pago'));const secret={...current.secret,...x},seconds=Number(secret.expires_in||0),expiresAt=seconds?new Date(Date.now()+seconds*1000).toISOString():null,sealed=await seal(secret),u=await admin.from('integration_credentials').update({ciphertext:sealed.ciphertext,iv:sealed.iv,expires_at:expiresAt,metadata_json:JSON.stringify({...current.metadata,refreshed_at:now()}),updated_at:now()}).eq('connection_id',connection.id);if(u.error)throw u.error;return{...current,secret,row:{...current.row,expires_at:expiresAt}}}
async function mp(connection:any,url:string,init:RequestInit={}){let c=await credential(connection);if(!c)throw new Error('Credencial Mercado Pago ausente');c=await fresh(connection,c);const r=await fetch(url,{...init,headers:{accept:'application/json',authorization:`Bearer ${c.secret.access_token}`,...(init.headers||{})}}),x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(String(x?.message||x?.error||x?.cause?.[0]?.description||'Mercado Pago recusou a solicitação'));return x}

async function capability(businessId:number){const [profileR,connectionR]=await Promise.all([admin.from('integration_profiles').select('use_mercadopago').eq('business_id',businessId).maybeSingle(),admin.from('integration_connections').select('id,status').eq('business_id',businessId).eq('provider','mercadopago').eq('status','active').limit(1).maybeSingle()]);if(profileR.error)throw profileR.error;if(connectionR.error)throw connectionR.error;if(!profileR.data?.use_mercadopago)return{available:false,reason:'disabled'};if(!connectionR.data)return{available:false,reason:'connection_required'};return{available:true,reason:'ready'}}

function paymentNode(order:any){return order?.transactions?.payments?.[0]||null}
function safe(row:any){return{token:row.public_token,status:row.status,status_detail:row.status_detail,paid:row.status==='processed',amount_cents:Number(row.amount_cents),qr_code:row.status==='processed'?null:row.qr_code,qr_code_base64:row.status==='processed'?null:row.qr_code_base64,ticket_url:row.status==='processed'?null:row.ticket_url,expires_at:row.expires_at,updated_at:row.updated_at}}
function status(value:string){return new Set(['created','action_required','processing','processed','failed','canceled','expired','refunded','charged_back']).has(value)?value:'processing'}
function pending(value:string){return ['created','action_required','processing'].includes(value)}
async function sync(intent:any,connection:any,remote:any){if(String(remote.external_reference||'')!==String(intent.external_reference))throw new Error('Referência de pagamento divergente');const cents=Math.round(Number(remote.total_amount||0)*100);if(cents&&cents!==Number(intent.amount_cents))throw new Error('Valor de pagamento divergente');const payment=paymentNode(remote),next=status(String(remote.status||'processing')),detail=clean(remote.status_detail,80)||null,paid=next==='processed'&&['accredited','partially_refunded','processed'].includes(String(detail||'accredited')),patch={external_order_id:String(remote.id||intent.external_order_id||'')||null,status:next,status_detail:detail,qr_code:payment?.payment_method?.qr_code||null,qr_code_base64:payment?.payment_method?.qr_code_base64||null,ticket_url:payment?.payment_method?.ticket_url||null,last_error:null,updated_at:now()};const u=await admin.from('payment_intents').update(patch).eq('id',intent.id).select('*').single();if(u.error)throw u.error;const o=await admin.from('orders').update({paid,updated_at:now()}).eq('id',intent.order_id).eq('business_id',intent.business_id);if(o.error)throw o.error;return u.data}

async function verifyDirectOrder(businessId:number,orderId:number,clientKey:string){if(clientKey.length<8)return null;const o=await admin.from('orders').select('id,business_id,customer_id,total_cents,paid,status,idempotency_key').eq('id',orderId).eq('business_id',businessId).maybeSingle();if(o.error)throw o.error;if(!o.data||String(o.data.idempotency_key)!==clientKey)return null;const checkout=await admin.from('direct_order_checkouts').select('order_id').eq('order_id',orderId).eq('business_id',businessId).maybeSingle();if(checkout.error)throw checkout.error;return checkout.data?o.data:null}

async function createPix(req:Request){const p:any=await body(req),businessId=Number(p.business_id),orderId=Number(p.order_id),clientKey=clean(p.client_order_key,120);if(!Number.isInteger(businessId)||!Number.isInteger(orderId))return fail(req,'Pedido inválido',422);const order=await verifyDirectOrder(businessId,orderId,clientKey);if(!order)return fail(req,'Este pedido não autoriza uma cobrança pública.',403);const cap=await capability(businessId);if(!cap.available)return fail(req,'Pix não está disponível nesta cozinha.',409,{code:cap.reason});if(order.paid)return out(req,{ok:true,already_paid:true,payment:{paid:true,status:'processed',amount_cents:Number(order.total_cents)}});
 const connectionR=await admin.from('integration_connections').select('*').eq('business_id',businessId).eq('provider','mercadopago').eq('status','active').limit(1).maybeSingle();if(connectionR.error)throw connectionR.error;const connection=connectionR.data;if(!connection)return fail(req,'Pix temporariamente indisponível',409);
 let email=clean(p.payer_email,320).toLowerCase();if(!email&&order.customer_id){const c=await admin.from('customers').select('email').eq('id',order.customer_id).eq('business_id',businessId).maybeSingle();email=clean(c.data?.email,320).toLowerCase()}if(!email.includes('@'))return fail(req,'Informe um e-mail válido para gerar o Pix.',422,{code:'payer_email_required'});
 let ir=await admin.from('payment_intents').select('*').eq('business_id',businessId).eq('order_id',orderId).eq('provider','mercadopago').eq('method','pix').maybeSingle();if(ir.error)throw ir.error;let intent=ir.data;
 if(intent?.external_order_id){try{const remote=await mp(connection,`https://api.mercadopago.com/v1/orders/${encodeURIComponent(intent.external_order_id)}`);intent=await sync(intent,connection,remote);if(['created','action_required','processing','processed'].includes(String(intent.status)))return out(req,{ok:true,reused:true,payment:safe(intent)})}catch(e){await admin.from('payment_intents').update({last_error:clean((e as any)?.message,800),updated_at:now()}).eq('id',intent.id)}}
 if(intent&&['failed','canceled','expired','refunded','charged_back'].includes(String(intent.status))){const r=await admin.from('payment_intents').update({idempotency_key:crypto.randomUUID(),external_order_id:null,status:'created',status_detail:null,qr_code:null,qr_code_base64:null,ticket_url:null,expires_at:null,last_error:null,updated_at:now()}).eq('id',intent.id).select('*').single();if(r.error)throw r.error;intent=r.data}
 if(!intent){const r=await admin.from('payment_intents').insert({business_id:businessId,order_id:orderId,connection_id:connection.id,provider:'mercadopago',method:'pix',external_reference:`c360:${businessId}:${orderId}`,amount_cents:Number(order.total_cents)}).select('*').single();if(r.error)throw r.error;intent=r.data}
 const amount=money(Number(intent.amount_cents)),payload={type:'online',total_amount:amount,external_reference:intent.external_reference,processing_mode:'automatic',transactions:{payments:[{amount,payment_method:{id:'pix',type:'bank_transfer'},expiration_time:'PT30M'}]},payer:{email}},remote=await mp(connection,'https://api.mercadopago.com/v1/orders',{method:'POST',headers:{'content-type':'application/json','X-Idempotency-Key':String(intent.idempotency_key)},body:JSON.stringify(payload)}),expiresAt=new Date(Date.now()+30*60_000).toISOString(),synced=await sync({...intent,expires_at:expiresAt},connection,remote),u=await admin.from('payment_intents').update({expires_at:expiresAt}).eq('id',intent.id).select('*').single();if(u.error)throw u.error;return out(req,{ok:true,reused:false,payment:safe({...synced,expires_at:expiresAt})},201)}

async function publicStatus(req:Request,token:string){const r=await admin.from('payment_intents').select('*').eq('public_token',token).maybeSingle();if(r.error)throw r.error;if(!r.data)return fail(req,'Cobrança não encontrada',404);let intent=r.data;if(pending(String(intent.status))&&intent.external_order_id){const c=await admin.from('integration_connections').select('*').eq('id',intent.connection_id).eq('business_id',intent.business_id).eq('provider','mercadopago').eq('status','active').maybeSingle();if(c.error)throw c.error;if(c.data){try{const remote=await mp(c.data,`https://api.mercadopago.com/v1/orders/${encodeURIComponent(intent.external_order_id)}`);intent=await sync(intent,c.data,remote)}catch(e){await admin.from('payment_intents').update({last_error:clean((e as any)?.message,800),updated_at:now()}).eq('id',intent.id)}}}return out(req,{payment:safe(intent)})}

Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(req)});const path=pathOf(req);try{if(path==='/livez'&&req.method==='GET')return out(req,{ok:true,service:SLUG,version:VERSION,provider:'mercadopago',surface:'public_checkout',active_reconciliation:true});let m=path.match(/^\/capability\/(\d+)$/);if(m&&req.method==='GET')return out(req,{pix:await capability(Number(m[1]))});if(path==='/pix'&&req.method==='POST')return await createPix(req);m=path.match(/^\/status\/([0-9a-f-]{36})$/i);if(m&&req.method==='GET')return await publicStatus(req,m[1]);return fail(req,'Rota não encontrada',404)}catch(e){console.error('checkout payment error',e);return fail(req,'Não foi possível processar o pagamento agora.',500)}})
