import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const U=Deno.env.get('SUPABASE_URL')!;const K=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const allowed=new Set(['https://plutyx.com','https://www.plutyx.com','https://ranking-conversao-preview.onrender.com','http://localhost:5173','http://127.0.0.1:5173']);
function cors(o:string|null){const origin=o&&allowed.has(o)?o:'https://plutyx.com';return {'access-control-allow-origin':origin,'access-control-allow-methods':'POST,OPTIONS','access-control-allow-headers':'content-type,authorization','vary':'Origin','content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'};}
function out(o:string|null,b:any,s=200){return new Response(JSON.stringify(b),{status:s,headers:cors(o)});}
async function rpc(name:string,body:any,token:string){const r=await fetch(`${U}/rest/v1/rpc/${name}`,{method:'POST',headers:{apikey:K,authorization:token,'content-type':'application/json'},body:JSON.stringify(body||{})});const t=await r.text();let d:any=null;try{d=t?JSON.parse(t):null}catch{d={raw:t.slice(0,500)}};if(!r.ok){const e=new Error(String(d?.message||d?.error||`rpc_${r.status}`));(e as any).status=r.status;throw e;}return d;}
async function adminRpc(name:string,body:any){const r=await fetch(`${U}/rest/v1/rpc/${name}`,{method:'POST',headers:{apikey:K,authorization:`Bearer ${K}`,'content-type':'application/json'},body:JSON.stringify(body||{})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error('rate_limit_failed');return d;}
async function me(token:string){const r=await fetch(`${U}/auth/v1/user`,{headers:{apikey:K,authorization:token}});if(!r.ok)throw new Error('authentication_required');return await r.json();}
async function verifyDomain(claimToken:string,token:string){const r=await fetch(`${U}/functions/v1/gcl-domain-verify`,{method:'POST',headers:{apikey:K,authorization:token,'content-type':'application/json'},body:JSON.stringify({claim_token:claimToken})});const d=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(String(d?.error||d?.detail||`verify_${r.status}`));(e as any).status=r.status;throw e;}return d;}
Deno.serve(async req=>{const origin=req.headers.get('origin');if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(origin)});if(origin&&!allowed.has(origin))return out(origin,{error:'origin_not_allowed'},403);if(req.method!=='POST')return out(origin,{error:'method_not_allowed'},405);const token=req.headers.get('authorization')||'';if(!token.toLowerCase().startsWith('bearer '))return out(origin,{error:'authentication_required'},401);
 try{const body=await req.json();const action=String(body?.action||'');const user=await me(token);const uid=String(user?.id||'');if(!uid)return out(origin,{error:'authentication_required'},401);const writes=['create_post','comment','create_project','apply_project','submit_hot_seat','create_experiment','create_case','verify_case','update_profile','react','comment_react','save_post','follow_member','view_post','checkout','begin_domain_claim','verify_domain','submit_awards','vote_awards','jury_score'];const rl=await adminRpc('consume_rate_limit',{p_route:`member:${action}`,p_bucket:uid,p_window_seconds:60,p_limit:writes.includes(action)?30:120});if(!rl?.allowed)return out(origin,{error:'rate_limited',reset_at:rl.reset_at},429);
 const call=(n:string,b:any={})=>rpc(n,b,token);
 if(action==='dashboard')return out(origin,{ok:true,result:await call('gcl_member_dashboard')});
 if(action==='link_purchases')return out(origin,{ok:true,result:await call('gcl_link_pending_purchases')});
 if(action==='analyses')return out(origin,{ok:true,result:await call('gcl_member_analyses')});
 if(action==='purchases')return out(origin,{ok:true,result:await call('gcl_member_purchases')});
 if(action==='checkout')return out(origin,{ok:true,result:await call('gcl_prepare_member_checkout',{p_product_code:String(body.product_code||''),p_domain_id:body.domain_id||null})},201);
 if(action==='begin_domain_claim')return out(origin,{ok:true,result:await call('gcl_begin_domain_claim',{p_domain:String(body.domain||''),p_method:String(body.method||'meta')})},201);
 if(action==='domain_claim_context')return out(origin,{ok:true,result:await call('gcl_domain_claim_context',{p_claim_token:body.claim_token})});
 if(action==='verify_domain')return out(origin,{ok:true,result:await verifyDomain(String(body.claim_token||''),token)});
 if(action==='spaces')return out(origin,{ok:true,result:await call('gcl_member_spaces')});
 if(action==='feed')return out(origin,{ok:true,result:await call('gcl_community_feed',{p_space_slug:String(body.space||'feed'),p_before:body.before||null,p_limit:Number(body.limit||30)})});
 if(action==='create_post')return out(origin,{ok:true,result:await call('gcl_create_post',{p_space_slug:String(body.space||'feed'),p_post_type:String(body.post_type||'discussion'),p_title:body.title||null,p_body:String(body.body||''),p_link_url:body.link_url||null,p_domain_id:body.domain_id||null,p_tags:Array.isArray(body.tags)?body.tags:[]})},201);
 if(action==='comments')return out(origin,{ok:true,result:await call('gcl_post_comments',{p_post_id:body.post_id,p_before:body.before||null,p_limit:Number(body.limit||50)})});
 if(action==='comment')return out(origin,{ok:true,result:await call('gcl_add_comment',{p_post_id:body.post_id,p_body:String(body.body||''),p_parent_comment_id:body.parent_comment_id||null})},201);
 if(action==='react')return out(origin,{ok:true,result:await call('gcl_toggle_post_reaction',{p_post_id:body.post_id,p_reaction:String(body.reaction||'useful')})});
 if(action==='comment_react')return out(origin,{ok:true,result:await call('gcl_toggle_comment_reaction',{p_comment_id:body.comment_id,p_reaction:String(body.reaction||'useful')})});
 if(action==='save_post')return out(origin,{ok:true,result:await call('gcl_toggle_save_post',{p_post_id:body.post_id})});
 if(action==='follow_member')return out(origin,{ok:true,result:await call('gcl_toggle_follow_member',{p_user_id:body.user_id})});
 if(action==='view_post')return out(origin,{ok:true,result:await call('gcl_view_post',{p_post_id:body.post_id})});
 if(action==='submit_awards')return out(origin,{ok:true,result:await call('gcl_submit_awards_entry',{p_domain_id:body.domain_id,p_category:body.category||null,p_technology_tags:Array.isArray(body.technology_tags)?body.technology_tags:[],p_story:body.story||null})},201);
 if(action==='vote_awards')return out(origin,{ok:true,result:await call('gcl_toggle_awards_vote',{p_entry_id:body.entry_id})});
 if(action==='jury_score')return out(origin,{ok:true,result:await call('gcl_jury_score_entry',{p_entry_id:body.entry_id,p_conversion_clarity:Number(body.conversion_clarity),p_user_experience:Number(body.user_experience),p_technical_execution:Number(body.technical_execution),p_trust_persuasion:Number(body.trust_persuasion),p_originality:Number(body.originality),p_note:body.note||null})});
 if(action==='resources')return out(origin,{ok:true,result:await call('gcl_resource_catalog',{p_type:body.type||null,p_limit:Number(body.limit||50)})});
 if(action==='directory')return out(origin,{ok:true,result:await call('gcl_directory',{p_query:body.query||null,p_specialty:body.specialty||null,p_limit:Number(body.limit||50)})});
 if(action==='projects')return out(origin,{ok:true,result:await call('gcl_projects',{p_status:String(body.status||'open'),p_limit:Number(body.limit||50)})});
 if(action==='create_project')return out(origin,{ok:true,result:await call('gcl_create_project',{p_title:String(body.title||''),p_description:String(body.description||''),p_category:body.category||null,p_budget_min:body.budget_min??null,p_budget_max:body.budget_max??null,p_currency:String(body.currency||'BRL'),p_urgency:String(body.urgency||'flexible'),p_domain_id:body.domain_id||null})},201);
 if(action==='apply_project')return out(origin,{ok:true,result:await call('gcl_apply_project',{p_project_id:body.project_id,p_message:body.message||null,p_proposed_price:body.proposed_price??null,p_currency:String(body.currency||'BRL')})},201);
 if(action==='hot_seats')return out(origin,{ok:true,result:await call('gcl_hot_seats',{p_status:body.status||null,p_limit:Number(body.limit||50)})});
 if(action==='submit_hot_seat')return out(origin,{ok:true,result:await call('gcl_submit_hot_seat',{p_page_url:String(body.page_url||''),p_goal:body.goal||null,p_context:body.context||null,p_domain_id:body.domain_id||null,p_audit_run_id:body.audit_run_id||null})},201);
 if(action==='experiments')return out(origin,{ok:true,result:await call('gcl_experiments',{p_status:body.status||null,p_limit:Number(body.limit||50)})});
 if(action==='create_experiment')return out(origin,{ok:true,result:await call('gcl_create_experiment',{p_domain_id:body.domain_id,p_title:String(body.title||''),p_hypothesis:String(body.hypothesis||''),p_primary_metric:String(body.primary_metric||''),p_experiment_type:String(body.experiment_type||'ab'),p_control_description:body.control_description||null,p_variant_description:body.variant_description||null})},201);
 if(action==='case_studies')return out(origin,{ok:true,result:await call('gcl_case_studies',{p_limit:Number(body.limit||50)})});
 if(action==='create_case')return out(origin,{ok:true,result:await call('gcl_create_case_study',{p_domain_id:body.domain_id,p_title:String(body.title||''),p_context:String(body.context||''),p_change_summary:String(body.change_summary||''),p_audit_before:body.audit_before||null,p_audit_after:body.audit_after||null,p_business_metric_name:body.business_metric_name||null,p_business_metric_before:body.business_metric_before??null,p_business_metric_after:body.business_metric_after??null,p_business_metric_source:body.business_metric_source||null})},201);
 if(action==='verify_case')return out(origin,{ok:true,result:await call('gcl_verify_case_study',{p_case_id:body.case_id})});
 if(action==='challenges')return out(origin,{ok:true,result:await call('gcl_challenges')});
 if(action==='update_profile')return out(origin,{ok:true,result:await call('gcl_update_profile',{p_display_name:body.display_name??null,p_headline:body.headline??null,p_bio:body.bio??null,p_member_type:body.member_type??null,p_company_name:body.company_name??null,p_website_url:body.website_url??null,p_country:body.country??null,p_state:body.state??null,p_city:body.city??null,p_skills:Array.isArray(body.skills)?body.skills:null,p_specialties:Array.isArray(body.specialties)?body.specialties:null,p_visibility:body.visibility??null})});
 if(action==='notifications')return out(origin,{ok:true,result:await call('gcl_notifications',{p_limit:Number(body.limit||50)})});
 if(action==='mark_notifications_read')return out(origin,{ok:true,result:await call('gcl_mark_notifications_read',{p_ids:Array.isArray(body.ids)?body.ids:null})});
 return out(origin,{error:'unknown_action'},400);
 }catch(e){const m=e instanceof Error?e.message:String(e);const status=(e as any)?.status||500;if(m.includes('community_access_required'))return out(origin,{error:'community_access_required'},403);if(m.includes('authentication_required'))return out(origin,{error:'authentication_required'},401);if(m.includes('verified_domain_required'))return out(origin,{error:'verified_domain_required'},403);if(m.includes('awards_purchase_required'))return out(origin,{error:'awards_purchase_required'},402);if(m.includes('analysis_required'))return out(origin,{error:'analysis_required'},409);if(m.includes('submissions_closed'))return out(origin,{error:'submissions_closed'},409);if(m.includes('voting_closed'))return out(origin,{error:'voting_closed'},409);if(m.includes('self_vote_not_allowed'))return out(origin,{error:'self_vote_not_allowed'},409);if(m.includes('jury_access_required'))return out(origin,{error:'jury_access_required'},403);if(m.includes('domain_access_denied')||m.includes('domain_not_owned'))return out(origin,{error:'domain_access_denied'},403);if(m.includes('domain_required'))return out(origin,{error:'domain_required'},400);if(m.includes('checkout_unavailable'))return out(origin,{error:'checkout_unavailable'},503);if(m.includes('claim_not_found'))return out(origin,{error:'claim_not_found'},404);if(m.includes('claim_expired'))return out(origin,{error:'claim_expired'},410);if(m.includes('invalid_domain'))return out(origin,{error:'invalid_domain'},400);if(m.includes('rate_limited'))return out(origin,{error:'rate_limited'},429);console.error('gcl-member-api',m);return out(origin,{error:'request_failed',detail:m.slice(0,180)},status>=400&&status<600?status:500);}
});