import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const U=Deno.env.get('SUPABASE_URL')!;const K=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const allowed=new Set(['https://plutyx.com','https://www.plutyx.com','https://ranking-conversao-preview.onrender.com','https://ranking-conversao-plutyx.netlify.app','http://localhost:5173','http://127.0.0.1:5173']);
function cors(o:string|null,type='application/json; charset=utf-8'){const origin=o&&allowed.has(o)?o:'https://plutyx.com';return{'access-control-allow-origin':origin,'access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type','vary':'Origin','content-type':type,'cache-control':'public, max-age=60, stale-while-revalidate=300','x-content-type-options':'nosniff'};}
function out(o:string|null,b:any,s=200){return new Response(JSON.stringify(b),{status:s,headers:cors(o)});}
async function sha(s:string){const b=new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)));return[...b].map(x=>x.toString(16).padStart(2,'0')).join('');}
async function rpc(name:string,body:any){const r=await fetch(`${U}/rest/v1/rpc/${name}`,{method:'POST',headers:{apikey:K,authorization:`Bearer ${K}`,'content-type':'application/json'},body:JSON.stringify(body||{})});const t=await r.text();let d:any=null;try{d=t?JSON.parse(t):null}catch{d=null}if(!r.ok)throw new Error(String(d?.message||`rpc_${r.status}`));return d;}
const xml=(v:any)=>String(v??'').replace(/[<>&"']/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot',"'":'&apos;'}[c]||c));
function badge(d:any){const valid=d?.status==='active';const label=xml(d?.label||'GCL Award');const season=xml(d?.season_code||'GCL');const code=xml(d?.verification_code||'');const state=valid?'VERIFIED':'NOT ACTIVE';const accent=valid?'#9cffb7':'#ffb86b';return `<svg xmlns="http://www.w3.org/2000/svg" width="360" height="108" viewBox="0 0 360 108" role="img" aria-label="${label} — ${state}"><rect width="360" height="108" rx="18" fill="#07100b"/><rect x="1" y="1" width="358" height="106" rx="17" fill="none" stroke="#26382d"/><circle cx="54" cy="54" r="31" fill="#0d1a12" stroke="${accent}"/><path d="M54 31l6.8 13.8 15.2 2.2-11 10.7 2.6 15.1L54 65.7 40.4 72.8 43 57.7 32 47l15.2-2.2z" fill="${accent}"/><text x="98" y="29" fill="#9ca9a0" font-family="Inter,Arial,sans-serif" font-size="10" letter-spacing="1.8">GLOBAL CONVERSION LEAGUE</text><text x="98" y="53" fill="#f4fff7" font-family="Inter,Arial,sans-serif" font-size="18" font-weight="700">${label}</text><text x="98" y="73" fill="${accent}" font-family="Inter,Arial,sans-serif" font-size="10" font-weight="700" letter-spacing="1.2">${state} · ${season}</text><text x="98" y="91" fill="#607168" font-family="ui-monospace,SFMono-Regular,Consolas,monospace" font-size="9">${code}</text></svg>`;}
Deno.serve(async req=>{const origin=req.headers.get('origin');if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(origin)});if(origin&&!allowed.has(origin))return out(origin,{error:'origin_not_allowed'},403);if(!['GET','POST'].includes(req.method))return out(origin,{error:'method_not_allowed'},405);try{let code='';let format='json';if(req.method==='GET'){const u=new URL(req.url);code=u.searchParams.get('code')||'';format=(u.searchParams.get('format')||'json').toLowerCase();}else{const b=await req.json().catch(()=>({}));code=String(b?.code||'');format=String(b?.format||'json').toLowerCase();}code=code.trim().toUpperCase();if(!/^GCL-[0-9]{4}-[A-F0-9]{14}$/.test(code))return out(origin,{error:'invalid_verification_code'},400);const ip=(req.headers.get('x-forwarded-for')||req.headers.get('cf-connecting-ip')||'unknown').split(',')[0].trim();const bucket=await sha(`${ip}|${(req.headers.get('user-agent')||'').slice(0,160)}|award-verify`);const rate=await rpc('consume_rate_limit',{p_route:'public:award_verify',p_bucket:bucket,p_window_seconds:60,p_limit:60});if(!rate?.allowed)return out(origin,{error:'rate_limited',reset_at:rate?.reset_at},429);const data=await rpc('gcl_award_verify',{p_code:code});if(!data)return out(origin,{error:'award_not_found'},404);if(format==='svg')return new Response(badge(data),{status:200,headers:{...cors(origin,'image/svg+xml; charset=utf-8'),'cache-control':'public, max-age=300, stale-while-revalidate=3600'}});return out(origin,{ok:true,result:data});}catch(e){console.error('gcl-award-verify',e);return out(origin,{error:'internal_error'},500);}});