import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const U=Deno.env.get('SUPABASE_URL')!;const A=Deno.env.get('SUPABASE_ANON_KEY')!;const K=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const allowed=new Set(['https://plutyx.com','https://www.plutyx.com','https://ranking-conversao-preview.onrender.com','http://localhost:5173','http://127.0.0.1:5173']);
function cors(o:string|null){const origin=o&&allowed.has(o)?o:'https://plutyx.com';return {'access-control-allow-origin':origin,'access-control-allow-methods':'POST,OPTIONS','access-control-allow-headers':'content-type,authorization,apikey','vary':'Origin','content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'};}
function out(o:string|null,b:any,s=200){return new Response(JSON.stringify(b),{status:s,headers:cors(o)});}
const isPriv=(x:string)=>x==='127.0.0.1'||x==='::1'||x==='0.0.0.0'||x.startsWith('10.')||x.startsWith('192.168.')||x.startsWith('169.254.')||/^172\.(1[6-9]|2\d|3[01])\./.test(x)||x.startsWith('fc')||x.startsWith('fd')||x.startsWith('fe80:');
async function safeUrl(raw:string,root:string){const u=new URL(raw);if(!['http:','https:'].includes(u.protocol)||u.hostname==='localhost'||u.hostname.endsWith('.local'))throw Error('unsafe_url');const h=u.hostname.toLowerCase();if(!(h===root||h.endsWith('.'+root)))throw Error('cross_domain_redirect');for(const t of ['A','AAAA'] as const){for(const ip of await Deno.resolveDns(h,t).catch(()=>[] as string[]))if(isPriv(String(ip)))throw Error('unsafe_ip')}return u;}
async function userRpc(name:string,body:any,auth:string){const r=await fetch(`${U}/rest/v1/rpc/${name}`,{method:'POST',headers:{apikey:A,authorization:auth,'content-type':'application/json'},body:JSON.stringify(body||{})});const t=await r.text();let d:any;try{d=t?JSON.parse(t):null}catch{d={raw:t}}if(!r.ok)throw Error(String(d?.message||d?.error||`rpc_${r.status}`));return d;}
async function trustedRpc(name:string,body:any){const r=await fetch(`${U}/rest/v1/rpc/${name}`,{method:'POST',headers:{apikey:K,authorization:`Bearer ${K}`,'content-type':'application/json'},body:JSON.stringify(body||{})});const t=await r.text();let d:any;try{d=t?JSON.parse(t):null}catch{d={raw:t}}if(!r.ok)throw Error(String(d?.message||d?.error||`rpc_${r.status}`));return d;}
async function fetchWithin(url:string,root:string){let u=await safeUrl(url,root);const chain:any[]=[];for(let i=0;i<5;i++){const r=await fetch(u,{redirect:'manual',headers:{'user-agent':'Mozilla/5.0 (compatible; GCLDomainVerifier/3.0; +https://plutyx.com/ranking-site/)','accept':'text/html,text/plain;q=0.9,*/*;q=0.1'}});const loc=r.headers.get('location');chain.push({url:u.toString(),status:r.status});if(r.status>=300&&r.status<400&&loc){u=await safeUrl(new URL(loc,u).toString(),root);continue}const text=(await r.text()).slice(0,1200000);return{ok:r.ok,status:r.status,url:u.toString(),text,chain};}throw Error('too_many_redirects');}
function hasMeta(html:string,token:string){const esc=token.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const a=new RegExp(`<meta\\b[^>]*name=["']gcl-site-verification["'][^>]*content=["']${esc}["'][^>]*>`,'i');const b=new RegExp(`<meta\\b[^>]*content=["']${esc}["'][^>]*name=["']gcl-site-verification["'][^>]*>`,'i');return a.test(html)||b.test(html);}
Deno.serve(async req=>{const origin=req.headers.get('origin');if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(origin)});if(origin&&!allowed.has(origin))return out(origin,{error:'origin_not_allowed'},403);if(req.method!=='POST')return out(origin,{error:'method_not_allowed'},405);const auth=req.headers.get('authorization')||'';if(!auth.toLowerCase().startsWith('bearer '))return out(origin,{error:'authentication_required'},401);try{const b=await req.json();const claim=String(b?.claim_token||'');if(!/^[0-9a-f-]{36}$/i.test(claim))return out(origin,{error:'invalid_claim_token'},400);
// Resolve context with the caller JWT first. A user may only verify their own pending challenge.
const c=await userRpc('gcl_domain_claim_context',{p_claim_token:claim},auth);const domain=String(c.domain);const token=String(c.verification_token);let verified=false;let evidence:any={method:c.method,checked_at:new Date().toISOString(),verifier:'gcl-domain-verify-v3'};let error:string|null=null;
if(c.method==='meta'){const r=await fetchWithin(`https://${domain}/`,domain);verified=r.ok&&hasMeta(r.text,token);evidence={...evidence,http_status:r.status,final_url:r.url,redirects:r.chain,meta_found:verified};if(!verified)error='verification_meta_not_found';}
else if(c.method==='file'){const r=await fetchWithin(`https://${domain}/.well-known/gcl-verification.txt`,domain);verified=r.ok&&r.text.trim().split(/\s+/).includes(token);evidence={...evidence,http_status:r.status,final_url:r.url,redirects:r.chain,file_match:verified};if(!verified)error='verification_file_not_found';}
else if(c.method==='dns'){const host=`_gcl.${domain}`;const txt:any=await Deno.resolveDns(host,'TXT').catch(()=>[]);const flat=(Array.isArray(txt)?txt:[]).flat(Infinity).map(String);verified=flat.some((x:string)=>x.includes(token));evidence={...evidence,host,txt_count:flat.length,token_found:verified};if(!verified)error='verification_dns_not_found';}
else throw Error('unsupported_claim_method');
// Persistence is server-authoritative. The browser never supplies p_verified to Postgres.
const persisted=await trustedRpc('gcl_record_domain_claim_attempt',{p_claim_token:claim,p_verified:verified,p_evidence:evidence,p_error:error});
return out(origin,{ok:true,...persisted});
}catch(e){const m=e instanceof Error?e.message:String(e);if(m.includes('claim_not_found'))return out(origin,{error:'claim_not_found'},404);if(m.includes('claim_expired'))return out(origin,{error:'claim_expired'},410);if(m.includes('authentication_required'))return out(origin,{error:'authentication_required'},401);if(m.includes('trusted_verifier_required'))return out(origin,{error:'trusted_verifier_required'},500);console.error('gcl-domain-verify',m);return out(origin,{error:'verification_failed',detail:m.slice(0,180)},422);}});