import React,{useEffect,useMemo,useState}from'react'
import{ArrowLeft,ArrowUpRight,Boxes,BrainCircuit,CheckCircle2,ChevronRight,ClipboardCheck,Clock3,Gauge,PackageCheck,RefreshCcw,ShieldCheck,ShoppingCart,SlidersHorizontal,Sparkles,Target,TriangleAlert,TrendingDown,TrendingUp,UtensilsCrossed,X}from'lucide-react'
import{request}from'./app'

const AUTOPILOT_API=import.meta.env.VITE_AUTOPILOT_API_URL||'https://npgheuzpnkwtxopswpqy.supabase.co/functions/v1/cozinha360-autopilot-v37'
type Business={id:number;name:string;city:string;role:string}
type Policy={horizon:number;bufferPct:number;minConfidence:'low'|'medium'|'high';protectStock:boolean}
type ProductPlan={product_id:number;product_name:string;historical_units_28d:number;recent_units_7d:number;forecast_units:number;open_committed_units:number;recommended_units:number;target_units:number;planned_remaining_units:number;to_plan_units:number;confidence:string;confidence_ok:boolean;method:string;trend:'accelerating'|'slowing'|'stable'|'insufficient';trend_ratio:number;recipe_complete:boolean;stock_risk:boolean;blocked_reason:string|null;eligible:boolean}
type ComponentPlan={ingredient_id:number;name:string;unit:string;required_milliunits:number;on_hand_milliunits:number;projected_milliunits:number;shortage_milliunits:number;affected_product_ids:number[]}
type Plan={business_id:number;generated_at:string;plan_hash:string;horizon_days:number;buffer_pct:number;min_confidence:string;protect_stock:boolean;summary:{forecast_units:number;target_units:number;planned_remaining_units:number;to_plan_units:number;eligible_units:number;blocked_units:number;stock_shortages:number;missing_recipes:number;low_confidence:number;growth_allowed:boolean};guard:{growth_allowed:boolean;contribution_cents_30d:number;revenue_cents_30d:number;orders_30d:number;delay_rate:number;error_rate:number};products:ProductPlan[];components:ComponentPlan[];next_action:{code:string;title:string;detail:string;href:string};source:{forecast_method:string;forecast_basis_days:number;decision_mode:string}}
type Run={request_id:string;horizon_days:number;buffer_bps:number;plan_hash:string;status:string;action_count:number;result_json:any;created_at:string;updated_at:string}
const defaultPolicy:Policy={horizon:1,bufferPct:10,minConfidence:'medium',protectStock:true}
const confidenceLabel:Record<string,string>={low:'baixa',medium:'média',high:'alta'}
const blockedLabel:Record<string,string>={missing_recipe:'Ficha incompleta',low_confidence:'Baixa confiança',stock_shortage:'Falta de insumo'}
function safeJSON<T>(raw:string|null,fallback:T):T{try{return raw?JSON.parse(raw):fallback}catch{return fallback}}
function formatQty(v:number,unit='un'){return `${new Intl.NumberFormat('pt-BR',{maximumFractionDigits:1}).format(v||0)} ${unit}`}
function percent(v:number){return `${(Number(v||0)*100).toFixed(1)}%`}
function money(cents:number){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(cents||0)/100)}
async function edge(path:string,token:string,options:RequestInit={}){const response=await fetch(`${AUTOPILOT_API}${path}`,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,...(options.headers||{})}});const body=await response.json().catch(()=>({detail:'Resposta inválida'}));if(!response.ok)throw new Error(body.detail||`Falha ${response.status}`);return body}

export function Autopilot360Route(){
 const token=localStorage.getItem('c360_token')||''
 const[businesses,setBusinesses]=useState<Business[]>([]),[businessId,setBusinessId]=useState(0),[policy,setPolicy]=useState<Policy>(defaultPolicy)
 const[plan,setPlan]=useState<Plan|null>(null),[runs,setRuns]=useState<Run[]>([]),[selected,setSelected]=useState<Set<number>>(new Set())
 const[loading,setLoading]=useState(true),[applying,setApplying]=useState(false),[confirming,setConfirming]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
 const key=(id:number)=>`c360-autopilot-v37-${id}`
 function persist(next:Policy,id=businessId){setPolicy(next);if(id)localStorage.setItem(key(id),JSON.stringify(next))}
 async function load(targetId=businessId,nextPolicy=policy){if(!token){setLoading(false);return}setError('');setMessage('');try{let bid=targetId;if(!businesses.length){const me=await request('/me',{},token);const rows=(me.businesses||[]) as Business[];setBusinesses(rows);bid=bid||Number(rows[0]?.id||0);if(bid)setBusinessId(bid)}if(!bid)return;const saved=safeJSON(localStorage.getItem(key(bid)),nextPolicy||defaultPolicy);if(targetId!==businessId||!plan)setPolicy(saved);const p=targetId!==businessId||!plan?saved:nextPolicy;const qs=new URLSearchParams({horizon_days:String(p.horizon),buffer_pct:String(p.bufferPct),min_confidence:p.minConfidence,protect_stock:String(p.protectStock)});const[data,history]=await Promise.all([edge(`/businesses/${bid}/plan?${qs}`,token),edge(`/businesses/${bid}/runs`,token)]);setPlan(data);setRuns(history.runs||[]);setSelected(new Set((data.products||[]).filter((x:ProductPlan)=>x.eligible).map((x:ProductPlan)=>x.product_id)))}catch(e){setError(e instanceof Error?e.message:'Não foi possível montar o Autopilot')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[])
 const currentBusiness=businesses.find(b=>b.id===businessId),canApply=['owner','admin'].includes(currentBusiness?.role||'')
 const selectedRows=useMemo(()=>plan?.products.filter(p=>p.eligible&&selected.has(p.product_id))||[],[plan,selected])
 const selectedUnits=selectedRows.reduce((a,p)=>a+p.to_plan_units,0),shortages=plan?.components.filter(c=>c.shortage_milliunits>0)||[]
 function toggle(id:number){setSelected(prev=>{const next=new Set(prev);next.has(id)?next.delete(id):next.add(id);return next})}
 function updatePolicy(next:Policy){persist(next);setPlan(null)}
 async function recalc(){setLoading(true);await load(businessId,policy)}
 function openApproval(){if(!selectedRows.length)return;setConfirming(true);setMessage('')}
 async function approve(){if(!plan||!selectedRows.length||!canApply)return;setApplying(true);setError('');try{const storageKey=`c360-autopilot-pending-${businessId}`;const cached=safeJSON<any>(sessionStorage.getItem(storageKey),null);const requestId=cached?.plan_hash===plan.plan_hash?cached.request_id:crypto.randomUUID();sessionStorage.setItem(storageKey,JSON.stringify({request_id:requestId,plan_hash:plan.plan_hash}));const result=await edge(`/businesses/${businessId}/apply`,token,{method:'POST',body:JSON.stringify({request_id:requestId,expected_plan_hash:plan.plan_hash,horizon_days:policy.horizon,buffer_pct:policy.bufferPct,min_confidence:policy.minConfidence,protect_stock:policy.protectStock,selected_product_ids:selectedRows.map(p=>p.product_id)})});if(result.status==='completed')sessionStorage.removeItem(storageKey);setMessage(result.status==='completed'?`${result.created?.length||0} lote(s) criados com trilha idempotente.`:`Execução ${result.status}: ${result.created?.length||0} criado(s), ${result.failed?.length||0} falha(s).`);setConfirming(false);await load(businessId,policy)}catch(e){setError(e instanceof Error?e.message:'Falha ao aplicar o plano')}finally{setApplying(false)}}
 if(!token)return <main className="auto-shell auto-center"><div className="auto-empty"><BrainCircuit/><h1>Entre na operação primeiro.</h1><p>O Autopilot só trabalha com dados do negócio autenticado.</p><a href="/">Entrar</a></div></main>
 if(loading)return <main className="auto-shell auto-center"><div className="auto-loader"><BrainCircuit/>CRUZANDO DEMANDA, PREPARO, ESTOQUE E MARGEM</div></main>
 return <main className="auto-shell">
  <header className="auto-topbar"><a href="/"><ArrowLeft/> Operação</a><b><BrainCircuit/> AUTOPILOT <span>360</span></b><div>{businesses.length>1&&<select value={businessId} onChange={async e=>{const id=Number(e.target.value);setBusinessId(id);const p=safeJSON(localStorage.getItem(key(id)),defaultPolicy);setPolicy(p);setLoading(true);await load(id,p)}}>{businesses.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select>}<button onClick={recalc} title="Recalcular"><RefreshCcw/></button></div></header>
  <section className="auto-page">
   <div className="auto-hero"><div><span>FORECAST → PREP → STOCK → MARGIN</span><h1>Um motor para decidir antes do pico.</h1><p>Transforma demanda observada em lotes de preparo, desconta produção já planejada, verifica fichas e insumos e só libera crescimento quando margem e operação suportam. <b>Nenhuma ação em massa acontece sem aprovação humana.</b></p></div><div className={`auto-permit ${plan?.summary.growth_allowed?'go':'hold'}`}><i>{plan?.summary.growth_allowed?<ShieldCheck/>:<TriangleAlert/>}</i><span>GROWTH PERMIT</span><strong>{plan?.summary.growth_allowed?'LIBERADO':'SEGURAR'}</strong><small>{plan?.summary.growth_allowed?'margem + operação + estoque passam':'há um gargalo antes de acelerar'}</small></div></div>
   {error&&<div className="auto-alert error"><TriangleAlert/>{error}</div>}{message&&<div className="auto-alert success"><CheckCircle2/>{message}</div>}
   <div className="auto-policy"><div className="auto-policy-title"><SlidersHorizontal/><div><b>Política do ciclo</b><span>Salva por negócio e sincroniza pela Memória Operacional.</span></div></div><label><span>Horizonte</span><select value={policy.horizon} onChange={e=>updatePolicy({...policy,horizon:Number(e.target.value)})}><option value={1}>Hoje · 1 dia</option><option value={3}>3 dias</option><option value={7}>7 dias</option></select></label><label><span>Buffer</span><div className="auto-input"><input type="number" min="0" max="50" value={policy.bufferPct} onChange={e=>updatePolicy({...policy,bufferPct:Math.max(0,Math.min(50,Number(e.target.value)||0))})}/><i>%</i></div></label><label><span>Confiança mínima</span><select value={policy.minConfidence} onChange={e=>updatePolicy({...policy,minConfidence:e.target.value as Policy['minConfidence']})}><option value="low">Baixa</option><option value="medium">Média</option><option value="high">Alta</option></select></label><label className="auto-check"><input type="checkbox" checked={policy.protectStock} onChange={e=>updatePolicy({...policy,protectStock:e.target.checked})}/><span>Bloquear lote com falta conhecida</span></label><button className="auto-recalc" onClick={recalc}><Sparkles/>Recalcular plano</button></div>
   {plan&&<>
    <div className="auto-kpis"><Kpi icon={<Target/>} label="Alvo com buffer" value={plan.summary.target_units} note={`${plan.summary.forecast_units} previsão base`}/><Kpi icon={<Boxes/>} label="Já em produção" value={plan.summary.planned_remaining_units} note="planejado + em andamento"/><Kpi icon={<ClipboardCheck/>} label="Elegível agora" value={plan.summary.eligible_units} note={`${plan.summary.blocked_units} bloqueadas`} good={plan.summary.eligible_units>0}/><Kpi icon={<ShoppingCart/>} label="Faltas previstas" value={plan.summary.stock_shortages} note={`${plan.summary.missing_recipes} fichas incompletas`} danger={plan.summary.stock_shortages>0}/></div>
    <div className="auto-decision"><div className="auto-decision-icon"><Gauge/></div><div><span>PRÓXIMA MELHOR AÇÃO</span><h2>{plan.next_action.title}</h2><p>{plan.next_action.detail}</p></div><a href={plan.next_action.href}>Abrir módulo <ArrowUpRight/></a></div>
    <div className="auto-grid">
     <article className="auto-panel auto-products"><PanelHead icon={<UtensilsCrossed/>} kicker="PREP PLAN" title="Lotes propostos com evidência." note={`Base: ${plan.source.forecast_basis_days} dias · ${plan.source.forecast_method}`}/><div className="auto-product-list">{plan.products.map(p=><div className={`auto-product ${p.blocked_reason?'blocked':''}`} key={p.product_id}><button className="auto-select" disabled={!p.eligible} onClick={()=>toggle(p.product_id)} aria-label={`Selecionar ${p.product_name}`}>{p.eligible&&selected.has(p.product_id)?<CheckCircle2/>:<span/>}</button><div className="auto-product-main"><div className="auto-product-title"><h3>{p.product_name}</h3><Trend trend={p.trend}/><span className={`auto-confidence ${p.confidence}`}>confiança {confidenceLabel[p.confidence]||p.confidence}</span></div><div className="auto-equation"><span><b>{p.forecast_units}</b> previsão</span><i>+</i><span><b>{p.open_committed_units}</b> comprometidas</span><i>→</i><span><b>{p.target_units}</b> alvo</span><i>−</i><span><b>{p.planned_remaining_units}</b> já planejadas</span></div></div><div className="auto-plan-qty"><span>CRIAR</span><strong>{p.to_plan_units}</strong><small>unidades</small></div><div className="auto-product-state">{p.blocked_reason?<><TriangleAlert/><span>{blockedLabel[p.blocked_reason]||p.blocked_reason}</span></>:p.to_plan_units===0?<><PackageCheck/><span>Coberto</span></>:<><CheckCircle2/><span>Elegível</span></>}</div></div>)}</div>
      <div className="auto-approve-bar"><div><span>{selectedRows.length} produto(s) selecionados</span><b>{selectedUnits} unidades para criar em lotes</b><small>O servidor recalcula o plano antes de gravar. Se os dados mudarem, a aprovação recebe 409 e nada é aplicado.</small></div>{canApply?<button disabled={!selectedRows.length} onClick={openApproval}><ClipboardCheck/>Revisar e aprovar</button>:<div className="auto-role-lock"><ShieldCheck/>Owner/admin aprova lotes em massa</div>}</div>
     </article>
     <aside className="auto-side">
      <article className="auto-panel"><PanelHead icon={<ShieldCheck/>} kicker="CONSTRAINT GUARD" title="Crescer só depois do gargalo."/><div className="auto-guards"><Guard label="Contribuição 30d" value={money(plan.guard.contribution_cents_30d)} pass={plan.guard.contribution_cents_30d>0}/><Guard label="Atrasos" value={percent(plan.guard.delay_rate)} pass={plan.guard.delay_rate<=.15}/><Guard label="Erros" value={percent(plan.guard.error_rate)} pass={plan.guard.error_rate<=.05}/><Guard label="Estoque previsto" value={shortages.length?`${shortages.length} falta(s)`:'coberto'} pass={!shortages.length}/></div><p className="auto-fineprint">O permit não garante lucro nem demanda. Ele impede que Growth seja tratado como solução quando contribuição, qualidade ou insumo já estão falhando.</p></article>
      <article className="auto-panel"><PanelHead icon={<Clock3/>} kicker="AUDIT TRAIL" title="Últimas execuções."/>{runs.length?<div className="auto-runs">{runs.slice(0,6).map(r=><div key={r.request_id}><i className={r.status}/><div><b>{r.action_count} ação(ões) · {r.status}</b><span>{new Date(r.created_at).toLocaleString('pt-BR')}</span></div><small>{r.request_id.slice(0,8)}</small></div>)}</div>:<div className="auto-empty-inline">Nenhum lote foi aprovado pelo Autopilot ainda.</div>}</article>
     </aside>
    </div>
    <article className="auto-panel auto-components"><PanelHead icon={<ShoppingCart/>} kicker="FORECASTED COMPONENTS" title="Insumos que precisam cobrir o alvo." note="Projeção operacional; não é baixa de estoque."/>{plan.components.length?<div className="auto-component-table"><div className="head"><span>Componente</span><span>Necessário</span><span>Em estoque</span><span>Após alvo</span><span>Status</span></div>{plan.components.map(c=><div key={c.ingredient_id} className={c.shortage_milliunits>0?'short':''}><span><b>{c.name}</b><small>{c.affected_product_ids.length} produto(s)</small></span><span>{formatQty(c.required_milliunits,c.unit)}</span><span>{formatQty(c.on_hand_milliunits,c.unit)}</span><span>{formatQty(c.projected_milliunits,c.unit)}</span><span>{c.shortage_milliunits>0?<b>Falta {formatQty(c.shortage_milliunits,c.unit)}</b>:<em>Coberto</em>}</span></div>)}</div>:<div className="auto-empty-inline">Sem componentes calculáveis. Complete as fichas técnicas dos produtos com demanda.</div>}</article>
    <div className="auto-method"><BrainCircuit/><div><b>Autopilot explicável, não caixa-preta.</b><span>Previsão = média móvel ponderada 7/21 já validada no núcleo. O módulo adiciona buffer declarado, desconta lotes ativos, explode fichas técnicas, verifica estoque e exige aprovação humana. Ações usam request ID idempotente e hash do plano para evitar clique duplicado e plano obsoleto.</span></div></div>
   </>}
  </section>
  {confirming&&plan&&<div className="auto-modal-backdrop" role="presentation"><section className="auto-modal" role="dialog" aria-modal="true" aria-labelledby="auto-confirm-title"><header><div><span>APROVAÇÃO HUMANA</span><h2 id="auto-confirm-title">Criar {selectedRows.length} lote(s)?</h2></div><button onClick={()=>setConfirming(false)}><X/></button></header><div className="auto-modal-summary"><div><span>Unidades adicionais</span><b>{selectedUnits}</b></div><div><span>Horizonte</span><b>{policy.horizon} dia(s)</b></div><div><span>Buffer</span><b>{policy.bufferPct}%</b></div></div><div className="auto-modal-products">{selectedRows.map(p=><div key={p.product_id}><span>{p.product_name}</span><b>{p.to_plan_units} un</b></div>)}</div><p><ShieldCheck/>Antes de gravar, o servidor recalcula demanda, estoque e produção e compara o hash. Repetir a mesma requisição não cria lotes duplicados.</p><footer><button className="secondary" onClick={()=>setConfirming(false)} disabled={applying}>Cancelar</button><button className="primary" onClick={approve} disabled={applying}>{applying?<><RefreshCcw className="spin"/>Aplicando...</>:<><CheckCircle2/>Aprovar lotes</>}</button></footer></section></div>}
 </main>
}
function PanelHead({icon,kicker,title,note}:{icon:React.ReactNode;kicker:string;title:string;note?:string}){return <header className="auto-panel-head"><i>{icon}</i><div><span>{kicker}</span><h2>{title}</h2>{note&&<small>{note}</small>}</div></header>}
function Kpi({icon,label,value,note,good=false,danger=false}:{icon:React.ReactNode;label:string;value:number;note:string;good?:boolean;danger?:boolean}){return <article className={`auto-kpi ${good?'good':''} ${danger?'danger':''}`}><i>{icon}</i><div><span>{label}</span><strong>{value}</strong><small>{note}</small></div></article>}
function Guard({label,value,pass}:{label:string;value:string;pass:boolean}){return <div className={pass?'pass':'fail'}><i>{pass?<CheckCircle2/>:<TriangleAlert/>}</i><span>{label}</span><b>{value}</b></div>}
function Trend({trend}:{trend:ProductPlan['trend']}){if(trend==='accelerating')return <span className="auto-trend up"><TrendingUp/>acelerando</span>;if(trend==='slowing')return <span className="auto-trend down"><TrendingDown/>desacelerando</span>;return <span className="auto-trend stable">{trend==='insufficient'?'histórico curto':'estável'}</span>}
