import React,{useEffect,useMemo,useState}from'react'
import{ArrowLeft,BadgeDollarSign,Calculator,ChevronRight,CircleDollarSign,Flame,Gauge,Landmark,RefreshCcw,ShieldAlert,Target,TrendingDown,TrendingUp,WalletCards}from'lucide-react'
import{money,request,type Dashboard,type Finance}from'./app'

type Business={id:number;name:string;city:string;role:string}
type FixedKey='internet'|'formalization'|'systems'|'cleaning'|'baseEnergy'|'maintenance'|'ownerPay'|'other'
type Plan={fixed:Record<FixedKey,string>;plannedContribution:string;plannedOrders:string;workingDays:string;windowsPerDay:string;cashBalance:string;targetProfit:string}
type Stage={minutes:number;parallel:number}
const fixedLabels:Record<FixedKey,string>={internet:'Internet + telefone',formalization:'Contador / formalização',systems:'Canais / sistemas',cleaning:'Limpeza / controle',baseEnergy:'Energia básica',maintenance:'Manutenção / depreciação',ownerPay:'Remuneração do trabalho',other:'Outros fixos'}
const emptyPlan:Plan={fixed:{internet:'',formalization:'',systems:'',cleaning:'',baseEnergy:'',maintenance:'',ownerPay:'',other:''},plannedContribution:'',plannedOrders:'',workingDays:'26',windowsPerDay:'1',cashBalance:'',targetProfit:''}
const number=(v:string|number)=>{const x=Number(String(v??'').replace(',','.'));return Number.isFinite(x)?x:0}
const ceil=(v:number)=>Number.isFinite(v)&&v>0?Math.ceil(v):0
const brl=(v:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(v||0)
function safeJSON<T>(raw:string|null,fallback:T):T{try{return raw?JSON.parse(raw):fallback}catch{return fallback}}

export function CashEngineRoute(){
 const token=localStorage.getItem('c360_token')||''
 const[businesses,setBusinesses]=useState<Business[]>([]);const[businessId,setBusinessId]=useState(0)
 const[finance,setFinance]=useState<Finance|null>(null);const[dashboard,setDashboard]=useState<Dashboard|null>(null)
 const[plan,setPlan]=useState<Plan>(emptyPlan);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[lastUpdate,setLastUpdate]=useState<Date|null>(null)
 async function load(target=businessId){if(!token){setLoading(false);return}setError('');try{let id=target;if(!businesses.length){const me=await request('/me',{},token);const rows=(me.businesses||[]) as Business[];setBusinesses(rows);id=id||Number(rows[0]?.id||0);if(id)setBusinessId(id)}if(!id)return;const[f,d]=await Promise.all([request(`/businesses/${id}/finance/summary?days=30`,{},token),request(`/businesses/${id}/dashboard`,{},token)]);setFinance(f);setDashboard(d);setPlan(safeJSON(localStorage.getItem(`c360-cash-v28-${id}`),emptyPlan));setLastUpdate(new Date())}catch(e){setError(e instanceof Error?e.message:'Não foi possível montar o plano financeiro')}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 function save(next:Plan){setPlan(next);if(businessId)localStorage.setItem(`c360-cash-v28-${businessId}`,JSON.stringify(next))}
 const fixedTotal=useMemo(()=>Object.values(plan.fixed).reduce((a,v)=>a+number(v),0),[plan.fixed])
 const orderCount=Number(finance?.order_count||0), revenue=Number(finance?.revenue_cents||0)/100, contribution=Number(finance?.contribution_cents||0)/100
 const observedTicket=orderCount?revenue/orderCount:0, observedContribution=orderCount?contribution/orderCount:0
 const contributionPerOrder=number(plan.plannedContribution)||observedContribution
 const plannedOrders=number(plan.plannedOrders)||orderCount
 const workingDays=Math.max(1,number(plan.workingDays)||1),windows=Math.max(1,number(plan.windowsPerDay)||1),targetProfit=Math.max(0,number(plan.targetProfit)),cash=Math.max(0,number(plan.cashBalance))
 const breakEvenOrders=contributionPerOrder>0?ceil(fixedTotal/contributionPerOrder):0
 const targetOrders=contributionPerOrder>0?ceil((fixedTotal+targetProfit)/contributionPerOrder):0
 const targetDaily=targetOrders/workingDays
 const plannedContributionTotal=plannedOrders*contributionPerOrder
 const projectedResult=plannedContributionTotal-fixedTotal
 const burn=Math.max(0,fixedTotal-plannedContributionTotal)
 const runway=burn>0&&cash>0?cash/burn:burn===0&&cash>0?Infinity:0
 const monthlyGap=Math.max(0,fixedTotal+targetProfit-plannedContributionTotal)
 const capacity=readCapacity(businessId)
 const monthlyCapacity=capacity.safeHour>0?capacity.safeHour*windows*workingDays:0
 const capacityFits=monthlyCapacity?targetOrders<=monthlyCapacity:null
 const status=contributionPerOrder<=0?'missing':projectedResult>=targetProfit?'healthy':projectedResult>=0?'warning':'danger'
 const scenarios=[{name:'Conservador',factor:.8},{name:'Plano',factor:1},{name:'Acelerado',factor:1.2}].map(s=>{const orders=Math.round(plannedOrders*s.factor),total=orders*contributionPerOrder,result=total-fixedTotal;return{...s,orders,total,result}})
 const currentBusiness=businesses.find(x=>x.id===businessId)
 if(!token)return <main className="cash-shell cash-center"><div className="cash-empty"><WalletCards/><h1>Entre na operação primeiro.</h1><a href="/">Entrar</a></div></main>
 if(loading)return <main className="cash-shell cash-center"><div className="cash-loader"><Calculator/>CALCULANDO CAIXA E MARGEM</div></main>
 return <main className="cash-shell"><header className="cash-topbar"><a href="/"><ArrowLeft/> Operação</a><b><WalletCards/> CASH & MARGIN <span>ENGINE</span></b><div>{businesses.length>1&&<select value={businessId} onChange={async e=>{const id=Number(e.target.value);setBusinessId(id);await load(id)}}>{businesses.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select>}<button onClick={()=>load()}><RefreshCcw/></button></div></header><section className="cash-page">
  <div className="cash-hero"><div><span>COZINHA DE BOLSO 360 · PLANILHAS VIVAS</span><h1>Quanto precisa vender para o caixa respirar?</h1><p>O modelo mensal cruza a contribuição real dos últimos 30 dias com os compromissos que você declara. Receita é contexto; a decisão nasce da contribuição por pedido, do ponto de equilíbrio e da capacidade.</p></div><div className={`cash-health ${status}`}><i>{status==='healthy'?<TrendingUp/>:status==='danger'?<TrendingDown/>:<Gauge/>}</i><span>PLANO MENSAL</span><b>{status==='missing'?'SEM BASE':status==='healthy'?'SUSTENTÁVEL':status==='warning'?'NO POSITIVO':'NO VERMELHO'}</b><small>{lastUpdate?`dados ${lastUpdate.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}`:'—'}</small></div></div>
  {error&&<div className="cash-error">{error}</div>}
  <div className="cash-live"><Kpi label="Receita 30d" value={money(finance?.revenue_cents||0)} note={`${orderCount} pedidos pagos`}/><Kpi label="Contribuição 30d" value={money(finance?.contribution_cents||0)} note={orderCount?`${brl(observedContribution)} / pedido`:'sem base observada'}/><Kpi label="Tíquete observado" value={brl(observedTicket)} note="não substitui contribuição"/><Kpi label="Perdas 30d" value={money(finance?.loss_cents||0)} note="registro operacional" danger={Number(finance?.loss_cents||0)>0}/></div>
  <div className="cash-grid">
   <article className="cash-panel"><Head icon={<Landmark/>} kicker="CUSTOS FIXOS MENSAIS" title="Preencha o que existe de verdade."/><p className="cash-muted">As categorias vêm do simulador da planilha; os valores de exemplo não são copiados para o seu negócio.</p><div className="cash-fixed">{(Object.keys(fixedLabels) as FixedKey[]).map(key=><label key={key}><span>{fixedLabels[key]}</span><div>R$ <input inputMode="decimal" value={plan.fixed[key]} onChange={e=>save({...plan,fixed:{...plan.fixed,[key]:e.target.value}})} placeholder="0,00"/></div></label>)}</div><div className="cash-total"><span>Total fixo mensal</span><strong>{brl(fixedTotal)}</strong></div></article>
   <article className="cash-panel"><Head icon={<Target/>} kicker="META E CAIXA" title="Defina o mês antes de perseguir volume."/><div className="cash-plan-fields"><Field label="Contribuição por pedido" prefix="R$" value={plan.plannedContribution} placeholder={observedContribution?observedContribution.toFixed(2).replace('.',','):'0,00'} onChange={v=>save({...plan,plannedContribution:v})}/><Field label="Pedidos previstos no mês" value={plan.plannedOrders} placeholder={String(orderCount||0)} onChange={v=>save({...plan,plannedOrders:v})}/><Field label="Dias de operação / mês" value={plan.workingDays} onChange={v=>save({...plan,workingDays:v})}/><Field label="Janelas de 1h / dia" value={plan.windowsPerDay} onChange={v=>save({...plan,windowsPerDay:v})}/><Field label="Caixa disponível" prefix="R$" value={plan.cashBalance} placeholder="0,00" onChange={v=>save({...plan,cashBalance:v})}/><Field label="Resultado-alvo após fixos" prefix="R$" value={plan.targetProfit} placeholder="0,00" onChange={v=>save({...plan,targetProfit:v})}/></div><div className="cash-source-buttons"><button onClick={()=>save({...plan,plannedContribution:observedContribution?observedContribution.toFixed(2):''})} disabled={!observedContribution}>Usar contribuição observada</button><a href="/?margin=1">Revisar preço por canal <ChevronRight/></a></div></article>
  </div>
  <div className="cash-result-grid"><Result icon={<CircleDollarSign/>} label="Ponto de equilíbrio" value={breakEvenOrders?`${breakEvenOrders} pedidos/mês`:'—'} note={breakEvenOrders?`${(breakEvenOrders/workingDays).toFixed(1)} por dia de operação`:'Informe contribuição por pedido'} state={breakEvenOrders?'neutral':'warn'}/><Result icon={<Target/>} label="Meta com resultado-alvo" value={targetOrders?`${targetOrders} pedidos/mês`:'—'} note={targetOrders?`${targetDaily.toFixed(1)} pedidos/dia`:'Sem base para calcular'} state={capacityFits===false?'danger':'neutral'}/><Result icon={<WalletCards/>} label="Resultado projetado" value={brl(projectedResult)} note={`${plannedOrders||0} pedidos × ${brl(contributionPerOrder)} de contribuição`} state={projectedResult<0?'danger':projectedResult<targetProfit?'warn':'good'}/><Result icon={<ShieldAlert/>} label="Runway de caixa" value={runway===Infinity?'sem queima':runway?`${runway.toFixed(1)} meses`:'—'} note={burn?`queima projetada ${brl(burn)}/mês`:'plano cobre os fixos'} state={burn>0?'danger':'good'}/></div>
  <div className="cash-grid lower"><article className="cash-panel cash-capacity"><Head icon={<Gauge/>} kicker="CAPACIDADE × META" title="Venda necessária precisa caber na cozinha."/>{capacity.safeHour>0?<><div className="cash-capacity-line"><div><span>Teto seguro detectado</span><strong>{capacity.safeHour}</strong><small>pedidos por janela de 1h</small></div><div><span>Capacidade mensal declarada</span><strong>{monthlyCapacity}</strong><small>{windows} janela(s) × {workingDays} dias</small></div><div className={capacityFits===false?'bad':'ok'}><span>Meta calculada</span><strong>{targetOrders||0}</strong><small>{capacityFits===false?'não cabe nas premissas atuais':'cabe nas premissas atuais'}</small></div></div>{capacityFits===false&&<div className="cash-warning">A meta financeira supera a capacidade configurada no Laboratório 360. Corrija margem, preço, janela ou processo antes de comprar tráfego.</div>}</>:<div className="cash-empty-inline">Faça o teste de capacidade no Laboratório 360 para cruzar o ponto de equilíbrio com o gargalo operacional. <a href="/?playbook=1">Abrir Capacity Engine</a></div>}</article>
   <article className="cash-panel"><Head icon={<Calculator/>} kicker="CENÁRIOS" title="Mude volume sem fingir certeza."/><div className="cash-scenarios">{scenarios.map(s=><div key={s.name} className={s.result<0?'loss':s.result>=targetProfit?'gain':''}><span>{s.name}</span><b>{s.orders} pedidos</b><strong>{brl(s.result)}</strong><small>{brl(s.total)} contribuição antes dos fixos</small></div>)}</div><p className="cash-muted">Conservador = 80% do volume planejado; acelerado = 120%. São cenários de sensibilidade, não previsão de demanda.</p></article>
  </div>
  <div className={`cash-decision ${monthlyGap>0?'attention':'good'}`}><div><span>PRÓXIMA DECISÃO</span><b>{monthlyGap>0?`Faltam ${brl(monthlyGap)} de contribuição para cobrir fixos + resultado-alvo.`:'A contribuição planejada cobre os fixos e o resultado-alvo declarado.'}</b><small>{monthlyGap>0&&contributionPerOrder>0?`Equivale a aproximadamente ${ceil(monthlyGap/contributionPerOrder)} pedidos adicionais na contribuição atual.`:'Proteja margem, capacidade e qualidade antes de ampliar.'}</small></div><div><a href="/?growth=1">Growth Lab</a><a href="/?margin=1">Margens & canais</a><a href="/?kitchen=1">Modo cozinha</a></div></div>
  <div className="cash-note"><Flame/><span><b>Visão operacional, não DRE contábil.</b> Compras, tributos, depreciação e obrigações só entram corretamente quando registrados/modelados. O simulador não inventa custos ausentes.</span></div>
 </section></main>
}
function readCapacity(businessId:number){const state=safeJSON<any>(localStorage.getItem(`c360-playbook-v21-${businessId}`),{});const stages=(state.stages||[]) as Stage[];const ceilings=stages.map(s=>s.minutes>0?Math.floor(60/s.minutes*Math.max(1,s.parallel||1)):0).filter(Boolean);const technical=ceilings.length?Math.min(...ceilings):0;const safety=Math.max(0,Math.min(60,number(state.safety)||25));return{technical,safeHour:technical?Math.floor(technical*(1-safety/100)):0}}
function Head({icon,kicker,title}:{icon:React.ReactNode;kicker:string;title:string}){return <header className="cash-panel-head"><div>{icon}<span>{kicker}</span><h2>{title}</h2></div></header>}
function Kpi({label,value,note,danger=false}:{label:string;value:string;note:string;danger?:boolean}){return <article className={`cash-kpi ${danger?'danger':''}`}><span>{label}</span><strong>{value}</strong><small>{note}</small></article>}
function Field({label,value,onChange,prefix,placeholder}:{label:string;value:string;onChange:(v:string)=>void;prefix?:string;placeholder?:string}){return <label><span>{label}</span><div>{prefix&&<i>{prefix}</i>}<input inputMode="decimal" value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></div></label>}
function Result({icon,label,value,note,state}:{icon:React.ReactNode;label:string;value:string;note:string;state:'neutral'|'warn'|'danger'|'good'}){return <article className={`cash-result ${state}`}><i>{icon}</i><span>{label}</span><strong>{value}</strong><small>{note}</small></article>}
