import React,{useEffect,useMemo,useState}from'react'
import{ArrowLeft,Check,ChevronRight,CloudCog,ExternalLink,Link2,Loader2,PlugZap,RefreshCcw,ShieldCheck,Sparkles,Unplug,WifiOff,Zap}from'lucide-react'
import{request}from'./app'

type Business={id:number;name:string;city:string;role:string}
type Connection={id:number;provider:string;external_account_ref:string|null;display_name:string|null;status:string;last_success_at:string|null;last_error:string|null}
type Provider={key:string;name:string;category:string;impact:string;why:string;mode:string;eta:string;platform_ready:boolean;missing:string[];optional_missing:string[];connection:Connection|null}
type Catalog={business_id:number;recommended_order:string[];providers:Provider[]}
type IfoodFlow={user_code:string;authorization_url:string;expires_in:number}|null

const INTEGRATIONS_API=import.meta.env.VITE_INTEGRATIONS_API_URL||'https://npgheuzpnkwtxopswpqy.supabase.co/functions/v1/cozinha360-integrations-v29'
const priority=['whatsapp','mercadopago','google','ifood','meta_ads']

async function ireq(path:string,options:RequestInit={},token=''){
 const res=await fetch(`${INTEGRATIONS_API}${path}`,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{ }),...(options.headers||{})}})
 const body=await res.json().catch(()=>({detail:'Resposta inválida'}))
 if(!res.ok){const e:any=new Error(body.detail||'Falha na integração');e.body=body;throw e}
 return body
}

export function ConnectionsHubRoute(){
 const token=localStorage.getItem('c360_token')||''
 const[businesses,setBusinesses]=useState<Business[]>([]),[businessId,setBusinessId]=useState(0)
 const[catalog,setCatalog]=useState<Catalog|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState(''),[ifood,setIfood]=useState<IfoodFlow>(null),[ifoodCode,setIfoodCode]=useState('')
 async function load(target=businessId){setError('');try{let id=target;if(!businesses.length){const me=await request('/me',{},token);const rows=(me.businesses||[]) as Business[];setBusinesses(rows);id=id||Number(rows[0]?.id||0);if(id)setBusinessId(id)}if(!id)return;setCatalog(await ireq(`/businesses/${id}/integrations`,{},token))}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar conexões')}finally{setLoading(false)}}
 useEffect(()=>{const q=new URLSearchParams(location.search),ok=q.get('connected'),bad=q.get('connection_error');if(ok)setMessage(`${label(ok)} conectado com sucesso.`);if(bad)setError(`Não foi possível concluir ${label(bad)}. Tente novamente.`);load()},[])
 const providers=catalog?.providers||[]
 const activeProviders=useMemo(()=>providers.filter(p=>p.connection?.status==='active'),[providers])
 const activeKeys=useMemo(()=>new Set(activeProviders.map(p=>p.key)),[activeProviders])
 const orderReady=activeKeys.has('whatsapp')||activeKeys.has('ifood')
 const paymentReady=activeKeys.has('mercadopago')
 const discoveryReady=activeKeys.has('google')
 const expansionReady=activeKeys.has('ifood')||activeKeys.has('meta_ads')
 const canSell=orderReady&&paymentReady
 const readiness=canSell?(discoveryReady?'OPERAÇÃO + AQUISIÇÃO PRONTAS':'PRONTO PARA VENDER'):orderReady?'CONECTE O PAGAMENTO':paymentReady?'CONECTE O CANAL DE PEDIDOS':'COMECE PELO CANAL DE PEDIDOS'
 const coreReady=[orderReady,paymentReady,discoveryReady].filter(Boolean).length
 const nextProvider=useMemo(()=>{
   const byKey=new Map(providers.map(p=>[p.key,p]))
   const desired=!orderReady?['whatsapp','ifood']:!paymentReady?['mercadopago']:!discoveryReady?['google']:['ifood','meta_ads']
   return [...desired,...priority].map(k=>byKey.get(k)).find(p=>p&&!activeKeys.has(p.key)&&p.platform_ready)||null
 },[providers,activeKeys,orderReady,paymentReady,discoveryReady])
 const selectedBusinessId=catalog?.business_id||businessId
 async function connect(p:Provider){if(!selectedBusinessId)return;setBusy(p.key);setError('');setMessage('');try{const r=await ireq(`/businesses/${selectedBusinessId}/integrations/${p.key}/start`,{method:'POST'},token);if(r.action==='redirect'){location.href=r.authorization_url;return}if(r.action==='device_code'){setIfood({user_code:r.user_code,authorization_url:r.authorization_url,expires_in:r.expires_in});window.open(r.authorization_url,'_blank','noopener,noreferrer')}}catch(e:any){if(e?.body?.code==='platform_setup_required')setError(`${p.name} ainda não foi habilitado pela plataforma. A tela já está pronta; falta apenas a credencial oficial do provedor.`);else setError(e instanceof Error?e.message:'Falha ao conectar')}finally{setBusy('')}}
 async function completeIfood(){if(!ifoodCode.trim()||!selectedBusinessId)return;setBusy('ifood-complete');setError('');try{await ireq(`/businesses/${selectedBusinessId}/integrations/ifood/complete`,{method:'POST',body:JSON.stringify({authorization_code:ifoodCode.trim()})},token);setIfood(null);setIfoodCode('');setMessage('iFood conectado. A operação já pode validar a conta.');await load(selectedBusinessId)}catch(e){setError(e instanceof Error?e.message:'Falha ao concluir iFood')}finally{setBusy('')}}
 async function test(p:Provider){if(!selectedBusinessId)return;setBusy(`test-${p.key}`);setError('');try{await ireq(`/businesses/${selectedBusinessId}/integrations/${p.key}/test`,{method:'POST'},token);setMessage(`${p.name}: conexão validada agora.`);await load(selectedBusinessId)}catch(e){setError(e instanceof Error?e.message:'Teste falhou');await load(selectedBusinessId)}finally{setBusy('')}}
 async function testAll(){if(!selectedBusinessId||!activeProviders.length)return;setBusy('test-all');setError('');setMessage('');let ok=0;const failed:string[]=[];for(const p of activeProviders){try{await ireq(`/businesses/${selectedBusinessId}/integrations/${p.key}/test`,{method:'POST'},token);ok++}catch{failed.push(p.name)}}await load(selectedBusinessId);if(failed.length)setError(`${ok}/${activeProviders.length} conexões validadas. Revise: ${failed.join(', ')}.`);else setMessage(`${ok}/${activeProviders.length} conexões validadas. Tudo saudável.`);setBusy('')}
 async function disconnect(p:Provider){if(!selectedBusinessId||!confirm(`Desconectar ${p.name}? O histórico operacional será preservado.`))return;setBusy(`off-${p.key}`);try{await ireq(`/businesses/${selectedBusinessId}/integrations/${p.key}`,{method:'DELETE'},token);setMessage(`${p.name} desconectado.`);await load(selectedBusinessId)}catch(e){setError(e instanceof Error?e.message:'Não foi possível desconectar')}finally{setBusy('')}}
 if(!token)return <main className="cx-shell cx-center"><div className="cx-empty"><PlugZap/><h1>Entre na operação primeiro.</h1><a href="/">Entrar</a></div></main>
 if(loading)return <main className="cx-shell cx-center"><div className="cx-loader"><Loader2/> PREPARANDO CONEXÕES</div></main>
 return <main className="cx-shell"><header className="cx-top"><a href="/"><ArrowLeft/> Operação</a><b><PlugZap/> CONNECTION <span>AUTOPILOT</span></b><div>{businesses.length>1&&<select value={selectedBusinessId} onChange={async e=>{const id=Number(e.target.value);setBusinessId(id);setLoading(true);await load(id)}}>{businesses.map(b=><option value={b.id} key={b.id}>{b.name}</option>)}</select>}<button onClick={()=>load(selectedBusinessId)} aria-label="Atualizar"><RefreshCcw/></button></div></header><section className="cx-page">
  <div className="cx-hero"><div><span>COZINHA DE BOLSO 360 · CONEXÕES</span><h1>Conecte uma vez. O 360 cuida da saúde.</h1><p>O app escolhe o próximo conector útil, valida as contas ativas e separa o que é necessário para vender do que serve para crescer. Você só entra na sua conta e autoriza quando o provedor pedir.</p></div><div className={`cx-readiness ${canSell?'good':''}`}><ShieldCheck/><span>{readiness}</span><b>{activeProviders.length}/{providers.length}</b><small>conexões ativas · {coreReady}/3 pilares</small></div></div>
  {message&&<div className="cx-banner ok"><Check/>{message}</div>}{error&&<div className="cx-banner bad"><WifiOff/>{error}</div>}
  <div className="cx-autopilot"><div><span>AUTOPILOT</span><h2>{nextProvider?`Próximo passo: ${nextProvider.name}`:'Conexões principais organizadas'}</h2><p>{nextProvider?nextProvider.impact:'Use “Testar conexões” periodicamente para confirmar que as autorizações continuam válidas.'}</p></div><div className="cx-autopilot-actions">{nextProvider&&<button onClick={()=>connect(nextProvider)} disabled={Boolean(busy)}>{busy===nextProvider.key?<Loader2/>:<Zap/>} Conectar {nextProvider.name}</button>}<button className="secondary" onClick={testAll} disabled={busy==='test-all'||!activeProviders.length}>{busy==='test-all'?<Loader2/>:<RefreshCcw/>} Testar conexões</button></div></div>
  <div className="cx-journey"><JourneyStep title="Pedidos" text="WhatsApp ou iFood" ready={orderReady}/><JourneyStep title="Pagamento" text="Mercado Pago / Pix" ready={paymentReady}/><JourneyStep title="Descoberta" text="Google local" ready={discoveryReady}/><JourneyStep title="Expansão" text="iFood e mídia paga" ready={expansionReady} optional/></div>
  <div className="cx-plan"><div><span>ORDEM INTELIGENTE</span><b>Pedido → Pagamento → Descoberta → Escala</b><small>O 360 pula conectores indisponíveis e não exige mídia paga para uma operação que ainda precisa fechar o básico.</small></div><div><Sparkles/><span>{canSell?'Você já tem estrutura mínima de canal + pagamento. Agora o foco pode ir para aquisição e eficiência.':'Ainda falta uma peça operacional para vender sem improviso. O Autopilot coloca essa peça primeiro.'}</span></div></div>
  <div className="cx-grid">{providers.map((p,i)=><ProviderCard key={p.key} p={p} index={i+1} busy={busy} onConnect={()=>connect(p)} onTest={()=>test(p)} onDisconnect={()=>disconnect(p)}/>)}</div>
  {ifood&&<section className="cx-ifood"><div><span>IFOOD · PASSO FINAL</span><h2>Autorize no Portal do Parceiro e cole o código.</h2><p>O código de ativação gerado foi <strong>{ifood.user_code}</strong>. O portal abriu em outra aba. Depois de autorizar o Cozinha 360, copie o código de autorização exibido e cole abaixo.</p><a href={ifood.authorization_url} target="_blank" rel="noreferrer">Abrir Portal iFood <ExternalLink/></a></div><div><label>Código de autorização<input value={ifoodCode} onChange={e=>setIfoodCode(e.target.value.toUpperCase())} placeholder="XXXX-XXXX" autoFocus/></label><button onClick={completeIfood} disabled={!ifoodCode.trim()||busy==='ifood-complete'}>{busy==='ifood-complete'?<Loader2/>:<Check/>} Concluir conexão</button></div></section>}
  <div className="cx-security"><ShieldCheck/><div><b>Segurança por padrão</b><span>Tokens são criptografados no servidor. A interface recebe somente status, nome da conta e saúde da conexão. Desconectar apaga a credencial, mas não destrói histórico de pedidos e auditoria.</span></div></div>
 </section></main>
}

function JourneyStep({title,text,ready,optional=false}:{title:string;text:string;ready:boolean;optional?:boolean}){return <div className={`cx-step ${ready?'ready':''}`}><i>{ready?<Check/>:<span/>}</i><div><b>{title}{optional&&<em> opcional</em>}</b><small>{ready?'Conectado':text}</small></div></div>}
function ProviderCard({p,index,busy,onConnect,onTest,onDisconnect}:{p:Provider;index:number;busy:string;onConnect:()=>void;onTest:()=>void;onDisconnect:()=>void}){const c=p.connection,isActive=c?.status==='active',isBad=c?.status==='degraded',waiting=!p.platform_ready;return <article className={`cx-card ${isActive?'active':''} ${isBad?'degraded':''}`}><header><i>{String(index).padStart(2,'0')}</i><div><span>{p.category}</span><h2>{p.name}</h2></div><Status active={isActive} bad={isBad} waiting={waiting}/></header><p>{p.impact}</p><div className="cx-why"><Link2/><span>{p.why}</span></div>{c&&<div className="cx-account"><span>CONTA</span><b>{c.display_name||c.external_account_ref||'Autorizada'}</b><small>{c.last_success_at?`validada ${new Date(c.last_success_at).toLocaleString('pt-BR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}`:c.status}</small>{c.last_error&&<em>{c.last_error}</em>}</div>}<footer><span>{p.eta}</span>{isActive?<><button className="ghost" onClick={onTest} disabled={Boolean(busy)}>{busy===`test-${p.key}`?<Loader2/>:<RefreshCcw/>} Testar</button><button className="icon" onClick={onDisconnect} disabled={Boolean(busy)} title="Desconectar"><Unplug/></button></>:<button onClick={onConnect} disabled={Boolean(busy)||waiting}>{busy===p.key?<Loader2/>:waiting?<CloudCog/>:<PlugZap/>}{waiting?'Aguardando ativação':'Conectar'}{!waiting&&<ChevronRight/>}</button>}</footer>{waiting&&<small className="cx-wait">O usuário não precisa configurar API. Falta apenas a ativação oficial deste provedor pela plataforma uma única vez.</small>}</article>}
function Status({active,bad,waiting}:{active:boolean;bad:boolean;waiting:boolean}){if(active)return <strong className="cx-status active"><Check/>ATIVO</strong>;if(bad)return <strong className="cx-status bad">REVISAR</strong>;if(waiting)return <strong className="cx-status wait">PLATAFORMA</strong>;return <strong className="cx-status">PRONTO</strong>}
function label(k:string){return({whatsapp:'WhatsApp Business',mercadopago:'Mercado Pago',google:'Google',ifood:'iFood',meta_ads:'Meta Ads'} as Record<string,string>)[k]||k}