import React,{useEffect,useMemo,useRef,useState}from'react'
import{Activity,AlertTriangle,ArrowLeft,Check,ChevronRight,Clock3,CloudCog,ExternalLink,HeartPulse,Link2,Loader2,PlugZap,RefreshCcw,Settings2,ShieldCheck,Sparkles,Unplug,WifiOff,X,Zap}from'lucide-react'
import{request}from'./app'
import'./connections-setup-v31.css'
import'./connections-doctor-v32.css'
import'./connections-fallback-v33.css'
import'./connections-plug-play-v55.css'

type Business={id:number;name:string;city:string;role:string}
type Connection={id:number;provider:string;external_account_ref:string|null;display_name:string|null;status:string;last_success_at:string|null;last_error:string|null;last_error_at?:string|null;updated_at?:string|null}
type Asset={ref:string;label:string;kind:string;detail?:string}
type Provider={key:string;name:string;category:string;impact:string;why:string;mode:string;eta:string;platform_ready:boolean;missing:string[];optional_missing:string[];connection:Connection|null;operational?:boolean;asset_count?:number;selection_required?:boolean;assets?:Asset[];selected_asset?:{ref:string;label:string}|null;credential_expires_at?:string|null}
type IntegrationProfile={business_id:number;order_source:'direct'|'whatsapp'|'ifood'|'mixed';use_mercadopago:boolean;use_google:boolean;use_meta_ads:boolean;configured_at:string|null;updated_by_user_id:number|null}
type ProfilePlan={profile:IntegrationProfile;recommended_order:string[];internal_order_ready:boolean}
type Catalog={business_id:number;recommended_order:string[];providers:Provider[];profile_plan:ProfilePlan}
type IfoodFlow={user_code:string;authorization_url:string;expires_in:number}|null
type AssetPicker={provider:string;name:string;assets:Asset[]}|null

const INTEGRATIONS_API=import.meta.env.VITE_INTEGRATIONS_API_URL||'https://npgheuzpnkwtxopswpqy.supabase.co/functions/v1/cozinha360-integrations-v29'
const PROFILE_API=import.meta.env.VITE_PROFILE_API_URL||'https://npgheuzpnkwtxopswpqy.supabase.co/functions/v1/cozinha360-profile-v31'
const HEALTH_TTL=24*60*60*1000

async function fetchJson(base:string,path:string,options:RequestInit={},token=''){
 const res=await fetch(`${base}${path}`,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{ }),...(options.headers||{})}})
 const body=await res.json().catch(()=>({detail:'Resposta inválida'}))
 if(!res.ok){const e:any=new Error(body.detail||'Falha na integração');e.body=body;throw e}
 return body
}
const ireq=(path:string,options:RequestInit={},token='')=>fetchJson(INTEGRATIONS_API,path,options,token)
const preq=(path:string,options:RequestInit={},token='')=>fetchJson(PROFILE_API,path,options,token)
const operational=(p:Provider)=>p.operational??p.connection?.status==='active'
const isStale=(p:Provider)=>operational(p)&&(!p.connection?.last_success_at||Date.now()-Date.parse(p.connection.last_success_at)>HEALTH_TTL)

export function ConnectionsHubRoute(){
 const token=localStorage.getItem('c360_token')||''
 const autoChecked=useRef(new Set<number>())
 const[businesses,setBusinesses]=useState<Business[]>([]),[businessId,setBusinessId]=useState(0)
 const[catalog,setCatalog]=useState<Catalog|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState(''),[doctorNote,setDoctorNote]=useState(''),[ifood,setIfood]=useState<IfoodFlow>(null),[ifoodCode,setIfoodCode]=useState(''),[draft,setDraft]=useState<IntegrationProfile|null>(null),[editingPlan,setEditingPlan]=useState(false),[assetPicker,setAssetPicker]=useState<AssetPicker>(null)
 async function load(target=businessId){setError('');try{let id=target;if(!businesses.length){const me=await request('/me',{},token);const rows=(me.businesses||[]) as Business[];setBusinesses(rows);id=id||Number(rows[0]?.id||0);if(id)setBusinessId(id)}if(!id)return;const[connections,profilePlan]=await Promise.all([ireq(`/businesses/${id}/integrations`,{},token),preq(`/businesses/${id}/profile`,{},token)]);setCatalog({...connections,profile_plan:profilePlan});setDraft(profilePlan.profile);setEditingPlan(false)}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar conexões')}finally{setLoading(false)}}
 useEffect(()=>{const q=new URLSearchParams(location.search),ok=q.get('connected'),bad=q.get('connection_error');if(ok)setMessage(`${label(ok)} conectado com sucesso.`);if(bad)setError(`Não foi possível concluir ${label(bad)}. Tente novamente.`);load()},[])
 const providers=catalog?.providers||[],profile=catalog?.profile_plan.profile||null,smartOrder=catalog?.profile_plan.recommended_order||[]
 const activeProviders=useMemo(()=>providers.filter(operational),[providers])
 const testableProviders=useMemo(()=>providers.filter(p=>!p.selection_required&&['active','degraded'].includes(p.connection?.status||'')),[providers])
 const degradedProviders=useMemo(()=>providers.filter(p=>p.connection?.status==='degraded'),[providers])
 const staleProviders=useMemo(()=>providers.filter(isStale),[providers])
 const healthyProviders=useMemo(()=>activeProviders.filter(p=>!isStale(p)),[activeProviders])
 const activeKeys=useMemo(()=>new Set(activeProviders.map(p=>p.key)),[activeProviders])
 const configured=Boolean(profile?.configured_at)
 const orderReady=profile?(profile.order_source==='direct'||profile.order_source==='whatsapp'&&activeKeys.has('whatsapp')||profile.order_source==='ifood'&&activeKeys.has('ifood')||profile.order_source==='mixed'&&activeKeys.has('whatsapp')&&activeKeys.has('ifood')):false
 const paymentReady=profile?(!profile.use_mercadopago||activeKeys.has('mercadopago')):false
 const discoveryReady=profile?(!profile.use_google||activeKeys.has('google')):false
 const expansionReady=profile?(!profile.use_meta_ads||activeKeys.has('meta_ads')):false
 const canSell=configured&&orderReady&&paymentReady
 const readiness=!configured?'CONFIGURE EM 30 SEGUNDOS':canSell?(discoveryReady?'OPERAÇÃO + DESCOBERTA PRONTAS':'PRONTO PARA VENDER'):orderReady?'CONECTE O PAGAMENTO':'CONECTE O CANAL DE PEDIDOS'
 const coreReady=[orderReady,paymentReady,discoveryReady].filter(Boolean).length
 const plannedActive=smartOrder.filter(k=>activeKeys.has(k)).length
 const nextNeeded=useMemo(()=>{const byKey=new Map(providers.map(p=>[p.key,p]));return smartOrder.map(k=>byKey.get(k)).find(p=>p&&!operational(p))||null},[providers,smartOrder,activeKeys])
 const nextProvider=nextNeeded?.platform_ready?nextNeeded:null,blockedProvider=nextNeeded&&!nextNeeded.platform_ready?nextNeeded:null
 const selectedBusinessId=catalog?.business_id||businessId
 const lastValidation=useMemo(()=>{const ts=testableProviders.map(p=>p.connection?.last_success_at?Date.parse(p.connection.last_success_at):0).filter(Boolean);return ts.length?new Date(Math.max(...ts)).toISOString():null},[testableProviders])
 useEffect(()=>{if(!catalog||!selectedBusinessId||autoChecked.current.has(selectedBusinessId))return;autoChecked.current.add(selectedBusinessId);const candidates=providers.filter(p=>p.connection?.status==='degraded'||isStale(p));if(candidates.length)void runHealth(candidates,'auto')},[catalog?.business_id])
 async function saveProfile(next:IntegrationProfile,success:string,busyKey:string){if(!selectedBusinessId)return;setBusy(busyKey);setError('');setMessage('');try{const saved=await preq(`/businesses/${selectedBusinessId}/profile`,{method:'PUT',body:JSON.stringify({order_source:next.order_source,use_mercadopago:next.use_mercadopago,use_google:next.use_google,use_meta_ads:next.use_meta_ads})},token);setCatalog(c=>c?{...c,profile_plan:saved}:c);setDraft(saved.profile);setEditingPlan(false);setMessage(success)}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar o plano')}finally{setBusy('')}}
 async function savePlan(){if(!draft)return;await saveProfile(draft,'Plano de conexões salvo. O Autopilot reorganizou os próximos passos.','save-plan')}
 async function applyFallback(p:Provider){if(!profile)return;let next={...profile};if(p.key==='mercadopago')next.use_mercadopago=false;else if(p.key==='google')next.use_google=false;else if(p.key==='meta_ads')next.use_meta_ads=false;else if(p.key==='whatsapp')next.order_source=profile.order_source==='mixed'?'ifood':'direct';else if(p.key==='ifood')next.order_source=profile.order_source==='mixed'?'whatsapp':'direct';else return;await saveProfile(next,`Plano ajustado: ${fallbackResult(p.key,next)}. Você pode conectar ${p.name} depois.`,`fallback-${p.key}`)}
 function openPicker(p:Provider){if(p.assets?.length)setAssetPicker({provider:p.key,name:p.name,assets:p.assets})}
 async function connect(p:Provider){if(!selectedBusinessId)return;if(p.selection_required&&p.assets?.length){openPicker(p);return}setBusy(p.key);setError('');setMessage('');try{const r=await ireq(`/businesses/${selectedBusinessId}/integrations/${p.key}/start`,{method:'POST',body:JSON.stringify({return_origin:location.origin})},token);if(r.action==='redirect'){location.href=r.authorization_url;return}if(r.action==='device_code'){setIfood({user_code:r.user_code,authorization_url:r.authorization_url,expires_in:r.expires_in});window.open(r.authorization_url,'_blank','noopener,noreferrer')}}catch(e:any){if(e?.body?.code==='platform_setup_required')setError(`${p.name} ainda não foi habilitado pela plataforma. Você não precisa configurar API: essa ativação é responsabilidade do Cozinha 360.`);else setError(e instanceof Error?e.message:'Falha ao conectar')}finally{setBusy('')}}
 async function completeIfood(){if(!ifoodCode.trim()||!selectedBusinessId)return;setBusy('ifood-complete');setError('');try{const r=await ireq(`/businesses/${selectedBusinessId}/integrations/ifood/complete`,{method:'POST',body:JSON.stringify({authorization_code:ifoodCode.trim()})},token);setIfood(null);setIfoodCode('');if(r.action==='select_asset'&&r.assets?.length){setAssetPicker({provider:'ifood',name:'iFood',assets:r.assets});setMessage('Autorização concluída. Falta apenas escolher qual loja pertence a esta operação.')}else setMessage('iFood conectado e vinculado à operação.');await load(selectedBusinessId)}catch(e){setError(e instanceof Error?e.message:'Falha ao concluir iFood')}finally{setBusy('')}}
 async function selectAsset(provider:string,asset:Asset){if(!selectedBusinessId)return;setBusy(`select-${provider}`);setError('');try{await ireq(`/businesses/${selectedBusinessId}/integrations/${provider}/select`,{method:'POST',body:JSON.stringify({asset_ref:asset.ref})},token);setAssetPicker(null);setMessage(`${asset.label} conectado à operação. O vínculo foi configurado automaticamente quando havia uma única marca.`);await load(selectedBusinessId)}catch(e){setError(e instanceof Error?e.message:'Não foi possível selecionar esta conta')}finally{setBusy('')}}
 async function test(p:Provider){if(!selectedBusinessId)return;if(p.selection_required&&p.assets?.length){openPicker(p);return}setBusy(`test-${p.key}`);setError('');try{await ireq(`/businesses/${selectedBusinessId}/integrations/${p.key}/test`,{method:'POST'},token);setMessage(`${p.name}: conexão validada agora.`);await load(selectedBusinessId)}catch(e:any){if(e?.body?.code==='asset_selection_required'&&e.body.assets?.length)setAssetPicker({provider:p.key,name:p.name,assets:e.body.assets});const msg=e instanceof Error?e.message:'Teste falhou';await load(selectedBusinessId);setError(msg)}finally{setBusy('')}}
 async function runHealth(list:Provider[],mode:'auto'|'manual'|'doctor'){if(!selectedBusinessId||!list.length||busy)return;setBusy(mode==='auto'?'doctor-auto':mode==='doctor'?'doctor':'test-all');if(mode!=='auto'){setError('');setMessage('')}let ok=0;const failed:string[]=[];for(const p of list){try{await ireq(`/businesses/${selectedBusinessId}/integrations/${p.key}/test`,{method:'POST'},token);ok++}catch{failed.push(p.name)}}await load(selectedBusinessId);if(mode==='auto'){setDoctorNote(failed.length?`Verificação automática: ${ok} saudável${ok===1?'':'s'}; ${failed.length} precisa${failed.length===1?'':'m'} de atenção.`:`${ok} ${ok===1?'conexão antiga revalidada':'conexões antigas revalidadas'} automaticamente.`)}else if(failed.length)setError(`${ok}/${list.length} conexões validadas. Revise: ${failed.join(', ')}.`);else setMessage(`${ok}/${list.length} conexões validadas. Tudo saudável.`);setBusy('')}
 async function testAll(){await runHealth(testableProviders,'manual')}
 async function disconnect(p:Provider){if(!selectedBusinessId||!confirm(`Desconectar ${p.name}? O histórico operacional será preservado.`))return;setBusy(`off-${p.key}`);try{await ireq(`/businesses/${selectedBusinessId}/integrations/${p.key}`,{method:'DELETE'},token);setMessage(`${p.name} desconectado.`);await load(selectedBusinessId)}catch(e){setError(e instanceof Error?e.message:'Não foi possível desconectar')}finally{setBusy('')}}
 if(!token)return <main className="cx-shell cx-center"><div className="cx-empty"><PlugZap/><h1>Entre na operação primeiro.</h1><a href="/">Entrar</a></div></main>
 if(loading)return <main className="cx-shell cx-center"><div className="cx-loader"><Loader2/> PREPARANDO CONEXÕES</div></main>
 return <main className="cx-shell"><header className="cx-top"><a href="/"><ArrowLeft/> Operação</a><b><PlugZap/> CONNECTION <span>AUTOPILOT</span></b><div>{businesses.length>1&&<select value={selectedBusinessId} onChange={async e=>{const id=Number(e.target.value);setBusinessId(id);setDoctorNote('');setAssetPicker(null);setLoading(true);await load(id)}}>{businesses.map(b=><option value={b.id} key={b.id}>{b.name}</option>)}</select>}<button onClick={()=>load(selectedBusinessId)} aria-label="Atualizar"><RefreshCcw/></button></div></header><section className="cx-page">
  <div className="cx-hero"><div><span>COZINHA DE BOLSO 360 · CONEXÕES</span><h1>Conecte sua operação, não APIs.</h1><p>Escolha como sua cozinha vende. O 360 abre a autorização oficial, encontra sua conta, testa a conexão e vincula automaticamente quando existe uma única opção segura.</p><div className="cx-plug-chip"><Sparkles/> Plug & play · sem copiar token, webhook ou merchant ID</div></div><div className={`cx-readiness ${canSell?'good':''}`}><ShieldCheck/><span>{readiness}</span><b>{smartOrder.length?`${plannedActive}/${smartOrder.length}`:'0'}</b><small>conexões operacionais · {coreReady}/3 pilares</small></div></div>
  {message&&<div className="cx-banner ok"><Check/>{message}</div>}{error&&<div className="cx-banner bad"><WifiOff/>{error}</div>}
  <ConnectionDoctor healthy={healthyProviders.length} stale={staleProviders.length} degraded={degradedProviders.length} total={testableProviders.length} lastValidation={lastValidation} note={doctorNote} busy={busy==='doctor'||busy==='doctor-auto'} onCheck={()=>runHealth(testableProviders,'doctor')}/>
  {draft&&(!configured||editingPlan)?<SetupWizard draft={draft} setDraft={setDraft} saving={busy==='save-plan'} onSave={savePlan} onCancel={configured?()=>{setDraft(profile);setEditingPlan(false)}:undefined}/>:<PlanSummary profile={profile} onEdit={()=>setEditingPlan(true)}/>} 
  <div className={`cx-autopilot ${blockedProvider?'blocked':''}`}><div><span>AUTOPILOT</span><h2>{!configured?'Primeiro: monte seu plano':blockedProvider?`${blockedProvider.name}: ativação da plataforma pendente`:nextProvider?.selection_required?`Só falta escolher sua conta de ${nextProvider.name}`:nextProvider?`Próximo passo: ${nextProvider.name}`:'Seu plano está organizado'}</h2><p>{!configured?'São quatro escolhas, sem token, webhook ou linguagem técnica.':blockedProvider?`A homologação de ${blockedProvider.name} não é tarefa sua. Você pode esperar a ativação ou usar a alternativa operacional abaixo e começar sem essa API.`:nextProvider?.selection_required?'A autorização já deu certo. O 360 encontrou mais de uma opção e precisa saber qual pertence a esta operação.':nextProvider?nextProvider.impact:'Não há outra API obrigatória no seu plano. O Doctor continua cuidando da saúde e renovação das autorizações existentes.'}</p></div><div className="cx-autopilot-actions">{nextProvider&&<button onClick={()=>connect(nextProvider)} disabled={Boolean(busy)}>{busy===nextProvider.key?<Loader2/>:nextProvider.selection_required?<Settings2/>:<Zap/>} {nextProvider.selection_required?'Escolher conta':`Conectar ${nextProvider.name}`}</button>}{blockedProvider&&<><span className="cx-platform-chip"><CloudCog/> Sem ação técnica sua</span><button className="cx-fallback" onClick={()=>applyFallback(blockedProvider)} disabled={Boolean(busy)}>{busy===`fallback-${blockedProvider.key}`?<Loader2/>:<ChevronRight/>} {fallbackLabel(blockedProvider.key,profile)}</button></>}<button className="secondary" onClick={testAll} disabled={Boolean(busy)||!testableProviders.length}>{busy==='test-all'?<Loader2/>:<RefreshCcw/>} Testar conexões</button></div></div>
  <div className="cx-journey"><JourneyStep title="Pedidos" text={orderText(profile)} ready={orderReady} readyText={orderReadyText(profile)}/><JourneyStep title="Pagamento" text={profile?.use_mercadopago?'Mercado Pago / Pix':'Manual — sem API externa'} ready={paymentReady} readyText={profile?.use_mercadopago?'Pagamento conectado':'Manual — sem API externa'}/><JourneyStep title="Descoberta" text={profile?.use_google?'Google local':'Não necessário no plano'} ready={discoveryReady} readyText={profile?.use_google?'Google conectado':'Não necessário no plano'}/><JourneyStep title="Crescimento" text={profile?.use_meta_ads?'Meta Ads':'Sem mídia paga por enquanto'} ready={expansionReady} readyText={profile?.use_meta_ads?'Meta Ads conectado':'Sem mídia paga por enquanto'} optional/></div>
  <div className="cx-plan"><div><span>ORDEM INTELIGENTE</span><b>Pedido → Pagamento → Descoberta → Escala</b><small>O objetivo é operar, não colecionar integrações. Autorizar é só o começo: a conta só fica verde quando o ativo externo foi identificado e testado.</small></div><div><Sparkles/><span>{canSell?'Seu canal de pedido e sua forma de pagamento já estão definidos. O próximo passo pode ser aquisição ou simplesmente operar.':'O Autopilot ainda encontrou uma peça necessária para o modelo que você escolheu.'}</span></div></div>
  <div className="cx-grid">{providers.map((p,i)=><ProviderCard key={p.key} p={p} index={i+1} planned={smartOrder.includes(p.key)} busy={busy} onConnect={()=>connect(p)} onTest={()=>test(p)} onDisconnect={()=>disconnect(p)} onChoose={()=>openPicker(p)}/>)}</div>
  {assetPicker&&<AssetPickerPanel picker={assetPicker} busy={busy===`select-${assetPicker.provider}`} onClose={()=>setAssetPicker(null)} onSelect={asset=>selectAsset(assetPicker.provider,asset)}/>} 
  {ifood&&<section className="cx-ifood"><div><span>IFOOD · PASSO FINAL</span><h2>Autorize no Portal do Parceiro e cole o código.</h2><p>O código de ativação gerado foi <strong>{ifood.user_code}</strong>. O portal abriu em outra aba. Depois de autorizar o Cozinha 360, copie o código de autorização exibido e cole abaixo.</p><a href={ifood.authorization_url} target="_blank" rel="noreferrer">Abrir Portal iFood <ExternalLink/></a></div><div><label>Código de autorização<input value={ifoodCode} onChange={e=>setIfoodCode(e.target.value.toUpperCase())} placeholder="XXXX-XXXX" autoFocus/></label><button onClick={completeIfood} disabled={!ifoodCode.trim()||busy==='ifood-complete'}>{busy==='ifood-complete'?<Loader2/>:<Check/>} Concluir conexão</button></div></section>}
  <div className="cx-security"><ShieldCheck/><div><b>Segurança por padrão</b><span>O navegador nunca recebe Client Secret ou token armazenado. Credenciais ficam criptografadas no servidor, são renovadas silenciosamente quando o provedor permite e podem ser revogadas sem apagar o histórico da operação.</span></div></div>
 </section></main>
}

function AssetPickerPanel({picker,busy,onClose,onSelect}:{picker:NonNullable<AssetPicker>;busy:boolean;onClose:()=>void;onSelect:(asset:Asset)=>void}){return <section className="cx-asset-picker" aria-label={`Escolher conta ${picker.name}`}><header><div><span>UMA ÚNICA ESCOLHA</span><h2>Qual {picker.name} pertence a esta operação?</h2><p>A autorização já foi concluída. Escolha pelo nome; IDs e credenciais continuam escondidos.</p></div><button onClick={onClose} aria-label="Fechar"><X/></button></header><div className="cx-asset-list">{picker.assets.map(asset=><button className="cx-asset-option" key={asset.ref} disabled={busy} onClick={()=>onSelect(asset)}>{busy?<Loader2/>:<><b>{asset.label}</b><small>{asset.detail||asset.kind}</small><span>Usar esta conta →</span></>}</button>)}</div></section>}
function ConnectionDoctor({healthy,stale,degraded,total,lastValidation,note,busy,onCheck}:{healthy:number;stale:number;degraded:number;total:number;lastValidation:string|null;note:string;busy:boolean;onCheck:()=>void}){const state=degraded?'bad':stale?'warn':total?'good':'empty',headline=degraded?`${degraded} conexão${degraded===1?'':'ões'} precisa${degraded===1?'':'m'} de atenção`:stale?`${stale} conexão${stale===1?'':'ões'} aguardando revalidação`:total?`${healthy}/${total} conexões saudáveis`:'Nenhuma conexão externa para diagnosticar';return <section className={`cx-doctor ${state}`}><div className="cx-doctor-icon">{degraded?<AlertTriangle/>:<HeartPulse/>}</div><div className="cx-doctor-copy"><span>CONNECTION DOCTOR</span><h2>{headline}</h2><p>{degraded?'O 360 tentou validar a autorização. Se o problema continuar, use “Reconectar” no cartão do provedor — sem copiar chave ou token.':stale?'Autorizações antigas são revalidadas automaticamente ao abrir esta tela.':'O 360 guarda a última validação, renova tokens compatíveis e recheca conexões antes que você dependa delas.'}</p>{note&&<small><Activity/>{note}</small>}</div><div className="cx-doctor-meta"><span><Clock3/>{lastValidation?`Último OK ${new Date(lastValidation).toLocaleString('pt-BR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}`:'Sem validação anterior'}</span><button onClick={onCheck} disabled={busy||!total}>{busy?<Loader2/>:<RefreshCcw/>} Diagnosticar agora</button></div></section>}
function SetupWizard({draft,setDraft,saving,onSave,onCancel}:{draft:IntegrationProfile;setDraft:(p:IntegrationProfile)=>void;saving:boolean;onSave:()=>void;onCancel?:()=>void}){const orderOptions:[IntegrationProfile['order_source'],string,string][]=[['direct','Loja própria','Pedidos entram pelo Cozinha 360. Nenhuma API externa.'],['whatsapp','WhatsApp','Conversa vira canal principal de pedido.'],['ifood','iFood','Marketplace é o canal principal.'],['mixed','WhatsApp + iFood','Os dois canais entram na mesma operação.']];return <section className="cx-setup"><div className="cx-setup-head"><div><span>SETUP RÁPIDO</span><h2>Como sua cozinha realmente vende?</h2><p>Escolha o cenário real. Você pode mudar depois.</p></div><b>4 decisões</b></div><div className="cx-setup-question"><strong>1. Onde entram os pedidos?</strong><div className="cx-order-options">{orderOptions.map(([value,title,text])=><button key={value} className={draft.order_source===value?'selected':''} onClick={()=>setDraft({...draft,order_source:value})} aria-pressed={draft.order_source===value}><Check/><b>{title}</b><small>{text}</small></button>)}</div></div><div className="cx-toggle-grid"><Choice title="2. Confirmar Pix automaticamente?" text="Conectar Mercado Pago para baixa automática." value={draft.use_mercadopago} onChange={v=>setDraft({...draft,use_mercadopago:v})}/><Choice title="3. Quer ser encontrado no Google?" text="Perfil local e avaliações conectadas à operação." value={draft.use_google} onChange={v=>setDraft({...draft,use_google:v})}/><Choice title="4. Já usa anúncios Meta?" text="Só conecte mídia paga quando ela fizer parte da operação." value={draft.use_meta_ads} onChange={v=>setDraft({...draft,use_meta_ads:v})}/></div><footer>{onCancel&&<button className="cx-setup-cancel" onClick={onCancel}>Cancelar</button>}<button className="cx-setup-save" onClick={onSave} disabled={saving}>{saving?<Loader2/>:<Sparkles/>} Montar meu plano</button></footer></section>}
function Choice({title,text,value,onChange}:{title:string;text:string;value:boolean;onChange:(v:boolean)=>void}){return <div className="cx-choice"><strong>{title}</strong><p>{text}</p><div><button className={value?'selected':''} onClick={()=>onChange(true)} aria-pressed={value}>Sim</button><button className={!value?'selected':''} onClick={()=>onChange(false)} aria-pressed={!value}>Agora não</button></div></div>}
function PlanSummary({profile,onEdit}:{profile:IntegrationProfile|null;onEdit:()=>void}){if(!profile)return null;return <div className="cx-plan-summary"><div><span>SEU PLANO</span><b>{orderLabel(profile.order_source)}</b><small>{[profile.use_mercadopago&&'Pix automático',profile.use_google&&'Google',profile.use_meta_ads&&'Meta Ads'].filter(Boolean).join(' · ')||'Sem APIs adicionais'}</small></div><button onClick={onEdit}><Settings2/> Ajustar plano</button></div>}
function JourneyStep({title,text,ready,readyText,optional=false}:{title:string;text:string;ready:boolean;readyText:string;optional?:boolean}){return <div className={`cx-step ${ready?'ready':''}`}><i>{ready?<Check/>:<span/>}</i><div><b>{title}{optional&&<em> opcional</em>}</b><small>{ready?readyText:text}</small></div></div>}
function ProviderCard({p,index,planned,busy,onConnect,onTest,onDisconnect,onChoose}:{p:Provider;index:number;planned:boolean;busy:string;onConnect:()=>void;onTest:()=>void;onDisconnect:()=>void;onChoose:()=>void}){const c=p.connection,isActive=operational(p),isBad=c?.status==='degraded',needsAsset=Boolean(p.selection_required&&p.assets?.length),waiting=!p.platform_ready;return <article className={`cx-card ${isActive?'active':''} ${isBad?'degraded':''} ${needsAsset?'needs-asset':''}`}><header><i>{String(index).padStart(2,'0')}</i><div><div className="cx-provider-kicker"><span>{p.category}</span>{planned&&<em>NO SEU PLANO</em>}</div><h2>{p.name}</h2></div><Status active={isActive} bad={isBad} waiting={waiting} choose={needsAsset}/></header><p>{p.impact}</p><div className="cx-why"><Link2/><span>{p.why}</span></div>{c&&<div className="cx-account"><span>CONTA</span><b>{c.display_name||c.external_account_ref||'Autorizada'}</b><small>{c.last_success_at?`validada ${new Date(c.last_success_at).toLocaleString('pt-BR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}`:c.status}</small>{needsAsset&&<small className="cx-account-note">Autorização concluída · escolha a conta para ativar</small>}{c.last_error&&!needsAsset&&<em>{c.last_error}</em>}</div>}<footer><span>{p.eta}</span>{needsAsset?<button className="choose-account" onClick={onChoose} disabled={Boolean(busy)}><Settings2/> Escolher conta <ChevronRight/></button>:isActive?<><button className="ghost" onClick={onTest} disabled={Boolean(busy)}>{busy===`test-${p.key}`?<Loader2/>:<RefreshCcw/>} Testar</button><button className="icon" onClick={onDisconnect} disabled={Boolean(busy)} title="Desconectar"><Unplug/></button></>:<button onClick={onConnect} disabled={Boolean(busy)||waiting}>{busy===p.key?<Loader2/>:waiting?<CloudCog/>:<PlugZap/>}{waiting?'Aguardando ativação':isBad?'Reconectar':'Conectar'}{!waiting&&<ChevronRight/>}</button>}</footer>{waiting&&<small className="cx-wait">Você não precisa configurar API. A habilitação oficial deste provedor é feita uma única vez pela plataforma.</small>}</article>}
function Status({active,bad,waiting,choose}:{active:boolean;bad:boolean;waiting:boolean;choose:boolean}){if(active)return <strong className="cx-status active"><Check/>ATIVO</strong>;if(choose)return <strong className="cx-status choose">ESCOLHER</strong>;if(bad)return <strong className="cx-status bad">REVISAR</strong>;if(waiting)return <strong className="cx-status wait">PLATAFORMA</strong>;return <strong className="cx-status">PRONTO</strong>}
function fallbackLabel(key:string,p:IntegrationProfile|null){if(key==='mercadopago')return'Usar Pix manual';if(key==='google')return'Continuar sem Google';if(key==='meta_ads')return'Continuar sem Meta Ads';if(key==='whatsapp'&&p?.order_source==='mixed')return'Ficar só com iFood';if(key==='ifood'&&p?.order_source==='mixed')return'Ficar só com WhatsApp';return'Usar loja própria'}
function fallbackResult(key:string,p:IntegrationProfile){if(key==='mercadopago')return'Pix manual por enquanto';if(key==='google')return'Google deixou de ser obrigatório';if(key==='meta_ads')return'mídia paga ficou para depois';return`pedidos agora entram por ${orderLabel(p.order_source)}`}
function orderText(p:IntegrationProfile|null){if(!p)return'Escolha como vende';if(p.order_source==='direct')return'Loja própria — sem API externa';if(p.order_source==='whatsapp')return'WhatsApp';if(p.order_source==='ifood')return'iFood';return'WhatsApp + iFood'}
function orderReadyText(p:IntegrationProfile|null){if(!p)return'Canal definido';return p.order_source==='direct'?'Loja própria — sem API externa':`${orderLabel(p.order_source)} conectado`}
function orderLabel(v:IntegrationProfile['order_source']){return({direct:'Loja própria do Cozinha 360',whatsapp:'WhatsApp',ifood:'iFood',mixed:'WhatsApp + iFood'} as const)[v]}
function label(k:string){return({whatsapp:'WhatsApp Business',mercadopago:'Mercado Pago',google:'Google',ifood:'iFood',meta_ads:'Meta Ads'} as Record<string,string>)[k]||k}
