import React,{useEffect,useMemo,useState}from'react'
import{ArrowLeft,RefreshCcw,Search,ShieldCheck,UserCheck,UserMinus,UserPlus,Users}from'lucide-react'
import{money,request}from'./app'

const CRM_API=import.meta.env.VITE_CRM_API_URL||'https://npgheuzpnkwtxopswpqy.supabase.co/functions/v1/cozinha360-crm-v16'
type Biz={id:number;name:string;city:string;role:string}
type Customer={customer_id:number;customer_name:string;phone:string;email:string;can_contact:boolean;completed_orders:number;revenue_cents:number;contribution_cents:number;days_since_last_order:number|null;segment:'prospect'|'new'|'repeat'|'dormant';suggested_action:string}
type Data={dormant_days:number;summary:{total:number;new:number;repeat:number;dormant:number;prospect:number;contactable:number;dormant_contactable:number;revenue_cents:number;contribution_cents:number};customers:Customer[]}
const label={prospect:'Sem compra',new:'Novo',repeat:'Recorrente',dormant:'Sumido'}

async function crmRequest(path:string,token:string){
  const res=await fetch(`${CRM_API}${path}`,{headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'}})
  const body=await res.json().catch(()=>({detail:'Resposta inválida'}))
  if(!res.ok)throw new Error(typeof body.detail==='string'?body.detail:'Não foi possível concluir')
  return body
}

export function CrmLifecycleRoute(){
  const token=localStorage.getItem('c360_token')||''
  const[businesses,setBusinesses]=useState<Biz[]>([]),[businessId,setBusinessId]=useState(0),[data,setData]=useState<Data|null>(null)
  const[segment,setSegment]=useState('all'),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('')
  async function load(id=businessId){if(!id)return;setError('');try{setData(await crmRequest(`/businesses/${id}/customer-lifecycle?dormant_days=30`,token))}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar CRM')}}
  async function boot(){if(!token){setLoading(false);return}try{const me=await request('/me',{},token);const rows:Biz[]=me.businesses||[];setBusinesses(rows);const id=rows[0]?.id||0;setBusinessId(id);if(id)await load(id)}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar conta')}finally{setLoading(false)}}
  useEffect(()=>{boot()},[])
  const rows=useMemo(()=>{const q=query.trim().toLowerCase();return(data?.customers||[]).filter(x=>(segment==='all'||x.segment===segment)&&(!q||`${x.customer_name} ${x.phone} ${x.email}`.toLowerCase().includes(q)))},[data,segment,query])
  const priority=useMemo(()=>{if(!data)return'Carregando a base.';if(data.summary.dormant_contactable>0)return`${data.summary.dormant_contactable} cliente(s) sumido(s) autorizaram contato. Comece por uma oferta de retorno, sem spam.`;if(data.summary.new>0)return`${data.summary.new} cliente(s) fizeram a primeira compra. A segunda compra é a próxima meta.`;if(data.summary.repeat>0)return'Proteja os recorrentes: consistência e bom atendimento valem mais que desconto automático.';return'Associe clientes aos pedidos concluídos para formar segmentos de recompra.'},[data])
  if(!token)return <main className="crm-shell center"><section className="crm-empty"><h1>Entre no Cozinha 360 primeiro.</h1><a href="/">Voltar ao login</a></section></main>
  if(loading)return <main className="crm-shell center"><b>Organizando clientes…</b></main>
  return <main className="crm-shell"><header className="crm-top"><a href="/"><ArrowLeft size={18}/>Operação</a><b>CRM DE RECOMPRA</b><div><select value={businessId} onChange={async e=>{const id=Number(e.target.value);setBusinessId(id);await load(id)}}>{businesses.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><button onClick={()=>load()}><RefreshCcw size={16}/></button></div></header><section className="crm-page"><div className="crm-hero"><span>CONSENTIMENTO + CICLO DE VIDA</span><h1>Saiba quem acabou de chegar, quem voltou e quem sumiu.</h1><p>O CRM usa pedidos concluídos para criar segmentos simples. Só recomenda contato quando existe consentimento ativo.</p></div>{error&&<div className="crm-error">{error}</div>}<div className="crm-priority"><ShieldCheck/><div><span>PRÓXIMA AÇÃO</span><b>{priority}</b></div></div>{data&&<><div className="crm-metrics"><Metric icon={<Users/>} value={data.summary.total} label="Clientes"/><Metric icon={<UserPlus/>} value={data.summary.new} label="Novos"/><Metric icon={<UserCheck/>} value={data.summary.repeat} label="Recorrentes"/><Metric icon={<UserMinus/>} value={data.summary.dormant} label="Sumidos +30d"/></div><div className="crm-value"><div><span>Receita histórica da base</span><b>{money(data.summary.revenue_cents)}</b></div><div><span>Contribuição histórica</span><b>{money(data.summary.contribution_cents)}</b></div><div><span>Com consentimento</span><b>{data.summary.contactable}</b></div></div><div className="crm-toolbar"><div className="crm-tabs">{[['all','Todos'],['new','Novos'],['repeat','Recorrentes'],['dormant','Sumidos'],['prospect','Sem compra']].map(([id,text])=><button key={id} className={segment===id?'active':''} onClick={()=>setSegment(id)}>{text}</button>)}</div><label><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar cliente"/></label></div><div className="crm-list">{rows.length?rows.map(x=><article key={x.customer_id}><div className="crm-person"><span className={`crm-dot ${x.segment}`}></span><div><b>{x.customer_name}</b><small>{x.phone||x.email||'Sem contato cadastrado'}</small></div></div><div className="crm-history"><span>{x.completed_orders} pedido(s)</span><b>{money(x.contribution_cents)} contribuição</b><small>{x.days_since_last_order==null?'Sem compra concluída':`última compra há ${x.days_since_last_order} dia(s)`}</small></div><div className="crm-status"><span className={`crm-segment ${x.segment}`}>{label[x.segment]}</span><span className={`crm-consent ${x.can_contact?'yes':'no'}`}>{x.can_contact?'Pode contatar':'Não contatar'}</span></div></article>):<div className="crm-empty">Nenhum cliente neste filtro.</div>}</div><small className="crm-note">“Sumido” significa última compra concluída há mais de {data.dormant_days} dias. Segmentação é operacional, não uma previsão de churn.</small></>}</section></main>}
function Metric({icon,value,label}:{icon:React.ReactNode;value:number;label:string}){return <article><i>{icon}</i><div><b>{value}</b><span>{label}</span></div></article>}
