import React,{useEffect,useMemo,useState} from 'react'
import {ArrowLeft,ArrowRight,BadgePercent,Bike,CalendarClock,CheckCircle2,ChefHat,CircleDollarSign,Clock3,ExternalLink,Gift,MapPin,Navigation,Network,PackageCheck,Plus,RefreshCcw,Route,Settings2,ShoppingBag,Store,Truck,Users,WalletCards,WifiOff} from 'lucide-react'
import {money,request} from './app'

const DELIVERY_API=import.meta.env.VITE_DELIVERY_API_URL||'https://npgheuzpnkwtxopswpqy.supabase.co/functions/v1/cozinha360-delivery-v40'
type Tab='agora'|'marcas'|'logistica'|'clientes'|'canais'|'config'
type Brand={id:number;name:string;slug:string|null;active:boolean;primary_channel:string;sort_order:number}
type BrandStat={brand_id:number;orders:number;open_orders:number;revenue_cents:number;contribution_cents:number}
type Channel={id:number;name:string;fee_bps:number;fixed_fee_cents:number;delivery_cents:number;promo_cents:number;media_cents:number;traffic_active:boolean}
type Driver={id:number;name:string;phone:string;vehicle:string;status:string;active:boolean;version:number}
type Zone={id:number;brand_id:number|null;name:string;zone_type:string;match_value:string;fee_cents:number;min_order_cents:number;free_delivery_over_cents?:number;eta_min:number;active:boolean;version:number;center_lat?:number|null;center_lng?:number|null;radius_km?:number|null}
type Delivery={id:number;order_id:number;driver_id:number|null;zone_id:number|null;status:string;fee_cents:number;driver_payout_cents?:number;version:number;promised_at:string|null;scheduled_for?:string|null;address_line?:string|null;neighborhood?:string|null;postal_code?:string|null;ready_at?:string|null;picked_up_at?:string|null;delivered_at?:string|null}
type Storefront={id:number;brand_id:number|null;slug:string;display_name:string;active:boolean}
type Connection={id:number;provider:string;display_name:string|null;status:string;mode:string;last_success_at:string|null;last_error:string|null}
type Order={id:number;brand_id:number|null;channel_id:number|null;customer_id:number|null;status:string;source:string;total_cents:number;contribution_cents:number;paid:boolean;delayed:boolean;error_flag:boolean;version:number;created_at:string;brand:Brand|null;channel:Channel|null;customer:{id:number;name:string}|null;delivery:Delivery|null;items:Array<{id:number;product_id:number;quantity:number;unit_price_cents:number;unit_variable_cost_cents:number}>}
type Plan={plan_key:string;display_name:string;monthly_cents:number;annual_cents:number;online_order_limit:number|null;brand_limit:number;driver_limit:number|null;route_quota:number|null;features_json:Record<string,unknown>}
type Settings={scheduled_orders_enabled:boolean;auto_accept_direct_orders:boolean;route_provider:string;route_optimization_enabled:boolean;customer_tracking_enabled:boolean;whatsapp_status_updates:boolean;brand_crm_isolation:boolean;prep_target_min:number;default_eta_min:number;sla_warning_minutes:number;max_scheduled_days:number}
type CustomerBrand={id:number;brand_id:number;customer_id:number;consent_marketing:boolean;opted_out_at:string|null;first_order_at:string|null;last_order_at:string|null;order_count:number;paid_order_count:number;revenue_cents:number;contribution_cents:number;customer:{id:number;name:string;phone?:string}|null;brand:Brand|null}
type RouteBatch={id:number;zone_id:number|null;driver_id:number|null;provider:string;status:string;distance_meters:number|null;duration_seconds:number|null;version:number;created_at:string;started_at:string|null;completed_at:string|null;stops:Array<{id:number;delivery_id:number;stop_order:number;status:string;address_snapshot:string|null}>}
type LedgerSummary={driver_id:number;name:string;balance_cents:number;entries:number}
type Overview={version:string;business:{id:number;name:string;city:string;currency:string};summary:{open_orders:number;delayed_orders:number;paid_orders:number;revenue_cents:number;contribution_cents:number;available_drivers:number;active_zones:number;scheduled_deliveries?:number;in_transit?:number;overdue_deliveries?:number;open_routes?:number};plan:{key:string;status:string;brand_limit:number;driver_limit?:number|null;route_quota?:number|null};plan_catalog?:Plan[];settings?:Settings;brands:Brand[];brand_stats:BrandStat[];channels:Channel[];orders:Order[];zones:Zone[];drivers:Driver[];deliveries:Delivery[];loyalty:{mode:string;points_per_real:number;cashback_bps:number;redeem_threshold:number;active:boolean};promos:Array<{id:number;brand_id:number|null;code:string;discount_type:string;value:number;min_order_cents:number;used_count:number;active:boolean}>;storefronts:Storefront[];connections:Connection[];customer_brand_profiles?:CustomerBrand[];routes?:RouteBatch[];driver_ledger_summary?:LedgerSummary[]}

async function dreq(path:string,token:string,options:RequestInit={}){const res=await fetch(`${DELIVERY_API}${path}`,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,...(options.headers||{})}});const parsed=await res.json().catch(()=>({detail:'Resposta inválida'}));if(!res.ok)throw new Error(typeof parsed.detail==='string'?parsed.detail:'Não foi possível concluir');return parsed}
const vehicleLabel:Record<string,string>={foot:'A pé',bike:'Bike',moto:'Moto',car:'Carro',utility:'Utilitário'}
const providerLabel:Record<string,string>={whatsapp:'WhatsApp',mercadopago:'Mercado Pago',google:'Google',ifood:'iFood',meta_ads:'Meta Ads'}
const statusLabel:Record<string,string>={waiting:'Aguardando',assigned:'Atribuída',picked_up:'Em rota',delivered:'Entregue',failed:'Falhou',cancelled:'Cancelada',new:'Novo',confirmed:'Confirmado',production:'Produção',checking:'Conferência',awaiting_delivery:'Aguardando entrega',ready:'Pronta',dispatched:'Despachada',completed:'Concluída',draft:'Rascunho'}
const time=(v:string|null|undefined)=>v?new Date(v).toLocaleString('pt-BR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}):'—'

export function DeliveryOSMarketRoute(){
 const token=localStorage.getItem('c360_token')||''
 const[data,setData]=useState<Overview|null>(null),[businessId,setBusinessId]=useState(0),[tab,setTab]=useState<Tab>('agora'),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false)
 const[brandName,setBrandName]=useState(''),[driverName,setDriverName]=useState(''),[driverPhone,setDriverPhone]=useState('')
 const[zone,setZone]=useState({name:'',zone_type:'neighborhood',match_value:'',fee:'',minimum:'',free_over:'',eta:'45'})
 const[selectedDeliveries,setSelectedDeliveries]=useState<number[]>([]),[routeDriver,setRouteDriver]=useState('')
 const[settlement,setSettlement]=useState({driver_id:'',amount:'',note:''})
 const[loyaltyMode,setLoyaltyMode]=useState('off'),[cashback,setCashback]=useState('0'),[points,setPoints]=useState('1'),[promoCode,setPromoCode]=useState(''),[promoValue,setPromoValue]=useState('10')
 const[settings,setSettings]=useState<Settings>({scheduled_orders_enabled:true,auto_accept_direct_orders:false,route_provider:'manual',route_optimization_enabled:false,customer_tracking_enabled:false,whatsapp_status_updates:false,brand_crm_isolation:true,prep_target_min:25,default_eta_min:45,sla_warning_minutes:10,max_scheduled_days:7})
 async function load(){if(!token){window.location.replace('/');return}setLoading(true);setError('');try{const me=await request('/me',{},token),id=Number(me.businesses?.[0]?.id||0);if(!id){window.location.replace('/');return}setBusinessId(id);const next=await dreq(`/businesses/${id}/overview`,token) as Overview;setData(next);setLoyaltyMode(next.loyalty.mode||'off');setCashback(String((next.loyalty.cashback_bps||0)/100));setPoints(String(next.loyalty.points_per_real||1));if(next.settings)setSettings(next.settings)}catch(e){setError(e instanceof Error?e.message:'Delivery 360 indisponível')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[])
 async function mutate(path:string,method:'POST'|'PATCH'|'PUT',payload:unknown,message:string){if(!businessId)return null;setBusy(true);setError('');setNotice('');try{const r=await dreq(`/businesses/${businessId}/${path}`,token,{method,body:JSON.stringify(payload)});setNotice(message);await load();return r}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar');return null}finally{setBusy(false)}}
 const openOrders=useMemo(()=>data?.orders.filter(o=>['new','confirmed','production','checking','awaiting_delivery'].includes(o.status))||[],[data])
 const dispatchable=useMemo(()=>data?.deliveries.filter(d=>!['delivered','cancelled','failed'].includes(d.status))||[],[data])
 const brandStats=new Map((data?.brand_stats||[]).map(r=>[r.brand_id,r]))
 const deliveryById=new Map((data?.deliveries||[]).map(d=>[d.id,d])),driverById=new Map((data?.drivers||[]).map(d=>[d.id,d])),zoneById=new Map((data?.zones||[]).map(z=>[z.id,z]))
 if(loading)return <main className="deliverym-shell deliverym-center"><div className="deliverym-loading"><Truck size={25}/>Organizando o Delivery 360…</div></main>
 if(error&&!data)return <main className="deliverym-shell deliverym-center"><section className="deliverym-error"><WifiOff/><h1>O Delivery 360 não carregou.</h1><p>{error}</p><button onClick={()=>void load()}><RefreshCcw size={16}/>Tentar novamente</button></section></main>
 if(!data)return null
 const plans=data.plan_catalog||[]
 return <main className="deliverym-shell"><header className="deliverym-top"><a href="/?today=1"><ArrowLeft size={16}/>Hoje</a><a href="/" className="deliverym-logo"><ChefHat size={20}/><b>COZINHA 360</b><span>Delivery 4.1</span></a><div><small>{data.business.name}</small><button onClick={()=>void load()} aria-label="Atualizar"><RefreshCcw size={15}/></button></div></header>
  <section className="deliverym-page"><header className="deliverym-hero"><div><span>DARK KITCHEN · VENDA DIRETA · LOGÍSTICA</span><h1>Controle a cozinha inteira sem virar refém de um ERP pesado.</h1><p>Marca, margem, pedido, entrega e recompra no mesmo fluxo. Recursos de terceiros só aparecem como ativos quando a conexão é real.</p></div><aside><small>PLANO ATUAL</small><b>{data.plan.key.toUpperCase()}</b><span>{data.brands.length}/{data.plan.brand_limit} marcas · {data.plan.route_quota||0} rotas incluídas</span></aside></header>
  {notice&&<div className="deliverym-notice"><CheckCircle2 size={16}/>{notice}</div>}{error&&<div className="deliverym-alert">{error}</div>}
  <nav className="deliverym-tabs">{([['agora','Agora',Route],['marcas','Marcas',Store],['logistica','Logística',Truck],['clientes','Recompra',Users],['canais','Canais & planos',Network],['config','Configurar',Settings2]] as [Tab,string,React.ElementType][]).map(([id,label,Icon])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><Icon size={16}/>{label}</button>)}</nav>

  {tab==='agora'&&<><div className="deliverym-kpis"><Kpi label="Pedidos abertos" value={String(data.summary.open_orders)} hint={data.summary.delayed_orders?`${data.summary.delayed_orders} atrasado(s)`:'sem atraso de pedido'}/><Kpi label="Em rota" value={String(data.summary.in_transit||0)} hint={`${data.summary.overdue_deliveries||0} entrega(s) fora do SLA`}/><Kpi label="Agendados" value={String(data.summary.scheduled_deliveries||0)} hint="janela futura"/><Kpi label="Contribuição paga" value={money(data.summary.contribution_cents)} hint={`${data.summary.paid_orders} pedido(s) pago(s)`}/></div>
   <section className="deliverym-panel"><SectionHead kicker="FILA DE DECISÃO" title="O que precisa acontecer agora" action={<a href="/?quick=1">+ Pedido rápido</a>}/>{openOrders.length?<div className="deliverym-orders">{openOrders.map(order=><OrderRow key={order.id} order={order} data={data} busy={busy} save={p=>void mutate(`deliveries/${order.id}`,'PUT',p,'Entrega atualizada.')}/>)}</div>:<Empty icon={PackageCheck} title="Fila limpa" text="Pedidos diretos, manuais ou integrados aparecem aqui com marca, canal, contribuição e entrega."/>}</section>
   {(data.deliveries||[]).some(d=>d.scheduled_for)&&<section className="deliverym-panel"><SectionHead kicker="AGENDA" title="Pedidos programados"/ ><div className="deliverym-schedule">{data.deliveries.filter(d=>d.scheduled_for&&!['delivered','cancelled'].includes(d.status)).slice(0,10).map(d=><article key={d.id}><CalendarClock size={17}/><div><b>Pedido #{d.order_id}</b><span>{d.neighborhood||d.postal_code||'Endereço a confirmar'}</span></div><strong>{time(d.scheduled_for)}</strong></article>)}</div></section>}
  </>}

  {tab==='marcas'&&<div className="deliverym-grid"><section className="deliverym-panel"><SectionHead kicker="MULTI-BRAND" title="Marcas da mesma cozinha" meta={`${data.brands.length}/${data.plan.brand_limit}`}/>{data.brands.length?<div className="deliverym-brand-list">{data.brands.map(b=>{const s=brandStats.get(b.id),store=data.storefronts.find(x=>x.brand_id===b.id);return <article key={b.id}><span className="deliverym-avatar">{b.name.slice(0,2).toUpperCase()}</span><div><b>{b.name}</b><small>{b.slug||'sem slug'} · {b.active?'ativa':'pausada'}</small></div><div className="deliverym-mini"><span><b>{s?.open_orders||0}</b> abertos</span><span><b>{money(s?.contribution_cents||0)}</b> contribuição</span></div>{store?<a href={`/?loja=${encodeURIComponent(store.slug)}`} target="_blank" rel="noreferrer">Loja <ExternalLink size={13}/></a>:<a href="/?direct=1">Criar loja</a>}</article>})}</div>:<Empty icon={Store} title="Comece com uma marca âncora" text="O sistema já separa pedidos, métricas, vitrine e CRM por marca sem misturar a operação consolidada."/>}</section><aside className="deliverym-panel deliverym-form"><span>NOVA MARCA</span><h2>Adicionar marca</h2><label>Nome<input value={brandName} onChange={e=>setBrandName(e.target.value)} placeholder="Ex.: Brasa 360"/></label><button disabled={busy||brandName.trim().length<2} onClick={async()=>{const ok=await mutate('brands','POST',{name:brandName},'Marca criada.');if(ok)setBrandName('')}}><Plus size={16}/>Criar marca</button><p>Os limites comerciais permanecem em observação até cobrança real e recuperação de pagamento estarem validadas.</p></aside></div>}

  {tab==='logistica'&&<><div className="deliverym-grid"><section className="deliverym-panel"><SectionHead kicker="ENTREGADORES" title="Disponibilidade e acerto" meta={`${data.summary.available_drivers} livres`}/>{data.drivers.length?<div className="deliverym-drivers">{data.drivers.map(d=>{const balance=data.driver_ledger_summary?.find(x=>x.driver_id===d.id)?.balance_cents||0;return <article key={d.id}><span className={`deliverym-dot ${d.status}`}></span><div><b>{d.name}</b><small>{vehicleLabel[d.vehicle]||d.vehicle} · {d.phone||'sem telefone'}</small></div><strong>{money(balance)}</strong><select value={d.status} disabled={busy} onChange={e=>void mutate(`drivers/${d.id}`,'PATCH',{version:d.version,status:e.target.value},'Status atualizado.')}><option value="available">Disponível</option><option value="busy">Em entrega</option><option value="offline">Offline</option></select></article>})}</div>:<Empty icon={Bike} title="Cadastre quem entrega" text="A pé, bike, moto, carro ou utilitário. O saldo do entregador é separado da taxa cobrada do cliente."/>}<div className="deliverym-inline"><input value={driverName} onChange={e=>setDriverName(e.target.value)} placeholder="Nome"/><input value={driverPhone} onChange={e=>setDriverPhone(e.target.value)} placeholder="Telefone"/><button disabled={busy||!driverName.trim()} onClick={async()=>{const ok=await mutate('drivers','POST',{name:driverName,phone:driverPhone,vehicle:'moto',status:'available'},'Entregador adicionado.');if(ok){setDriverName('');setDriverPhone('')}}}><Plus size={15}/>Adicionar</button></div></section>
   <section className="deliverym-panel"><SectionHead kicker="ZONAS & TAXAS" title="Onde vale a pena entregar?" meta={`${data.summary.active_zones} ativas`}/>{data.zones.length?<div className="deliverym-zones">{data.zones.map(z=><article key={z.id}><div><b>{z.name}</b><small>{z.match_value||z.zone_type} · até {z.eta_min} min{z.min_order_cents?` · mínimo ${money(z.min_order_cents)}`:''}</small></div><strong>{money(z.fee_cents)}</strong>{(z.free_delivery_over_cents||0)>0&&<em>grátis ≥ {money(z.free_delivery_over_cents||0)}</em>}</article>)}</div>:<Empty icon={MapPin} title="Defina uma região simples" text="Bairro ou CEP funcionam sem API externa. Raio e rota otimizada exigem coordenadas/provedor compatível."/>}<div className="deliverym-zone-form"><input value={zone.name} onChange={e=>setZone({...zone,name:e.target.value})} placeholder="Centro"/><select value={zone.zone_type} onChange={e=>setZone({...zone,zone_type:e.target.value})}><option value="neighborhood">Bairro</option><option value="cep">CEP</option></select><input value={zone.match_value} onChange={e=>setZone({...zone,match_value:e.target.value})} placeholder={zone.zone_type==='cep'?'08700':'Centro'}/><input value={zone.fee} onChange={e=>setZone({...zone,fee:e.target.value})} placeholder="Taxa R$"/><input value={zone.minimum} onChange={e=>setZone({...zone,minimum:e.target.value})} placeholder="Mínimo R$"/><input value={zone.free_over} onChange={e=>setZone({...zone,free_over:e.target.value})} placeholder="Frete grátis ≥ R$"/><button disabled={busy||!zone.name.trim()} onClick={async()=>{const toC=(v:string)=>Math.max(0,Math.round((Number(v.replace(',','.'))||0)*100)),ok=await mutate('zones','POST',{name:zone.name,zone_type:zone.zone_type,match_value:zone.match_value,fee_cents:toC(zone.fee),min_order_cents:toC(zone.minimum),free_delivery_over_cents:toC(zone.free_over),eta_min:Number(zone.eta)||45},'Zona criada.');if(ok)setZone({name:'',zone_type:'neighborhood',match_value:'',fee:'',minimum:'',free_over:'',eta:'45'})}><Plus size={15}/>Criar</button></div></section></div>
   <div className="deliverym-grid"><section className="deliverym-panel"><SectionHead kicker="ROTAS" title="Agrupe entregas antes de sair" meta={`${data.summary.open_routes||0} abertas`}/>{dispatchable.length?<div className="deliverym-route-builder"><div className="deliverym-select-deliveries">{dispatchable.slice(0,30).map(d=><label key={d.id}><input type="checkbox" checked={selectedDeliveries.includes(d.id)} onChange={e=>setSelectedDeliveries(prev=>e.target.checked?[...prev,d.id]:prev.filter(x=>x!==d.id))}/><span><b>#{d.order_id}</b><small>{d.neighborhood||d.address_line||'Endereço pendente'} · {statusLabel[d.status]||d.status}</small></span></label>)}</div><div className="deliverym-route-actions"><select value={routeDriver} onChange={e=>setRouteDriver(e.target.value)}><option value="">Escolher entregador</option>{data.drivers.filter(d=>d.active).map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select><button disabled={busy||!selectedDeliveries.length} onClick={async()=>{const ok=await mutate('routes','POST',{delivery_ids:selectedDeliveries,driver_id:routeDriver?Number(routeDriver):null,optimize:false},'Rota manual criada.');if(ok){setSelectedDeliveries([]);setRouteDriver('')}}}><Route size={16}/>Montar rota manual</button></div><small>Otimização automática e GPS só serão ativados depois que um provedor de mapas estiver conectado e validado.</small></div>:<Empty icon={Navigation} title="Sem entregas para agrupar" text="Quando houver pedidos aguardando despacho, você pode criar uma rota manual por zona e entregador."/>}</section>
   <section className="deliverym-panel"><SectionHead kicker="ROTAS ATIVAS" title="Despacho sem tablet perdido"/>{data.routes?.length?<div className="deliverym-routes">{data.routes.slice(0,12).map(r=><article key={r.id}><div><b>Rota #{r.id}</b><small>{r.stops.length} parada(s) · {driverById.get(Number(r.driver_id))?.name||'sem entregador'}</small></div><span>{statusLabel[r.status]||r.status}</span><div className="deliverym-stops">{r.stops.slice(0,5).map(s=><small key={s.id}>{s.stop_order}. Pedido #{deliveryById.get(s.delivery_id)?.order_id||'—'} · {s.address_snapshot||'endereço'}</small>)}</div>{['ready','draft'].includes(r.status)&&<button disabled={busy} onClick={()=>void mutate(`routes/${r.id}`,'PATCH',{version:r.version,status:'dispatched'},'Rota despachada.')}><ArrowRight size={14}/>Despachar</button>}</article>)}</div>:<Empty icon={Route} title="Nenhuma rota criada" text="A sequência de paradas fica registrada e auditável. Otimização por mapa continua desacoplada."/>}</section></div>
   <section className="deliverym-panel"><SectionHead kicker="ACERTO" title="Pagar entregador sem misturar com frete do cliente"/ ><div className="deliverym-settlement"><select value={settlement.driver_id} onChange={e=>setSettlement({...settlement,driver_id:e.target.value})}><option value="">Entregador</option>{data.drivers.map(d=><option key={d.id} value={d.id}>{d.name} · saldo {money(data.driver_ledger_summary?.find(x=>x.driver_id===d.id)?.balance_cents||0)}</option>)}</select><input value={settlement.amount} onChange={e=>setSettlement({...settlement,amount:e.target.value})} placeholder="Valor pago R$" inputMode="decimal"/><input value={settlement.note} onChange={e=>setSettlement({...settlement,note:e.target.value})} placeholder="Observação"/><button disabled={busy||!settlement.driver_id||!settlement.amount} onClick={async()=>{const cents=Math.round((Number(settlement.amount.replace(',','.'))||0)*100),ok=await mutate('driver-ledger','POST',{driver_id:Number(settlement.driver_id),entry_type:'payment',amount_cents:cents,note:settlement.note},'Pagamento registrado.');if(ok)setSettlement({driver_id:'',amount:'',note:''})}}><WalletCards size={16}/>Registrar pagamento</button></div></section>
  </>}

  {tab==='clientes'&&<div className="deliverym-grid"><section className="deliverym-panel"><SectionHead kicker="CRM POR MARCA" title="Cliente da Marca A não vira lead da Marca B" meta={`${data.customer_brand_profiles?.length||0} perfis`}/>{data.customer_brand_profiles?.length?<div className="deliverym-crm">{data.customer_brand_profiles.slice(0,80).map(p=><article key={p.id}><div><b>{p.customer?.name||`Cliente #${p.customer_id}`}</b><small>{p.brand?.name||`Marca #${p.brand_id}`} · {p.order_count} pedido(s) · última {time(p.last_order_at)}</small></div><strong>{money(p.contribution_cents)}</strong><label><input type="checkbox" checked={p.consent_marketing} onChange={e=>void mutate(`customer-brands/${p.id}`,'PATCH',{consent_marketing:e.target.checked},e.target.checked?'Consentimento ativado.':'Opt-out registrado.')}/><span>{p.consent_marketing?'Pode receber ofertas':'Sem marketing'}</span></label></article>)}</div>:<Empty icon={Users} title="CRM nasce dos pedidos" text="Quando pedidos com marca e cliente entrarem, frequência, receita, contribuição e consentimento ficam separados por marca."/>}</section>
   <aside className="deliverym-panel deliverym-form"><span>FIDELIDADE</span><h2>Recompra com margem</h2><label>Modelo<select value={loyaltyMode} onChange={e=>setLoyaltyMode(e.target.value)}><option value="off">Desligado</option><option value="points">Pontos</option><option value="cashback">Cashback</option></select></label>{loyaltyMode==='points'&&<label>Pontos por R$1<input value={points} onChange={e=>setPoints(e.target.value)}/></label>}{loyaltyMode==='cashback'&&<label>Cashback %<input value={cashback} onChange={e=>setCashback(e.target.value)}/></label>}<button disabled={busy} onClick={()=>void mutate('loyalty','PUT',{mode:loyaltyMode,active:loyaltyMode!=='off',points_per_real:Number(points.replace(',','.'))||1,cashback_bps:Math.round((Number(cashback.replace(',','.'))||0)*100)},'Fidelidade atualizada.')}><Gift size={16}/>Salvar fidelidade</button><hr/><span>CUPOM</span><label>Código<input value={promoCode} onChange={e=>setPromoCode(e.target.value.toUpperCase())} placeholder="VOLTA10"/></label><label>Desconto %<input value={promoValue} onChange={e=>setPromoValue(e.target.value)}/></label><button disabled={busy||promoCode.length<3} onClick={async()=>{const ok=await mutate('promos','POST',{code:promoCode,discount_type:'percent',value:Math.max(0,Math.round(Number(promoValue)||0)),min_order_cents:0},'Cupom criado.');if(ok)setPromoCode('')}}><BadgePercent size={16}/>Criar cupom</button></aside></div>}

  {tab==='canais'&&<><div className="deliverym-grid"><section className="deliverym-panel"><SectionHead kicker="CONEXÕES REAIS" title="Omnicanal sem fingir integração"/ ><div className="deliverym-connections">{['whatsapp','mercadopago','ifood','google','meta_ads'].map(provider=>{const c=data.connections.find(x=>x.provider===provider),ok=c?.status==='active';return <article key={provider}><span className={ok?'ok':''}>{ok?<CheckCircle2 size={16}/>:<Clock3 size={16}/>}</span><div><b>{providerLabel[provider]||provider}</b><small>{ok?(c?.display_name||'Conectado'):'Requer configuração'}</small></div><em>{ok?'ATIVO':'CONFIGURAR'}</em></article>})}</div><a className="deliverym-link" href="/?connections=1">Abrir central de conexões <ArrowRight size={14}/></a></section><section className="deliverym-panel"><SectionHead kicker="CANAL PRÓPRIO" title="Venda direta sem comissão do Cozinha 360"/ ><p className="deliverym-muted">Gateway, marketplaces, WhatsApp, mapas e logística de terceiros podem cobrar taxas próprias. Elas não são escondidas na mensalidade.</p>{data.storefronts.length?<div className="deliverym-storefronts">{data.storefronts.map(s=><a key={s.id} href={`/?loja=${encodeURIComponent(s.slug)}`} target="_blank" rel="noreferrer"><ShoppingBag size={16}/><span><b>{s.display_name}</b><small>/{s.slug}</small></span><ExternalLink size={14}/></a>)}</div>:<Empty icon={Store} title="Nenhuma vitrine publicada" text="Crie o link próprio e valide preço, zona e margem antes de divulgar."/>}<a className="deliverym-link" href="/?direct=1">Configurar venda direta <ArrowRight size={14}/></a></section></div>
   <section className="deliverym-panel"><SectionHead kicker="PLANOS COZINHA 360" title="Preço previsível, APIs variáveis separadas"/>{plans.length?<div className="deliverym-plans">{plans.map(p=><article key={p.plan_key} className={p.plan_key===data.plan.key?'current':''}><span>{p.display_name}</span><h3>{p.monthly_cents===0?'Grátis':`${money(p.monthly_cents)}/mês`}</h3><small>{p.annual_cents?`${money(p.annual_cents)}/ano`:p.online_order_limit?`até ${p.online_order_limit} pedidos online/mês`:'sem anuidade'}</small><ul><li>{p.brand_limit} marca(s)</li><li>{p.driver_limit==null?'entregadores flexíveis':`${p.driver_limit} entregador(es)`}</li><li>{p.route_quota?`${p.route_quota} rotas/mês`:'roteamento manual'}</li></ul>{p.plan_key===data.plan.key&&<b>PLANO ATUAL</b>}</article>)}</div>:<Empty icon={CircleDollarSign} title="Catálogo comercial ainda não carregou" text="O servidor mantém os preços e limites fora do navegador."/>}</section>
  </>}

  {tab==='config'&&<div className="deliverym-grid"><section className="deliverym-panel"><SectionHead kicker="SLA & EXPERIÊNCIA" title="Regras simples para o cliente receber no prazo"/ ><div className="deliverym-settings"><Toggle label="Aceitar pedidos agendados" text={`Janela de até ${settings.max_scheduled_days} dia(s)`} checked={settings.scheduled_orders_enabled} onChange={v=>setSettings({...settings,scheduled_orders_enabled:v})}/><Toggle label="Rastreamento do cliente" text="Mostra status; mapa só com provedor compatível" checked={settings.customer_tracking_enabled} onChange={v=>setSettings({...settings,customer_tracking_enabled:v})}/><Toggle label="CRM isolado por marca" text="Consentimento e relacionamento separados" checked={settings.brand_crm_isolation} onChange={v=>setSettings({...settings,brand_crm_isolation:v})}/><Toggle label="Status via WhatsApp" text="Só envia quando a conexão oficial estiver ativa" checked={settings.whatsapp_status_updates} onChange={v=>setSettings({...settings,whatsapp_status_updates:v})}/></div><div className="deliverym-number-settings"><label>Meta de preparo (min)<input type="number" value={settings.prep_target_min} onChange={e=>setSettings({...settings,prep_target_min:Number(e.target.value)})}/></label><label>ETA padrão (min)<input type="number" value={settings.default_eta_min} onChange={e=>setSettings({...settings,default_eta_min:Number(e.target.value)})}/></label><label>Alerta antes do SLA (min)<input type="number" value={settings.sla_warning_minutes} onChange={e=>setSettings({...settings,sla_warning_minutes:Number(e.target.value)})}/></label><label>Agendar até (dias)<input type="number" value={settings.max_scheduled_days} onChange={e=>setSettings({...settings,max_scheduled_days:Number(e.target.value)})}/></label></div><button className="deliverym-primary" disabled={busy} onClick={()=>void mutate('settings','PUT',settings,'Configurações salvas.')}><CheckCircle2 size={16}/>Salvar regras do delivery</button></section>
   <aside className="deliverym-panel"><SectionHead kicker="ROTEAMENTO" title="Provider-neutral por projeto"/ ><div className="deliverym-provider"><Navigation size={24}/><div><b>{settings.route_provider==='manual'?'Manual':settings.route_provider}</b><span>{settings.route_provider==='manual'?'Nenhuma API de mapas conectada':'Provider configurado no servidor'}</span></div></div><p className="deliverym-muted">Enquanto o provider estiver em “manual”, o Cozinha 360 permite agrupar e despachar paradas, mas não chama isso de rota ótima nem exibe GPS em tempo real.</p><a className="deliverym-link" href="/?connections=1">Conectar serviços <ArrowRight size={14}/></a></aside></div>}
  </section></main>
}

function Kpi({label,value,hint}:{label:string;value:string;hint:string}){return <article className="deliverym-kpi"><span>{label}</span><strong>{value}</strong><small>{hint}</small></article>}
function SectionHead({kicker,title,meta,action}:{kicker:string;title:string;meta?:string;action?:React.ReactNode}){return <header className="deliverym-section-head"><div><span>{kicker}</span><h2>{title}</h2></div>{action||<b>{meta||''}</b>}</header>}
function Empty({icon:Icon,title,text}:{icon:React.ElementType;title:string;text:string}){return <div className="deliverym-empty"><Icon size={28}/><b>{title}</b><span>{text}</span></div>}
function Toggle({label,text,checked,onChange}:{label:string;text:string;checked:boolean;onChange:(v:boolean)=>void}){return <label className="deliverym-toggle"><span><b>{label}</b><small>{text}</small></span><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/><i></i></label>}
function OrderRow({order,data,busy,save}:{order:Order;data:Overview;busy:boolean;save:(p:unknown)=>void}){const [driver,setDriver]=useState(String(order.delivery?.driver_id||'')),[zone,setZone]=useState(String(order.delivery?.zone_id||'')),[status,setStatus]=useState(order.delivery?.status||'waiting'),[payout,setPayout]=useState(order.delivery?.driver_payout_cents?String((order.delivery.driver_payout_cents/100).toFixed(2).replace('.',',')):'');return <article className={`deliverym-order ${order.delayed?'delayed':''}`}><div><span>#{order.id}</span><b>{order.brand?.name||'Sem marca'}</b><small>{order.channel?.name||order.source}</small></div><div><b>{order.customer?.name||'Cliente não identificado'}</b><small>{statusLabel[order.status]||order.status} · {time(order.created_at)}</small></div><div className="deliverym-order-money"><b>{money(order.total_cents)}</b><small>{money(order.contribution_cents)} contribuição</small></div><div className="deliverym-dispatch"><select value={zone} onChange={e=>setZone(e.target.value)}><option value="">Zona</option>{data.zones.filter(z=>z.active).map(z=><option key={z.id} value={z.id}>{z.name}</option>)}</select><select value={driver} onChange={e=>setDriver(e.target.value)}><option value="">Entregador</option>{data.drivers.filter(d=>d.active).map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="waiting">Aguardando</option><option value="assigned">Atribuída</option><option value="picked_up">Em rota</option><option value="delivered">Entregue</option><option value="failed">Falhou</option></select><input value={payout} onChange={e=>setPayout(e.target.value)} placeholder="Repasse R$"/><button disabled={busy} onClick={()=>save({version:order.delivery?.version,driver_id:driver?Number(driver):null,zone_id:zone?Number(zone):null,status,fee_cents:order.delivery?.fee_cents||0,driver_payout_cents:Math.round((Number(payout.replace(',','.'))||0)*100)})}>Salvar</button></div></article>}
