import React,{useEffect,useMemo,useState} from 'react'
import {ArrowLeft,BarChart3,Bike,CalendarClock,CheckCircle2,Clock3,ExternalLink,MapPin,Minus,Navigation,Plus,RefreshCcw,ShieldCheck,ShoppingBag,Store,Target,TicketPercent,Truck} from 'lucide-react'
import {money,request} from './app'
import {PixCheckoutExperience} from './pix-checkout-experience'

const DIRECT_API=import.meta.env.VITE_DIRECT_API_URL||'https://npgheuzpnkwtxopswpqy.supabase.co/functions/v1/cozinha360-direct-v17'

type Biz={id:number;name:string;city:string;role:string}
type Product={id:number;name:string;category:string;brand_id:number|null;sale_price_cents:number}
type Fulfillment={pickup:boolean;delivery:boolean;scheduled_orders:boolean;max_scheduled_days:number;customer_tracking:boolean}
type PublicStore={storefront:{id:number;slug:string;display_name:string;brand_id:number|null;channel_id:number};business:{id:number;name:string;city:string;currency:string};brand:{id:number;name:string}|null;products:Product[];fulfillment:Fulfillment}
type Quote={items:Array<{product_id:number;quantity:number}>;fulfillment:'delivery'|'pickup';subtotal_cents:number;zone:{id:number;name:string;eta_min:number;fee_cents:number;free_delivery_over_cents:number;min_order_cents:number}|null;base_delivery_fee_cents:number;delivery_fee_cents:number;discount_cents:number;promo:{id:number;code:string;discount_type:string;value:number}|null;total_cents:number;scheduled_for:string|null}
type CheckoutResult={id:number;total_cents:number;subtotal_cents?:number;delivery_fee_cents?:number;discount_cents?:number;promised_at?:string|null;tracking_url?:string|null}
type Tracking={status:string;promised_at:string|null;scheduled_for:string|null;ready_at:string|null;picked_up_at:string|null;delivered_at:string|null;order_id:number;brand:string|null}
type Storefront={id:number;business_id:number;brand_id:number|null;channel_id:number;slug:string;display_name:string;active:boolean;brands?:{name:string}|null;channels?:{name:string}|null}
type Campaign={utm_source:string;utm_medium:string;utm_campaign:string;orders:number;revenue_cents:number;media_cost_cents:number;contribution_after_media_cents:number;revenue_per_media:number|null;contribution_per_media:number|null}
type Attribution={days:number;summary:{orders:number;revenue_cents:number;media_cost_cents:number;contribution_after_media_cents:number};campaigns:Campaign[]}

async function direct(path:string,options:RequestInit={},token=''){
  const res=await fetch(`${DIRECT_API}${path}`,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{ }),...(options.headers||{})}})
  const parsed=await res.json().catch(()=>({detail:'Resposta inválida'}))
  if(!res.ok)throw new Error(typeof parsed.detail==='string'?parsed.detail:'Não foi possível concluir')
  return parsed
}
function sessionKey(){const key='c360_direct_session',existing=sessionStorage.getItem(key);if(existing)return existing;const next=globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}`;sessionStorage.setItem(key,next);return next}
function newOrderKey(){return globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}`}
function dateTimeLabel(value:string|null|undefined){if(!value)return '—';const d=new Date(value);return Number.isNaN(d.getTime())?'—':d.toLocaleString('pt-BR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}
const trackingLabels:Record<string,string>={waiting:'Pedido recebido',assigned:'Entregador definido',picked_up:'Saiu para entrega',delivered:'Entregue',failed:'Problema na entrega',cancelled:'Entrega cancelada'}

export function PublicStorefrontRoute({slug}:{slug:string}){
  const [data,setData]=useState<PublicStore|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('')
  const [cart,setCart]=useState<Record<number,number>>({}),[sending,setSending]=useState(false),[quoting,setQuoting]=useState(false),[quote,setQuote]=useState<Quote|null>(null),[quoteError,setQuoteError]=useState('')
  const [success,setSuccess]=useState<CheckoutResult|null>(null),[orderKey,setOrderKey]=useState(newOrderKey),[paymentKey,setPaymentKey]=useState('')
  const [form,setForm]=useState({name:'',phone:'',email:'',consent:false,fulfillment:'pickup' as 'pickup'|'delivery',address_line:'',neighborhood:'',postal_code:'',address_reference:'',promo_code:'',scheduled_for:''})
  useEffect(()=>{direct(`/store/${encodeURIComponent(slug)}`).then((next:PublicStore)=>{setData(next);if(next.fulfillment.delivery&&!next.fulfillment.pickup)setForm(v=>({...v,fulfillment:'delivery'}))}).catch(e=>setError(e instanceof Error?e.message:'Loja indisponível')).finally(()=>setLoading(false))},[slug])
  const subtotal=useMemo(()=>data?.products.reduce((sum,p)=>sum+(cart[p.id]||0)*p.sale_price_cents,0)||0,[data,cart])
  const count=useMemo(()=>Object.values(cart).reduce((a,b)=>a+b,0),[cart])
  const cartItems=useMemo(()=>Object.entries(cart).filter(([,q])=>q>0).map(([product_id,quantity])=>({product_id:Number(product_id),quantity})),[cart])
  function qty(id:number,delta:number){setCart(prev=>({...prev,[id]:Math.max(0,Math.min(20,(prev[id]||0)+delta))}));setQuote(null);setQuoteError('')}
  function quotePayload(){return{items:cartItems,fulfillment:form.fulfillment,address_line:form.address_line,neighborhood:form.neighborhood,postal_code:form.postal_code,address_reference:form.address_reference,promo_code:form.promo_code,scheduled_for:form.scheduled_for||null}}
  async function refreshQuote(){if(!data||!count)return null;if(form.fulfillment==='delivery'&&!form.neighborhood.trim()&&!form.postal_code.trim()){setQuote(null);setQuoteError('Informe bairro ou CEP para calcular a entrega.');return null}setQuoting(true);setQuoteError('');try{const q=await direct(`/store/${encodeURIComponent(slug)}/quote`,{method:'POST',body:JSON.stringify(quotePayload())}) as Quote;setQuote(q);return q}catch(e){setQuote(null);setQuoteError(e instanceof Error?e.message:'Não foi possível calcular o pedido');return null}finally{setQuoting(false)}}
  useEffect(()=>{if(!count){setQuote(null);setQuoteError('');return}const timer=window.setTimeout(()=>{void refreshQuote()},420);return()=>window.clearTimeout(timer)},[count,form.fulfillment,form.neighborhood,form.postal_code,form.promo_code,form.scheduled_for])
  async function checkout(e:React.FormEvent){e.preventDefault();if(!data||count===0)return;setSending(true);setError('');const q=await refreshQuote();if(!q){setSending(false);return}const usedOrderKey=orderKey;try{const qs=new URLSearchParams(location.search),result=await direct(`/store/${encodeURIComponent(slug)}`,{method:'POST',body:JSON.stringify({...quotePayload(),client_order_key:usedOrderKey,customer_name:form.name,phone:form.phone,email:form.email,consent_marketing:form.consent,attribution:{session_key:sessionKey(),referrer:document.referrer||null,utm_source:qs.get('utm_source'),utm_medium:qs.get('utm_medium'),utm_campaign:qs.get('utm_campaign'),utm_content:qs.get('utm_content'),utm_term:qs.get('utm_term'),gclid:qs.get('gclid'),fbclid:qs.get('fbclid'),ttclid:qs.get('ttclid')}})}) as CheckoutResult;setSuccess(result);setPaymentKey(usedOrderKey);setCart({});setQuote(null);setOrderKey(newOrderKey())}catch(e){setError(e instanceof Error?e.message:'Não foi possível enviar o pedido')}finally{setSending(false)}}
  if(loading)return <main className="direct-public center"><b>Carregando cardápio…</b></main>
  if(error&&!data)return <main className="direct-public center"><section className="direct-message"><h1>Loja indisponível</h1><p>{error}</p></section></main>
  if(!data)return null
  const finalTotal=quote?.total_cents??subtotal
  return <main className="direct-public">
    <header className="direct-store-head"><div><span>PEDIDO DIRETO · SEM COMISSÃO DO COZINHA 360</span><h1>{data.storefront.display_name}</h1><p>{data.brand?.name||data.business.name}{data.business.city?` · ${data.business.city}`:''}</p></div><div className="direct-bag"><ShoppingBag size={18}/><b>{count}</b></div></header>
    <section className="direct-store-body">
      <div className="direct-trust-strip"><span><ShieldCheck size={15}/>Preço confirmado no servidor</span><span><MapPin size={15}/>Taxa por região</span><span><Clock3 size={15}/>ETA da própria cozinha</span></div>
      {success&&<div className="direct-success"><CheckCircle2/><div><b>Pedido #{success.id} recebido</b><span>Total {money(success.total_cents)}{success.promised_at?` · previsão ${dateTimeLabel(success.promised_at)}`:''}.</span>{success.tracking_url&&<a href={success.tracking_url}>Acompanhar entrega <Navigation size={13}/></a>}</div></div>}
      {success&&paymentKey&&<PixCheckoutExperience businessId={data.business.id} orderId={success.id} clientOrderKey={paymentKey} payerEmail={form.email} amountCents={success.total_cents}/>} 
      {error&&<div className="direct-error">{error}</div>}
      <div className="direct-products">{data.products.map(p=><article className="direct-product" key={p.id}><div><small>{p.category||'Cardápio'}</small><h2>{p.name}</h2><b>{money(p.sale_price_cents)}</b></div><div className="direct-qty"><button type="button" onClick={()=>qty(p.id,-1)} aria-label={`Remover ${p.name}`}><Minus size={17}/></button><strong>{cart[p.id]||0}</strong><button type="button" onClick={()=>qty(p.id,1)} aria-label={`Adicionar ${p.name}`}><Plus size={17}/></button></div></article>)}</div>
      {data.products.length===0&&<div className="direct-message"><h2>Cardápio em preparação</h2><p>A cozinha ainda não publicou preços neste canal.</p></div>}
      {count>0&&<form className="direct-checkout" onSubmit={checkout}>
        <div className="direct-checkout-title"><div><span>SEU PEDIDO</span><b>{count} item(ns)</b></div><strong>{money(finalTotal)}</strong></div>
        {(data.fulfillment.delivery||data.fulfillment.pickup)&&<div className="direct-fulfillment">{data.fulfillment.pickup&&<button type="button" className={form.fulfillment==='pickup'?'active':''} onClick={()=>{setForm({...form,fulfillment:'pickup'});setQuote(null)}}><Store size={16}/><span><b>Retirar</b><small>Sem taxa de entrega</small></span></button>}{data.fulfillment.delivery&&<button type="button" className={form.fulfillment==='delivery'?'active':''} onClick={()=>{setForm({...form,fulfillment:'delivery'});setQuote(null)}}><Truck size={16}/><span><b>Entrega</b><small>Taxa calculada pela região</small></span></button>}</div>}
        {form.fulfillment==='delivery'&&<section className="direct-delivery-fields"><div className="direct-section-label"><MapPin size={15}/><b>Onde entregar?</b></div><label>Endereço<input value={form.address_line} onChange={e=>setForm({...form,address_line:e.target.value})} placeholder="Rua, número" required maxLength={300}/></label><div className="direct-form-grid"><label>Bairro<input value={form.neighborhood} onChange={e=>setForm({...form,neighborhood:e.target.value})} placeholder="Centro" maxLength={120}/></label><label>CEP<input value={form.postal_code} onChange={e=>setForm({...form,postal_code:e.target.value})} inputMode="numeric" placeholder="00000-000" maxLength={20}/></label></div><label>Referência <span>opcional</span><input value={form.address_reference} onChange={e=>setForm({...form,address_reference:e.target.value})} placeholder="Ex.: portaria B" maxLength={220}/></label></section>}
        <div className="direct-form-grid direct-commerce-tools"><label><span><TicketPercent size={14}/>Cupom</span><input value={form.promo_code} onChange={e=>setForm({...form,promo_code:e.target.value.toUpperCase()})} placeholder="VOLTA10" maxLength={40}/></label>{data.fulfillment.scheduled_orders?<label><span><CalendarClock size={14}/>Agendar <em>opcional</em></span><input type="datetime-local" value={form.scheduled_for} onChange={e=>setForm({...form,scheduled_for:e.target.value})}/></label>:<div className="direct-tool-disabled"><CalendarClock size={15}/><span>Agendamento não habilitado</span></div>}</div>
        {(quote||quoteError||quoting)&&<div className={`direct-quote ${quoteError?'bad':''}`}>{quoting?<span>Calculando preço e entrega…</span>:quote?<><div><span>Itens</span><b>{money(quote.subtotal_cents)}</b></div>{quote.fulfillment==='delivery'&&<div><span>{quote.zone?.name||'Entrega'} · até {quote.zone?.eta_min||'—'} min</span><b>{quote.delivery_fee_cents===0?'Grátis':money(quote.delivery_fee_cents)}</b></div>}{quote.discount_cents>0&&<div className="discount"><span>Desconto {quote.promo?.code?`· ${quote.promo.code}`:''}</span><b>− {money(quote.discount_cents)}</b></div>}<div className="total"><span>Total confirmado</span><b>{money(quote.total_cents)}</b></div></>:<span>{quoteError}</span>}</div>}
        <div className="direct-customer-block"><div className="direct-section-label"><Bike size={15}/><b>Quem recebe?</b></div><label>Nome<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required maxLength={160}/></label><div className="direct-form-grid"><label>WhatsApp<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} inputMode="tel" maxLength={40}/></label><label>E-mail<input value={form.email} onChange={e=>setForm({...form,email:e.target.value})} type="email" maxLength={320}/></label></div></div>
        <label className="direct-consent"><input type="checkbox" checked={form.consent} onChange={e=>setForm({...form,consent:e.target.checked})}/><span>Aceito receber novidades e ofertas desta marca. Posso cancelar quando quiser.</span></label>
        <button className="direct-order-button" disabled={sending||quoting}>{sending?'Enviando…':`Enviar pedido · ${money(finalTotal)}`}</button><small className="direct-privacy">O Cozinha 360 não marca pagamento como aprovado sem confirmação real do gateway. Taxas de Pix/cartão, marketplaces, WhatsApp, mapas ou logística externa pertencem aos respectivos provedores.</small>
      </form>}
    </section>
  </main>
}

export function DeliveryTrackingRoute({token}:{token:string}){
  const [data,setData]=useState<Tracking|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('')
  async function load(){setError('');try{setData(await direct(`/track/${encodeURIComponent(token)}`))}catch(e){setError(e instanceof Error?e.message:'Rastreamento indisponível')}finally{setLoading(false)}}
  useEffect(()=>{void load()},[token])
  if(loading)return <main className="direct-public center"><b>Buscando sua entrega…</b></main>
  return <main className="direct-public direct-track-page"><section className="direct-track-card"><div className="direct-track-icon"><Navigation size={24}/></div><span>ACOMPANHAMENTO DO PEDIDO</span>{error?<><h1>Rastreamento indisponível</h1><p>{error}</p></>:data&&<><h1>{trackingLabels[data.status]||data.status}</h1><p>{data.brand?`${data.brand} · `:''}Pedido #{data.order_id}</p><div className="direct-track-timeline"><TrackStep done title="Pedido recebido"/><TrackStep done={['assigned','picked_up','delivered'].includes(data.status)} title="Entregador definido"/><TrackStep done={['picked_up','delivered'].includes(data.status)} title="Saiu para entrega"/><TrackStep done={data.status==='delivered'} title="Entregue"/></div><div className="direct-track-facts"><div><span>Previsão</span><b>{dateTimeLabel(data.promised_at)}</b></div><div><span>Agendado</span><b>{dateTimeLabel(data.scheduled_for)}</b></div></div></>}<button type="button" onClick={()=>void load()}><RefreshCcw size={15}/>Atualizar status</button><small>Localização em mapa só é exibida quando a cozinha conecta um provedor compatível e o rastreamento está habilitado.</small></section></main>
}
function TrackStep({done,title}:{done:boolean;title:string}){return <div className={done?'done':''}><span>{done?<CheckCircle2 size={15}/>:<Clock3 size={15}/>}</span><b>{title}</b></div>}

export function DirectCommerceAdminRoute(){
  const token=localStorage.getItem('c360_token')||''
  const [businesses,setBusinesses]=useState<Biz[]>([]),[businessId,setBusinessId]=useState(0),[stores,setStores]=useState<Storefront[]>([]),[attr,setAttr]=useState<Attribution|null>(null)
  const [loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[days,setDays]=useState(30)
  const [draft,setDraft]=useState({display_name:'',slug:''})
  async function load(id=businessId,d=days){if(!id)return;setError('');try{const [s,a]=await Promise.all([direct(`/businesses/${id}/storefronts`,{},token),direct(`/businesses/${id}/attribution?days=${d}`,{},token)]);setStores(s);setAttr(a)}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar venda direta')}}
  useEffect(()=>{if(!token){setLoading(false);return}request('/me',{},token).then(async me=>{const rows:Biz[]=me.businesses||[];setBusinesses(rows);const id=rows[0]?.id||0;setBusinessId(id);if(id)await load(id)}).catch(e=>setError(e instanceof Error?e.message:'Falha ao carregar conta')).finally(()=>setLoading(false))},[])
  async function createStore(e:React.FormEvent){e.preventDefault();setError('');try{const created=await direct(`/businesses/${businessId}/storefronts`,{method:'POST',body:JSON.stringify(draft)},token);setDraft({display_name:'',slug:''});setNotice(`Loja ${created.display_name} criada.`);await load();setTimeout(()=>setNotice(''),2600)}catch(e){setError(e instanceof Error?e.message:'Não foi possível criar a loja')}}
  async function toggle(store:Storefront){setError('');try{await direct(`/businesses/${businessId}/storefronts/${store.id}`,{method:'PATCH',body:JSON.stringify({active:!store.active})},token);await load()}catch(e){setError(e instanceof Error?e.message:'Erro ao atualizar')}}
  if(!token)return <main className="direct-admin center"><section className="direct-message"><h1>Entre no Cozinha 360 primeiro.</h1><a href="/">Voltar para login</a></section></main>
  if(loading)return <main className="direct-admin center"><b>Carregando Venda Direta…</b></main>
  return <main className="direct-admin"><header className="direct-admin-top"><a href="/"><ArrowLeft size={18}/> Operação</a><b>VENDA DIRETA</b><div><select value={businessId} onChange={async e=>{const id=Number(e.target.value);setBusinessId(id);await load(id)}}>{businesses.map(b=><option value={b.id} key={b.id}>{b.name}</option>)}</select><button onClick={()=>load()} title="Atualizar"><RefreshCcw size={16}/></button></div></header>
    <section className="direct-admin-body"><div className="direct-admin-hero"><span>FIRST-PARTY COMMERCE</span><h1>Venda no seu próprio link e saiba qual campanha trouxe margem — não só faturamento.</h1><p>Agora o checkout também valida região, taxa, pedido mínimo, cupom e agendamento no servidor antes de gravar o pedido.</p></div>{notice&&<div className="direct-success compact"><CheckCircle2/><b>{notice}</b></div>}{error&&<div className="direct-error">{error}</div>}
      <div className="direct-admin-grid"><article className="direct-panel"><div className="direct-panel-head"><div><span>LOJAS</span><h2>Links próprios</h2></div><Store/></div><form onSubmit={createStore} className="direct-create"><label>Nome da loja<input value={draft.display_name} onChange={e=>setDraft({...draft,display_name:e.target.value})} placeholder="Ex.: Brasa Burger" required/></label><label>Endereço curto<input value={draft.slug} onChange={e=>setDraft({...draft,slug:e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,'')})} placeholder="brasa-burger" minLength={3} maxLength={60} required/></label><button><Plus size={16}/> Criar link de venda</button></form><p className="direct-note">Na primeira loja, o sistema cria automaticamente o canal “Pedido direto”. Defina preços em <a href="/?margin=1">Margens & canais</a> e regiões em <a href="/?delivery=1">Delivery 360</a>.</p><div className="direct-store-list">{stores.map(s=><div key={s.id} className="direct-store-row"><div><b>{s.display_name}</b><span>/{s.slug} · {s.channels?.name||'Canal direto'}</span></div><div><a href={`/?loja=${encodeURIComponent(s.slug)}`} target="_blank" rel="noreferrer" title="Abrir loja"><ExternalLink size={16}/></a><button onClick={()=>toggle(s)} className={s.active?'on':'off'}>{s.active?'Ativa':'Pausada'}</button></div></div>)}</div></article>
        <article className="direct-panel"><div className="direct-panel-head"><div><span>ATRIBUIÇÃO</span><h2>Contribuição após mídia</h2></div><Target/></div><div className="direct-period"><span>Janela</span><select value={days} onChange={async e=>{const d=Number(e.target.value);setDays(d);await load(businessId,d)}}><option value={7}>7 dias</option><option value={30}>30 dias</option><option value={90}>90 dias</option><option value={365}>365 dias</option></select></div><div className="direct-kpis"><div><span>Pedidos atribuídos</span><b>{attr?.summary.orders||0}</b></div><div><span>Receita</span><b>{money(attr?.summary.revenue_cents||0)}</b></div><div><span>Mídia</span><b>{money(attr?.summary.media_cost_cents||0)}</b></div><div><span>Contribuição pós-mídia</span><b>{money(attr?.summary.contribution_after_media_cents||0)}</b></div></div><div className="direct-campaigns">{attr?.campaigns.map((c,i)=><div className="direct-campaign" key={`${c.utm_source}-${c.utm_campaign}-${i}`}><div><b>{c.utm_campaign}</b><span>{c.utm_source} / {c.utm_medium}</span></div><div><strong>{money(c.contribution_after_media_cents)}</strong><span>{c.orders} pedido(s){c.contribution_per_media!=null?` · ${Number(c.contribution_per_media).toLocaleString('pt-BR')}x contribuição/mídia`:''}</span></div></div>)}{!attr?.campaigns.length&&<div className="direct-message small"><BarChart3/><p>As campanhas aparecem aqui depois que pedidos do link próprio forem concluídos.</p></div>}</div></article></div>
    </section></main>
}