export type ExecutionResource={id:number;category:string;name:string;url:string;note:string}
const r=(id:number,category:string,name:string,url:string,note:string):ExecutionResource=>({id,category,name,url,note})
export const executionResources:ExecutionResource[]=[
r(1,'Governo & sanitário','gov.br — Empresas e Negócios / Redesim','https://www.gov.br/empresas-e-negocios/pt-br','CNPJ, viabilidade e licenciamento.'),
r(2,'Governo & sanitário','Receita Federal — Consulta CNPJ','https://solucoes.receita.fazenda.gov.br/Servicos/cnpjreva/Cnpjreva_Solicitacao.asp','Situação cadastral.'),
r(3,'Governo & sanitário','Sintegra — Inscrição estadual','http://www.sintegra.gov.br/','Consulta de IE por UF.'),
r(4,'Governo & sanitário','Portal NF-e — Consulta chave','https://www.nfe.fazenda.gov.br/portal/consultaRecaptcha.aspx','Consulta DANFE / chave.'),
r(5,'Governo & sanitário','consumidor.gov.br','https://www.consumidor.gov.br/','Histórico público de reclamações.'),
r(6,'Governo & sanitário','Anvisa — Página oficial','https://www.gov.br/anvisa/pt-br','Controle sanitário e orientações.'),
r(7,'Governo & sanitário','Anvisa — Publicações alimentos','https://www.gov.br/anvisa/pt-br/centrais-de-conteudo/publicacoes/alimentos','Cartilhas e manuais.'),
r(8,'Governo & sanitário','MAPA — Ministério da Agricultura','https://www.gov.br/agricultura/pt-br','Inspeção de produtos de origem animal.'),
r(9,'Governo & sanitário','INPI — Busca de marca','https://busca.inpi.gov.br/','Pesquisa de nome/marca.'),
r(10,'Governo & sanitário','Portal do Empreendedor (MEI)','https://www.gov.br/empresas-e-negocios/pt-br/empreendedor','Formalização MEI.'),
r(11,'Governo & sanitário','Ministério da Fazenda','https://www.gov.br/fazenda/pt-br','Informações tributárias e fiscais.'),
r(12,'Governo & sanitário','Ministério do Trabalho','https://www.gov.br/trabalho-e-emprego/pt-br','Regras trabalhistas.'),
r(13,'Governo & sanitário','Lei Complementar 123','https://www.planalto.gov.br/ccivil_03/leis/lcp/lcp123.htm','Texto do Simples Nacional.'),
r(14,'Governo & sanitário','gov.br — Alvará de funcionamento','https://www.gov.br/pt-br/servicos/obter-alvara-de-funcionamento','Orientação geral; confirme no município.'),
r(15,'Governo & sanitário','Anvisa — Rotulagem de alimentos','https://www.gov.br/anvisa/pt-br/assuntos/alimentos/rotulagem','Ingredientes, alergênicos e informação nutricional.'),
r(16,'Governo & sanitário','Anvisa — Embalagens','https://www.gov.br/anvisa/pt-br/assuntos/alimentos/embalagens','Materiais em contato com alimentos.'),
r(17,'Governo & sanitário','Receita — Compras internacionais','https://www.gov.br/receitafederal/pt-br/assuntos/aduana-e-comercio-exterior/manuais/despacho-de-importacao','Orientações de importação.'),
r(18,'Governo & sanitário','Correios — Encomenda internacional','https://www.correios.com.br/enviar/encomendas/encomenda-internacional','Envio e recebimento do exterior.'),
r(19,'Governo & sanitário','Inmetro','https://www.gov.br/inmetro/pt-br','Conformidade de equipamentos e produtos.'),
r(20,'Governo & sanitário','Banco Central — Pix','https://www.bcb.gov.br/estabilidadefinanceira/pix','Regras e segurança do Pix.'),
r(21,'Cursos gratuitos','OMS — Cinco chaves para alimentos mais seguros','https://www.who.int/publications/i/item/9789241594639','Material de higiene e segurança.'),
r(22,'Cursos gratuitos','EV.G — Manipulação de alimentos','https://www.escolavirtual.gov.br/curso/287','Curso público de boas práticas.'),
r(23,'Cursos gratuitos','FAO eLearning','https://elearning.fao.org/','Cursos de segurança dos alimentos.'),
r(24,'Cursos gratuitos','Sebrae — Cursos on-line','https://www.sebrae.com.br/sites/PortalSebrae/cursosonline','Gestão, estoque e marketing.'),
r(25,'Cursos gratuitos','Senac-SP','https://www.sp.senac.br/','Gastronomia e alimentação.'),
r(26,'Cursos gratuitos','Academia de Negócios Bunge','https://www.academiadenegociosbunge.com.br/','Panificação, fritura e gestão.'),
r(27,'Cursos gratuitos','Codex Alimentarius','https://www.fao.org/fao-who-codexalimentarius/codex-texts/list-standards/en/','Normas internacionais.'),
r(28,'Cursos gratuitos','Google Skillshop','https://skillshop.exceedlms.com/student/catalog','Treinamento oficial Google.'),
r(29,'Cursos gratuitos','Google Analytics Academy','https://analytics.google.com/analytics/academy/','Treinamento de GA4.'),
r(30,'Cursos gratuitos','Meta Blueprint','https://www.facebook.com/business/learn','Treinamento oficial Meta.'),
r(31,'Cursos gratuitos','TikTok Academy','https://ads.tiktok.com/business/en/academy','Treinamento oficial TikTok.'),
r(32,'Cursos gratuitos','WhatsApp Business','https://www.whatsapp.com/business','Recursos oficiais.'),
r(33,'Cursos gratuitos','Google — Perfil da Empresa','https://support.google.com/business/','Central de aprendizagem.'),
r(34,'Cursos gratuitos','Google Tag Manager — Ajuda','https://support.google.com/tagmanager/','Documentação oficial.'),
r(35,'Cursos gratuitos','Sebrae no YouTube','https://www.youtube.com/@Sebrae','Conteúdo prático.'),
r(36,'Abastecimento','Conab','https://www.conab.gov.br/','Preços e abastecimento.'),
r(37,'Abastecimento','CEAGESP','https://www.ceagesp.gov.br/','Central de abastecimento SP.'),
r(38,'Abastecimento','CEASA Campinas','https://www.ceasa.campinas.sp.gov.br/','Central regional.'),
r(39,'Abastecimento','CRAISA — Santo André','https://www.craisa.com.br/','Abastecimento no Grande ABC.'),
r(40,'Abastecimento','Martins Atacado','https://www.martinsatacado.com.br/','Mercearia e reposição.'),
r(41,'Abastecimento','Zona Cerealista Online','https://www.zonacerealista.com.br/','Grãos, secos e temperos.'),
r(42,'Abastecimento','Atacadão','https://www.atacadao.com.br/','Atacado e retirada.'),
r(43,'Abastecimento','Assaí Atacadista','https://www.assai.com.br/','Atacado e reposição.'),
r(44,'Abastecimento','Makro','https://www.makro.com.br/','Food service; confirme disponibilidade.'),
r(45,'Abastecimento',"Sam's Club",'https://www.samsclub.com.br/','Atacado com associação.'),
r(46,'Abastecimento','Portal Ceasas Brasil','https://www.ceasas.com.br/','Centrais pelo país.'),
r(47,'Abastecimento','MAPA — Inspeção produtos de origem animal','https://www.gov.br/agricultura/pt-br/assuntos/inspecao/produtos-animal','SIF e orientações.'),
r(48,'Abastecimento','Embrapa','https://www.embrapa.br/','Pesquisa agroalimentar.'),
r(49,'Abastecimento','IBGE','https://www.ibge.gov.br/','Dados e estatísticas.'),
r(50,'Abastecimento','SIDRA / IBGE','https://sidra.ibge.gov.br/','Recuperação de dados.'),
r(51,'Ingredientes profissionais','Harald','https://www.harald.com.br/','Chocolate e confeitaria.'),
r(52,'Ingredientes profissionais','Puratos Brasil','https://www.puratos.com.br/','Panificação e confeitaria.'),
r(53,'Ingredientes profissionais','Bunge Profissional','https://www.bunge.com.br/','Óleos, farinhas e food service.'),
r(54,'Ingredientes profissionais','Frooty Food Service','https://www.frooty.com.br/','Açaí e gelados.'),
r(55,'Ingredientes profissionais','Sakura Food Service','https://www.sakura.com.br/','Linha oriental.'),
r(56,'Ingredientes profissionais','Ajinomoto Food Service','https://www.ajinomoto.com.br/','Molhos e temperos.'),
r(57,'Ingredientes profissionais','Nestlé Professional','https://www.nestleprofessional.com.br/','Soluções food service.'),
r(58,'Ingredientes profissionais','Unilever Food Solutions','https://www.unileverfoodsolutions.com.br/','Soluções profissionais.'),
r(59,'Ingredientes profissionais','Ceratti','https://www.ceratti.com.br/','Embutidos e frios.'),
r(60,'Ingredientes profissionais','Seara','https://www.seara.com.br/','Proteínas e food service.'),
r(61,'Ingredientes profissionais','Aurora','https://www.auroraalimentos.com.br/','Proteínas e laticínios.'),
r(62,'Ingredientes profissionais','Italac','https://www.italac.com.br/','Laticínios e bebidas.'),
r(63,'Embalagens','Galvanotek','https://www.galvanotek.com.br/','Potes e delivery.'),
r(64,'Embalagens','Copobras','https://www.grupocopobras.com.br/','Descartáveis.'),
r(65,'Embalagens','Wyda','https://www.lojawyda.com.br/','Alumínio e filme.'),
r(66,'Embalagens','Prafesta','https://www.prafesta.com.br/','Copos e potes.'),
r(67,'Embalagens','Termoform','https://www.termoform.com.br/','Embalagens termoformadas.'),
r(68,'Embalagens','Total Embalagens','https://www.totalembalagens.com.br/','Soluções para delivery.'),
r(69,'Embalagens','EmbalagemMarca','https://www.embalagemmarca.com.br/','Conteúdo e fornecedores.'),
r(70,'Embalagens','Plastipack','https://www.plastipack.com.br/','Embalagens plásticas.'),
r(71,'Embalagens','Kartondo','https://www.kartondo.com.br/','Caixas e papelão.'),
r(72,'Embalagens','Ibema','https://www.ibema.com.br/','Papéis e cartões.'),
r(73,'Equipamentos','Skymsen','https://www.skymsen.com.br/','Equipamentos profissionais.'),
r(74,'Equipamentos','Metvisa','https://www.metvisa.com.br/','Equipamentos e assistência.'),
r(75,'Equipamentos','Progás / Braesi','https://www.progas.com.br/','Cocção e panificação.'),
r(76,'Equipamentos','Venâncio','https://www.venancio.com.br/','Cocção e refrigeração.'),
r(77,'Equipamentos','Tedesco','https://www.tedesco.com.br/','Padaria e confeitaria.'),
r(78,'Equipamentos','Imbera','https://www.imbera.com/','Refrigeração comercial.'),
r(79,'Equipamentos','Gelopar','https://www.gelopar.com.br/','Expositores e refrigeração.'),
r(80,'Equipamentos','Cristófoli','https://www.cristofoli.com.br/','Esterilização e apoio.'),
r(81,'Equipamentos','Balanças digitais','https://www.balancadigital.com.br/','Porcionamento; priorize assistência.'),
r(82,'Equipamentos','Termômetros — referência','https://www.termo.com.br/','Temperatura; confira calibração.'),
r(83,'PDV & automação','Consumer — Cardápio digital','https://consumer.com.br/cardapio-digital','PDV e delivery.'),
r(84,'PDV & automação','Saipos','https://saipos.com/planos-e-precos','Gestão e integrações.'),
r(85,'PDV & automação','Anota AI','https://anota.ai/cardapio-digital','WhatsApp e cardápio.'),
r(86,'PDV & automação','Goomer','https://www.goomer.com.br/','Cardápio digital.'),
r(87,'PDV & automação','Menudino','https://www.menudino.com.br/','Cardápio digital.'),
r(88,'PDV & automação','Cardápio Web','https://www.cardapioweb.com/','Cardápio on-line.'),
r(89,'PDV & automação','TOTVS','https://www.totvs.com/','Sistemas de gestão.'),
r(90,'PDV & automação','iFood Parceiros','https://www.ifood.com.br/parceiros','Portal de lojistas.'),
r(91,'PDV & automação','99Food','https://99app.com/99food/','Informações para parceiros.'),
r(92,'PDV & automação','Rappi','https://www.rappi.com.br/','Plataforma e parceiros.'),
r(93,'Pagamento & entrega','Mercado Pago','https://www.mercadopago.com.br/','Pagamento e taxas.'),
r(94,'Pagamento & entrega','PagBank','https://www.pagbank.com.br/','Pagamento.'),
r(95,'Pagamento & entrega','Ton','https://www.ton.com.br/','Pagamento.'),
r(96,'Pagamento & entrega','Stone','https://www.stone.com.br/','Pagamento.'),
r(97,'Pagamento & entrega','Cielo','https://www.cielo.com.br/','Adquirência.'),
r(98,'Pagamento & entrega','Lalamove','https://www.lalamove.com/brasil/pt-br/','Entrega sob demanda.'),
r(99,'Pagamento & entrega','Loggi','https://www.loggi.com/','Entrega local.'),
r(100,'Pagamento & entrega','Uber Direct / entrega','https://www.uber.com/br/pt-br/deliver/','Consulte disponibilidade.'),
r(101,'Pagamento & entrega','iFood — experiência cliente','https://www.ifood.com.br/','Experiência do consumidor.'),
r(102,'Pagamento & entrega','Keeta','https://keeta.com/','Confirme status/cobertura.'),
r(103,'Pagamento & entrega','Rappi Partners','https://www.rappi.com.br/partners','Portal de parceiros.'),
r(104,'Pagamento & entrega','99 App','https://www.99app.com/','99 e 99Food.'),
r(105,'Pagamento & entrega','Banco Central','https://www.bcb.gov.br/','Normas financeiras.'),
r(106,'Foto, vídeo & design','Canva','https://www.canva.com/','Design e cardápio.'),
r(107,'Foto, vídeo & design','Adobe Express','https://www.adobe.com/br/express/','Foto, vídeo e design.'),
r(108,'Foto, vídeo & design','CapCut','https://www.capcut.com/','Vídeo vertical.'),
r(109,'Foto, vídeo & design','Snapseed — informação','https://snapseed.online/','Use o app oficial nas lojas.'),
r(110,'Foto, vídeo & design','Photopea','https://www.photopea.com/','Editor no navegador.'),
r(111,'Foto, vídeo & design','remove.bg','https://remove.bg/','Remoção de fundo.'),
r(112,'Foto, vídeo & design','Figma','https://www.figma.com/','Design e protótipos.'),
r(113,'Foto, vídeo & design','Unsplash','https://unsplash.com/','Banco de apoio; não substitui foto real.'),
r(114,'Foto, vídeo & design','Pexels','https://www.pexels.com/pt-br/','Banco de apoio.'),
r(115,'Foto, vídeo & design','Google Fonts','https://fonts.google.com/','Tipografia.'),
r(116,'Tráfego & mensuração','Google Ads','https://ads.google.com/','Campanhas Google.'),
r(117,'Tráfego & mensuração','Meta Business Suite','https://business.facebook.com/','Facebook e Instagram.'),
r(118,'Tráfego & mensuração','TikTok Ads','https://ads.tiktok.com/','Anúncios TikTok.'),
r(119,'Tráfego & mensuração','Google Tag Manager','https://tagmanager.google.com/','Gerenciamento de tags.'),
r(120,'Tráfego & mensuração','Google Analytics 4','https://analytics.google.com/','Analytics.'),
r(121,'Tráfego & mensuração','Meta Pixel','https://www.facebook.com/business/tools/meta-pixel','Documentação do Pixel.'),
r(122,'Tráfego & mensuração','TikTok Pixel','https://ads.tiktok.com/help/article/tiktok-pixel','Ajuda oficial.'),
r(123,'Tráfego & mensuração','Google Search Console','https://search.google.com/search-console','Busca orgânica.'),
r(124,'Tráfego & mensuração','Google Business Profile','https://business.google.com/','Perfil da Empresa.'),
r(125,'Tráfego & mensuração','Instagram','https://www.instagram.com/','Conta profissional.'),
r(126,'Global & B2B','Alibaba','https://www.alibaba.com/','Fornecedores globais; avalie proteção/conformidade.'),
r(127,'Global & B2B','Global Sources','https://www.globalsources.com/','Descoberta B2B.'),
r(128,'Global & B2B','Europages','https://www.europages.com/','Diretório B2B Europa.'),
r(129,'Global & B2B','Made-in-China','https://www.made-in-china.com/','Avalie conformidade no Brasil.'),
r(130,'Global & B2B','Receita Federal','https://www.gov.br/receitafederal/pt-br','Impostos e comércio exterior.'),
]
export const executionCategories=['Todos',...Array.from(new Set(executionResources.map(x=>x.category)))]
