import React,{useEffect,useMemo,useState}from'react'
import{ArrowLeft,BookOpenCheck,Check,ChevronRight,ClipboardCheck,Copy,ExternalLink,Flame,Map,RefreshCcw,Search,ShieldCheck,ShoppingCart,Workflow}from'lucide-react'
import{request,type Product}from'./app'
import{executionCategories,executionResources}from'./execution-directory'

type Business={id:number;name:string;city:string;role:string}
type Tab='legal'|'flow'|'scripts'|'purchase'|'directory'
type Flow={arrival:string;stock:string;rawEnd:string;pack:string;handoff:string;crossing:boolean}
type Purchase={critical:string;unit:string;testUse:string;measure:string;cep:string;localQuote:boolean;regionalQuote:boolean;nationalQuote:boolean;document:boolean;sample:boolean;travel:boolean;yield:boolean;landed:boolean;backup:boolean}
const emptyFlow:Flow={arrival:'',stock:'',rawEnd:'',pack:'',handoff:'',crossing:false}
const emptyPurchase:Purchase={critical:'',unit:'',testUse:'',measure:'',cep:'',localQuote:false,regionalQuote:false,nationalQuote:false,document:false,sample:false,travel:false,yield:false,landed:false,backup:false}
const purchaseTextFields:[keyof Purchase,string][]=[['critical','Item crítico'],['unit','Unidade de comparação'],['testUse','Consumo de teste'],['measure','Temperatura / medida'],['cep','CEP']]
function safeJSON<T>(raw:string|null,fallback:T):T{try{return raw?JSON.parse(raw):fallback}catch{return fallback}}

export function ExecutionHubRoute(){
 const token=localStorage.getItem('c360_token')||''
 const[businesses,setBusinesses]=useState<Business[]>([]);const[businessId,setBusinessId]=useState(0);const[products,setProducts]=useState<Product[]>([]);const[tab,setTab]=useState<Tab>('legal');const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[copied,setCopied]=useState('')
 const[legal,setLegal]=useState({product:'',address:'',mode:'entrega',protocol:''});const[flow,setFlow]=useState<Flow>(emptyFlow);const[purchase,setPurchase]=useState<Purchase>(emptyPurchase);const[script,setScript]=useState({brand:'',item:'',cep:'',value:'',pix:'',time:'',occasion:'',offer:'',period:'',code:'SITE'});const[query,setQuery]=useState('');const[category,setCategory]=useState('Todos')
 function persist(id:number){if(!id)return;localStorage.setItem(`c360-execution-v25-${id}`,JSON.stringify({legal,flow,purchase,script}))}
 async function load(target=businessId){if(!token){setLoading(false);return}setError('');try{let id=target;let rows=businesses;if(!rows.length){const me=await request('/me',{},token);rows=(me.businesses||[])as Business[];setBusinesses(rows);id=id||Number(rows[0]?.id||0);if(id)setBusinessId(id)}if(!id)return;const p=await request(`/businesses/${id}/products`,{},token);setProducts(p);const b=rows.find(x=>x.id===id);const saved=safeJSON(localStorage.getItem(`c360-execution-v25-${id}`),{legal:{product:'',address:'',mode:'entrega',protocol:''},flow:emptyFlow,purchase:emptyPurchase,script:{brand:b?.name||'',item:'',cep:'',value:'',pix:'',time:'',occasion:'',offer:'',period:'',code:'SITE'}});setLegal(saved.legal);setFlow(saved.flow);setPurchase(saved.purchase);setScript({...saved.script,brand:saved.script.brand||b?.name||''})}catch(e){setError(e instanceof Error?e.message:'Não foi possível montar o Execution Hub')}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 useEffect(()=>{if(businessId)persist(businessId)},[legal,flow,purchase,script])
 const active=products.filter(x=>x.active);const productName=legal.product||script.item||active[0]?.name||'[ALIMENTO]';const legalMessage=`Pretendo produzir ${productName} em pequena escala no endereço ${legal.address||'[CEP / rua]'}, somente para ${legal.mode==='retirada'?'retirada':'entrega'}. Qual regra oficial se aplica ao uso do solo, à licença sanitária e à atividade domiciliar? Poderia indicar o documento e o canal de protocolo?`
 const scripts={first:`Olá! Aqui é a ${script.brand||'[MARCA]'}. Temos ${script.item||productName} hoje. Me passa seu CEP para eu confirmar se atendemos e o prazo?`,confirm:`Fechado: [QTD]x ${script.item||productName} — ${script.value||'R$ [VALOR]'}. Pagamento via Pix ${script.pix||'[CHAVE]'}. Após o comprovante, produzimos e saímos às ${script.time||'[HORA]'}. Qualquer dúvida, me chama.`,limit:'Nossa janela de hoje já fechou. Produzimos em lotes pequenos para manter qualidade. Posso te avisar na próxima abertura?',after:'Chegou como na foto? Sua nota sincera sobre produto, embalagem e entrega ajuda a melhorar. Obrigado!',repeat:`Você pediu ${script.item||productName} há ${script.period||'[PERÍODO]'}. Nesta ${script.occasion||'[OCASIÃO]'} temos ${script.offer||'[OFERTA]'}. Quer receber o menu? Se não, responda SAIR.`,ad:`${businesses.find(x=>x.id===businessId)?.city||'[BAIRRO]'}, hoje tem ${script.item||productName}. Pedidos na janela real. Entrega por CEP. Envie ${script.code||'SITE'}.`}
 const phase1=[purchase.critical,purchase.unit,purchase.testUse,purchase.measure,purchase.cep].filter(Boolean).length;const phase2=[purchase.localQuote,purchase.regionalQuote,purchase.nationalQuote].filter(Boolean).length;const phase3=[purchase.document,purchase.sample,purchase.travel,purchase.yield,purchase.landed,purchase.backup].filter(Boolean).length;const purchasePct=Math.round((phase1+phase2+phase3)/14*100)
 const filtered=useMemo(()=>executionResources.filter(x=>(category==='Todos'||x.category===category)&&(!query.trim()||`${x.name} ${x.note} ${x.category}`.toLowerCase().includes(query.toLowerCase()))),[category,query])
 async function copy(label:string,value:string){try{await navigator.clipboard.writeText(value);setCopied(label);setTimeout(()=>setCopied(''),1500)}catch{/* unavailable */}}
 if(!token)return <main className="exh-shell exh-center"><div className="exh-empty"><Flame/><h1>Entre na operação.</h1><p>Execution Hub organiza tarefas de campo e fontes do método.</p><a href="/">Entrar</a></div></main>
 if(loading)return <main className="exh-shell exh-center"><div className="exh-loader"><Workflow/>MONTANDO EXECUTION HUB</div></main>
 return <main className="exh-shell"><header className="exh-topbar"><a href="/?system360=1"><ArrowLeft/> Sistema 360</a><b><Flame/> EXECUTION HUB <span>CAMPO · SCRIPTS · 130 RECURSOS</span></b><div>{businesses.length>1&&<select value={businessId} onChange={async e=>{const id=Number(e.target.value);setBusinessId(id);await load(id)}}>{businesses.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select>}<button onClick={()=>load()}><RefreshCcw/></button></div></header><section className="exh-page">
 <div className="exh-hero"><div><span>COZINHA DE BOLSO 360 · ACELERADORES DE EXECUÇÃO</span><h1>Menos memória. Mais registro, fonte e próxima ação.</h1><p>Consulta legal, fluxo da cozinha, scripts, primeira compra e o diretório de 130 recursos agora ficam no mesmo sistema operacional.</p></div><div className="exh-source"><BookOpenCheck/><span>BASE DO MATERIAL</span><b>130 recursos · edição 2026</b><small>Links e regras mudam: confirme sempre na fonte.</small></div></div>{error&&<div className="exh-error">{error}</div>}
 <nav className="exh-tabs"><button className={tab==='legal'?'active':''} onClick={()=>setTab('legal')}><ShieldCheck/>Consulta legal</button><button className={tab==='flow'?'active':''} onClick={()=>setTab('flow')}><Map/>Fluxo cozinha</button><button className={tab==='scripts'?'active':''} onClick={()=>setTab('scripts')}><ClipboardCheck/>Scripts</button><button className={tab==='purchase'?'active':''} onClick={()=>setTab('purchase')}><ShoppingCart/>Compra 72h</button><button className={tab==='directory'?'active':''} onClick={()=>setTab('directory')}><Search/>Diretório 130</button></nav>
 {tab==='legal'&&<section className="exh-tool"><Head kicker="CONSULTA LEGAL / SANITÁRIA" title="Pergunte à autoridade certa sem presumir a resposta."/><div className="exh-form-grid"><label>Produto<select value={legal.product} onChange={e=>setLegal({...legal,product:e.target.value})}><option value="">Escolher produto</option>{active.map(p=><option key={p.id}>{p.name}</option>)}</select></label><label>CEP / endereço<input value={legal.address} onChange={e=>setLegal({...legal,address:e.target.value})} placeholder="Endereço da operação"/></label><label>Modalidade<select value={legal.mode} onChange={e=>setLegal({...legal,mode:e.target.value})}><option value="entrega">Entrega</option><option value="retirada">Retirada</option></select></label><label>Protocolo / resposta<input value={legal.protocol} onChange={e=>setLegal({...legal,protocol:e.target.value})} placeholder="Órgão · protocolo · data"/></label></div><div className="exh-output"><span>MENSAGEM PRONTA</span><p>{legalMessage}</p><button onClick={()=>copy('legal',legalMessage)}>{copied==='legal'?<Check/>:<Copy/>}{copied==='legal'?'Copiada':'Copiar'}</button></div><div className="exh-legal-links"><a href="https://www.gov.br/anvisa/pt-br" target="_blank" rel="noreferrer">Anvisa <ExternalLink/></a><a href="https://www.gov.br/empresas-e-negocios/pt-br" target="_blank" rel="noreferrer">Redesim <ExternalLink/></a><a href="https://www.gov.br/pt-br/servicos/obter-alvara-de-funcionamento" target="_blank" rel="noreferrer">Alvará — orientação geral <ExternalLink/></a></div><div className="exh-warning"><ShieldCheck/><span>O app não declara sua operação autorizada. Registre órgão, protocolo, resposta sobre o endereço e qualquer pendência que impeça produção.</span></div></section>}
 {tab==='flow'&&<section className="exh-tool"><Head kicker="MAPA DA COZINHA EM 5 MINUTOS" title="Desenhe a rota, não o cômodo."/><div className="exh-flow"><FlowField n="01" label="Onde chega o insumo" value={flow.arrival} onChange={v=>setFlow({...flow,arrival:v})}/><FlowField n="02" label="Onde fica o estoque exclusivo" value={flow.stock} onChange={v=>setFlow({...flow,stock:v})}/><FlowField n="03" label="Onde o alimento cru termina" value={flow.rawEnd} onChange={v=>setFlow({...flow,rawEnd:v})}/><FlowField n="04" label="Onde o produto pronto é embalado" value={flow.pack} onChange={v=>setFlow({...flow,pack:v})}/><FlowField n="05" label="Onde a entrega recebe sem entrar" value={flow.handoff} onChange={v=>setFlow({...flow,handoff:v})}/></div><button className={`exh-cross ${flow.crossing?'risk':''}`} onClick={()=>setFlow({...flow,crossing:!flow.crossing})}><i>{flow.crossing?'!':'✓'}</i><span><b>As rotas se cruzam?</b><small>{flow.crossing?'Mude horário, posição ou ordem. Não trate risco com “mais cuidado” no pico.':'Nenhum cruzamento declarado no mapa.'}</small></span></button></section>}
 {tab==='scripts'&&<section className="exh-tool"><Head kicker="WHATSAPP + ANÚNCIO LOCAL" title="Respostas rápidas sem transformar atendimento em robô."/><div className="exh-script-fields"><label>Marca<input value={script.brand} onChange={e=>setScript({...script,brand:e.target.value})}/></label><label>Item<input value={script.item} onChange={e=>setScript({...script,item:e.target.value})} placeholder={productName}/></label><label>Valor<input value={script.value} onChange={e=>setScript({...script,value:e.target.value})} placeholder="R$ 39,90"/></label><label>Pix<input value={script.pix} onChange={e=>setScript({...script,pix:e.target.value})}/></label><label>Hora<input value={script.time} onChange={e=>setScript({...script,time:e.target.value})}/></label><label>Código origem<input value={script.code} onChange={e=>setScript({...script,code:e.target.value.toUpperCase().replace(/\s/g,'').slice(0,18)})}/></label><label>Ocasião<input value={script.occasion} onChange={e=>setScript({...script,occasion:e.target.value})}/></label><label>Oferta<input value={script.offer} onChange={e=>setScript({...script,offer:e.target.value})}/></label></div><div className="exh-scripts">{Object.entries({"Primeira resposta":scripts.first,"Confirmação":scripts.confirm,"Limite de capacidade":scripts.limit,"Pós-venda":scripts.after,"Recompra com consentimento":scripts.repeat,"Anúncio local":scripts.ad}).map(([label,value])=><article key={label}><span>{label}</span><p>{value}</p><button onClick={()=>copy(label,value)}>{copied===label?<Check/>:<Copy/>}</button></article>)}</div></section>}
 {tab==='purchase'&&<section className="exh-tool"><Head kicker="CHECKLIST DE PRIMEIRA COMPRA" title="72 horas para comparar custo total com risco controlado."/><div className="exh-purchase-progress"><strong>{purchasePct}%</strong><div><i style={{width:`${purchasePct}%`}}/></div><span>Não antecipe estoque grande antes de testar.</span></div><div className="exh-purchase-grid"><article><span>0–24 H</span><b>Defina</b>{purchaseTextFields.map(([k,l])=><label key={String(k)}>{l}<input value={String(purchase[k])} onChange={e=>setPurchase({...purchase,[k]:e.target.value})}/></label>)}</article><article><span>24–48 H</span><b>Cote com a mesma mensagem</b><CheckRow label="Bairro / local" value={purchase.localQuote} onChange={v=>setPurchase({...purchase,localQuote:v})}/><CheckRow label="Região" value={purchase.regionalQuote} onChange={v=>setPurchase({...purchase,regionalQuote:v})}/><CheckRow label="Brasil" value={purchase.nationalQuote} onChange={v=>setPurchase({...purchase,nationalQuote:v})}/></article><article><span>48–72 H</span><b>Teste antes de comprar grande</b><CheckRow label="Documento" value={purchase.document} onChange={v=>setPurchase({...purchase,document:v})}/><CheckRow label="Amostra" value={purchase.sample} onChange={v=>setPurchase({...purchase,sample:v})}/><CheckRow label="Viagem" value={purchase.travel} onChange={v=>setPurchase({...purchase,travel:v})}/><CheckRow label="Rendimento" value={purchase.yield} onChange={v=>setPurchase({...purchase,yield:v})}/><CheckRow label="Custo posto" value={purchase.landed} onChange={v=>setPurchase({...purchase,landed:v})}/><CheckRow label="Plano B" value={purchase.backup} onChange={v=>setPurchase({...purchase,backup:v})}/></article></div><div className="exh-warning"><ShoppingCart/><span>Critério final: menor custo total com risco controlado — não necessariamente o menor preço unitário.</span></div></section>}
 {tab==='directory'&&<section className="exh-tool"><Head kicker="DIRETÓRIO DE EXECUÇÃO" title="130 pontos de partida em um índice pesquisável."/><div className="exh-directory-warning">Base do material: agosto/2026. Links, preços, cobertura e interfaces podem mudar. Fornecedor listado não é endosso.</div><div className="exh-directory-toolbar"><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar Anvisa, embalagem, GA4, entrega..."/></label><select value={category} onChange={e=>setCategory(e.target.value)}>{executionCategories.map(c=><option key={c}>{c}</option>)}</select><b>{filtered.length} resultado(s)</b></div><div className="exh-directory">{filtered.map(x=><a key={x.id} href={x.url} target="_blank" rel="noreferrer"><span>{String(x.id).padStart(3,'0')}</span><div><b>{x.name}</b><small>{x.category} · {x.note}</small></div><ExternalLink/></a>)}</div></section>}
 </section></main>
}
function Head({kicker,title}:{kicker:string;title:string}){return <div className="exh-head"><div><span>{kicker}</span><h2>{title}</h2></div><Workflow/></div>}
function FlowField({n,label,value,onChange}:{n:string;label:string;value:string;onChange:(v:string)=>void}){return <label><span>{n}</span><b>{label}</b><textarea value={value} onChange={e=>onChange(e.target.value)}/><ChevronRight/></label>}
function CheckRow({label,value,onChange}:{label:string;value:boolean;onChange:(v:boolean)=>void}){return <button className={value?'checked':''} onClick={()=>onChange(!value)}><i>{value?<Check/>:'—'}</i><span>{label}</span></button>}
