import React,{useEffect,useMemo,useState}from'react'
import{ArrowLeft,BarChart3,Check,ChevronRight,CircleDollarSign,Copy,Flame,Gauge,MapPinned,Megaphone,RefreshCcw,ShieldCheck,Target,TriangleAlert}from'lucide-react'
import{money,request,type Dashboard,type Finance,type Product}from'./app'

type Business={id:number;name:string;city:string;role:string}
type Tab='metrics'|'events'|'radius'|'offers'
type Metrics={impressions:string;clicks:string;conversations:string;orders:string;spend:string;revenue:string;contribution:string;repeat:string;customers:string}
type EventRow={name:'PageView'|'view_item'|'click_whatsapp'|'purchase';expected:string;ga4:boolean;meta:boolean;tiktok:boolean}
type RadiusRow={km:number;minutes:string;texture:boolean;leak:boolean;presentation:boolean}
type Offer={id:number;name:string;structure:string;test:string;guard:string}

const defaultMetrics:Metrics={impressions:'10000',clicks:'220',conversations:'44',orders:'12',spend:'84',revenue:'0',contribution:'0',repeat:'3',customers:'12'}
const defaultEvents:EventRow[]=[
 {name:'PageView',expected:'1 por página',ga4:false,meta:false,tiktok:false},
 {name:'view_item',expected:'1 por oferta vista',ga4:false,meta:false,tiktok:false},
 {name:'click_whatsapp',expected:'1 por clique real',ga4:false,meta:false,tiktok:false},
 {name:'purchase',expected:'1 por pedido realmente confirmado',ga4:false,meta:false,tiktok:false},
]
const defaultRadius:RadiusRow[]=[{km:1,minutes:'',texture:false,leak:false,presentation:false},{km:2,minutes:'',texture:false,leak:false,presentation:false},{km:3,minutes:'',texture:false,leak:false,presentation:false}]
const offers:Offer[]=[
 {id:1,name:'Herói completo',structure:'Herói + acompanhamento + bebida.',test:'Tíquete e contribuição.',guard:'Mostre preço avulso real e economia somente se existirem.'},
 {id:2,name:'Solo / divide / festa',structure:'Mesmo núcleo em três quantidades alinhadas à ocasião.',test:'Mix de tamanhos e perda.',guard:'Quantidade e rendimento precisam ser testados.'},
 {id:3,name:'Adicional inteligente',structure:'Molho, bebida, doce ou complemento com afinidade e contribuição.',test:'Taxa de adesão.',guard:'Adicional nunca pode ser obrigatório e escondido.'},
 {id:4,name:'Janela ociosa',structure:'Benefício real para horário de baixa.',test:'Pedidos incrementais.',guard:'Não desloque o pico para uma janela com prejuízo.'},
 {id:5,name:'Primeira prova',structure:'Formato menor, bônus de custo controlado ou retirada.',test:'CPA + recompra em 30 dias.',guard:'Não transforme aquisição em desconto sem limite.'},
 {id:6,name:'Pré-venda limitada',structure:'Reserva por capacidade real e produção programada.',test:'Ocupação e cancelamento.',guard:'Só use limite se a capacidade for realmente limitada.'},
 {id:7,name:'Família sem caos',structure:'Escolha reduzida e quantidade clara para uma refeição.',test:'Erro, atraso e contribuição.',guard:'Pare se aumentar erro ou atraso.'},
 {id:8,name:'Degustação',structure:'Porções menores de sabores cruzados para descoberta.',test:'Recompra do favorito.',guard:'Controle custo e validade dos sabores extras.'},
 {id:9,name:'Presenteável',structure:'Produto + embalagem + cartão + janela de entrega.',test:'Conversão e contribuição.',guard:'Inclua embalagem, cartão e entrega no custo.'},
 {id:10,name:'Recuperação',structure:'Contato consentido para cliente dormente.',test:'Retorno e opt-out.',guard:'Dê saída simples e respeite consentimento.'},
 {id:11,name:'Recompra',structure:'Convite após satisfação para próxima ocasião ou complemento.',test:'Recompra em 7/30 dias.',guard:'Não envie para quem recusou comunicação.'},
 {id:12,name:'Recorrência',structure:'Plano semanal depois de demanda comprovada.',test:'Churn e margem.',guard:'Só depois de capacidade e cancelamento claros.'},
]
function num(v:string){const n=Number(String(v).replace(',','.'));return Number.isFinite(n)?n:0}
function pct(v:number){return Number.isFinite(v)?`${(v*100).toLocaleString('pt-BR',{maximumFractionDigits:2})}%`:'—'}
function brl(v:number){return new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:2}).format(Number.isFinite(v)?v:0)}
function safeJSON<T>(raw:string|null,fallback:T):T{try{return raw?JSON.parse(raw):fallback}catch{return fallback}}

export function GrowthLabRoute(){
 const token=localStorage.getItem('c360_token')||''
 const[businesses,setBusinesses]=useState<Business[]>([]);const[businessId,setBusinessId]=useState(0);const[products,setProducts]=useState<Product[]>([]);const[dashboard,setDashboard]=useState<Dashboard|null>(null);const[finance,setFinance]=useState<Finance|null>(null);const[tab,setTab]=useState<Tab>('metrics');const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[copied,setCopied]=useState('')
 const[metrics,setMetrics]=useState<Metrics>(defaultMetrics);const[events,setEvents]=useState<EventRow[]>(defaultEvents);const[radius,setRadius]=useState<RadiusRow[]>(defaultRadius);const[selectedOffer,setSelectedOffer]=useState(1);const[offerNote,setOfferNote]=useState('')
 function persist(id:number,next?:Partial<{metrics:Metrics;events:EventRow[];radius:RadiusRow[];selectedOffer:number;offerNote:string}>){if(!id)return;localStorage.setItem(`c360-growth-v23-${id}`,JSON.stringify({metrics:next?.metrics??metrics,events:next?.events??events,radius:next?.radius??radius,selectedOffer:next?.selectedOffer??selectedOffer,offerNote:next?.offerNote??offerNote}))}
 async function load(target=businessId){if(!token){setLoading(false);return}setError('');try{let id=target;if(!businesses.length){const me=await request('/me',{},token);const rows=(me.businesses||[])as Business[];setBusinesses(rows);id=id||Number(rows[0]?.id||0);if(id)setBusinessId(id)}if(!id)return;const[p,d,f]=await Promise.all([request(`/businesses/${id}/products`,{},token),request(`/businesses/${id}/dashboard`,{},token),request(`/businesses/${id}/finance/summary?days=30`,{},token)]);setProducts(p);setDashboard(d);setFinance(f);const saved=safeJSON(localStorage.getItem(`c360-growth-v23-${id}`),{metrics:defaultMetrics,events:defaultEvents,radius:defaultRadius,selectedOffer:1,offerNote:''});setMetrics(saved.metrics||defaultMetrics);setEvents(saved.events||defaultEvents);setRadius(saved.radius||defaultRadius);setSelectedOffer(saved.selectedOffer||1);setOfferNote(saved.offerNote||'')}catch(e){setError(e instanceof Error?e.message:'Não foi possível montar o Growth Lab')}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 const m=useMemo(()=>{const impressions=num(metrics.impressions),clicks=num(metrics.clicks),conversations=num(metrics.conversations),orders=num(metrics.orders),spend=num(metrics.spend),revenue=num(metrics.revenue),contribution=num(metrics.contribution),repeat=num(metrics.repeat),customers=num(metrics.customers);return{ctr:impressions?clicks/impressions:0,cpc:clicks?spend/clicks:0,costConversation:conversations?spend/conversations:0,conversion:conversations?orders/conversations:0,cpa:orders?spend/orders:0,roas:spend?revenue/spend:0,postMedia:contribution-spend,repurchase:customers?repeat/customers:0}},[metrics])
 const systemCpa=safeJSON(localStorage.getItem(`c360-system360-cpa-${businessId}`),{max:'0'});const cpaMax=num(systemCpa.max);const cpaHealthy=cpaMax>0&&m.cpa>0&&m.cpa<=cpaMax
 const eventScore=events.reduce((sum,e)=>sum+[e.ga4,e.meta,e.tiktok].filter(Boolean).length,0);const eventTotal=events.length*3;const eventPct=Math.round(eventScore/eventTotal*100)
 const farthest=radius.filter(r=>num(r.minutes)>0&&r.texture&&r.leak&&r.presentation).sort((a,b)=>b.km-a.km)[0]?.km||0
 const currentOffer=offers.find(x=>x.id===selectedOffer)||offers[0];const hero=products.find(p=>p.active)?.name||'[PRODUTO]';const offerCopy=`${currentOffer.name}: ${currentOffer.structure} Produto-base: ${hero}. Hipótese: ${offerNote||currentOffer.test} Critério: ${currentOffer.test} Regra: ${currentOffer.guard}`
 const delayRate=Math.round(Number(dashboard?.delay_rate||0)*100);const paid30=Number(finance?.order_count||0)
 function setMetric(k:keyof Metrics,v:string){const next={...metrics,[k]:v};setMetrics(next);persist(businessId,{metrics:next})}
 function toggleEvent(i:number,channel:'ga4'|'meta'|'tiktok'){const next=events.map((e,idx)=>idx===i?{...e,[channel]:!e[channel]}:e);setEvents(next);persist(businessId,{events:next})}
 function setRadiusRow(i:number,patch:Partial<RadiusRow>){const next=radius.map((r,idx)=>idx===i?{...r,...patch}:r);setRadius(next);persist(businessId,{radius:next})}
 async function copy(label:string,value:string){try{await navigator.clipboard.writeText(value);setCopied(label);setTimeout(()=>setCopied(''),1500)}catch{/* no clipboard */}}
 if(!token)return <main className="grw-shell grw-center"><div className="grw-empty"><Flame/><h1>Entre na operação.</h1><p>Growth Lab precisa de uma cozinha ativa para cruzar mídia e operação.</p><a href="/">Entrar</a></div></main>
 if(loading)return <main className="grw-shell grw-center"><div className="grw-loader"><Gauge/>CALCULANDO GROWTH LAB</div></main>
 return <main className="grw-shell"><header className="grw-topbar"><a href="/?system360=1"><ArrowLeft/> Sistema 360</a><b><Flame/> GROWTH LAB <span>MENSURAR · TESTAR · PARAR</span></b><div>{businesses.length>1&&<select value={businessId} onChange={async e=>{const id=Number(e.target.value);setBusinessId(id);await load(id)}}>{businesses.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select>}<button onClick={()=>load()}><RefreshCcw/></button></div></header><section className="grw-page">
  <div className="grw-hero"><div><span>COZINHA DE BOLSO 360 · MOTORES TRÁFEGO + OFERTA</span><h1>Mídia só cresce quando o sinal e a cozinha concordam.</h1><p>Este laboratório converte o mapa de dados, o teste de eventos, o raio real e os 12 modelos de oferta em instrumentos de decisão.</p></div><div className="grw-live"><div><span>Pedidos pagos 30d</span><b>{paid30}</b></div><div><span>Atraso atual</span><b>{delayRate}%</b></div><div><span>CPA máx. salvo</span><b>{cpaMax?brl(cpaMax):'—'}</b></div></div></div>{error&&<div className="grw-error">{error}</div>}
  <nav className="grw-tabs"><button className={tab==='metrics'?'active':''} onClick={()=>setTab('metrics')}><BarChart3/>Métricas</button><button className={tab==='events'?'active':''} onClick={()=>setTab('events')}><ShieldCheck/>Event QA</button><button className={tab==='radius'?'active':''} onClick={()=>setTab('radius')}><MapPinned/>Radius Test</button><button className={tab==='offers'?'active':''} onClick={()=>setTab('offers')}><Megaphone/>Offer Lab</button></nav>
  {tab==='metrics'&&<section className="grw-tool"><div className="grw-head"><div><span>MÉTRICAS SEM NEBLINA</span><h2>Acompanhe o funil até o dinheiro que sobra.</h2></div><CircleDollarSign/></div><div className="grw-metric-inputs"><MetricInput label="Impressões" value={metrics.impressions} onChange={v=>setMetric('impressions',v)}/><MetricInput label="Cliques" value={metrics.clicks} onChange={v=>setMetric('clicks',v)}/><MetricInput label="Conversas" value={metrics.conversations} onChange={v=>setMetric('conversations',v)}/><MetricInput label="Pedidos pagos" value={metrics.orders} onChange={v=>setMetric('orders',v)}/><MetricInput label="Gasto mídia (R$)" value={metrics.spend} onChange={v=>setMetric('spend',v)}/><MetricInput label="Receita atribuída (R$)" value={metrics.revenue} onChange={v=>setMetric('revenue',v)}/><MetricInput label="Contribuição antes da mídia (R$)" value={metrics.contribution} onChange={v=>setMetric('contribution',v)}/><MetricInput label="Recompras 30d" value={metrics.repeat} onChange={v=>setMetric('repeat',v)}/><MetricInput label="Clientes" value={metrics.customers} onChange={v=>setMetric('customers',v)}/></div><div className="grw-results"><Result label="CTR" value={pct(m.ctr)} note="cliques ÷ impressões"/><Result label="CPC" value={brl(m.cpc)} note="gasto ÷ cliques"/><Result label="Custo/conversa" value={brl(m.costConversation)} note="gasto ÷ conversas"/><Result label="Conversão" value={pct(m.conversion)} note="pedidos ÷ conversas"/><Result label="CPA" value={brl(m.cpa)} note={cpaMax?`teto salvo ${brl(cpaMax)}`:'compare ao teto do Sistema 360'} status={cpaMax&&m.cpa?(cpaHealthy?'ok':'bad'):undefined}/><Result label="ROAS" value={`${m.roas.toLocaleString('pt-BR',{maximumFractionDigits:2})}x`} note="receita ÷ mídia"/><Result label="Contribuição pós-mídia" value={brl(m.postMedia)} note="contribuição - mídia" status={m.postMedia>=0?'ok':'bad'}/><Result label="Recompra 30d" value={pct(m.repurchase)} note="recompras ÷ clientes"/></div><div className={`grw-decision ${cpaMax&&m.cpa&&!cpaHealthy?'stop':'go'}`}>{cpaMax&&m.cpa&&!cpaHealthy?<TriangleAlert/>:<Target/>}<div><b>{cpaMax&&m.cpa&&!cpaHealthy?'PAUSAR E RECALCULAR':'DECISÃO POR SINAL'}</b><span>{cpaMax&&m.cpa&&!cpaHealthy?`CPA ${brl(m.cpa)} está acima do teto ${brl(cpaMax)}. Não aumente orçamento.`:'Escala exige CPA saudável, contribuição pós-mídia positiva e operação sem atraso.'}</span></div></div></section>}
  {tab==='events'&&<section className="grw-tool"><div className="grw-head"><div><span>CHECKLIST DE PUBLICAÇÃO</span><h2>Nada está instalado até provar o caminho completo.</h2></div><ShieldCheck/></div><div className="grw-event-score"><strong>{eventPct}%</strong><span>{eventScore}/{eventTotal} confirmações marcadas</span><div><i style={{width:`${eventPct}%`}}/></div></div><div className="grw-event-table"><header><span>Evento</span><span>Esperado</span><span>GA4</span><span>Meta</span><span>TikTok</span></header>{events.map((e,i)=><div key={e.name}><b>{e.name}</b><span>{e.expected}</span><button className={e.ga4?'ok':''} onClick={()=>toggleEvent(i,'ga4')}>{e.ga4?<Check/>:'—'}</button><button className={e.meta?'ok':''} onClick={()=>toggleEvent(i,'meta')}>{e.meta?<Check/>:'—'}</button><button className={e.tiktok?'ok':''} onClick={()=>toggleEvent(i,'tiktok')}>{e.tiktok?<Check/>:'—'}</button></div>)}</div><div className="grw-qa-note"><ShieldCheck/><div><b>Prova mínima</b><span>Prévia/Debug → visita real → clique real → pedido realmente confirmado → conferir duplicidade e valor coerente. Clique no WhatsApp não é compra.</span></div></div></section>}
  {tab==='radius'&&<section className="grw-tool"><div className="grw-head"><div><span>O RAIO NASCE DO PRODUTO</span><h2>1 km, 2 km e 3 km são testes — não mandamento.</h2></div><MapPinned/></div><div className="grw-radius-result"><div><span>RAIO APROVADO</span><strong>{farthest?`${farthest} km`:'—'}</strong></div><p>O app só aprova um trajeto quando há tempo registrado e textura, vazamento e apresentação passam juntos.</p></div><div className="grw-radius-grid">{radius.map((r,i)=><article key={r.km}><header><MapPinned/><b>{r.km} km</b></header><label>Tempo porta a porta<input type="number" inputMode="numeric" value={r.minutes} onChange={e=>setRadiusRow(i,{minutes:e.target.value})} placeholder="min"/></label><Toggle label="Textura passa" value={r.texture} onChange={v=>setRadiusRow(i,{texture:v})}/><Toggle label="Sem vazamento" value={r.leak} onChange={v=>setRadiusRow(i,{leak:v})}/><Toggle label="Apresentação passa" value={r.presentation} onChange={v=>setRadiusRow(i,{presentation:v})}/><footer className={num(r.minutes)>0&&r.texture&&r.leak&&r.presentation?'pass':'fail'}>{num(r.minutes)>0&&r.texture&&r.leak&&r.presentation?'PASSA':'AINDA NÃO PASSA'}</footer></article>)}</div><div className="grw-qa-note"><TriangleAlert/><div><b>Repita no pior contexto relevante</b><span>Faça o mesmo trajeto em pico e chuva quando isso muda a operação. Defina o limite pelo pior trajeto aceitável, não pela média otimista.</span></div></div></section>}
  {tab==='offers'&&<section className="grw-tool"><div className="grw-head"><div><span>12 OFERTAS QUE PRESERVAM MARGEM</span><h2>Copie a estrutura. Nunca copie números.</h2></div><Megaphone/></div><div className="grw-offer-layout"><div className="grw-offer-list">{offers.map(o=><button key={o.id} className={selectedOffer===o.id?'active':''} onClick={()=>{setSelectedOffer(o.id);persist(businessId,{selectedOffer:o.id})}}><span>{String(o.id).padStart(2,'0')}</span><div><b>{o.name}</b><small>{o.structure}</small></div><ChevronRight/></button>)}</div><aside className="grw-offer-editor"><span>OFERTA SELECIONADA</span><h3>{currentOffer.name}</h3><p>{currentOffer.structure}</p><div className="grw-offer-rule"><b>Teste</b><span>{currentOffer.test}</span></div><div className="grw-offer-rule"><b>Regra</b><span>{currentOffer.guard}</span></div><label>Hipótese desta cozinha<textarea value={offerNote} onChange={e=>{setOfferNote(e.target.value);persist(businessId,{offerNote:e.target.value})}} placeholder="O que precisa acontecer para considerar este teste útil?"/></label><div className="grw-offer-copy"><p>{offerCopy}</p><button onClick={()=>copy('offer',offerCopy)}>{copied==='offer'?<Check/>:<Copy/>}{copied==='offer'?'Copiado':'Copiar plano'}</button></div><a href="/?vitrine=1">Levar para Vitrine Studio <ChevronRight/></a></aside></div></section>}
 </section></main>
}
function MetricInput({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label>{label}<input inputMode="decimal" value={value} onChange={e=>onChange(e.target.value)}/></label>}
function Result({label,value,note,status}:{label:string;value:string;note:string;status?:'ok'|'bad'}){return <article className={status||''}><span>{label}</span><strong>{value}</strong><small>{note}</small></article>}
function Toggle({label,value,onChange}:{label:string;value:boolean;onChange:(v:boolean)=>void}){return <button className={`grw-toggle ${value?'on':''}`} onClick={()=>onChange(!value)}><i>{value?<Check/>:'—'}</i><span>{label}</span></button>}
