import React,{useEffect,useMemo,useState}from'react'
import{ArrowLeft,ArrowRight,Building2,Check,CheckCircle2,ChevronDown,CloudCog,CreditCard,ExternalLink,FileText,Link2,MapPinned,RefreshCcw,Route,Settings2,ShieldCheck,Sparkles,Store,Unplug,WifiOff,Zap}from'lucide-react'
import{request}from'./app'
import'./integration-setup-v42.css'

const SETUP_API=import.meta.env.VITE_SETUP_API_URL||'https://npgheuzpnkwtxopswpqy.supabase.co/functions/v1/cozinha360-setup-v42'
type Business={id:number;name:string;city?:string}
type Brand={id:number;name:string;slug:string|null;active:boolean;primary_channel:string}
type Connection={id:number;provider:string;display_name:string|null;status:string;last_success_at:string|null;last_error:string|null}
type Provider={key:string;name:string;category:string;kind:string;setup:string;purpose:string;recommended:boolean;state:string;connection:Connection|null}
type Binding={id:number;brand_id:number;connection_id:number;channel_id:number|null;provider:string;external_store_ref:string|null;order_import_enabled:boolean;menu_sync_enabled:boolean;price_sync_enabled:boolean;availability_sync_enabled:boolean;auto_accept_orders:boolean;active:boolean}
type Fiscal={brand_id:number;legal_name:string|null;tax_id:string|null;state_registration:string|null;municipal_registration:string|null;tax_regime:string;fiscal_provider:string|null;provider_profile_ref:string|null;issuance_enabled:boolean;active:boolean}
type Settings={route_provider:string;route_mode:string;route_optimization_enabled:boolean;customer_tracking_enabled:boolean;whatsapp_status_updates:boolean}
type Setup={version:string;business_id:number;brands:Brand[];connections:Connection[];providers:Provider[];bindings:Binding[];fiscal_profiles:Fiscal[];settings:Settings;summary:{active_brands:number;active_connections:number;unbound_connections:number;fiscal_configured:number;route_mode:string;route_provider:string};next_actions:string[]}

type FiscalDraft={legal_name:string;tax_id:string;tax_regime:string;state_registration:string;municipal_registration:string}
const providerIcon:Record<string,React.ElementType>={direct:Store,whatsapp:Link2,mercadopago:CreditCard,ifood:Store,google:Building2,meta_ads:Zap,'99food':Store,keeta:Store,maps_google:MapPinned,mapbox:MapPinned}
const providerLabel:Record<string,string>={direct:'Loja própria',whatsapp:'WhatsApp',mercadopago:'Mercado Pago',ifood:'iFood',google:'Google',meta_ads:'Meta Ads','99food':'99Food',keeta:'Keeta',maps_google:'Google Maps',mapbox:'Mapbox'}
const statusText:Record<string,string>={active:'ATIVO',attention:'ATENÇÃO',connecting:'CONECTANDO',partner_onboarding:'PARCERIA/ACESSO',platform_setup:'CHAVE DA PLATAFORMA',not_connected:'CONECTAR',available:'DISPONÍVEL'}

async function sreq(path:string,token:string,options:RequestInit={}){const r=await fetch(`${SETUP_API}${path}`,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,...(options.headers||{})}});const data=await r.json().catch(()=>({detail:'Resposta inválida'}));if(!r.ok){const e:any=new Error(data.detail||'Não foi possível concluir');e.body=data;throw e}return data}

export function IntegrationSetupLauncher(){return <a className="setup42-launcher" href="/?setup=1"><Sparkles size={16}/><span>Configuração inteligente</span></a>}

export function IntegrationSetupV42Route(){
 const token=localStorage.getItem('c360_token')||''
 const[businesses,setBusinesses]=useState<Business[]>([]),[businessId,setBusinessId]=useState(0),[data,setData]=useState<Setup|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('')
 const[routeMode,setRouteMode]=useState('manual'),[routeProvider,setRouteProvider]=useState('manual'),[tracking,setTracking]=useState(false),[whatsappStatus,setWhatsappStatus]=useState(false)
 const[fiscalDrafts,setFiscalDrafts]=useState<Record<number,FiscalDraft>>({})
 async function load(target=businessId){setLoading(true);setError('');try{let id=target;if(!businesses.length){const me=await request('/me',{},token);const rows=(me.businesses||[]) as Business[];setBusinesses(rows);id=id||Number(rows[0]?.id||0);if(id)setBusinessId(id)}if(!id){setData(null);return}const next=await sreq(`/businesses/${id}/setup`,token) as Setup;setData(next);setRouteMode(next.settings.route_mode||'manual');setRouteProvider(next.settings.route_provider||'manual');setTracking(Boolean(next.settings.customer_tracking_enabled));setWhatsappStatus(Boolean(next.settings.whatsapp_status_updates));const drafts:Record<number,FiscalDraft>={};for(const brand of next.brands){const f=next.fiscal_profiles.find(x=>x.brand_id===brand.id);drafts[brand.id]={legal_name:f?.legal_name||'',tax_id:f?.tax_id||'',tax_regime:f?.tax_regime||'unconfigured',state_registration:f?.state_registration||'',municipal_registration:f?.municipal_registration||''}}setFiscalDrafts(drafts)}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar a configuração.')}finally{setLoading(false)}}
 useEffect(()=>{if(!token){location.replace('/');return}void load()},[])
 const activeConnections=useMemo(()=>data?.connections.filter(c=>c.status==='active')||[],[data])
 const bindable=useMemo(()=>activeConnections.filter(c=>['ifood','whatsapp','mercadopago'].includes(c.provider)),[activeConnections])
 const bindableProviders=useMemo(()=>[...new Set(bindable.map(c=>c.provider))],[bindable])
 const routeProviders=useMemo(()=>{const out:string[]=[];if(data?.providers.some(p=>p.key==='maps_google'&&p.state==='active'))out.push('google');if(data?.providers.some(p=>p.key==='mapbox'&&p.state==='active'))out.push('mapbox');return out},[data])
 const mapReady=routeProviders.length>0
 async function mutate(path:string,method:'POST'|'PUT'|'DELETE',payload:any,ok:string){if(!businessId)return null;setBusy(path);setError('');setNotice('');try{const r=await sreq(`/businesses/${businessId}/${path}`,token,{method,body:method==='DELETE'?undefined:JSON.stringify(payload)});setNotice(ok);await load(businessId);return r}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar.');return null}finally{setBusy('')}}
 async function setBinding(brand:Brand,connection:Connection){const label=providerLabel[connection.provider]||connection.provider,account=connection.display_name||`${label} #${connection.id}`;await mutate('bindings','POST',{brand_id:brand.id,connection_id:connection.id,provider:connection.provider,order_import_enabled:['ifood','whatsapp'].includes(connection.provider),auto_accept_orders:false},`${label} · ${account} ligado à marca ${brand.name}.`)}
 async function removeBinding(brand:Brand,provider:string){const existing=data?.bindings.find(b=>b.brand_id===brand.id&&b.provider===provider&&b.active);if(existing)await mutate(`bindings/${existing.id}`,'DELETE',null,`${providerLabel[provider]||provider} removido de ${brand.name}.`)}
 async function toggleBinding(brand:Brand,connection:Connection){const existing=data?.bindings.find(b=>b.brand_id===brand.id&&b.provider===connection.provider&&b.active);if(existing?.connection_id===connection.id){await removeBinding(brand,connection.provider);return}await setBinding(brand,connection)}
 async function chooseBinding(brand:Brand,provider:string,connectionId:number){if(!connectionId){await removeBinding(brand,provider);return}const connection=bindable.find(c=>c.id===connectionId&&c.provider===provider);if(!connection){setError('A conta selecionada não está mais ativa. Atualize a página e tente novamente.');return}await setBinding(brand,connection)}
 async function saveFiscal(brand:Brand){const d=fiscalDrafts[brand.id];if(!d)return;await mutate(`fiscal/${brand.id}`,'PUT',{...d,issuance_enabled:false,active:true},`Dados fiscais de ${brand.name} salvos. A emissão continua desligada até um provedor fiscal real ser conectado.`)}
 async function saveRoute(){await mutate('route','PUT',{route_mode:routeMode,route_provider:routeMode==='manual'?'manual':routeProvider,customer_tracking_enabled:tracking,whatsapp_status_updates:whatsappStatus},routeMode==='manual'?'Roteamento manual salvo. Nenhuma API de mapas será cobrada.':'Configuração de logística salva.')}
 async function autoConfigure(){if(!businessId)return;setBusy('auto-configure');setError('');setNotice('');try{const r=await sreq(`/businesses/${businessId}/auto-configure`,token,{method:'POST',body:JSON.stringify({})});if(r.requires_review)setNotice('Operação multi-marca detectada. O 360 não distribuiu contas automaticamente para evitar pedidos, pagamentos ou clientes na marca errada. Escolha abaixo qual conta atende cada marca.');else if(Number(r.created_count||0)>0)setNotice(`${r.created_count} ${Number(r.created_count)===1?'vínculo configurado':'vínculos configurados'} automaticamente com segurança.`);else setNotice('Tudo que pode ser configurado automaticamente já está organizado.');await load(businessId)}catch(e){setError(e instanceof Error?e.message:'Não foi possível configurar automaticamente.')}finally{setBusy('')}}
 if(loading)return <main className="setup42-shell setup42-center"><div className="setup42-loading"><CloudCog/>Preparando uma configuração segura…</div></main>
 if(!data)return <main className="setup42-shell setup42-center"><div className="setup42-error"><WifiOff/><h1>Não há operação disponível.</h1><p>{error||'Entre novamente e tente outra vez.'}</p><a href="/">Voltar</a></div></main>
 const readyProviders=data.providers.filter(p=>p.state==='active').length
 return <main className="setup42-shell"><header className="setup42-top"><a href="/?connections=1"><ArrowLeft size={16}/>Conexões</a><a href="/" className="setup42-logo"><Sparkles size={18}/><b>SETUP 360</b><span>v4.2</span></a><div>{businesses.length>1&&<select value={businessId} onChange={e=>{const id=Number(e.target.value);setBusinessId(id);void load(id)}}>{businesses.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select>}<button onClick={()=>void load(businessId)} aria-label="Atualizar"><RefreshCcw size={15}/></button></div></header><section className="setup42-page">
  <header className="setup42-hero"><div><span>CONEXÕES SEM COMPLEXIDADE</span><h1>Conecte só o que sua cozinha realmente usa.</h1><p>O sistema separa funções nativas, contas conectadas, APIs que dependem de homologação e recursos que geram custo variável. Nenhum logo aparece como “ativo” sem conexão real.</p></div><aside><ShieldCheck/><div><b>{readyProviders}</b><span>recursos ativos</span></div><div><b>{data.summary.unbound_connections}</b><span>conexões para distribuir</span></div></aside></header>
  {notice&&<div className="setup42-banner ok"><CheckCircle2/>{notice}</div>}{error&&<div className="setup42-banner bad"><WifiOff/>{error}</div>}
  <section className="setup42-callout"><div><span>CONFIGURAÇÃO AUTOMÁTICA SEGURA</span><h2>Já conectou contas? Distribua em um clique.</h2><p>Com uma única marca, o 360 liga iFood, WhatsApp e Mercado Pago ativos automaticamente. Em operações multi-marca ele não adivinha: você escolhe abaixo qual conta atende cada marca, evitando pedidos e pagamentos no negócio errado.</p></div><button disabled={Boolean(busy)||!bindable.length||!data.brands.length} onClick={()=>void autoConfigure()}><Sparkles size={17}/>{busy==='auto-configure'?'Configurando…':'Configurar automaticamente'}</button></section>

  <section className="setup42-panel"><Head kicker="PASSO 1" title="O que está realmente disponível" meta={`${readyProviders}/${data.providers.length}`}/><div className="setup42-provider-grid">{data.providers.map(p=>{const Icon=providerIcon[p.key]||Settings2;const actionable=['whatsapp','mercadopago','ifood','google','meta_ads'].includes(p.key);return <article key={p.key} className={`state-${p.state}`}><div className="setup42-provider-icon"><Icon/></div><div className="setup42-provider-copy"><span>{p.category}</span><h3>{p.name}</h3><p>{p.purpose}</p></div><em>{statusText[p.state]||p.state}</em>{p.connection?.display_name&&<small>{p.connection.display_name}</small>}{p.connection?.last_error&&<small className="error">{p.connection.last_error}</small>}{p.state!=='active'&&actionable&&<a href="/?connections=1">Conectar <ArrowRight size={13}/></a>}{p.state==='partner_onboarding'&&<small>Sem promessa de API antes do acesso oficial do parceiro.</small>}{p.state==='platform_setup'&&<small>A chave de servidor é responsabilidade da plataforma, não do usuário final.</small>}</article>})}</div></section>

  <section className="setup42-panel"><Head kicker="PASSO 2" title="Qual conta atende qual marca?" meta={`${data.bindings.filter(b=>b.active).length} vínculos`}/>{data.brands.length?<div className="setup42-brand-matrix">{data.brands.map(brand=><article key={brand.id}><header><span>{brand.name.slice(0,2).toUpperCase()}</span><div><b>{brand.name}</b><small>{brand.slug?`/${brand.slug}`:'sem vitrine publicada'}</small></div></header><div className="setup42-chips">{bindableProviders.length?bindableProviders.map(provider=>{const options=bindable.filter(c=>c.provider===provider),current=data.bindings.find(b=>b.brand_id===brand.id&&b.provider===provider&&b.active),label=providerLabel[provider]||provider;if(options.length===1){const c=options[0],active=current?.connection_id===c.id;return <button key={provider} disabled={Boolean(busy)} className={active?'active':''} title={c.display_name||label} onClick={()=>void toggleBinding(brand,c)}>{active?<Check size={14}/>:<Link2 size={14}/>} {label}{c.display_name&&<small>{c.display_name}</small>}</button>}return <label className="setup42-account-picker" key={provider}><span>{label}<em>{options.length} contas</em></span><select aria-label={`${label} · ${brand.name}`} disabled={Boolean(busy)} value={current?.connection_id||''} onChange={e=>void chooseBinding(brand,provider,Number(e.target.value))}><option value="">Escolha a conta</option>{options.map(c=><option key={c.id} value={c.id}>{c.display_name||`${label} #${c.id}`}</option>)}</select><small>{current?'Conta vinculada explicitamente a esta marca.':'Selecione a conta correta; o 360 não escolhe por você.'}</small></label>}):<span className="setup42-muted">Conecte iFood, WhatsApp ou Mercado Pago para distribuir contas entre marcas.</span>}</div></article>)}</div>:<Empty icon={Store} title="Crie a primeira marca" text="O vínculo por marca aparece quando existe uma marca operacional."/>}</section>

  <div className="setup42-columns"><section className="setup42-panel"><Head kicker="PASSO 3" title="Dados fiscais sem ativação falsa"/><p className="setup42-lead">Cadastre a identidade fiscal de cada marca agora. Emissão automática só será liberada quando um provedor fiscal compatível estiver conectado e validado.</p>{data.brands.map(brand=>{const d=fiscalDrafts[brand.id]||{legal_name:'',tax_id:'',tax_regime:'unconfigured',state_registration:'',municipal_registration:''};return <details key={brand.id} className="setup42-fiscal"><summary><div><FileText/><span><b>{brand.name}</b><small>{d.tax_id||'dados fiscais ainda não preenchidos'}</small></span></div><ChevronDown/></summary><div className="setup42-form-grid"><label>Razão social<input value={d.legal_name} onChange={e=>setFiscalDrafts(x=>({...x,[brand.id]:{...d,legal_name:e.target.value}}))}/></label><label>CNPJ / documento<input value={d.tax_id} onChange={e=>setFiscalDrafts(x=>({...x,[brand.id]:{...d,tax_id:e.target.value}}))}/></label><label>Regime<select value={d.tax_regime} onChange={e=>setFiscalDrafts(x=>({...x,[brand.id]:{...d,tax_regime:e.target.value}}))}><option value="unconfigured">Não definido</option><option value="mei">MEI</option><option value="simples">Simples Nacional</option><option value="presumed">Lucro presumido</option><option value="real">Lucro real</option><option value="other">Outro</option></select></label><label>Inscrição estadual<input value={d.state_registration} onChange={e=>setFiscalDrafts(x=>({...x,[brand.id]:{...d,state_registration:e.target.value}}))}/></label><label>Inscrição municipal<input value={d.municipal_registration} onChange={e=>setFiscalDrafts(x=>({...x,[brand.id]:{...d,municipal_registration:e.target.value}}))}/></label></div><button className="setup42-primary" disabled={Boolean(busy)} onClick={()=>void saveFiscal(brand)}>Salvar dados fiscais</button></details>})}</section>
   <section className="setup42-panel"><Head kicker="PASSO 4" title="Logística sem conta surpresa"/><div className="setup42-route-choice"><button className={routeMode==='manual'?'active':''} onClick={()=>{setRouteMode('manual');setRouteProvider('manual')}}><Route/><b>Manual</b><span>R$ 0 em API de mapa</span></button><button disabled={!mapReady} className={routeMode==='assisted'?'active':''} onClick={()=>{setRouteMode('assisted');if(!routeProviders.includes(routeProvider))setRouteProvider(routeProviders[0]||'manual')}}><MapPinned/><b>Assistida</b><span>ETA/distância com provider</span></button><button disabled={!mapReady} className={routeMode==='intelligent'?'active':''} onClick={()=>{setRouteMode('intelligent');if(!routeProviders.includes(routeProvider))setRouteProvider(routeProviders[0]||'manual')}}><Sparkles/><b>Inteligente</b><span>otimização com provider validado</span></button></div>{routeMode!=='manual'&&<label className="setup42-field">Provedor<select value={routeProvider==='manual'?'':routeProvider} onChange={e=>setRouteProvider(e.target.value)}><option value="">Escolher</option>{routeProviders.includes('google')&&<option value="google">Google Maps Routes</option>}{routeProviders.includes('mapbox')&&<option value="mapbox">Mapbox</option>}</select></label>}<label className="setup42-switch"><span><b>Tracking para o cliente</b><small>Status funciona nativamente; mapa ao vivo depende do provider.</small></span><input type="checkbox" checked={tracking} onChange={e=>setTracking(e.target.checked)}/></label><label className="setup42-switch"><span><b>Avisos pelo WhatsApp</b><small>Só serão enviados com conexão oficial ativa.</small></span><input type="checkbox" checked={whatsappStatus} onChange={e=>setWhatsappStatus(e.target.checked)}/></label><button className="setup42-primary" disabled={Boolean(busy)||routeMode!=='manual'&&!routeProviders.includes(routeProvider)} onClick={()=>void saveRoute()}>Salvar logística</button><div className="setup42-cost-note"><CloudCog/><p><b>Regra de custo:</b> agrupamento manual continua no Cozinha 360. Rotas otimizadas, geocoding, mensagens, gateway e marketplaces podem ter cobrança externa e ficam separados da mensalidade.</p></div></section></div>

  <section className="setup42-final"><div><span>ESTADO DA OPERAÇÃO</span><h2>{data.summary.unbound_connections?'Há conexões prontas para distribuir.':'Sua base de conexões está coerente.'}</h2><p>{data.summary.active_brands} marca(s) ativa(s) · {data.summary.active_connections} conta(s) conectada(s) · logística {data.summary.route_mode||'manual'}.</p></div><div><a href="/?connections=1">Gerenciar autorizações <ExternalLink/></a><a href="/?delivery=1" className="primary">Abrir Delivery 360 <ArrowRight/></a></div></section>
 </section></main>
}

function Head({kicker,title,meta}:{kicker:string;title:string;meta?:string}){return <header className="setup42-head"><div><span>{kicker}</span><h2>{title}</h2></div>{meta&&<b>{meta}</b>}</header>}
function Empty({icon:Icon,title,text}:{icon:React.ElementType;title:string;text:string}){return <div className="setup42-empty"><Icon/><b>{title}</b><span>{text}</span></div>}
