import React, { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { BarChart3, ChefHat, CircleDollarSign, ClipboardList, LogOut, Package, Plus, RefreshCcw, ShoppingBag, Users } from 'lucide-react'
import './styles.css'

const API = import.meta.env.VITE_API_URL || '/api'

type User = { id:number; email:string; full_name:string }
type Business = { id:number; name:string; city:string; role:string; preferences:Record<string,unknown> }
type Pulse = { revenue_cents:number; contribution_cents:number; loss_cents:number }
type Dashboard = { pulse:Pulse; open_orders:number; delay_rate:number; error_rate:number; next_action:{code:string;title:string;severity:string} }
type Ingredient = { id:number; name:string; unit:string; last_purchase_price_cents:number; usable_qty_milliunits:number; version:number }

const money=(c=0)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(c/100)

async function request(path:string, options:RequestInit={}, token?:string){
  const res=await fetch(`${API}${path}`,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{ }),...(options.headers||{})}})
  const body=await res.json().catch(()=>({detail:'Resposta inválida'}))
  if(!res.ok) throw new Error(typeof body.detail==='string'?body.detail:'Não foi possível concluir')
  return body
}

function Auth({onAuth}:{onAuth:(token:string)=>void}){
  const [mode,setMode]=useState<'login'|'signup'>('login'); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [name,setName]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false)
  async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const body=await request(`/auth/${mode}`,{method:'POST',body:JSON.stringify(mode==='signup'?{email,password,full_name:name}:{email,password})});localStorage.setItem('c360_token',body.access_token);onAuth(body.access_token)}catch(err){setError(err instanceof Error?err.message:'Erro')}finally{setBusy(false)}}
  return <main className="auth-shell"><section className="brand-panel"><div className="brand"><ChefHat size={28}/><span>COZINHA 360</span></div><h1>Seu negócio de comida toma decisões com você.</h1><p>Custos, margem, capacidade e pedidos em um fluxo simples.</p><div className="brand-proof"><b>Sem fantasia.</b><span>O app mostra o que fazer antes de pedir mais vendas.</span></div></section><section className="auth-card"><h2>{mode==='login'?'Entrar':'Criar sua cozinha'}</h2><p>{mode==='login'?'Acesse sua operação.':'Comece com uma conta e um negócio próprio.'}</p><form onSubmit={submit}>{mode==='signup'&&<label>Nome<input value={name} onChange={e=>setName(e.target.value)} placeholder="Seu nome" required/></label>}<label>E-mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="voce@empresa.com" required/></label><label>Senha<input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={10} placeholder="Mínimo 10 caracteres" required/></label>{error&&<div className="error">{error}</div>}<button className="primary" disabled={busy}>{busy?'Aguarde...':mode==='login'?'Entrar':'Criar conta'}</button></form><button className="link" onClick={()=>setMode(mode==='login'?'signup':'login')}>{mode==='login'?'Ainda não tenho conta':'Já tenho conta'}</button></section></main>
}

function EmptyBusiness({token,onCreated}:{token:string;onCreated:()=>void}){const [name,setName]=useState('');const[city,setCity]=useState('');const[error,setError]=useState('');async function submit(e:React.FormEvent){e.preventDefault();try{await request('/businesses',{method:'POST',body:JSON.stringify({name,city})},token);onCreated()}catch(err){setError(err instanceof Error?err.message:'Erro')}}return <main className="center"><div className="empty-card"><ChefHat size={36}/><h2>Crie sua primeira operação</h2><p>Você terá uma área privada para produtos, custos, pedidos e financeiro.</p><form onSubmit={submit}><input value={name} onChange={e=>setName(e.target.value)} placeholder="Ex.: Brasa da Ana" required/><input value={city} onChange={e=>setCity(e.target.value)} placeholder="Cidade"/><button className="primary">Criar negócio</button>{error&&<div className="error">{error}</div>}</form></div></main>}

function App(){
 const [token,setToken]=useState(localStorage.getItem('c360_token')||'');const[user,setUser]=useState<User|null>(null);const[businesses,setBusinesses]=useState<Business[]>([]);const[businessId,setBusinessId]=useState<number|null>(null);const[dashboard,setDashboard]=useState<Dashboard|null>(null);const[ingredients,setIngredients]=useState<Ingredient[]>([]);const[tab,setTab]=useState('hoje');const[loading,setLoading]=useState(true);const[modal,setModal]=useState<string|null>(null);const[notice,setNotice]=useState('')
 async function loadMe(t=token){if(!t){setLoading(false);return}try{const me=await request('/me',{},t);setUser(me.user);setBusinesses(me.businesses);const id=businessId||me.businesses?.[0]?.id||null;setBusinessId(id);if(id)await loadBusiness(id,t)}catch{logout()}finally{setLoading(false)}}
 async function loadBusiness(id:number,t=token){const [d,i]=await Promise.all([request(`/businesses/${id}/dashboard`,{},t),request(`/businesses/${id}/ingredients`,{},t)]);setDashboard(d);setIngredients(i)}
 useEffect(()=>{loadMe()},[token])
 function logout(){localStorage.removeItem('c360_token');setToken('');setUser(null);setBusinesses([]);setBusinessId(null)}
 function quick(kind:string){if(!businessId)return;setModal(kind)}
 if(loading)return <main className="center"><div className="loader">COZINHA 360</div></main>
 if(!token)return <Auth onAuth={setToken}/>
 if(!businesses.length)return <EmptyBusiness token={token} onCreated={()=>loadMe()}/>
 const current=businesses.find(b=>b.id===businessId)||businesses[0]
 return <div className="app-shell"><aside><div className="brand small"><ChefHat size={24}/><span>COZINHA 360</span></div><nav>{[['hoje',BarChart3,'Hoje'],['custos',CircleDollarSign,'Custos'],['pedidos',ClipboardList,'Pedidos'],['clientes',Users,'Clientes'],['vender',ShoppingBag,'Vender'],['mais',Package,'Mais']].map(([id,Icon,label])=><button key={String(id)} className={tab===id?'active':''} onClick={()=>setTab(String(id))}>{React.createElement(Icon as React.ElementType,{size:19})}<span>{String(label)}</span></button>)}</nav><button className="logout" onClick={logout}><LogOut size={18}/>Sair</button></aside><main className="workspace"><header><div><span className="eyebrow">{current.city||'Sua operação'}</span><h2>{current.name}</h2></div><div className="user-chip">{user?.full_name||user?.email}</div></header>{notice&&<div className="notice">{notice}</div>}{tab==='hoje'&&<Today d={dashboard} onQuick={quick} onRefresh={()=>businessId&&loadBusiness(businessId)}/>} {tab==='custos'&&<Costs ingredients={ingredients} onAdd={()=>setModal('ingredient')}/>} {tab!=='hoje'&&tab!=='custos'&&<ComingSoon tab={tab}/>}</main>{modal&&businessId&&<QuickModal kind={modal} businessId={businessId} token={token} onClose={()=>setModal(null)} onDone={async(msg)=>{setModal(null);setNotice(msg);await loadBusiness(businessId)}}/>}</div>
}

function Today({d,onQuick,onRefresh}:{d:Dashboard|null;onQuick:(k:string)=>void;onRefresh:()=>void}){const pulse=d?.pulse;return <section><div className="today-head"><div><span className="eyebrow">DECISÃO DE HOJE</span><h1>{d?.next_action.title||'Registre os primeiros dados para receber uma recomendação.'}</h1></div><button className="icon-btn" onClick={onRefresh} aria-label="Atualizar"><RefreshCcw size={18}/></button></div><div className={`decision ${d?.next_action.severity||'info'}`}><span>{d?.next_action.code==='steady'?'Operação estável':'Prioridade'}</span><b>{d?.next_action.title||'Ainda sem dados suficientes'}</b></div><div className="pulse-grid"><Metric label="Vendas" value={money(pulse?.revenue_cents)} sub="registradas"/><Metric label="Contribuição" value={money(pulse?.contribution_cents)} sub="depois dos custos variáveis" emphasis/><Metric label="Perdas" value={money(pulse?.loss_cents)} sub="registradas"/></div><div className="section-title"><div><span className="eyebrow">AÇÃO RÁPIDA</span><h3>Registre o que aconteceu.</h3></div></div><div className="quick-grid"><Quick icon={Plus} label="Venda" text="Novo pedido" onClick={()=>onQuick('sale')}/><Quick icon={Package} label="Compra" text="Novo ingrediente" onClick={()=>onQuick('ingredient')}/><Quick icon={CircleDollarSign} label="Perda" text="Desperdício" onClick={()=>onQuick('loss')}/><Quick icon={RefreshCcw} label="Preço mudou" text="Atualize o custo" onClick={()=>onQuick('ingredient')}/></div><div className="ops-strip"><div><span>Pedidos abertos</span><b>{d?.open_orders||0}</b></div><div><span>Atraso</span><b>{Math.round((d?.delay_rate||0)*100)}%</b></div><div><span>Erro</span><b>{Math.round((d?.error_rate||0)*100)}%</b></div></div></section>}
function Metric({label,value,sub,emphasis}:{label:string;value:string;sub:string;emphasis?:boolean}){return <article className={`metric ${emphasis?'emphasis':''}`}><span>{label}</span><strong>{value}</strong><small>{sub}</small></article>}
function Quick({icon:Icon,label,text,onClick}:{icon:React.ElementType;label:string;text:string;onClick:()=>void}){return <button className="quick" onClick={onClick}><Icon size={22}/><div><b>{label}</b><span>{text}</span></div></button>}
function Costs({ingredients,onAdd}:{ingredients:Ingredient[];onAdd:()=>void}){return <section><div className="today-head"><div><span className="eyebrow">CUSTOS</span><h1>Quanto sua cozinha realmente custa?</h1></div><button className="primary compact" onClick={onAdd}><Plus size={17}/> Ingrediente</button></div><div className="table-card">{ingredients.length===0?<div className="empty-inline">Cadastre seu primeiro ingrediente. O app usa o custo útil, não apenas o preço da embalagem.</div>:ingredients.map(x=><div className="row" key={x.id}><div><b>{x.name}</b><span>{x.unit} · rendimento cadastrado</span></div><strong>{money(x.last_purchase_price_cents)}</strong></div>)}</div></section>}
function ComingSoon({tab}:{tab:string}){const map:Record<string,[string,string]>={pedidos:['Pedidos','Kanban operacional e KDS leve.'],clientes:['Clientes','Recompra com consentimento, sem CRM pesado.'],vender:['Vender','Preço, CPA, conteúdo e ofertas ligados à margem.'],mais:['Mais','Capacidade, sprint, fornecedores, auditoria e configurações.']};const [title,text]=map[tab]||['Área',''];return <section><span className="eyebrow">MÓDULO</span><h1>{title}</h1><div className="empty-card module"><h3>{text}</h3><p>O núcleo já está preparado no backend; esta tela será aprofundada sem inflar a navegação principal.</p></div></section>}
function QuickModal({kind,businessId,token,onClose,onDone}:{kind:string;businessId:number;token:string;onClose:()=>void;onDone:(m:string)=>void}){const [a,setA]=useState('');const[b,setB]=useState('');const[c,setC]=useState('');const[error,setError]=useState('');async function submit(e:React.FormEvent){e.preventDefault();try{if(kind==='ingredient'){await request(`/businesses/${businessId}/ingredients`,{method:'POST',body:JSON.stringify({name:a,unit:'g',price_cents:Math.round(Number(b)*100),purchase_qty_milliunits:1000,usable_qty_milliunits:Math.max(1,Number(c)||1000)})},token);onDone('Ingrediente salvo.')}else if(kind==='sale'){await request(`/businesses/${businessId}/orders`,{method:'POST',body:JSON.stringify({total_cents:Math.round(Number(a)*100),variable_cost_cents:Math.round(Number(b)*100),source:'manual',paid:true})},token);onDone('Venda registrada.')}else{await request(`/businesses/${businessId}/losses`,{method:'POST',body:JSON.stringify({reason:a,qty_milliunits:0,estimated_cost_cents:Math.round(Number(b)*100)})},token);onDone('Perda registrada.')}}catch(err){setError(err instanceof Error?err.message:'Erro')}}return <div className="modal-backdrop" onMouseDown={onClose}><form className="modal" onMouseDown={e=>e.stopPropagation()} onSubmit={submit}><div className="modal-head"><h3>{kind==='ingredient'?'Novo ingrediente':kind==='sale'?'Registrar venda':'Registrar perda'}</h3><button type="button" onClick={onClose}>×</button></div>{kind==='ingredient'?<><label>Ingrediente<input value={a} onChange={e=>setA(e.target.value)} placeholder="Carne moída" required/></label><label>Preço pago (R$)<input type="number" step="0.01" value={b} onChange={e=>setB(e.target.value)} required/></label><label>Quantidade útil (g)<input type="number" value={c} onChange={e=>setC(e.target.value)} placeholder="900" required/></label></>:kind==='sale'?<><label>Total recebido (R$)<input type="number" step="0.01" value={a} onChange={e=>setA(e.target.value)} required/></label><label>Custos variáveis do pedido (R$)<input type="number" step="0.01" value={b} onChange={e=>setB(e.target.value)} required/></label></>:<><label>Motivo<input value={a} onChange={e=>setA(e.target.value)} placeholder="Produto descartado" required/></label><label>Custo estimado (R$)<input type="number" step="0.01" value={b} onChange={e=>setB(e.target.value)} required/></label></>}{error&&<div className="error">{error}</div>}<button className="primary">Salvar</button></form></div>}

createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>)
