import React,{useEffect,useMemo,useState}from'react'
import{ArrowLeft,Calculator,Check,ChevronRight,ClipboardCheck,Flame,Gauge,Layers3,RefreshCcw,ShieldCheck,Target,TriangleAlert,UtensilsCrossed}from'lucide-react'
import{request,type Ingredient,type KdsOrder,type Product}from'./app'

type Business={id:number;name:string;city:string;role:string}
type Recipe={product_id:number;product_name:string;items:{ingredient_id:number;name:string;qty_used_milliunits:number;estimated_cost_cents:number;on_hand_milliunits:number}[]}
type Stage={id:string;name:string;minutes:number;parallel:number}
type MenuRoles={hero:number|null;alternative:number|null;entry:number|null;combo:number|null}

const readiness=[
 'Posso separar estoque da casa e da venda.','Tenho água, limpeza e superfícies adequadas.','Consigo controlar tempo e temperatura.','Vou consultar as regras locais do endereço.','Tenho rota sem cruzar lixo, animais e produto pronto.',
 'Sei pesar um lote e medir o rendimento.','Meu teste não usa dinheiro essencial da casa.','Consigo começar com três itens e um combo.','Aceito cobrar pela contribuição, não pelo medo.','Vou registrar perdas, taxa e embalagem.',
 'Posso responder durante o horário aberto.','Tenho WhatsApp separado ou bem organizado.','Consigo limitar pedidos quando lotar.','Vou usar foto compatível com o produto real.','Posso testar entrega antes de vender.',
 'Vou perguntar como o cliente chegou.','Vou calcular custo por pedido.','Não vou escalar só por curtidas.','Aceito encerrar uma oferta sem margem.','Vou auditar os primeiros 30 pedidos pagos.'
]
const defaultStages:Stage[]=[
 {id:'production',name:'Produzir / finalizar',minutes:6,parallel:2},
 {id:'pack',name:'Montar e embalar',minutes:4,parallel:1},
 {id:'service',name:'Atender e confirmar',minutes:3,parallel:1},
 {id:'dispatch',name:'Despachar',minutes:5,parallel:1},
]
function n(v:string|number){const x=Number(v);return Number.isFinite(x)?x:0}
function safeJSON<T>(raw:string|null,fallback:T):T{try{return raw?JSON.parse(raw):fallback}catch{return fallback}}

export function PlaybookLabRoute(){
 const token=localStorage.getItem('c360_token')||''
 const[businesses,setBusinesses]=useState<Business[]>([]);const[businessId,setBusinessId]=useState(0)
 const[products,setProducts]=useState<Product[]>([]);const[ingredients,setIngredients]=useState<Ingredient[]>([]);const[orders,setOrders]=useState<KdsOrder[]>([]);const[recipes,setRecipes]=useState<Recipe[]>([])
 const[tab,setTab]=useState<'readiness'|'capacity'|'menu'>('readiness');const[loading,setLoading]=useState(true);const[error,setError]=useState('')
 const[answers,setAnswers]=useState<boolean[]>(Array(20).fill(false));const[stages,setStages]=useState<Stage[]>(defaultStages);const[safety,setSafety]=useState(25);const[roles,setRoles]=useState<MenuRoles>({hero:null,alternative:null,entry:null,combo:null})

 const persist=(id:number,next?:{answers?:boolean[];stages?:Stage[];safety?:number;roles?:MenuRoles})=>{if(!id)return;const payload={answers:next?.answers??answers,stages:next?.stages??stages,safety:next?.safety??safety,roles:next?.roles??roles};localStorage.setItem(`c360-playbook-v21-${id}`,JSON.stringify(payload))}
 const restore=(id:number)=>{const s=safeJSON(localStorage.getItem(`c360-playbook-v21-${id}`),{answers:Array(20).fill(false),stages:defaultStages,safety:25,roles:{hero:null,alternative:null,entry:null,combo:null}as MenuRoles});setAnswers(s.answers?.slice(0,20).concat(Array(20).fill(false)).slice(0,20)||Array(20).fill(false));setStages(s.stages?.length?s.stages:defaultStages);setSafety(n(s.safety)||25);setRoles(s.roles||{hero:null,alternative:null,entry:null,combo:null})}
 async function load(target=businessId){if(!token){setLoading(false);return}setError('');try{let id=target;if(!businesses.length){const me=await request('/me',{},token);const rows=(me.businesses||[])as Business[];setBusinesses(rows);id=id||Number(rows[0]?.id||0);if(id)setBusinessId(id)}if(!id)return;restore(id);const[p,i,k]=await Promise.all([request(`/businesses/${id}/products`,{},token),request(`/businesses/${id}/ingredients`,{},token),request(`/businesses/${id}/kds`,{},token)]);setProducts(p);setIngredients(i);setOrders(k.orders||[]);const active=(p as Product[]).filter(x=>x.active);const rs=await Promise.all(active.map(x=>request(`/businesses/${id}/products/${x.id}/recipe`,{},token).catch(()=>({product_id:x.id,product_name:x.name,items:[]}))));setRecipes(rs)}catch(e){setError(e instanceof Error?e.message:'Falha ao montar laboratório')}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 const autoChecks=useMemo(()=>({menu:products.filter(x=>x.active).length>0&&products.filter(x=>x.active).length<=4,cost:recipes.some(r=>r.items.length>0),limit:orders.length>=0,stock:ingredients.length>0&&ingredients.every(i=>i.par_level_milliunits>0&&i.reorder_target_milliunits>0)}),[products,recipes,orders,ingredients])
 const readinessScore=answers.filter(Boolean).length
 const readinessBand=readinessScore>=15?['Pronto para o plano de 14 dias','good']:readinessScore>=9?['Corrija pendências antes do lote','warn']:['Não compre estoque ainda; valide em conversa','danger']
 const capacities=stages.map(s=>({...s,hour:s.minutes>0?Math.floor(60/s.minutes*Math.max(1,s.parallel)):0}));const bottleneck=capacities.filter(x=>x.hour>0).sort((a,b)=>a.hour-b.hour)[0];const safeLimit=bottleneck?Math.max(0,Math.floor(bottleneck.hour*(1-safety/100))):0;const open=orders.filter(o=>!['completed','cancelled'].includes(o.status)).length;const loadPct=safeLimit?Math.round(open/safeLimit*100):0;const loadState=loadPct>100?'red':loadPct>=70?'yellow':'green'
 const active=products.filter(x=>x.active);const chosen=[roles.hero,roles.alternative,roles.entry,roles.combo].filter(Boolean) as number[];const duplicate=chosen.length!==new Set(chosen).size
 const selectedRecipes=recipes.filter(r=>chosen.includes(r.product_id));const usage=new Map<number,{name:string;count:number}>();for(const r of selectedRecipes)for(const item of r.items){const cur=usage.get(item.ingredient_id)||{name:item.name,count:0};cur.count++;usage.set(item.ingredient_id,cur)}const shared=[...usage.values()].filter(x=>x.count>=2).sort((a,b)=>b.count-a.count);const single=[...usage.values()].filter(x=>x.count===1)
 const roleComplete=Boolean(roles.hero&&roles.alternative&&roles.entry&&roles.combo&&!duplicate);const menuHealth=roleComplete?Math.max(0,100-Math.min(50,single.length*8)+Math.min(20,shared.length*4)):Math.round(chosen.length/4*60)
 const setAnswer=(i:number,v:boolean)=>{const next=[...answers];next[i]=v;setAnswers(next);persist(businessId,{answers:next})};const setStage=(id:string,key:'minutes'|'parallel',value:number)=>{const next=stages.map(s=>s.id===id?{...s,[key]:Math.max(key==='parallel'?1:.1,value)}:s);setStages(next);persist(businessId,{stages:next})};const setRole=(key:keyof MenuRoles,value:number|null)=>{const next={...roles,[key]:value};setRoles(next);persist(businessId,{roles:next})}
 if(!token)return <main className="pbl-shell pbl-center"><div className="pbl-empty"><Flame/><h1>Entre na operação.</h1><p>O Laboratório 360 precisa dos dados da sua cozinha.</p><a href="/">Entrar</a></div></main>
 if(loading)return <main className="pbl-shell pbl-center"><div className="pbl-loader"><Gauge/>CALCULANDO LABORATÓRIO 360</div></main>
 return <main className="pbl-shell"><header className="pbl-topbar"><a href="/?system360=1"><ArrowLeft/> Sistema 360</a><b><Flame/> LABORATÓRIO 360 <span>5 · 14 · 30</span></b><div>{businesses.length>1&&<select value={businessId} onChange={async e=>{const id=Number(e.target.value);setBusinessId(id);await load(id)}}>{businesses.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select>}<button onClick={()=>load()}><RefreshCcw/></button></div></header><section className="pbl-page">
 <div className="pbl-hero"><div><span>COZINHA DE BOLSO 360 · FERRAMENTAS VIVAS</span><h1>Teste a cozinha antes de testar o anúncio.</h1><p>Três instrumentos do manual agora calculam a sua realidade: prontidão, teto operacional e arquitetura do menu.</p></div><div className="pbl-live"><i/><span>{products.filter(x=>x.active).length} produtos · {ingredients.length} insumos</span><small>{orders.length} pedidos abertos no KDS</small></div></div>{error&&<div className="pbl-error">{error}</div>}
 <nav className="pbl-tabs"><button className={tab==='readiness'?'active':''} onClick={()=>setTab('readiness')}><ClipboardCheck/>Raio-X 20 pontos</button><button className={tab==='capacity'?'active':''} onClick={()=>setTab('capacity')}><Calculator/>Capacity Engine</button><button className={tab==='menu'?'active':''} onClick={()=>setTab('menu')}><Layers3/>Menu 3 + 1</button></nav>
 {tab==='readiness'&&<section className="pbl-tool"><div className={`pbl-verdict ${readinessBand[1]}`}><div><strong>{readinessScore}</strong><span>/20</span></div><div><b>{readinessBand[0]}</b><small>Um ponto por resposta verdadeira. Confirmações são suas; o app não inventa legalidade, higiene ou capacidade.</small></div></div><div className="pbl-auto"><span>AUTO-CHECAGENS DO APP</span><i className={autoChecks.menu?'ok':''}>Menu ≤4 {autoChecks.menu?'✓':'—'}</i><i className={autoChecks.cost?'ok':''}>Ficha técnica {autoChecks.cost?'✓':'—'}</i><i className={autoChecks.stock?'ok':''}>Estoque mínimo/alvo {autoChecks.stock?'✓':'—'}</i></div><div className="pbl-check-grid">{readiness.map((q,i)=><label key={q} className={answers[i]?'checked':''}><input type="checkbox" checked={answers[i]} onChange={e=>setAnswer(i,e.target.checked)}/><i>{answers[i]?<Check/>:<span>{String(i+1).padStart(2,'0')}</span>}</i><span>{q}</span></label>)}</div></section>}
 {tab==='capacity'&&<section className="pbl-tool"><div className={`pbl-capacity-banner ${loadState}`}><div><span>CAPACIDADE SEGURA / HORA</span><strong>{safeLimit}</strong><small>margem de segurança {safety}%</small></div><div><span>GARGALO</span><b>{bottleneck?.name||'—'}</b><small>{bottleneck?`${bottleneck.hour} pedidos/h antes da margem`:'Preencha as etapas'}</small></div><div><span>CARGA KDS</span><b>{open} / {safeLimit||'—'}</b><small>{loadPct}% do teto · {loadState==='green'?'verde':loadState==='yellow'?'amarelo':'vermelho'}</small></div></div><div className="pbl-stage-head"><div><span>TESTE DE UMA HORA</span><h2>O menor teto manda.</h2></div><label>Margem de segurança<input type="number" min="0" max="60" value={safety} onChange={e=>{const v=Math.max(0,Math.min(60,n(e.target.value)));setSafety(v);persist(businessId,{safety:v})}}/><b>%</b></label></div><div className="pbl-stage-grid">{capacities.map((s,i)=><article key={s.id}><header><span>0{i+1}</span><b>{s.name}</b></header><label>Minutos/pedido<input type="number" min="0.1" step="0.1" value={s.minutes} onChange={e=>setStage(s.id,'minutes',n(e.target.value))}/></label><label>Simultâneos<input type="number" min="1" step="1" value={s.parallel} onChange={e=>setStage(s.id,'parallel',n(e.target.value))}/></label><footer><span>Teto/h</span><strong>{s.hour}</strong></footer></article>)}</div><div className="pbl-rule"><Target/><div><b>Trava prática</b><span>{loadState==='red'?'Acima do limite: pause entrada, comunique prazo e recupere a fila.':loadState==='yellow'?'70–100%: pause mídia e aceite seletivamente.':'Até 70%: canais podem permanecer abertos se estoque e qualidade estiverem normais.'}</span></div></div></section>}
 {tab==='menu'&&<section className="pbl-tool"><div className="pbl-menu-head"><div><span>MATRIZ LEGO</span><h2>Variedade percebida sem geladeira caótica.</h2><p>3 produtos: herói, alternativa e entrada. 1 combo: herói + companhia natural.</p></div><div className={`pbl-menu-score ${roleComplete&&!duplicate?'ok':''}`}><strong>{menuHealth}</strong><span>/100</span><small>saúde estrutural</small></div></div><div className="pbl-role-grid">{([['hero','Herói'],['alternative','Alternativa'],['entry','Entrada'],['combo','Combo']]as [keyof MenuRoles,string][]).map(([key,label])=><label key={key}><span>{label}</span><select value={roles[key]||''} onChange={e=>setRole(key,e.target.value?Number(e.target.value):null)}><option value="">Escolher produto</option>{active.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>)}</div>{duplicate&&<div className="pbl-warning"><TriangleAlert/>Um produto não pode ocupar dois papéis no 3 + 1.</div>}<div className="pbl-menu-insights"><article><header><UtensilsCrossed/><span>INSUMOS COMPARTILHADOS</span></header><strong>{shared.length}</strong><p>{shared.length?shared.slice(0,6).map(x=>`${x.name} (${x.count} itens)`).join(' · '):'Escolha os quatro papéis e mantenha fichas técnicas preenchidas.'}</p></article><article className={single.length?'risk':''}><header><TriangleAlert/><span>INSUMOS DE UM ÚNICO ITEM</span></header><strong>{single.length}</strong><p>{single.length?single.slice(0,8).map(x=>x.name).join(' · '):'Nenhum insumo isolado entre os itens escolhidos.'}</p></article><article><header><ShieldCheck/><span>REGRA DE DECISÃO</span></header><strong>{roleComplete&&!duplicate?'PASSA':'ABERTO'}</strong><p>{roleComplete&&!duplicate?single.length>3?'O 3+1 está montado, mas há muitos insumos isolados; revise perda e validade.':'Estrutura enxuta e com bom potencial de cruzamento de insumos.':'Preencha os quatro papéis com produtos diferentes.'}</p></article></div><a className="pbl-products-link" href="/#produtos">Editar produtos e fichas técnicas <ChevronRight/></a></section>}
 </section></main>
}
