import React,{useEffect,useMemo,useState}from'react'
import{ArrowLeft,BookOpenCheck,Camera,Check,ChevronRight,Copy,Flame,Globe2,Image as ImageIcon,LayoutTemplate,MapPin,Megaphone,RefreshCcw,ShieldCheck,Sparkles,Target,Video}from'lucide-react'
import{request,type Product}from'./app'

type Business={id:number;name:string;city:string;role:string}
type Tab='brand'|'photo'|'content'|'site'
type Draft={occasion:string;promise:string;proof:string;personality:string;avoid:string;region:string;whatsapp:string;keyword:string;hours:string;payment:string}
type MenuRoles={hero:number|null;alternative:number|null;entry:number|null;combo:number|null}

const defaultDraft:Draft={occasion:'sexta à noite',promise:'produto finalizado em pequenos lotes',proof:'porção real, embalagem real e janela confirmada',personality:'direto, quente, confiável',avoid:'exagerado, infantil, genérico',region:'',whatsapp:'',keyword:'SITE',hours:'',payment:'Pix e outras formas confirmadas no pedido'}
const shotList=[
 ['Hero','Ângulo mais apetitoso, fundo limpo e composição que funciona na capa.'],
 ['Escala','Mostre embalagem ou referência real para deixar o tamanho evidente.'],
 ['Textura','Corte, crocância, recheio ou molho — sem alterar o produto que será entregue.'],
 ['Chegada','Fotografe exatamente dentro da embalagem usada no delivery.'],
 ['Combo','Todos os componentes e quantidades visíveis na mesma cena.'],
]
const calendar=[
 ['Produto','Herói em plano geral'],['Prova','Bastidor de higiene'],['Produto','Textura em vídeo'],['Ocasião','Ocasião local'],['Oferta','Combo + palavra'],['Prova','Embalagem real'],['Ocasião','Pergunta/enquete'],['Produto','Ingrediente-chave'],['Prova','Tempo de finalização'],['Produto','Foto de escala'],
 ['Ocasião','Área atendida'],['Oferta','Oferta B'],['Prova','Avaliação autorizada'],['Prova','FAQ'],['Produto','Alternativa do menu'],['Prova','Preparação do lote'],['Produto','Som crocante'],['Ocasião','Para dividir'],['Oferta','Adicional'],['Prova','Lacre/conferência'],
 ['Ocasião','Votação'],['Produto','Herói com novo ângulo'],['Prova','Erro que você evita'],['Prova','Chegada na caixa'],['Ocasião','Retirada programada'],['Oferta','Oferta vencedora'],['Prova','Cliente recorrente'],['Prova','FAQ 2'],['Produto','Resumo do mês: mais pedido, prova e agradecimento'],['Oferta','Convite consentido para lista de novidades'],
]
function safeJSON<T>(raw:string|null,fallback:T):T{try{return raw?JSON.parse(raw):fallback}catch{return fallback}}
function textForCategory(cat:string,d:Draft,hero:string){
 const region=d.region||'[REGIÃO]';const keyword=d.keyword||'SITE'
 if(cat==='Produto')return `${region}: ${hero}. Mostre composição, porção e acabamento reais. Envie ${keyword} para confirmar a próxima janela.`
 if(cat==='Prova')return `Mostre uma prova concreta do processo: ${d.proof||'porção, embalagem ou preparo real'}. Sem prometer o que a operação não mede.`
 if(cat==='Ocasião')return `${d.occasion||'Hoje'} em ${region}: conecte o produto ao momento real e termine com uma ação rastreável.`
 return `Oferta em teste: diga o que vem, preço/janela reais e limite baseado na capacidade. Use o código ${keyword}.`
}

export function VitrineStudioRoute(){
 const token=localStorage.getItem('c360_token')||''
 const[businesses,setBusinesses]=useState<Business[]>([]);const[businessId,setBusinessId]=useState(0);const[products,setProducts]=useState<Product[]>([]);const[tab,setTab]=useState<Tab>('brand');const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[copied,setCopied]=useState('')
 const[draft,setDraft]=useState<Draft>(defaultDraft);const[roles,setRoles]=useState<MenuRoles>({hero:null,alternative:null,entry:null,combo:null})
 function persist(id:number,next:Draft){if(id)localStorage.setItem(`c360-vitrine-v22-${id}`,JSON.stringify(next))}
 function setField<K extends keyof Draft>(key:K,value:Draft[K]){const next={...draft,[key]:value};setDraft(next);persist(businessId,next)}
 async function load(target=businessId){if(!token){setLoading(false);return}setError('');try{let id=target;if(!businesses.length){const me=await request('/me',{},token);const rows=(me.businesses||[])as Business[];setBusinesses(rows);id=id||Number(rows[0]?.id||0);if(id)setBusinessId(id)}if(!id)return;const p=await request(`/businesses/${id}/products`,{},token);setProducts(p);const business=(businesses.length?businesses:[]).find(x=>x.id===id);const stored=safeJSON(localStorage.getItem(`c360-vitrine-v22-${id}`),{...defaultDraft,region:business?.city||''});setDraft({...defaultDraft,...stored,region:stored.region||business?.city||''});const play=safeJSON(localStorage.getItem(`c360-playbook-v21-${id}`),{roles:{hero:null,alternative:null,entry:null,combo:null}});setRoles(play.roles||{hero:null,alternative:null,entry:null,combo:null})}catch(e){setError(e instanceof Error?e.message:'Não foi possível montar o Vitrine Studio')}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 const active=products.filter(x=>x.active);const byId=(id:number|null)=>active.find(x=>x.id===id);const hero=byId(roles.hero)||active[0];const alt=byId(roles.alternative)||active[1];const entry=byId(roles.entry)||active[2];const combo=byId(roles.combo)||active[3];const heroName=hero?.name||'[PRODUTO HERÓI]'
 const brandLine=`Somos a marca de ${heroName} para ${draft.occasion||'[PÚBLICO/OCASIÃO]'}. Entregamos ${draft.promise||'[PROMESSA]'} por meio de ${draft.proof||'[PROVA]'}. Falamos de forma ${draft.personality||'[3 ADJETIVOS]'}. Nunca parecemos ${draft.avoid||'[3 PROIBIÇÕES]'}.`
 const pageCopy=useMemo(()=>({headline:`${heroName} feito em pequenos lotes para ${draft.occasion||'[OCASIÃO]'} em ${draft.region||'[REGIÃO]'}.`,sub:`Peça ${draft.promise||'[PROMESSA CONCRETA]'}, com ${draft.proof||'[PROVA]'}, entrega em ${draft.region||'[ÁREA]'} e janela confirmada antes do pagamento.`,proof:`Você recebe exatamente a porção fotografada, na embalagem real e com os acompanhamentos descritos no pedido.`,cta:`Envie ${draft.keyword||'SITE'} no WhatsApp para confirmar CEP, entrega e próximo horário.`}),[heroName,draft])
 async function copy(label:string,value:string){try{await navigator.clipboard.writeText(value);setCopied(label);setTimeout(()=>setCopied(''),1600)}catch{setCopied('')}}
 if(!token)return <main className="vst-shell vst-center"><div className="vst-empty"><Flame/><h1>Entre na operação primeiro.</h1><p>O Vitrine Studio usa seus produtos reais para montar marca, conteúdo e página.</p><a href="/">Entrar</a></div></main>
 if(loading)return <main className="vst-shell vst-center"><div className="vst-loader"><Sparkles/>MONTANDO VITRINE STUDIO</div></main>
 return <main className="vst-shell"><header className="vst-topbar"><a href="/?system360=1"><ArrowLeft/> Sistema 360</a><b><Flame/> VITRINE STUDIO <span>MARCA · FOTO · CONTEÚDO · SITE</span></b><div>{businesses.length>1&&<select value={businessId} onChange={async e=>{const id=Number(e.target.value);setBusinessId(id);await load(id)}}>{businesses.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select>}<button onClick={()=>load()}><RefreshCcw/></button></div></header><section className="vst-page">
  <div className="vst-hero"><div><span>COZINHA DE BOLSO 360 · MOTOR VITRINE</span><h1>Transforme produto real em marca que o cliente entende.</h1><p>Briefing, direção de arte, calendário e página de venda deixam de ser capítulos soltos e passam a usar o mesmo produto, região, prova e palavra de origem.</p></div><div className="vst-source"><BookOpenCheck/><span>MÉTODO ATIVO</span><b>{active.length} produtos reais na operação</b><small>{roles.hero?'Menu 3+1 conectado':'Use o Laboratório 360 para definir o Menu 3+1'}</small></div></div>{error&&<div className="vst-error">{error}</div>}
  <nav className="vst-tabs"><button className={tab==='brand'?'active':''} onClick={()=>setTab('brand')}><Target/>Brand Brief</button><button className={tab==='photo'?'active':''} onClick={()=>setTab('photo')}><Camera/>Photo Coach</button><button className={tab==='content'?'active':''} onClick={()=>setTab('content')}><Megaphone/>Content Engine</button><button className={tab==='site'?'active':''} onClick={()=>setTab('site')}><LayoutTemplate/>Site 1 Página</button></nav>
  {tab==='brand'&&<section className="vst-tool"><div className="vst-section-head"><div><span>BRIEF DE UMA PÁGINA</span><h2>Cinco decisões antes de abrir qualquer editor.</h2></div><ShieldCheck/></div><div className="vst-brand-grid"><label>01 · Ocasião<span>Quando e com quem a pessoa pede?</span><input value={draft.occasion} onChange={e=>setField('occasion',e.target.value)} placeholder="Ex.: sexta à noite, visita, almoço"/></label><label>02 · Promessa sensorial<span>O que a experiência entrega sem exagero?</span><input value={draft.promise} onChange={e=>setField('promise',e.target.value)} placeholder="Ex.: crocante, quente, porção clara"/></label><label>03 · Herói<span>Vem do Menu 3+1.</span><div className="vst-locked">{heroName}<a href="/?playbook=1">editar</a></div></label><label>04 · Prova<span>O que torna a promessa verificável?</span><input value={draft.proof} onChange={e=>setField('proof',e.target.value)} placeholder="Ex.: porção pesada + embalagem real"/></label><label>05 · Personalidade<span>Três adjetivos.</span><input value={draft.personality} onChange={e=>setField('personality',e.target.value)}/></label><label>Proibições<span>Três coisas que a marca nunca parece.</span><input value={draft.avoid} onChange={e=>setField('avoid',e.target.value)}/></label></div><div className="vst-output"><span>POSICIONAMENTO GERADO</span><p>{brandLine}</p><button onClick={()=>copy('brand',brandLine)}>{copied==='brand'?<Check/>:<Copy/>}{copied==='brand'?'Copiado':'Copiar briefing'}</button></div><div className="vst-writing"><article><b>Evite</b><p>“O melhor da cidade”, “explosão de sabor”, “imperdível”.</p></article><article><b>Prefira</b><p>Processo, quantidade, ingrediente, textura, janela e prova que possam ser conferidos.</p></article></div></section>}
  {tab==='photo'&&<section className="vst-tool"><div className="vst-section-head"><div><span>ESTÚDIO DE BOLSO</span><h2>Cinco fotos que resolvem o lançamento.</h2></div><Camera/></div><div className="vst-photo-layout"><div className="vst-shotlist">{shotList.map(([name,desc],i)=><article key={name}><span>0{i+1}</span><div><b>{name}</b><p>{desc}</p></div><button onClick={()=>copy(name,`${name} — ${desc}`)}><Copy/></button></article>)}</div><aside className="vst-photo-coach"><div className="vst-coach-visual"><ImageIcon/><span>{heroName}</span><small>produto real · porção real · embalagem real</small></div><div className="vst-coach-steps"><p><b>Luz</b> · mesa a 45° de uma janela; desligue lâmpadas de cores diferentes.</p><p><b>Rebatedor</b> · cartolina branca do lado oposto para suavizar sombra.</p><p><b>Fundo</b> · fosco, limpo e sem estampa concorrente.</p><p><b>Câmera</b> · lente limpa, câmera principal, grade e apoio estável.</p><p><b>Produto</b> · monte a porção exata e fotografe imediatamente.</p></div></aside></div><div className="vst-video"><Video/><div><span>ROTEIRO 10 S</span><b>0–1s embalagem abre · 1–3s plano geral · 3–5s textura · 5–7s movimento · 7–8s escala · 8–9s embalagem lacrada · 9–10s oferta + região + ação.</b></div><button onClick={()=>copy('video',`0–1s embalagem abre; 1–3s plano geral; 3–5s textura; 5–7s movimento; 7–8s escala; 8–9s embalagem lacrada; 9–10s oferta, ${draft.region||'região'} e CTA ${draft.keyword||'SITE'}.`)}>{copied==='video'?<Check/>:<Copy/>}</button></div></section>}
  {tab==='content'&&<section className="vst-tool"><div className="vst-section-head"><div><span>40 · 30 · 20 · 10</span><h2>Conteúdo que cria desejo, confiança e ocasião.</h2></div><Megaphone/></div><div className="vst-mix"><div><strong>40%</strong><span>Produto</span><small>textura · montagem · tamanho · ingredientes · embalagem</small></div><div><strong>30%</strong><span>Prova</span><small>bastidor · processo · avaliação autorizada · pedido real</small></div><div><strong>20%</strong><span>Ocasião</span><small>sexta · jogo · visita · presente · festa pequena</small></div><div><strong>10%</strong><span>Oferta</span><small>combo · janela · lançamento · adicional · recuperação</small></div></div><div className="vst-content-fields"><label>Região<input value={draft.region} onChange={e=>setField('region',e.target.value)} placeholder="Bairro, cidade ou raio"/></label><label>Palavra de origem<input value={draft.keyword} onChange={e=>setField('keyword',e.target.value.toUpperCase().replace(/\s+/g,'').slice(0,18))} placeholder="BACON"/></label></div><div className="vst-calendar">{calendar.map(([cat,title],i)=><article key={`${i}-${title}`}><span>{String(i+1).padStart(2,'0')}</span><i data-cat={cat}>{cat}</i><b>{title}</b><p>{textForCategory(cat,draft,heroName)}</p><button onClick={()=>copy(`day-${i}`,textForCategory(cat,draft,heroName))}>{copied===`day-${i}`?<Check/>:<Copy/>}</button></article>)}</div></section>}
  {tab==='site'&&<section className="vst-tool"><div className="vst-section-head"><div><span>BASE PRÓPRIA</span><h2>Uma página que remove as sete dúvidas do pedido.</h2></div><Globe2/></div><div className="vst-site-fields"><label>Região / área<input value={draft.region} onChange={e=>setField('region',e.target.value)}/></label><label>WhatsApp<input value={draft.whatsapp} onChange={e=>setField('whatsapp',e.target.value.replace(/[^0-9+]/g,''))} placeholder="55DDDNUMERO"/></label><label>Horários<input value={draft.hours} onChange={e=>setField('hours',e.target.value)} placeholder="Sex 18h–22h"/></label><label>Pagamento<input value={draft.payment} onChange={e=>setField('payment',e.target.value)}/></label></div><div className="vst-site-grid"><div className="vst-site-preview"><div className="vst-preview-bar">{draft.region||'[ÁREA]'} · {draft.hours||'janela confirmada no pedido'}</div><header><b>{businesses.find(x=>x.id===businessId)?.name||'Sua marca'}</b><span>Menu · Entrega · FAQ</span></header><section className="vst-preview-hero"><span>{heroName.toUpperCase()} · PEQUENOS LOTES</span><h3>{pageCopy.headline}</h3><p>{pageCopy.sub}</p><button>Confirmar próxima janela</button></section><section className="vst-preview-menu"><div><small>COMECE AQUI</small><b>{heroName}</b></div><div><small>ALTERNATIVA</small><b>{alt?.name||'Produto 2'}</b></div><div><small>ENTRADA</small><b>{entry?.name||'Produto 3'}</b></div><div><small>COMBO</small><b>{combo?.name||'Combo'}</b></div></section><section className="vst-preview-proof"><MapPin/><p>{pageCopy.proof}</p></section><footer>{pageCopy.cta}</footer></div><aside className="vst-site-copy"><CopyBlock label="Headline" value={pageCopy.headline} onCopy={()=>copy('headline',pageCopy.headline)} copied={copied==='headline'}/><CopyBlock label="Subheadline" value={pageCopy.sub} onCopy={()=>copy('sub',pageCopy.sub)} copied={copied==='sub'}/><CopyBlock label="Prova" value={pageCopy.proof} onCopy={()=>copy('proof',pageCopy.proof)} copied={copied==='proof'}/><CopyBlock label="Chamada" value={pageCopy.cta} onCopy={()=>copy('cta',pageCopy.cta)} copied={copied==='cta'}/><div className="vst-site-check"><ShieldCheck/><div><b>Antes de publicar</b><span>Substitua fotos, confirme preço e área, revise privacidade, teste WhatsApp, celular, HTTPS e eventos. Não marque cookies de marketing como necessários.</span></div></div><a href="/?direct=1">Abrir Venda Direta <ChevronRight/></a></aside></div></section>}
 </section></main>
}
function CopyBlock({label,value,onCopy,copied}:{label:string;value:string;onCopy:()=>void;copied:boolean}){return <div className="vst-copyblock"><span>{label}</span><p>{value}</p><button onClick={onCopy}>{copied?<Check/>:<Copy/>}</button></div>}
