import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const U=Deno.env.get("SUPABASE_URL")!;const K=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const allowed=new Set(["https://plutyx.com","https://www.plutyx.com","https://ranking-conversao-preview.onrender.com","https://ranking-conversao-plutyx.netlify.app","http://localhost:5173","http://127.0.0.1:5173"]);
function cors(origin:string|null){const o=origin&&allowed.has(origin)?origin:"https://plutyx.com";return{"access-control-allow-origin":o,"access-control-allow-methods":"GET,POST,OPTIONS","access-control-allow-headers":"content-type","vary":"Origin","content-type":"application/json; charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff"}}
function reply(origin:string|null,body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:cors(origin)})}
async function sha256(s:string){const b=new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s)));return[...b].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function rpc(name:string,body:Record<string,unknown>){const r=await fetch(`${U}/rest/v1/rpc/${name}`,{method:"POST",headers:{apikey:K,authorization:`Bearer ${K}`,"content-type":"application/json"},body:JSON.stringify(body)});const text=await r.text();let data:any=null;try{data=text?JSON.parse(text):null}catch{data={raw:text.slice(0,1000)}}if(!r.ok){const message=String(data?.message||data?.error||text||`rpc_${r.status}`);const err=new Error(message);(err as any).status=r.status;throw err}return data}
function normalize(raw:unknown){if(typeof raw!=="string")throw new Error("invalid_url");let s=raw.trim();if(!/^https?:\/\//i.test(s))s=`https://${s}`;if(s.length<8||s.length>2048)throw new Error("invalid_url");const u=new URL(s);if(!["http:","https:"].includes(u.protocol)||u.username||u.password)throw new Error("invalid_url");if(u.port&&!['80','443'].includes(u.port))throw new Error("invalid_url");u.hash="";return u.toString()}
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function clientKey(req:Request,version:string){const ip=(req.headers.get("x-forwarded-for")||req.headers.get("cf-connecting-ip")||"unknown").split(",")[0].trim();const ua=(req.headers.get("user-agent")||"unknown").slice(0,220);return`${ip}|${ua}|${version}`}
function clean(v:unknown,max=500){return typeof v==='string'?v.trim().slice(0,max):null}
function finite(v:unknown){return v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v))}
function publicReport(report:any,competition:any){
 const rank=report?.ranking||{};const dist=report?.score_distribution||{};const truth=report?.diagnostic_truth||{};
 const preliminaryAxes=Number(truth?.preliminary_axes??rank?.preliminary_axes??dist?.preliminary_axes??0)||0;
 const readyAxes=Number(truth?.ready_axes??rank?.ready_axes??dist?.ready_axes??0)||0;
 const measuredAxes=Number(dist?.measured_axes??(preliminaryAxes+readyAxes))||0;
 const technicalEligible=competition?.eligible_technically===true;
 const official=rank?.score_status==='official'&&rank?.ranking_scope==='official_competition'&&rank?.official_competition_eligible===true&&competition?.official_participant===true;
 const hasEstimate=finite(rank?.score_100)&&technicalEligible&&measuredAxes>=5;
 const visibility=official?'official':hasEstimate?'provisional':'forming';
 const visibleScore=visibility==='forming'?null:rank?.score_100;
 const visibleRaw=visibility==='forming'?null:rank?.raw_score_100;
 const ranking={...rank,score_100:visibleScore,raw_score_100:visibleRaw,score_status:visibility,score_visibility:visibility,minimum_public_axes:5,public_axes_observed:measuredAxes,official_competition_eligible:official,ranking_scope:official?'official_competition':'autonomous_diagnostic',overall_rank:official?rank?.overall_rank??null:null,category_rank:official?rank?.category_rank??null:null,percentile:official?rank?.percentile??null:null,previous_rank:official?rank?.previous_rank??null:null,rank_delta:official?rank?.rank_delta??null:null,position_kind:official?'official':null,official_participant:Boolean(competition?.official_participant),score_visibility_reason:official?'official_contract_met':hasEstimate?'autonomous_evidence_gate_met':finite(rank?.score_100)?'minimum_evidence_gate_not_met':'no_weighted_evidence'};
 const score_distribution={...dist,gcl_score_100:visibility==='forming'?null:dist?.gcl_score_100??visibleScore,score_status:visibility,score_visibility:visibility,minimum_public_axes:5,public_axes_observed:measuredAxes,official_competition_eligible:official,ranking_scope:official?'official_competition':'autonomous_diagnostic',disclosure:visibility==='forming'?'Score em formação: a estimativa pública só aparece depois que a auditoria atende ao gate técnico e possui evidência em pelo menos 5 dimensões. Evidência ausente continua desconhecida.':dist?.disclosure};
 const diagnostic_truth={...truth,score_status:visibility,score_visibility:visibility,minimum_public_axes:5,public_axes_observed:measuredAxes,official_competition_eligible:official,public_score_disclosure:visibility==='forming'?'Score em formação: ainda não há evidência suficiente para exibir uma estimativa numérica pública.':visibility==='provisional'?'Estimativa diagnóstica provisória; não é posição oficial nem taxa de conversão medida.':'Score oficial conforme o contrato explícito de competição.'};
 const dimensions=visibility==='forming'&&Array.isArray(report?.dimensions)?report.dimensions.map((d:any)=>d?.dimension_code==='site_experience_index'?{...d,score_10:null,preliminary_score_10:null}:d):report?.dimensions;
 const publicCompetition={...(competition||{}),technical_score:visibility==='forming'?null:competition?.technical_score??visibleScore,official_position:official?rank?.overall_rank??null:null};
 return {...(report||{}),ranking,score_distribution,diagnostic_truth,dimensions,competition:publicCompetition};
}
Deno.serve(async(req)=>{const origin=req.headers.get("origin");if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors(origin)});if(origin&&!allowed.has(origin))return reply(origin,{error:"origin_not_allowed"},403);if(req.method==="GET")return reply(origin,{ok:true,service:"sac-ranking-site-api",version:16,brand:"Global Conversion League",paid_analysis_gate:true,official_ranking_membership_gate:true,public_score_gate:true,capabilities:["qualify","capture_interest","start_paid","status","home","report","offers","health","queue_health","market_for_token","nominees","awards_methodology","award_detail","blog_index","blog_post"]});if(req.method!=="POST")return reply(origin,{error:"method_not_allowed"},405);
try{const body=await req.json();const action=String(body?.action||"");
 if(action==="qualify"){const url=normalize(body?.url);const bucket=await sha256(clientKey(req,"gcl-ranking-v14"));const rate=await rpc("consume_rate_limit",{p_route:"public:qualify",p_bucket:bucket,p_window_seconds:60,p_limit:20});if(!rate?.allowed)return reply(origin,{error:"rate_limited",reset_at:rate?.reset_at},429);const data=await rpc("sac_api_prepare_analysis",{p_url:url,p_bucket_key:bucket});let checkout:any={checkout_ready:false};if(data?.intent_token){checkout=await rpc("gcl_analysis_checkout_url",{p_intent_token:data.intent_token,p_sandbox:false});}return reply(origin,{ok:true,result:{...data,checkout}});}
 if(action==="capture_interest"){const token=String(body?.intent_token||"");if(!uuid.test(token))return reply(origin,{error:"invalid_intent_token"},400);const email=clean(body?.email,254)||'';const bucket=await sha256(clientKey(req,"gcl-interest-v14")+'|'+email.toLowerCase());const rate=await rpc("consume_rate_limit",{p_route:"public:capture_interest",p_bucket:bucket,p_window_seconds:300,p_limit:5});if(!rate?.allowed)return reply(origin,{error:"rate_limited",reset_at:rate?.reset_at},429);const data=await rpc("gcl_capture_analysis_interest",{p_intent_token:token,p_email:email,p_phone:clean(body?.phone,80),p_company_name:clean(body?.company_name,180),p_role_title:clean(body?.role_title,140),p_stage:String(body?.stage||'checkout_interest').slice(0,40),p_source_path:clean(body?.source_path,500)||'/ranking-site/',p_referrer:clean(body?.referrer,1000),p_utm_source:clean(body?.utm_source,160),p_utm_medium:clean(body?.utm_medium,160),p_utm_campaign:clean(body?.utm_campaign,240),p_utm_content:clean(body?.utm_content,240),p_utm_term:clean(body?.utm_term,240),p_marketing_consent:Boolean(body?.marketing_consent)});return reply(origin,{ok:true,result:data},201);}
 if(action==="start"){const token=String(body?.intent_token||"");if(!uuid.test(token))return reply(origin,{error:body?.url?"payment_intent_required":"invalid_intent_token"},402);const data=await rpc("sac_api_request_paid_analysis",{p_intent_token:token});return reply(origin,{ok:true,...data},202);}
 if(action==="status"){const token=String(body?.token||"");if(!uuid.test(token))return reply(origin,{error:"invalid_token"},400);const data=await rpc("sac_api_preview_status",{p_token:token});return reply(origin,{ok:true,result:data});}
 if(action==="home"){const limit=Math.max(1,Math.min(Number(body?.limit||25),50));const data=await rpc("gcl_public_home",{p_limit:limit});return reply(origin,{ok:true,result:data});}
 if(action==="offers"){const data=await rpc("sac_api_offer_catalog",{});return reply(origin,{ok:true,result:data});}
 if(action==="health"){const data=await rpc("gcl_public_health",{});return reply(origin,{ok:true,result:data});}
 if(action==="queue_health"){const data=await rpc("gcl_scan_queue_health",{});return reply(origin,{ok:true,result:data});}
 if(action==="market_for_token"){const token=String(body?.token||"");if(!uuid.test(token))return reply(origin,{error:"invalid_token"},400);const bucket=await sha256(clientKey(req,"gcl-market-read-v14"));const rate=await rpc("consume_rate_limit",{p_route:"public:market_for_token",p_bucket:bucket,p_window_seconds:60,p_limit:60});if(!rate?.allowed)return reply(origin,{error:"rate_limited",reset_at:rate?.reset_at},429);const limit=Math.max(1,Math.min(Number(body?.limit||8),16));const data=await rpc("sac_api_market_for_token",{p_token:token,p_limit:limit});if(!data?.found)return reply(origin,{error:"analysis_not_found"},404);return reply(origin,{ok:true,result:data});}
 if(action==="nominees"){const category=body?.category?String(body.category).slice(0,120):null;const limit=Math.max(1,Math.min(Number(body?.limit||50),100));const data=await rpc("gcl_awards_nominees",{p_category:category,p_limit:limit});return reply(origin,{ok:true,result:data});}
 if(action==="awards_methodology"){const data=await rpc("gcl_awards_methodology",{});return reply(origin,{ok:true,result:data});}
 if(action==="award_detail"){const slug=String(body?.slug||"").trim();if(!slug||slug.length>220)return reply(origin,{error:"invalid_slug"},400);const data=await rpc("gcl_awards_entry_detail",{p_slug:slug});if(!data)return reply(origin,{error:"nominee_not_found"},404);return reply(origin,{ok:true,result:data});}
 if(action==="blog_index"){const data=await rpc("gcl_blog_index",{p_category:body?.category||null,p_limit:Math.max(1,Math.min(Number(body?.limit||20),50))});return reply(origin,{ok:true,result:data});}
 if(action==="blog_post"){const slug=String(body?.slug||"").trim();if(!slug||slug.length>180)return reply(origin,{error:"invalid_slug"},400);const data=await rpc("gcl_blog_post",{p_slug:slug});return reply(origin,{ok:true,result:data});}
 if(action==="report"){const token=String(body?.token||"");if(!uuid.test(token))return reply(origin,{error:"invalid_token"},400);const [report,competition]=await Promise.all([rpc("sac_api_deep_report",{p_token:token}),rpc("sac_api_competition_context",{p_token:token})]);return reply(origin,{ok:true,result:publicReport(report,competition)});}
 return reply(origin,{error:"unknown_action"},400);
}catch(e){const m=e instanceof Error?e.message:String(e);if(m.includes("payment_required"))return reply(origin,{error:"payment_required"},402);if(m.includes("analysis_intent_expired"))return reply(origin,{error:"analysis_intent_expired"},410);if(m.includes("analysis_intent_not_found"))return reply(origin,{error:"analysis_intent_not_found"},404);if(m.includes("invalid_email"))return reply(origin,{error:"invalid_email"},400);if(m.includes("daily_preview_limit")||m.includes("rate_limited"))return reply(origin,{error:"rate_limited"},429);if(m.includes("scanner_busy"))return reply(origin,{error:"scanner_busy"},503);if(m.includes("invalid_url")||m.includes("Invalid URL"))return reply(origin,{error:"invalid_url"},400);console.error("sac-ranking-site-api",m);return reply(origin,{error:"internal_error",detail:m.slice(0,220)},500)}});
