import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.57.4";

// GCL sac-public-api v82 / Edge release target v8.
const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const db = createClient(SUPABASE_URL, SERVICE_ROLE_KEY, { auth: { persistSession: false, autoRefreshToken: false } });
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const BROWSER_ACQUISITION_EVENTS = new Set(["landing_view","diagnostic_started","consent_updated"]);

const allowedOrigins = new Set([
  "https://plutyx.com","https://www.plutyx.com","https://ranking-conversao-preview.onrender.com","http://localhost:5173","http://127.0.0.1:5173",
]);
function cors(origin:string|null){const allowed=origin&&allowedOrigins.has(origin)?origin:"https://plutyx.com";return{"Access-Control-Allow-Origin":allowed,"Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Vary":"Origin","Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"};}
function reply(origin:string|null,body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:cors(origin)});}
async function sha256(value:string){const digest=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value));return Array.from(new Uint8Array(digest)).map(b=>b.toString(16).padStart(2,"0")).join("");}
function normalizeUrl(raw:unknown){if(typeof raw!=="string"||raw.trim().length<4||raw.length>2048)throw new Error("invalid_url");const url=new URL(raw.trim());if(!["http:","https:"].includes(url.protocol))throw new Error("invalid_url");url.hash="";url.username="";url.password="";url.hostname=url.hostname.toLowerCase();return url.toString();}
function sanitizedText(raw:unknown,max:number){if(typeof raw!=="string")return null;const v=raw.trim();return v?v.slice(0,max):null;}
function sanitizeAttribution(raw:unknown,forceTracking?:boolean){const a=raw&&typeof raw==="object"&&!Array.isArray(raw)?raw as Record<string,unknown>:{};const trackingConsent=forceTracking===undefined?a.tracking_consent===true:forceTracking===true;return{
  utm_source:sanitizedText(a.utm_source,255),utm_medium:sanitizedText(a.utm_medium,255),utm_campaign:sanitizedText(a.utm_campaign,255),utm_content:sanitizedText(a.utm_content,255),utm_term:sanitizedText(a.utm_term,255),
  referrer:sanitizedText(a.referrer,2048),landing_path:sanitizedText(a.landing_path,1024),tracking_consent:trackingConsent,
  gclid:trackingConsent?sanitizedText(a.gclid,255):null,fbclid:trackingConsent?sanitizedText(a.fbclid,255):null,msclkid:trackingConsent?sanitizedText(a.msclkid,255):null,ttclid:trackingConsent?sanitizedText(a.ttclid,255):null,
};}
function sanitizeEventMetadata(raw:unknown,eventName:string){const m=raw&&typeof raw==="object"&&!Array.isArray(raw)?raw as Record<string,unknown>:{};if(eventName==="landing_view")return{path:sanitizedText(m.path,256)};if(eventName==="consent_updated")return{necessary:true,analytics:m.analytics===true,ads:m.ads===true};return{};}
function requestIdentity(req:Request){const ip=(req.headers.get("x-forwarded-for")||req.headers.get("cf-connecting-ip")||req.headers.get("x-real-ip")||"unknown").split(",")[0].trim();const ua=(req.headers.get("user-agent")||"unknown").slice(0,200);return{ip,ua};}
async function consumePublicRateLimit(req:Request,route:string,limit:number,windowSeconds:number){const{ip,ua}=requestIdentity(req);const bucket=await sha256(`${ip}|${ua}|${route}`);const{data,error}=await db.rpc("consume_rate_limit",{p_route:route,p_bucket:bucket,p_window_seconds:windowSeconds,p_limit:limit});if(error)throw error;return data as {allowed?:boolean;reset_at?:string}|null;}
async function recordAcquisitionEvent(args:{eventName:string;sessionId:string;previewToken?:string|null;leadId?:string|null;attribution?:any;analyticsConsent:boolean;adsConsent:boolean;metadata?:Record<string,unknown>}){const a=sanitizeAttribution(args.attribution,args.adsConsent);const{data,error}=await db.rpc("gcl_record_acquisition_event",{p_event_name:args.eventName,p_session_id:args.sessionId,p_preview_token:args.previewToken||null,p_lead_id:args.leadId||null,p_utm_source:a.utm_source,p_utm_medium:a.utm_medium,p_utm_campaign:a.utm_campaign,p_utm_content:a.utm_content,p_utm_term:a.utm_term,p_referrer:a.referrer,p_landing_path:a.landing_path,p_gclid:a.gclid,p_fbclid:a.fbclid,p_msclkid:a.msclkid,p_ttclid:a.ttclid,p_analytics_consent:args.analyticsConsent,p_ads_consent:args.adsConsent,p_metadata:args.metadata||{}});if(error)throw error;return data;}
function sourceEvidence(f:any){return{source:"common_crawl",snapshot_timestamp:f?.snapshot_timestamp||null,index_id:f?.index_id||null,captured_url:f?.captured_url||null,current_state:false};}
function fallbackFindings(f:any){const s=f?.static||{},ev=sourceEvidence(f),trackers=s.trackers||{},trackerCount=Object.values(trackers).filter(Boolean).length;const out:any[]=[{criterion_code:"SAC-SRC-ARCHIVE-001",status:"not_verifiable",severity:"info",confidence:1,points_available:0,explanation:`O origin atual está protegido. Os sinais de conteúdo, SEO e estrutura abaixo vêm de um snapshot público do Common Crawl de ${f?.snapshot_timestamp||"data registrada"}.`,recommendation:"Interprete copy e estrutura conforme a data da captura. Métricas atuais continuam separadas.",evidence:ev}];
 out.push({criterion_code:"SAC-SEO-001",status:s.title?"pass":"warning",severity:s.title?"info":"warning",confidence:.82,points_available:4,explanation:s.title?`Title detectado: ${s.title}`:"Title não detectado no snapshot.",recommendation:s.title?null:"Adicionar title único e descritivo.",evidence:{...ev,title:s.title}});
 out.push({criterion_code:"SAC-SEO-002",status:s.description?"pass":"warning",severity:s.description?"info":"opportunity",confidence:.82,points_available:3,explanation:s.description?"Meta description detectada no snapshot.":"Meta description não detectada no snapshot.",recommendation:s.description?null:"Adicionar uma descrição útil e específica.",evidence:{...ev,description:s.description}});
 out.push({criterion_code:"SAC-SEO-003",status:Array.isArray(s.h1s)&&s.h1s.length===1?"pass":"warning",severity:Array.isArray(s.h1s)&&s.h1s.length===1?"info":"warning",confidence:.82,points_available:4,explanation:Array.isArray(s.h1s)&&s.h1s.length===1?`H1 principal: ${s.h1s[0]}`:`O snapshot possui ${Array.isArray(s.h1s)?s.h1s.length:0} H1 detectável(is).`,recommendation:"Revisar a hierarquia semântica da página.",evidence:{...ev,h1s:s.h1s||[]}});
 out.push({criterion_code:"SAC-MOB-001",status:s.viewport?"pass":"warning",severity:s.viewport?"info":"important",confidence:.82,points_available:5,explanation:s.viewport?"Viewport responsivo declarado no snapshot.":"Viewport mobile não detectado no snapshot.",recommendation:s.viewport?null:"Adicionar viewport responsivo e validar layout mobile atual.",evidence:{...ev,viewport:s.viewport}});
 const missing=Number(s.images_missing_alt||0),images=Number(s.images||0);out.push({criterion_code:"SAC-MED-001",status:missing===0?"pass":"warning",severity:missing===0?"info":"warning",confidence:.82,points_available:5,explanation:missing===0?`${images} imagens no snapshot sem ausência de ALT detectável.`:`${missing} de ${images} imagens sem ALT no snapshot.`,recommendation:missing===0?null:"Revisar ALT das imagens relevantes.",evidence:{...ev,images,missing_alt:missing}});
 out.push({criterion_code:"SAC-SCH-001",status:Number(s.json_ld_blocks||0)>0?"pass":"warning",severity:Number(s.json_ld_blocks||0)>0?"info":"opportunity",confidence:.82,points_available:4,explanation:Number(s.json_ld_blocks||0)>0?`${s.json_ld_blocks} bloco(s) JSON-LD detectado(s).`:"JSON-LD não detectado no snapshot.",recommendation:Number(s.json_ld_blocks||0)>0?null:"Avaliar structured data aplicável.",evidence:{...ev,json_ld_blocks:s.json_ld_blocks||0}});
 out.push({criterion_code:"SAC-TRK-001",status:trackerCount?"pass":"not_verifiable",severity:"info",confidence:.78,points_available:8,explanation:trackerCount?`Sinais públicos de mensuração detectados no snapshot (${trackerCount}).`:"Nenhum tracker comum foi detectado no snapshot; ausência pública não prova ausência de mensuração.",recommendation:trackerCount?null:"Conectar dados próprios para verificar tracking com maior confiança.",evidence:{...ev,trackers}});return out;}

async function commonCrawlFallback(url:string){
  const {data:cached,error:cacheErr}=await db.rpc("sac_api_source_cache_get",{p_url:url,p_source:"common_crawl"});
  if(!cacheErr&&cached?.available)return{...cached,cache_hit:true};
  const r=await fetch(`${SUPABASE_URL}/functions/v1/sac-commoncrawl`,{method:"POST",headers:{"Content-Type":"application/json","apikey":SERVICE_ROLE_KEY,"Authorization":`Bearer ${SERVICE_ROLE_KEY}`},body:JSON.stringify({url})});
  if(!r.ok)return null;const body=await r.json().catch(()=>null);if(!body?.available)return null;
  const sourceKey=`${body.index_id||"cc"}:${body.digest||await sha256(`${url}|${body.snapshot_timestamp||""}`)}`;
  await db.rpc("sac_api_source_cache_put",{p_url:url,p_source:"common_crawl",p_source_key:sourceKey,p_captured_at:body.snapshot_timestamp||null,p_payload:body}).catch(()=>{});
  return{...body,cache_hit:false};
}

Deno.serve(async(req:Request)=>{const origin=req.headers.get("origin");if(req.method==="OPTIONS")return new Response(null,{status:204,headers:cors(origin)});if(req.method!=="POST")return reply(origin,{error:"method_not_allowed"},405);if(origin&&!allowedOrigins.has(origin))return reply(origin,{error:"origin_not_allowed"},403);
 try{const payload=await req.json(),action=payload?.action;
  if(action==="snapshot"){const{data,error}=await db.rpc("sac_api_snapshot");if(error)throw error;return reply(origin,data);}
  if(action==="request-preview"){const url=normalizeUrl(payload?.url);const{ip,ua}=requestIdentity(req),bucket=await sha256(`${ip}|${ua}|sac-preview-v1`);const{data,error}=await db.rpc("sac_api_request_preview",{p_url:url,p_bucket_key:bucket});if(error){const m=String(error.message||"");if(m.includes("daily_preview_limit"))return reply(origin,{error:"daily_preview_limit"},429);if(m.includes("scanner_busy"))return reply(origin,{error:"scanner_busy"},503);if(m.includes("invalid_url"))return reply(origin,{error:"invalid_url"},400);throw error;}return reply(origin,data,202);}
  if(action==="preview-status"){const token=String(payload?.token||"");if(!UUID_RE.test(token))return reply(origin,{error:"invalid_token"},400);const{data,error}=await db.rpc("sac_api_preview_status",{p_token:token});if(error)throw error;if(data?.found&&data?.status==="completed"&&data?.error_code==="access_limited"&&data?.url){const f=await commonCrawlFallback(String(data.url));if(f){data.error_code="access_fallback";data.content_source={kind:"common_crawl",current:false,snapshot_timestamp:f.snapshot_timestamp,index_id:f.index_id,captured_url:f.captured_url,cache_hit:f.cache_hit===true,disclosure:f.freshness_disclosure};data.access={...(data.access||{}),limited:true,fallback_used:true,fallback_source:"common_crawl"};data.coverage={...(data.coverage||{}),degraded:true,site_content:true,current_site_content:false,archived_site_content:true,content_source:"common_crawl",javascript_rendering:false,axe:false};data.findings=fallbackFindings(f);data.preview_score=null;}}return reply(origin,data);}
  if(action==="acquisition-event"){const eventName=String(payload?.event_name||"").trim().toLowerCase(),sessionId=String(payload?.session_id||""),previewToken=payload?.preview_token?String(payload.preview_token):null;if(!BROWSER_ACQUISITION_EVENTS.has(eventName))return reply(origin,{error:"invalid_acquisition_event"},400);if(!UUID_RE.test(sessionId))return reply(origin,{error:"invalid_session_id"},400);if(previewToken&&!UUID_RE.test(previewToken))return reply(origin,{error:"invalid_preview_token"},400);const analyticsConsent=payload?.analytics_consent===true,adsConsent=payload?.ads_consent===true;if((eventName==="landing_view"||eventName==="diagnostic_started")&&!analyticsConsent)return reply(origin,{recorded:false,reason:"analytics_consent_required"},202);const rl=await consumePublicRateLimit(req,"public:gcl:acquisition-event",30,60);if(rl?.allowed===false)return reply(origin,{error:"rate_limited",reset_at:rl.reset_at||null},429);const attr=eventName==="consent_updated"?{}:payload?.attribution;const metadata=sanitizeEventMetadata(payload?.metadata,eventName);const data=await recordAcquisitionEvent({eventName,sessionId,previewToken,attribution:attr,analyticsConsent,adsConsent,metadata});return reply(origin,data,201);}
  if(action==="save-lead"){const token=String(payload?.preview_token||"");if(!UUID_RE.test(token))return reply(origin,{error:"invalid_token"},400);const email=String(payload?.email||"").trim().slice(0,254),phone=sanitizedText(payload?.phone,40),company=sanitizedText(payload?.company_name,160),segment=sanitizedText(payload?.segment,120),goal=sanitizedText(payload?.goal,160),ticket=sanitizedText(payload?.ticket_band,80),modules=Array.isArray(payload?.selected_modules)?payload.selected_modules.map((x:unknown)=>String(x).slice(0,80)).slice(0,20):[],marketingConsent=payload?.marketing_consent===true,attribution=sanitizeAttribution(payload?.attribution);const{data,error}=await db.rpc("sac_api_save_lead_v81",{p_preview_token:token,p_email:email,p_phone:phone,p_company_name:company,p_segment:segment,p_goal:goal,p_ticket_band:ticket,p_selected_modules:modules,p_marketing_consent:marketingConsent,p_utm_source:attribution.utm_source,p_utm_medium:attribution.utm_medium,p_utm_campaign:attribution.utm_campaign,p_utm_content:attribution.utm_content,p_utm_term:attribution.utm_term,p_referrer:attribution.referrer,p_landing_path:attribution.landing_path,p_gclid:attribution.gclid,p_fbclid:attribution.fbclid,p_msclkid:attribution.msclkid,p_ttclid:attribution.ttclid,p_tracking_consent:attribution.tracking_consent});if(error){const m=String(error.message||"");if(m.includes("invalid_email"))return reply(origin,{error:"invalid_email"},400);if(m.includes("preview_not_completed"))return reply(origin,{error:"preview_not_completed"},409);throw error;}const sessionId=String(payload?.acquisition_session_id||""),analyticsConsent=payload?.consent?.analytics===true,adsConsent=payload?.consent?.ads===true&&attribution.tracking_consent===true;if(UUID_RE.test(sessionId)&&data?.lead_id){recordAcquisitionEvent({eventName:"lead_saved",sessionId,previewToken:token,leadId:String(data.lead_id),attribution,analyticsConsent,adsConsent,metadata:{}}).catch(e=>console.error("gcl lead_saved telemetry",e));}return reply(origin,data,201);}
  return reply(origin,{error:"unknown_action"},400);
 }catch(err){console.error("sac-public-api",err);const m=err instanceof Error?err.message:String(err);if(m==="invalid_url"||m.includes("Invalid URL"))return reply(origin,{error:"invalid_url"},400);if(m.includes("rate_limited"))return reply(origin,{error:"rate_limited"},429);return reply(origin,{error:"internal_error"},500);}
});
