import { createClient } from 'npm:@supabase/supabase-js@2.115.0'

const SUPABASE_URL=Deno.env.get('SUPABASE_URL')!
const ANON_KEY=Deno.env.get('SUPABASE_ANON_KEY')!
const SERVICE_KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
const FUNCTION_SLUG='cozinha360-integrations-v29'
const VERSION='5.5.0'
const DEFAULT_APP='https://cozinha-360-os-v41.onrender.com'
const RETURN_ORIGINS=new Set([DEFAULT_APP,'https://cozinha-360-os.netlify.app','http://localhost:5173','http://127.0.0.1:5173','http://localhost:3000'])
const anon=createClient(SUPABASE_URL,ANON_KEY,{auth:{persistSession:false,autoRefreshToken:false}})
const admin=createClient(SUPABASE_URL,SERVICE_KEY,{auth:{persistSession:false,autoRefreshToken:false}})
const enc=new TextEncoder(),dec=new TextDecoder()
const now=()=>new Date().toISOString()
const env=(name:string)=>(Deno.env.get(name)||'').trim()
const safeOrigin=(value:unknown)=>{try{const origin=new URL(String(value||'')).origin;return RETURN_ORIGINS.has(origin)?origin:DEFAULT_APP}catch{return DEFAULT_APP}}
const safeJson=(value:unknown,fallback:any={})=>{try{return typeof value==='string'?JSON.parse(value):value??fallback}catch{return fallback}}
const h=(value:unknown)=>String(value??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]||m))
function cors(req:Request){const origin=safeOrigin(req.headers.get('origin')||DEFAULT_APP);return{'Access-Control-Allow-Origin':origin,'Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'GET,POST,DELETE,OPTIONS','Access-Control-Max-Age':'86400','Vary':'Origin','Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}}
const j=(req:Request,data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:cors(req)})
const fail=(req:Request,detail:string,status=400,extra:Record<string,unknown>={})=>j(req,{detail,...extra},status)
const parseJson=async(req:Request)=>{try{return await req.json()}catch{return{}}}
const b64=(b:Uint8Array)=>{let s='';for(const x of b)s+=String.fromCharCode(x);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
const unb64=(s:string)=>{s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';const raw=atob(s);return Uint8Array.from(raw,c=>c.charCodeAt(0))}
function routePath(req:Request){const p=new URL(req.url).pathname,marker='/'+FUNCTION_SLUG,i=p.indexOf(marker);return i>=0?(p.slice(i+marker.length)||'/'):p}
function callbackUrl(provider:string){return `${SUPABASE_URL}/functions/v1/${FUNCTION_SLUG}/oauth/${provider}/callback`}

async function auth(req:Request){const h=req.headers.get('authorization')||'',token=h.startsWith('Bearer ')?h.slice(7):'';if(!token)return null;const{data,error}=await anon.auth.getUser(token);if(error||!data.user)return null;let profile=(await admin.from('users').select('id,email,full_name').eq('auth_user_id',data.user.id).maybeSingle()).data;if(!profile&&data.user.email)profile=(await admin.from('users').select('id,email,full_name').ilike('email',data.user.email).maybeSingle()).data;return profile||null}
async function member(userId:number,businessId:number,write=false){const row=(await admin.from('memberships').select('id,role').eq('user_id',userId).eq('business_id',businessId).maybeSingle()).data;if(!row)return null;if(write&&!['owner','admin'].includes(row.role))return null;return row}
async function audit(businessId:number,userId:number,action:string,entityType:string,entityId:string,payload:unknown){await admin.from('audit_logs').insert({business_id:businessId,actor_user_id:userId,action,entity_type:entityType,entity_id:entityId,payload_json:JSON.stringify(payload??{})})}

async function rootBytes(){const seed=env('C360_INTEGRATION_KEY')||`${SERVICE_KEY}:c360-integrations-v29`;return new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(seed)))}
async function aesKey(){return crypto.subtle.importKey('raw',await rootBytes(),{name:'AES-GCM'},false,['encrypt','decrypt'])}
async function seal(value:unknown){const iv=crypto.getRandomValues(new Uint8Array(12)),ct=await crypto.subtle.encrypt({name:'AES-GCM',iv},await aesKey(),enc.encode(JSON.stringify(value)));return{ciphertext:b64(new Uint8Array(ct)),iv:b64(iv)}}
async function openSecret(row:any){const pt=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(row.iv)},await aesKey(),unb64(row.ciphertext));return JSON.parse(dec.decode(pt))}
async function hmacKey(){return crypto.subtle.importKey('raw',await rootBytes(),{name:'HMAC',hash:'SHA-256'},false,['sign','verify'])}
async function signState(payload:Record<string,unknown>){const body=b64(enc.encode(JSON.stringify(payload))),sig=await crypto.subtle.sign('HMAC',await hmacKey(),enc.encode(body));return body+'.'+b64(new Uint8Array(sig))}
async function verifyState(state:string){try{const[body,sig]=state.split('.');if(!body||!sig)return null;const ok=await crypto.subtle.verify('HMAC',await hmacKey(),unb64(sig),enc.encode(body));if(!ok)return null;const data=JSON.parse(dec.decode(unb64(body)));if(Number(data.exp||0)<Date.now())return null;return data}catch{return null}}

const providers=[
 {key:'whatsapp',name:'WhatsApp Business',category:'Vendas & CRM',impact:'Pedidos, recuperação e atendimento em um só fluxo.',why:'Autorize uma vez; o 360 encontra o número empresarial e vincula sozinho quando não há ambiguidade.',needs:['META_APP_ID','META_APP_SECRET'],mode:'oauth',eta:'~2 min',asset_kind:'Número WhatsApp'},
 {key:'mercadopago',name:'Mercado Pago / Pix',category:'Pagamentos',impact:'Conciliação de pagamentos e confirmação automática do pedido.',why:'OAuth + PKCE, renovação silenciosa e baixa automática sem expor credenciais.',needs:['MERCADOPAGO_CLIENT_ID','MERCADOPAGO_CLIENT_SECRET'],mode:'oauth',eta:'~1 min',asset_kind:'Conta Mercado Pago'},
 {key:'google',name:'Google Business',category:'Aquisição local',impact:'Perfil local e presença no Google conectados à mesma operação.',why:'O 360 detecta as contas Business Profile disponíveis e pede escolha só quando houver mais de uma.',needs:['GOOGLE_CLIENT_ID','GOOGLE_CLIENT_SECRET'],optional:['GOOGLE_ADS_DEVELOPER_TOKEN'],mode:'oauth',eta:'~2 min',asset_kind:'Conta Business Profile'},
 {key:'ifood',name:'iFood',category:'Marketplace',impact:'Pedidos do iFood entram na fila operacional sem redigitação.',why:'Usa autorização distribuída oficial, identifica a loja e prepara polling/webhook sem senha do restaurante.',needs:['IFOOD_CLIENT_ID','IFOOD_CLIENT_SECRET'],mode:'device_code',eta:'~3 min',asset_kind:'Loja iFood'},
 {key:'meta_ads',name:'Meta Ads',category:'Aquisição',impact:'Campanhas e atribuição podem conversar com margem e venda direta.',why:'O 360 descobre as contas de anúncio disponíveis e mantém o token fora do navegador.',needs:['META_APP_ID','META_APP_SECRET'],mode:'oauth',eta:'~2 min',asset_kind:'Conta de anúncios'}
]
function readiness(p:any){const missing=p.needs.filter((n:string)=>!env(n)),optionalMissing=(p.optional||[]).filter((n:string)=>!env(n));return{platform_ready:missing.length===0,missing,optional_missing:optionalMissing}}
async function ensureConnection(businessId:number,provider:string){const r=await admin.from('integration_connections').select('*').eq('business_id',businessId).eq('provider',provider).order('id',{ascending:true}).limit(1).maybeSingle();if(r.data){await admin.from('integration_connections').update({status:'connecting',last_error:null,updated_at:now()}).eq('id',r.data.id);return{...r.data,status:'connecting'}}const ins=await admin.from('integration_connections').insert({business_id:businessId,provider,mode:provider==='ifood'?'polling':'webhook',status:'connecting'}).select('*').single();if(ins.error)throw ins.error;return ins.data}
async function saveCredential(connection:any,payload:any,expiresAt:string|null=null,scopes:string[]=[],metadata:any={}){const sealed=await seal(payload),r=await admin.from('integration_credentials').upsert({connection_id:connection.id,business_id:connection.business_id,provider:connection.provider,ciphertext:sealed.ciphertext,iv:sealed.iv,key_version:1,expires_at:expiresAt,scopes_json:JSON.stringify(scopes),metadata_json:JSON.stringify(metadata),updated_at:now()},{onConflict:'connection_id'});if(r.error)throw r.error}
async function credential(connectionId:number){const r=await admin.from('integration_credentials').select('*').eq('connection_id',connectionId).maybeSingle();if(r.error)throw r.error;return r.data?{row:r.data,secret:await openSecret(r.data),metadata:safeJson(r.data.metadata_json,{}),scopes:safeJson(r.data.scopes_json,[])}:null}
async function activate(connection:any,external:string,display:string){const patch={external_account_ref:external||connection.external_account_ref||null,display_name:display||connection.display_name||null,status:'active',last_success_at:now(),last_error:null,updated_at:now()},r=await admin.from('integration_connections').update(patch).eq('id',connection.id).select('*').single();if(r.error)throw r.error;return r.data}
async function mark(connectionId:number,status:'active'|'connecting'|'degraded',message:string|null=null){await admin.from('integration_connections').update({status,last_error:message?message.slice(0,800):null,last_error_at:message?now():null,...(status==='active'?{last_success_at:now()}:{}),updated_at:now()}).eq('id',connectionId)}

async function jsonFetch(url:string,init:RequestInit,label:string){const r=await fetch(url,init),x=await r.json().catch(()=>({}));if(!r.ok)throw new Error(String(x?.error?.message||x?.message||x?.error_description||x?.error||`${label} recusou a solicitação`));return x}
const bearer=(token:string)=>({authorization:`Bearer ${token}`})

function googleAuth(state:string){const q=new URLSearchParams({client_id:env('GOOGLE_CLIENT_ID'),redirect_uri:callbackUrl('google'),response_type:'code',access_type:'offline',prompt:'consent',include_granted_scopes:'true',scope:['openid','email','profile','https://www.googleapis.com/auth/business.manage'].join(' '),state});return'https://accounts.google.com/o/oauth2/v2/auth?'+q}
function mercadoAuth(state:string,challenge:string){const q=new URLSearchParams({client_id:env('MERCADOPAGO_CLIENT_ID'),response_type:'code',platform_id:'mp',state,redirect_uri:callbackUrl('mercadopago'),code_challenge:challenge,code_challenge_method:'S256',scope:'read write offline_access'});return'https://auth.mercadopago.com.br/authorization?'+q}
function metaAuth(provider:string,state:string){const scopes=provider==='whatsapp'?['business_management','whatsapp_business_management','whatsapp_business_messaging']:['business_management','ads_read','ads_management'],q=new URLSearchParams({client_id:env('META_APP_ID'),redirect_uri:callbackUrl(provider),response_type:'code',state,scope:scopes.join(',')});return'https://www.facebook.com/dialog/oauth?'+q}
async function pkce(){const verifier=b64(crypto.getRandomValues(new Uint8Array(48))),digest=await crypto.subtle.digest('SHA-256',enc.encode(verifier));return{verifier,challenge:b64(new Uint8Array(digest))}}

async function exchangeGoogle(code:string){const form=new URLSearchParams({code,client_id:env('GOOGLE_CLIENT_ID'),client_secret:env('GOOGLE_CLIENT_SECRET'),redirect_uri:callbackUrl('google'),grant_type:'authorization_code'}),x=await jsonFetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:form},'Google OAuth'),u=await jsonFetch('https://www.googleapis.com/oauth2/v3/userinfo',{headers:bearer(x.access_token)},'Google');return{token:x,identity:{ref:String(u.sub||u.email||''),label:String(u.email||u.name||'Google')}}}
async function exchangeMercado(code:string,verifier:string){const x=await jsonFetch('https://api.mercadopago.com/oauth/token',{method:'POST',headers:{accept:'application/json','content-type':'application/json'},body:JSON.stringify({client_id:env('MERCADOPAGO_CLIENT_ID'),client_secret:env('MERCADOPAGO_CLIENT_SECRET'),code,grant_type:'authorization_code',redirect_uri:callbackUrl('mercadopago'),code_verifier:verifier})},'Mercado Pago OAuth'),u=await jsonFetch('https://api.mercadopago.com/users/me',{headers:bearer(x.access_token)},'Mercado Pago');return{token:x,identity:{ref:String(x.user_id||u.id||''),label:String(u.nickname||u.email||'Mercado Pago')}}}
async function exchangeMeta(provider:string,code:string){const q=new URLSearchParams({client_id:env('META_APP_ID'),client_secret:env('META_APP_SECRET'),redirect_uri:callbackUrl(provider),code}),x=await jsonFetch('https://graph.facebook.com/oauth/access_token?'+q,{method:'GET'},'Meta OAuth'),u=await jsonFetch('https://graph.facebook.com/me?fields=id,name',{headers:bearer(x.access_token)},'Meta');return{token:x,identity:{ref:String(u.id||''),label:String(u.name||'Meta')}}}

async function refreshGoogle(secret:any){if(!secret.refresh_token)throw new Error('Google exige nova autorização');const form=new URLSearchParams({client_id:env('GOOGLE_CLIENT_ID'),client_secret:env('GOOGLE_CLIENT_SECRET'),refresh_token:String(secret.refresh_token),grant_type:'refresh_token'}),x=await jsonFetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:form},'Google refresh');return{...secret,...x,refresh_token:secret.refresh_token}}
async function refreshMercado(secret:any){if(!secret.refresh_token)throw new Error('Mercado Pago exige nova autorização');const x=await jsonFetch('https://api.mercadopago.com/oauth/token',{method:'POST',headers:{accept:'application/json','content-type':'application/json'},body:JSON.stringify({client_id:env('MERCADOPAGO_CLIENT_ID'),client_secret:env('MERCADOPAGO_CLIENT_SECRET'),grant_type:'refresh_token',refresh_token:secret.refresh_token})},'Mercado Pago refresh');return{...secret,...x}}
async function refreshIfood(secret:any){if(!secret.refreshToken)throw new Error('iFood exige nova autorização');const form=new URLSearchParams({grantType:'refresh_token',clientId:env('IFOOD_CLIENT_ID'),clientSecret:env('IFOOD_CLIENT_SECRET'),refreshToken:String(secret.refreshToken)});const x=await jsonFetch('https://merchant-api.ifood.com.br/authentication/v1.0/oauth/token',{method:'POST',headers:{accept:'application/json','content-type':'application/x-www-form-urlencoded'},body:form},'iFood refresh');return{...secret,...x}}
function expiryFrom(secret:any,fallbackSeconds=0){const seconds=Number(secret.expires_in||secret.expiresIn||fallbackSeconds);return seconds?new Date(Date.now()+seconds*1000).toISOString():null}
async function ensureFresh(connection:any,cred:any){const exp=cred.row.expires_at?Date.parse(cred.row.expires_at):0;if(!exp||exp>Date.now()+5*60_000)return cred;let secret=cred.secret;if(connection.provider==='google')secret=await refreshGoogle(secret);else if(connection.provider==='mercadopago')secret=await refreshMercado(secret);else if(connection.provider==='ifood')secret=await refreshIfood(secret);else throw new Error(`${connection.provider} exige nova autorização`);const expiresAt=expiryFrom(secret),metadata={...cred.metadata,refreshed_at:now()};await saveCredential(connection,secret,expiresAt,cred.scopes,metadata);return{...cred,secret,metadata,row:{...cred.row,expires_at:expiresAt}}}

type Asset={ref:string;label:string;kind:string;detail?:string}
async function discoverAssets(provider:string,secret:any,identity?:any):Promise<Asset[]>{
 if(provider==='mercadopago')return identity?.ref?[{ref:identity.ref,label:identity.label||'Mercado Pago',kind:'Conta Mercado Pago'}]:[]
 if(provider==='google'){const x=await jsonFetch('https://mybusinessaccountmanagement.googleapis.com/v1/accounts',{headers:bearer(secret.access_token)},'Google Business Profile');return (x.accounts||[]).map((a:any)=>({ref:String(a.name||''),label:String(a.accountName||a.name||'Google Business'),kind:'Conta Business Profile',detail:String(a.type||'')})).filter((a:Asset)=>a.ref)}
 if(provider==='meta_ads'){const x=await jsonFetch('https://graph.facebook.com/me/adaccounts?fields=id,name,account_status,currency&limit=100',{headers:bearer(secret.access_token)},'Meta Ads');return (x.data||[]).map((a:any)=>({ref:String(a.id||''),label:String(a.name||a.id||'Conta Meta Ads'),kind:'Conta de anúncios',detail:String(a.currency||'')})).filter((a:Asset)=>a.ref)}
 if(provider==='whatsapp'){const businesses=await jsonFetch('https://graph.facebook.com/me/businesses?fields=id,name&limit=50',{headers:bearer(secret.access_token)},'WhatsApp Business'),assets:Asset[]=[];for(const b of (businesses.data||[]).slice(0,50)){try{const w=await jsonFetch(`https://graph.facebook.com/${encodeURIComponent(b.id)}/owned_whatsapp_business_accounts?fields=id,name&limit=50`,{headers:bearer(secret.access_token)},'WhatsApp Business');for(const wa of (w.data||[])){try{const p=await jsonFetch(`https://graph.facebook.com/${encodeURIComponent(wa.id)}/phone_numbers?fields=id,display_phone_number,verified_name,quality_rating&limit=50`,{headers:bearer(secret.access_token)},'WhatsApp Business');for(const phone of (p.data||[]))assets.push({ref:String(phone.id),label:String(phone.verified_name||phone.display_phone_number||wa.name||'WhatsApp'),kind:'Número WhatsApp',detail:String(phone.display_phone_number||b.name||'')})}catch{}}}catch{}}return assets}
 if(provider==='ifood'){const rows=await jsonFetch('https://merchant-api.ifood.com.br/merchant/v1.0/merchants',{headers:bearer(secret.accessToken)},'iFood');return (Array.isArray(rows)?rows:rows.merchants||[]).map((m:any)=>({ref:String(m.id||''),label:String(m.name||m.corporateName||m.id||'iFood'),kind:'Loja iFood',detail:String(m.corporateName||'')})).filter((a:Asset)=>a.ref)}
 return[]
}
async function persistDiscovery(connection:any,cred:any,assets:Asset[],selected:Asset|null,extra:any={}){const metadata={...cred.metadata,...extra,assets,asset_count:assets.length,selected_asset_ref:selected?.ref||null,selected_asset_label:selected?.label||null,selection_required:assets.length>1&&!selected,last_discovered_at:now()};await saveCredential(connection,cred.secret,cred.row.expires_at,cred.scopes,metadata);return metadata}
async function autoBindSingleBrand(connection:any,asset:Asset|null){if(!['ifood','whatsapp','mercadopago'].includes(String(connection.provider)))return{configured:false,reason:'not_applicable'};const{data:brands=[]}=await admin.from('brands').select('id,name').eq('business_id',connection.business_id).eq('active',true).eq('soft_deleted',false);if((brands||[]).length!==1)return{configured:false,reason:(brands||[]).length?'multi_brand':'no_brand'};const brand=(brands||[])[0],provider=String(connection.provider);const row={business_id:connection.business_id,brand_id:brand.id,connection_id:connection.id,provider,external_store_ref:asset?.ref||null,order_import_enabled:['ifood','whatsapp'].includes(provider),menu_sync_enabled:false,price_sync_enabled:false,availability_sync_enabled:false,auto_accept_orders:false,active:true,updated_at:now()};const r=await admin.from('brand_integration_bindings').upsert(row,{onConflict:'business_id,brand_id,provider'}).select('id').single();return r.error?{configured:false,reason:'binding_error'}:{configured:true,brand_id:brand.id,binding_id:r.data.id}}

function selectionHtml(provider:string,ticket:string,assets:Asset[]){const title=providers.find(p=>p.key===provider)?.name||provider,links=assets.map(a=>`<a href="${callbackUrl(provider).replace('/callback','/select')}?ticket=${encodeURIComponent(ticket)}&asset_ref=${encodeURIComponent(a.ref)}"><strong>${h(a.label)}</strong><small>${h(a.detail||a.kind)}</small><span>Usar esta conta →</span></a>`).join('');return`<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Escolha sua conta · Cozinha 360</title><style>body{margin:0;background:#0d1015;color:#f7f7f5;font:16px Inter,system-ui,sans-serif;min-height:100vh;display:grid;place-items:center}.box{width:min(680px,calc(100% - 32px));padding:32px;border:1px solid #ffffff1f;border-radius:28px;background:#171b22e8;box-shadow:0 30px 90px #0008}p{color:#aeb7c3;line-height:1.6}a{display:grid;grid-template-columns:1fr auto;gap:5px 18px;margin-top:12px;padding:18px 20px;border:1px solid #ffffff1a;border-radius:18px;color:inherit;text-decoration:none;background:#ffffff08}a:hover{border-color:#73e9ba88;background:#73e9ba0d}a strong{font-size:17px}a small{color:#8f9aa8}a span{grid-row:1/3;grid-column:2;align-self:center;color:#73e9ba}.eyebrow{font-size:12px;letter-spacing:.16em;color:#73e9ba;text-transform:uppercase}</style></head><body><main class="box"><div class="eyebrow">Cozinha 360 · conexão segura</div><h1>Qual ${h(title)} pertence a esta operação?</h1><p>Encontramos mais de uma opção. Escolha uma vez; o 360 guarda apenas a referência necessária e mantém o token criptografado no servidor.</p>${links}</main></body></html>`}

async function finishOAuth(req:Request,provider:string,state:any,connection:any,result:any){const expiresAt=expiryFrom(result.token),scopes=String(result.token.scope||'').split(/[ ,]+/).filter(Boolean),baseCred={row:{expires_at:expiresAt},secret:result.token,metadata:{identity_ref:result.identity.ref,identity_label:result.identity.label,return_origin:safeOrigin(state.return_origin||DEFAULT_APP)},scopes};let assets=await discoverAssets(provider,result.token,result.identity);if(provider==='mercadopago'&&!assets.length)assets=[{ref:result.identity.ref,label:result.identity.label,kind:'Conta Mercado Pago'}];if(!assets.length){await saveCredential(connection,result.token,expiresAt,scopes,{...baseCred.metadata,assets:[],asset_count:0,selection_required:false,last_discovered_at:now()});await mark(connection.id,'degraded','Autorização concluída, mas nenhum ativo operacional foi encontrado nesta conta.');throw new Error('Nenhum ativo operacional encontrado')}
 if(assets.length>1){await persistDiscovery(connection,baseCred,assets,null);await mark(connection.id,'connecting','Escolha qual conta deve ser usada nesta operação.');const ticket=await signState({business_id:connection.business_id,user_id:Number(state.user_id),provider,connection_id:connection.id,return_origin:safeOrigin(state.return_origin||DEFAULT_APP),exp:Date.now()+15*60_000});return new Response(selectionHtml(provider,ticket,assets),{status:200,headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}})}
 const asset=assets[0];await persistDiscovery(connection,baseCred,assets,asset);const active=await activate(connection,asset.ref,asset.label),binding=await autoBindSingleBrand(active,asset);await audit(connection.business_id,Number(state.user_id),'connect','integration_connection',String(connection.id),{provider,asset_ref:asset.ref,auto_binding:binding});return Response.redirect(`${safeOrigin(state.return_origin||DEFAULT_APP)}/?connections=1&connected=${encodeURIComponent(provider)}`,302)}

async function handleStart(req:Request,businessId:number,provider:string,userId:number){const def=providers.find(p=>p.key===provider);if(!def)return fail(req,'Integração desconhecida',404);const ready=readiness(def);if(!ready.platform_ready)return fail(req,'A plataforma ainda precisa das credenciais oficiais deste provedor.',503,{code:'platform_setup_required',provider,missing:ready.missing});const payload:any=await parseJson(req),returnOrigin=safeOrigin(payload.return_origin||req.headers.get('origin')||DEFAULT_APP),c=await ensureConnection(businessId,provider),statePayload={business_id:businessId,user_id:userId,provider,connection_id:c.id,return_origin:returnOrigin,exp:Date.now()+10*60_000};if(provider==='google'){const state=await signState(statePayload);return j(req,{action:'redirect',authorization_url:googleAuth(state),connection_id:c.id,return_origin:returnOrigin})}if(provider==='mercadopago'){const p=await pkce();await saveCredential(c,{pkce_verifier:p.verifier},new Date(Date.now()+10*60_000).toISOString(),[],{stage:'oauth_pending',return_origin:returnOrigin});const state=await signState(statePayload);return j(req,{action:'redirect',authorization_url:mercadoAuth(state,p.challenge),connection_id:c.id,return_origin:returnOrigin})}if(provider==='whatsapp'||provider==='meta_ads'){const state=await signState(statePayload);return j(req,{action:'redirect',authorization_url:metaAuth(provider,state),connection_id:c.id,return_origin:returnOrigin})}if(provider==='ifood'){const form=new URLSearchParams({clientId:env('IFOOD_CLIENT_ID')}),x=await jsonFetch('https://merchant-api.ifood.com.br/authentication/v1.0/oauth/userCode',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:form},'iFood');await saveCredential(c,{authorizationCodeVerifier:x.authorizationCodeVerifier},new Date(Date.now()+Number(x.expiresIn||600)*1000).toISOString(),[],{stage:'device_code',user_code:x.userCode,verification_url:x.verificationUrlComplete||x.verificationUrl,return_origin:returnOrigin});return j(req,{action:'device_code',connection_id:c.id,user_code:x.userCode,authorization_url:x.verificationUrlComplete||x.verificationUrl,expires_in:Number(x.expiresIn||600),next:'Autorize no Portal do Parceiro e cole o código exibido.'})}return fail(req,'Fluxo não implementado',501)}

async function handleOAuth(req:Request,provider:string){const url=new URL(req.url),state=await verifyState(url.searchParams.get('state')||''),code=url.searchParams.get('code')||'',oauthError=url.searchParams.get('error')||'';if(!state||state.provider!==provider)return new Response('OAuth state inválido ou expirado',{status:400,headers:{'Content-Type':'text/plain; charset=utf-8'}});const businessId=Number(state.business_id),userId=Number(state.user_id),connectionId=Number(state.connection_id),returnOrigin=safeOrigin(state.return_origin||DEFAULT_APP);if(!await member(userId,businessId,true))return new Response('Acesso revogado',{status:403});const c=(await admin.from('integration_connections').select('*').eq('id',connectionId).eq('business_id',businessId).maybeSingle()).data;if(!c)return new Response('Conexão não encontrada',{status:404});try{if(oauthError||!code)throw new Error(oauthError||'Autorização cancelada');let result:any;if(provider==='google')result=await exchangeGoogle(code);else if(provider==='mercadopago'){const pending=await credential(connectionId);result=await exchangeMercado(code,String(pending?.secret?.pkce_verifier||''))}else if(provider==='whatsapp'||provider==='meta_ads')result=await exchangeMeta(provider,code);else throw new Error('Provider callback inválido');return await finishOAuth(req,provider,state,c,result)}catch(e){await mark(c.id,'degraded',String((e as any)?.message||e));return Response.redirect(`${returnOrigin}/?connections=1&connection_error=${encodeURIComponent(provider)}`,302)}}

async function handleOAuthSelect(req:Request,provider:string){const url=new URL(req.url),ticket=await verifyState(url.searchParams.get('ticket')||''),assetRef=String(url.searchParams.get('asset_ref')||'');if(!ticket||ticket.provider!==provider)return new Response('Seleção expirada',{status:400});const businessId=Number(ticket.business_id),userId=Number(ticket.user_id),connectionId=Number(ticket.connection_id),returnOrigin=safeOrigin(ticket.return_origin||DEFAULT_APP);if(!await member(userId,businessId,true))return new Response('Acesso revogado',{status:403});const connection=(await admin.from('integration_connections').select('*').eq('id',connectionId).eq('business_id',businessId).maybeSingle()).data,cred=connection?await credential(connectionId):null;if(!connection||!cred)return new Response('Conexão não encontrada',{status:404});const assets=(cred.metadata.assets||[]) as Asset[],asset=assets.find(a=>a.ref===assetRef);if(!asset)return new Response('Conta inválida',{status:422});try{await persistDiscovery(connection,cred,assets,asset,{selection_required:false,selected_at:now()});const active=await activate(connection,asset.ref,asset.label),binding=await autoBindSingleBrand(active,asset);await audit(businessId,userId,'select_asset','integration_connection',String(connectionId),{provider,asset_ref:asset.ref,auto_binding:binding});return Response.redirect(`${returnOrigin}/?connections=1&connected=${encodeURIComponent(provider)}`,302)}catch(e){await mark(connectionId,'degraded',String((e as any)?.message||e));return Response.redirect(`${returnOrigin}/?connections=1&connection_error=${encodeURIComponent(provider)}`,302)}}

async function handleIfoodComplete(req:Request,businessId:number,userId:number,p:any){const c=(await admin.from('integration_connections').select('*').eq('business_id',businessId).eq('provider','ifood').order('id',{ascending:true}).limit(1).maybeSingle()).data;if(!c)return fail(req,'Inicie a conexão iFood primeiro.',409);const pending=await credential(c.id),verifier=String(pending?.secret?.authorizationCodeVerifier||''),authorizationCode=String(p.authorization_code||'').trim();if(!verifier||!authorizationCode)return fail(req,'Código de autorização ou verificador ausente/expirado.',422);try{const form=new URLSearchParams({grantType:'authorization_code',clientId:env('IFOOD_CLIENT_ID'),clientSecret:env('IFOOD_CLIENT_SECRET'),authorizationCode,authorizationCodeVerifier:verifier}),token=await jsonFetch('https://merchant-api.ifood.com.br/authentication/v1.0/oauth/token',{method:'POST',headers:{accept:'application/json','content-type':'application/x-www-form-urlencoded'},body:form},'iFood OAuth'),expiresAt=expiryFrom(token,21600),baseCred={row:{expires_at:expiresAt},secret:token,metadata:{return_origin:safeOrigin(pending?.metadata?.return_origin||DEFAULT_APP)},scopes:[]},assets=await discoverAssets('ifood',token);if(!assets.length)throw new Error('Nenhuma loja iFood autorizada foi encontrada.');let asset:Asset|null=null;if(assets.length===1)asset=assets[0];else if(p.merchant_id)asset=assets.find(a=>a.ref===String(p.merchant_id))||null;await persistDiscovery(c,baseCred,assets,asset);if(!asset){await mark(c.id,'connecting','Escolha qual loja iFood pertence a esta operação.');return j(req,{ok:true,action:'select_asset',connection_id:c.id,assets,selection_required:true})}const active=await activate(c,asset.ref,asset.label),binding=await autoBindSingleBrand(active,asset);await audit(businessId,userId,'connect','integration_connection',String(c.id),{provider:'ifood',asset_ref:asset.ref,auto_binding:binding});return j(req,{ok:true,connection:active,asset,auto_binding:binding})}catch(e){await mark(c.id,'degraded',String((e as any)?.message||e));return fail(req,String((e as any)?.message||e),400)}}

async function handleSelect(req:Request,businessId:number,userId:number,provider:string,p:any){const c=(await admin.from('integration_connections').select('*').eq('business_id',businessId).eq('provider',provider).order('id',{ascending:true}).limit(1).maybeSingle()).data;if(!c)return fail(req,'Conexão não encontrada',404);const cred=await credential(c.id);if(!cred)return fail(req,'Credencial não encontrada',404);const assets=(cred.metadata.assets||[]) as Asset[],asset=assets.find(a=>a.ref===String(p.asset_ref||''));if(!asset)return fail(req,'Conta externa inválida.',422);await persistDiscovery(c,cred,assets,asset,{selection_required:false,selected_at:now()});const active=await activate(c,asset.ref,asset.label),binding=await autoBindSingleBrand(active,asset);await audit(businessId,userId,'select_asset','integration_connection',String(c.id),{provider,asset_ref:asset.ref,auto_binding:binding});return j(req,{ok:true,connection:active,asset,auto_binding:binding})}

async function handleTest(req:Request,connection:any){const original=await credential(connection.id);if(!original)return fail(req,'Credencial não encontrada',404);try{const cred=await ensureFresh(connection,original),assets=await discoverAssets(connection.provider,cred.secret,{ref:connection.external_account_ref,label:connection.display_name}),selectedRef=String(cred.metadata.selected_asset_ref||connection.external_account_ref||''),selected=assets.find(a=>a.ref===selectedRef)||(!selectedRef&&assets.length===1?assets[0]:null);if(!assets.length)throw new Error('Nenhum ativo operacional encontrado nesta conta.');if(assets.length>1&&!selected){await persistDiscovery(connection,cred,assets,null);await mark(connection.id,'connecting','Escolha qual conta deve ser usada nesta operação.');return fail(req,'Há mais de uma conta disponível. Escolha qual pertence a esta operação.',409,{code:'asset_selection_required',assets})}await persistDiscovery(connection,cred,assets,selected);const active=await activate(connection,selected?.ref||connection.external_account_ref||'',selected?.label||connection.display_name||'');const binding=await autoBindSingleBrand(active,selected);return j(req,{ok:true,status:'active',tested_at:now(),asset:selected,auto_binding:binding,token_refreshed:cred.secret!==original.secret})}catch(e){await mark(connection.id,'degraded',String((e as any)?.message||e));return fail(req,String((e as any)?.message||e),502,{status:'degraded'})}}

Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(req)});const path=routePath(req),method=req.method;try{if(path==='/livez'&&method==='GET')return j(req,{ok:true,service:FUNCTION_SLUG,version:VERSION});if(path==='/readyz'&&method==='GET'){const r=await admin.from('integration_connections').select('id',{head:true,count:'exact'});return r.error?fail(req,'database_not_ready',503):j(req,{ok:true,database:'ready',providers:providers.length,version:VERSION})}
 let m=path.match(/^\/oauth\/(google|mercadopago|whatsapp|meta_ads)\/callback$/);if(m&&method==='GET')return handleOAuth(req,m[1]);m=path.match(/^\/oauth\/(google|mercadopago|whatsapp|meta_ads)\/select$/);if(m&&method==='GET')return handleOAuthSelect(req,m[1]);
 const user:any=await auth(req);if(!user)return fail(req,'Sessão inválida',401);
 m=path.match(/^\/businesses\/(\d+)\/integrations$/);if(m&&method==='GET'){const bid=Number(m[1]);if(!await member(user.id,bid))return fail(req,'Sem acesso',403);const[{data:connections=[]},{data:creds=[]}]=await Promise.all([admin.from('integration_connections').select('id,provider,external_account_ref,display_name,status,last_event_at,last_success_at,last_error_at,last_error,updated_at').eq('business_id',bid).order('provider'),admin.from('integration_credentials').select('connection_id,provider,expires_at,metadata_json').eq('business_id',bid)]),metaBy=new Map((creds||[]).map((x:any)=>[Number(x.connection_id),{expires_at:x.expires_at,metadata:safeJson(x.metadata_json,{})}])),by=new Map((connections||[]).map((x:any)=>[x.provider,x]));return j(req,{business_id:bid,recommended_order:['whatsapp','mercadopago','google','ifood','meta_ads'],providers:providers.map(p=>{const c:any=by.get(p.key)||null,cm:any=c?metaBy.get(Number(c.id)):null,metadata:any=cm?.metadata||{},operational=Boolean(c?.status==='active'&&(!metadata.selection_required)&&(metadata.asset_count===undefined||metadata.asset_count>0));return{...p,...readiness(p),connection:c,operational,asset_count:Number(metadata.asset_count||0),selection_required:Boolean(metadata.selection_required),assets:metadata.selection_required?metadata.assets||[]:undefined,selected_asset:metadata.selected_asset_ref?{ref:metadata.selected_asset_ref,label:metadata.selected_asset_label}:null,credential_expires_at:cm?.expires_at||null}})})}
 m=path.match(/^\/businesses\/(\d+)\/integrations\/([a-z_]+)\/start$/);if(m&&method==='POST'){const bid=Number(m[1]);if(!await member(user.id,bid,true))return fail(req,'Somente owner/admin pode conectar contas',403);return handleStart(req,bid,m[2],user.id)}
 m=path.match(/^\/businesses\/(\d+)\/integrations\/ifood\/complete$/);if(m&&method==='POST'){const bid=Number(m[1]);if(!await member(user.id,bid,true))return fail(req,'Somente owner/admin',403);return handleIfoodComplete(req,bid,user.id,await parseJson(req))}
 m=path.match(/^\/businesses\/(\d+)\/integrations\/([a-z_]+)\/select$/);if(m&&method==='POST'){const bid=Number(m[1]);if(!await member(user.id,bid,true))return fail(req,'Somente owner/admin',403);return handleSelect(req,bid,user.id,m[2],await parseJson(req))}
 m=path.match(/^\/businesses\/(\d+)\/integrations\/([a-z_]+)\/test$/);if(m&&method==='POST'){const bid=Number(m[1]);if(!await member(user.id,bid,true))return fail(req,'Somente owner/admin',403);const c=(await admin.from('integration_connections').select('*').eq('business_id',bid).eq('provider',m[2]).order('id',{ascending:true}).limit(1).maybeSingle()).data;if(!c)return fail(req,'Conexão não encontrada',404);return handleTest(req,c)}
 m=path.match(/^\/businesses\/(\d+)\/integrations\/([a-z_]+)$/);if(m&&method==='DELETE'){const bid=Number(m[1]);if(!await member(user.id,bid,true))return fail(req,'Somente owner/admin',403);const{data:rows=[]}=await admin.from('integration_connections').select('id').eq('business_id',bid).eq('provider',m[2]);for(const c of rows||[])await admin.from('integration_credentials').delete().eq('connection_id',c.id);await admin.from('integration_connections').update({status:'disabled',last_error:null,updated_at:now()}).eq('business_id',bid).eq('provider',m[2]);await audit(bid,user.id,'disconnect','integration_connection',m[2],{provider:m[2]});return j(req,{ok:true,status:'disabled'})}
 return fail(req,'Rota não encontrada',404)}catch(e){console.error('integrations-v29',e);return fail(req,'Erro interno',500)}})