import { createClient } from 'npm:@supabase/supabase-js@2.115.0'

const SUPABASE_URL=Deno.env.get('SUPABASE_URL')!
const ANON_KEY=Deno.env.get('SUPABASE_ANON_KEY')!
const SERVICE_KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
const SLUG='cozinha360-google-business-v75'
const VERSION='7.5.0'
const DEFAULT_APP='https://cozinha-360-os-v41.onrender.com'
const RETURN_ORIGINS=new Set([DEFAULT_APP,'https://cozinha-360-os.netlify.app','http://localhost:5173','http://127.0.0.1:5173','http://localhost:3000'])
const anon=createClient(SUPABASE_URL,ANON_KEY,{auth:{persistSession:false,autoRefreshToken:false}})
const admin=createClient(SUPABASE_URL,SERVICE_KEY,{auth:{persistSession:false,autoRefreshToken:false}})
const enc=new TextEncoder(),dec=new TextDecoder()
const now=()=>new Date().toISOString()
const env=(name:string)=>(Deno.env.get(name)||'').trim()
const safeJson=(value:any,fallback:any={})=>{try{return typeof value==='string'?JSON.parse(value):value??fallback}catch{return fallback}}
const b64=(b:Uint8Array)=>{let s='';for(const x of b)s+=String.fromCharCode(x);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
const unb64=(s:string)=>{s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';const raw=atob(s);return Uint8Array.from(raw,c=>c.charCodeAt(0))}
const sha=async(value:string)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(value)))).map(x=>x.toString(16).padStart(2,'0')).join('')
const normalize=(value:any)=>String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()
function routePath(req:Request){const p=new URL(req.url).pathname,marker='/'+SLUG,i=p.indexOf(marker);return i>=0?(p.slice(i+marker.length)||'/'):p}
function cors(req:Request){let origin=DEFAULT_APP;try{const candidate=new URL(req.headers.get('origin')||DEFAULT_APP).origin;if(RETURN_ORIGINS.has(candidate))origin=candidate}catch{}return{'Access-Control-Allow-Origin':origin,'Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type, x-c360-google-key','Access-Control-Allow-Methods':'GET,POST,PUT,OPTIONS','Access-Control-Max-Age':'86400','Vary':'Origin','Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}}
const json=(req:Request,data:any,status=200)=>new Response(JSON.stringify(data),{status,headers:cors(req)})
const fail=(req:Request,detail:string,status=400,extra:any={})=>json(req,{detail,...extra},status)
const parseJson=async(req:Request)=>{try{return await req.json()}catch{return{}}}

class HttpError extends Error{status:number;body:any;constructor(status:number,message:string,body:any={}){super(message);this.status=status;this.body=body}}
async function api(url:string,init:RequestInit,label:string){const response=await fetch(url,init);if(response.status===204)return null;const body=await response.json().catch(()=>({}));if(!response.ok)throw new HttpError(response.status,String(body?.error?.message||body?.message||body?.error_description||body?.error||`${label} recusou a solicitação`),body);return body}

async function rootBytes(){const seed=env('C360_INTEGRATION_KEY')||`${SERVICE_KEY}:c360-integrations-v29`;return new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(seed)))}
async function aesKey(){return crypto.subtle.importKey('raw',await rootBytes(),{name:'AES-GCM'},false,['encrypt','decrypt'])}
async function seal(value:any){const iv=crypto.getRandomValues(new Uint8Array(12)),ct=await crypto.subtle.encrypt({name:'AES-GCM',iv},await aesKey(),enc.encode(JSON.stringify(value)));return{ciphertext:b64(new Uint8Array(ct)),iv:b64(iv)}}
async function openSecret(row:any){const pt=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(row.iv)},await aesKey(),unb64(row.ciphertext));return JSON.parse(dec.decode(pt))}

async function auth(req:Request){const header=req.headers.get('authorization')||'',token=header.startsWith('Bearer ')?header.slice(7):'';if(!token)return null;const{data,error}=await anon.auth.getUser(token);if(error||!data.user)return null;let profile=(await admin.from('users').select('id,email').eq('auth_user_id',data.user.id).maybeSingle()).data;if(!profile&&data.user.email)profile=(await admin.from('users').select('id,email').ilike('email',data.user.email).maybeSingle()).data;return profile||null}
async function member(userId:number,businessId:number,write=false){const r=await admin.from('memberships').select('role').eq('user_id',userId).eq('business_id',businessId).maybeSingle();if(!r.data)return null;if(write&&!['owner','admin'].includes(r.data.role))return null;return r.data}
async function workerAuthorized(req:Request){const key=req.headers.get('x-c360-google-key')||'';if(!key)return false;const r=await admin.rpc('c360_verify_google_worker_key',{p_value:key});return !r.error&&r.data===true}

async function connectionFor(businessId:number){const r=await admin.from('integration_connections').select('*').eq('business_id',businessId).eq('provider','google').order('id',{ascending:true}).limit(1).maybeSingle();if(r.error)throw r.error;return r.data}
async function credential(connectionId:number){const r=await admin.from('integration_credentials').select('*').eq('connection_id',connectionId).maybeSingle();if(r.error)throw r.error;return r.data?{row:r.data,secret:await openSecret(r.data),metadata:safeJson(r.data.metadata_json,{}),scopes:safeJson(r.data.scopes_json,[])}:null}
async function saveCredential(connection:any,cred:any,secret:any,expiresAt:string|null,metadata:any){const sealed=await seal(secret),r=await admin.from('integration_credentials').update({ciphertext:sealed.ciphertext,iv:sealed.iv,expires_at:expiresAt,metadata_json:JSON.stringify(metadata),updated_at:now()}).eq('connection_id',connection.id);if(r.error)throw r.error;return{...cred,secret,metadata,row:{...cred.row,expires_at:expiresAt}}}
async function saveMetadata(connectionId:number,metadata:any){const r=await admin.from('integration_credentials').update({metadata_json:JSON.stringify(metadata),updated_at:now()}).eq('connection_id',connectionId);if(r.error)throw r.error}
async function ensureFresh(connection:any,cred:any){const exp=cred.row.expires_at?Date.parse(cred.row.expires_at):0;if(!exp||exp>Date.now()+5*60_000)return cred;if(!cred.secret.refresh_token)throw new Error('Google exige nova autorização');const form=new URLSearchParams({client_id:env('GOOGLE_CLIENT_ID'),client_secret:env('GOOGLE_CLIENT_SECRET'),refresh_token:String(cred.secret.refresh_token),grant_type:'refresh_token'}),fresh=await api('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:form},'Google refresh'),secret={...cred.secret,...fresh,refresh_token:cred.secret.refresh_token},seconds=Number(fresh.expires_in||3600),expiresAt=new Date(Date.now()+seconds*1000).toISOString(),metadata={...cred.metadata,refreshed_at:now()};return saveCredential(connection,cred,secret,expiresAt,metadata)}
const bearer=(token:string)=>({authorization:`Bearer ${token}`,accept:'application/json'})

function accountName(value:any){const raw=String(value||'').trim();if(!raw)return'';return raw.startsWith('accounts/')?raw:`accounts/${raw}`}
function locationName(value:any){const raw=String(value||'').trim();if(!raw)return'';return raw.startsWith('locations/')?raw:`locations/${raw.replace(/^.*\/locations\//,'')}`}
function accountId(value:any){return accountName(value).replace(/^accounts\//,'')}
function locationId(value:any){return locationName(value).replace(/^locations\//,'')}

type LocationAsset={ref:string;title:string;address:string;phone:string;website:string;place_id:string;maps_uri:string;open_status:string;primary_category:string}
function mapLocation(item:any):LocationAsset{return{ref:locationName(item.name),title:String(item.title||item.name||'Perfil Google'),address:[item.storefrontAddress?.addressLines?.join(' '),item.storefrontAddress?.locality,item.storefrontAddress?.administrativeArea,item.storefrontAddress?.postalCode].filter(Boolean).join(', '),phone:String(item.phoneNumbers?.primaryPhone||''),website:String(item.websiteUri||''),place_id:String(item.metadata?.placeId||''),maps_uri:String(item.metadata?.mapsUri||''),open_status:String(item.openInfo?.status||''),primary_category:String(item.categories?.primaryCategory?.displayName||item.categories?.primaryCategory?.name||'')}}
async function listLocations(accountRef:string,token:string){const readMask=['name','title','storefrontAddress','phoneNumbers','websiteUri','regularHours','metadata','categories','openInfo'].join(','),items:any[]=[],base=`https://mybusinessbusinessinformation.googleapis.com/v1/${encodeURI(accountName(accountRef))}/locations`;let pageToken='';for(let page=0;page<5;page++){const q=new URLSearchParams({readMask,pageSize:'100'});if(pageToken)q.set('pageToken',pageToken);const data=await api(`${base}?${q}`,{headers:bearer(token)},'Google Business locations');items.push(...(data?.locations||[]));pageToken=String(data?.nextPageToken||'');if(!pageToken)break}return items.map(mapLocation).filter(x=>x.ref)}

async function upsertBinding(businessId:number,brandId:number,connectionId:number,locationRef:string){const row={business_id:businessId,brand_id:brandId,connection_id:connectionId,provider:'google',external_store_ref:locationName(locationRef),order_import_enabled:false,menu_sync_enabled:false,price_sync_enabled:false,availability_sync_enabled:false,auto_accept_orders:false,active:true,last_error:null,updated_at:now()},r=await admin.from('brand_integration_bindings').upsert(row,{onConflict:'business_id,brand_id,provider'}).select('*').single();if(r.error)throw r.error;return r.data}
async function autoBind(connection:any,cred:any,locations:LocationAsset[]){const[{data:brands=[]},{data:bindings=[]}]=await Promise.all([admin.from('brands').select('id,name').eq('business_id',connection.business_id).eq('active',true).eq('soft_deleted',false).order('sort_order'),admin.from('brand_integration_bindings').select('*').eq('business_id',connection.business_id).eq('provider','google').eq('active',true)]),used=new Set((bindings||[]).map((b:any)=>locationName(b.external_store_ref))),bound=new Set((bindings||[]).map((b:any)=>Number(b.brand_id))),created:any[]=[];
 if((brands||[]).length===1&&locations.length===1&&!bound.has(Number(brands[0].id))){created.push(await upsertBinding(connection.business_id,Number(brands[0].id),connection.id,locations[0].ref));used.add(locations[0].ref);bound.add(Number(brands[0].id))}
 for(const brand of brands||[]){if(bound.has(Number(brand.id)))continue;const matches=locations.filter(location=>!used.has(location.ref)&&normalize(location.title)===normalize(brand.name));if(matches.length===1){created.push(await upsertBinding(connection.business_id,Number(brand.id),connection.id,matches[0].ref));used.add(matches[0].ref);bound.add(Number(brand.id))}}
 const pendingBrands=(brands||[]).filter((b:any)=>!bound.has(Number(b.id))).map((b:any)=>({id:Number(b.id),name:b.name})),availableLocations=locations.filter(location=>!used.has(location.ref)),selectionRequired=pendingBrands.length>0&&availableLocations.length>0,metadata={...cred.metadata,google_locations:locations,google_location_count:locations.length,google_location_selection_required:selectionRequired,google_unbound_brands:pendingBrands,google_available_locations:availableLocations,google_locations_discovered_at:now()};await saveMetadata(connection.id,metadata);return{bindings_created:created.length,pending_brands:pendingBrands,available_locations:availableLocations,selection_required:selectionRequired,metadata}}

function normalizeReview(review:any,accountRef:string,locationRef:string){return{review_id:String(review.reviewId||review.name?.split('/').pop()||''),name:String(review.name||''),account_ref:accountName(accountRef),location_ref:locationName(locationRef),star_rating:String(review.starRating||''),comment:String(review.comment||''),create_time:review.createTime||null,update_time:review.updateTime||null,reviewer:{display_name:String(review.reviewer?.displayName||''),profile_photo_url:String(review.reviewer?.profilePhotoUrl||''),is_anonymous:Boolean(review.reviewer?.isAnonymous)},reply:review.reviewReply||null,reply_state:review.reviewReplyState||null,policy_violation:review.policyViolation||null,review_reply_url:String(review.reviewReplyUrl||'')}}
async function ingestReview(connection:any,accountRef:string,locationRef:string,review:any){const normalized=normalizeReview(review,accountRef,locationRef),raw=JSON.stringify(review),digest=await sha(raw),version=String(review.updateTime||review.createTime||digest.slice(0,16)),external=`review:${locationId(locationRef)}:${normalized.review_id}:${version}`.slice(0,500),ingest=await admin.rpc('c360_ingest_integration_event',{p_business_id:connection.business_id,p_provider:'google',p_external_event_id:external,p_event_type:'review.snapshot',p_external_order_id:null,p_occurred_at:review.updateTime||review.createTime||null,p_payload_sha256:digest,p_payload_json:raw,p_signature_verified:true,p_connection_id:connection.id});if(ingest.error)throw ingest.error;const stored=ingest.data;if(stored?.idempotent_replay&&['processed','ignored'].includes(String(stored.status)))return{created:false,id:Number(stored.id)};await admin.rpc('c360_mark_integration_event',{p_event_id:Number(stored.id),p_status:'processing'});const marked=await admin.rpc('c360_mark_integration_event',{p_event_id:Number(stored.id),p_status:'processed',p_canonical_event_type:'review.synced',p_normalized_json:JSON.stringify(normalized),p_canonical_order_id:null,p_error:null,p_next_retry_at:null});if(marked.error)throw marked.error;return{created:true,id:Number(stored.id)}}
async function syncReviewsForBinding(connection:any,binding:any,token:string){const aid=accountId(connection.external_account_ref),lid=locationId(binding.external_store_ref);if(!aid||!lid)throw new Error('Conta ou localização Google não selecionada');let pageToken='',received=0,created=0,unanswered=0,ratingTotal=0,ratingCount=0;const ratingMap:any={ONE:1,TWO:2,THREE:3,FOUR:4,FIVE:5,ONE_STAR:1,TWO_STAR:2,THREE_STAR:3,FOUR_STAR:4,FIVE_STAR:5};for(let page=0;page<3;page++){const q=new URLSearchParams({pageSize:'50',orderBy:'updateTime desc'});if(pageToken)q.set('pageToken',pageToken);const data=await api(`https://mybusiness.googleapis.com/v4/accounts/${encodeURIComponent(aid)}/locations/${encodeURIComponent(lid)}/reviews?${q}`,{headers:bearer(token)},'Google reviews'),reviews=Array.isArray(data?.reviews)?data.reviews:[];for(const review of reviews){received++;if(!review.reviewReply)unanswered++;const score=ratingMap[String(review.starRating||'').toUpperCase()]||0;if(score){ratingTotal+=score;ratingCount++}const stored=await ingestReview(connection,connection.external_account_ref,binding.external_store_ref,review);if(stored.created)created++}pageToken=String(data?.nextPageToken||'');if(!pageToken)break}
 await admin.from('brand_integration_bindings').update({last_sync_at:now(),last_success_at:now(),last_error:null,updated_at:now()}).eq('id',binding.id);return{binding_id:binding.id,brand_id:binding.brand_id,location_ref:binding.external_store_ref,received,created,unanswered,average_rating:ratingCount?Math.round((ratingTotal/ratingCount)*10)/10:null}}

async function reconcileConnection(connection:any){let cred=await credential(connection.id);if(!cred)throw new Error('Credencial Google não encontrada');cred=await ensureFresh(connection,cred);const token=String(cred.secret.access_token||'');if(!token)throw new Error('Token Google ausente');const accountRef=accountName(connection.external_account_ref);if(!accountRef)throw new Error('Conta Google Business não selecionada');const locations=await listLocations(accountRef,token),bindingResult=await autoBind(connection,cred,locations),{data:bindings=[]}=await admin.from('brand_integration_bindings').select('*').eq('business_id',connection.business_id).eq('provider','google').eq('connection_id',connection.id).eq('active',true),reviews:any[]=[];for(const binding of bindings||[]){try{reviews.push(await syncReviewsForBinding(connection,binding,token))}catch(e){const message=String((e as any)?.message||e);await admin.from('brand_integration_bindings').update({last_sync_at:now(),last_error_at:now(),last_error:message.slice(0,800),updated_at:now()}).eq('id',binding.id);reviews.push({binding_id:binding.id,error:message})}}
 const hasError=reviews.some(r=>r.error);await admin.from('integration_connections').update({status:hasError?'degraded':'active',last_success_at:hasError?connection.last_success_at:now(),last_error_at:hasError?now():connection.last_error_at,last_error:hasError?String(reviews.find(r=>r.error)?.error||'Falha ao sincronizar Google').slice(0,800):null,updated_at:now()}).eq('id',connection.id);return{business_id:connection.business_id,connection_id:connection.id,locations:locations.length,...bindingResult,reviews}}

async function overview(req:Request,businessId:number,userId:number){if(!await member(userId,businessId))return fail(req,'Sem acesso',403);const connection=await connectionFor(businessId);if(!connection)return json(req,{ok:true,connected:false,provider:'google',locations:[],bindings:[],reviews:[],summary:{total_reviews:0,unanswered:0,average_rating:null}});const cred=await credential(connection.id),metadata=cred?.metadata||{},[{data:bindings=[]},{data:events=[]}]=await Promise.all([admin.from('brand_integration_bindings').select('id,brand_id,external_store_ref,last_sync_at,last_success_at,last_error').eq('business_id',businessId).eq('provider','google').eq('active',true),admin.from('integration_events').select('id,normalized_json,occurred_at,created_at').eq('business_id',businessId).eq('provider','google').eq('canonical_event_type','review.synced').eq('status','processed').order('created_at',{ascending:false}).limit(250)]),latest=new Map<string,any>();for(const event of events||[]){const review=safeJson(event.normalized_json,{}),id=String(review.review_id||'');if(id&&!latest.has(id))latest.set(id,{...review,event_id:event.id})}const reviews=[...latest.values()],ratingMap:any={ONE:1,TWO:2,THREE:3,FOUR:4,FIVE:5,ONE_STAR:1,TWO_STAR:2,THREE_STAR:3,FOUR_STAR:4,FIVE_STAR:5},scores=reviews.map(r=>ratingMap[String(r.star_rating||'').toUpperCase()]||0).filter(Boolean),summary={total_reviews:reviews.length,unanswered:reviews.filter(r=>!r.reply).length,average_rating:scores.length?Math.round((scores.reduce((a:number,b:number)=>a+b,0)/scores.length)*10)/10:null};return json(req,{ok:true,connected:true,provider:'google',connection:{id:connection.id,status:connection.status,display_name:connection.display_name,last_success_at:connection.last_success_at,last_error:connection.last_error},locations:metadata.google_locations||[],selection_required:Boolean(metadata.google_location_selection_required),unbound_brands:metadata.google_unbound_brands||[],available_locations:metadata.google_available_locations||[],bindings,reviews:reviews.slice(0,80),summary})}

async function selectLocation(req:Request,businessId:number,userId:number,p:any){if(!await member(userId,businessId,true))return fail(req,'Somente owner/admin pode vincular o perfil Google',403);const connection=await connectionFor(businessId);if(!connection)return fail(req,'Conexão Google não encontrada',404);const cred=await credential(connection.id);if(!cred)return fail(req,'Credencial Google não encontrada',409);const brandId=Number(p.brand_id||0),ref=locationName(p.location_ref),locations=(cred.metadata.google_locations||[]) as LocationAsset[],location=locations.find(x=>x.ref===ref);if(!brandId||!location)return fail(req,'Marca ou localização inválida',422);const brand=(await admin.from('brands').select('id,name').eq('id',brandId).eq('business_id',businessId).eq('active',true).eq('soft_deleted',false).maybeSingle()).data;if(!brand)return fail(req,'Marca não encontrada',404);const binding=await upsertBinding(businessId,brandId,connection.id,ref),freshCred=await credential(connection.id);if(freshCred)await autoBind(connection,freshCred,locations);await admin.from('audit_logs').insert({business_id:businessId,actor_user_id:userId,action:'google.select_location',entity_type:'brand_integration_binding',entity_id:String(binding.id),payload_json:JSON.stringify({brand_id:brandId,location_ref:ref,location_title:location.title})});return json(req,{ok:true,binding,location})}

async function replyReview(req:Request,businessId:number,userId:number,reviewIdValue:string,p:any){if(!await member(userId,businessId,true))return fail(req,'Somente owner/admin pode responder avaliações',403);const comment=String(p.comment||'').trim(),locationRef=locationName(p.location_ref);if(!comment||comment.length>4096)return fail(req,'Resposta deve ter entre 1 e 4096 caracteres',422);const connection=await connectionFor(businessId);if(!connection||connection.status!=='active')return fail(req,'Google Business não está operacional',409);const binding=(await admin.from('brand_integration_bindings').select('*').eq('business_id',businessId).eq('provider','google').eq('connection_id',connection.id).eq('external_store_ref',locationRef).eq('active',true).maybeSingle()).data;if(!binding)return fail(req,'Localização Google não vinculada a esta operação',409);let cred=await credential(connection.id);if(!cred)return fail(req,'Credencial Google ausente',409);try{cred=await ensureFresh(connection,cred);const aid=accountId(connection.external_account_ref),lid=locationId(locationRef),reviewId=decodeURIComponent(reviewIdValue),remote=await api(`https://mybusiness.googleapis.com/v4/accounts/${encodeURIComponent(aid)}/locations/${encodeURIComponent(lid)}/reviews/${encodeURIComponent(reviewId)}/reply`,{method:'PUT',headers:{...bearer(String(cred.secret.access_token)),'content-type':'application/json'},body:JSON.stringify({comment})},'Resposta Google');await admin.from('audit_logs').insert({business_id:businessId,actor_user_id:userId,action:'google.review_reply',entity_type:'google_review',entity_id:reviewId,payload_json:JSON.stringify({location_ref:locationRef,comment_length:comment.length})});return json(req,{ok:true,review_id:reviewId,location_ref:locationRef,reply:remote})}catch(e){return fail(req,String((e as any)?.message||e),(e as any)?.status||502)}}

async function tenantReconcile(req:Request,businessId:number,userId:number){if(!await member(userId,businessId,true))return fail(req,'Somente owner/admin pode sincronizar o perfil Google',403);const connection=await connectionFor(businessId);if(!connection)return fail(req,'Conexão Google não encontrada',404);try{const result=await reconcileConnection(connection);await admin.from('audit_logs').insert({business_id:businessId,actor_user_id:userId,action:'google.reconcile',entity_type:'integration_connection',entity_id:String(connection.id),payload_json:JSON.stringify({locations:result.locations,bindings_created:result.bindings_created,reviews:result.reviews.map((r:any)=>({binding_id:r.binding_id,received:r.received,created:r.created,error:r.error||null}))})});return json(req,{ok:true,...result})}catch(e){const message=String((e as any)?.message||e);await admin.from('integration_connections').update({status:'degraded',last_error_at:now(),last_error:message.slice(0,800),updated_at:now()}).eq('id',connection.id);return fail(req,message,(e as any)?.status||502)}}

async function reconcileAll(req:Request){if(!await workerAuthorized(req))return fail(req,'Worker não autorizado',401);const{data:connections=[]}=await admin.from('integration_connections').select('*').eq('provider','google').eq('status','active').order('last_success_at',{ascending:true,nullsFirst:true}).limit(8),results:any[]=[];for(const connection of connections||[]){try{results.push(await reconcileConnection(connection))}catch(e){const message=String((e as any)?.message||e);await admin.from('integration_connections').update({status:'degraded',last_error_at:now(),last_error:message.slice(0,800),updated_at:now()}).eq('id',connection.id);results.push({business_id:connection.business_id,connection_id:connection.id,error:message})}}return json(req,{ok:true,service:SLUG,version:VERSION,processed:results.length,results})}

Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(req)});const path=routePath(req),method=req.method;try{if(path==='/livez'&&method==='GET')return json(req,{ok:true,service:SLUG,version:VERSION,mode:'business_profile_v1_plus_reviews_v4'});if(path==='/readyz'&&method==='GET'){const configured=Boolean(env('GOOGLE_CLIENT_ID')&&env('GOOGLE_CLIENT_SECRET')),db=await admin.from('integration_connections').select('id',{head:true,count:'exact'});return db.error||!configured?json(req,{ok:false,service:SLUG,version:VERSION,database:db.error?'not_ready':'ready',oauth_configured:configured},503):json(req,{ok:true,service:SLUG,version:VERSION,database:'ready',oauth_configured:true})}if(path==='/reconcile'&&method==='POST')return reconcileAll(req);
 const user:any=await auth(req);if(!user)return fail(req,'Sessão inválida',401);let m=path.match(/^\/businesses\/(\d+)\/overview$/);if(m&&method==='GET')return overview(req,Number(m[1]),user.id);m=path.match(/^\/businesses\/(\d+)\/reconcile$/);if(m&&method==='POST')return tenantReconcile(req,Number(m[1]),user.id);m=path.match(/^\/businesses\/(\d+)\/locations\/select$/);if(m&&method==='POST')return selectLocation(req,Number(m[1]),user.id,await parseJson(req));m=path.match(/^\/businesses\/(\d+)\/reviews\/([^/]+)\/reply$/);if(m&&method==='PUT')return replyReview(req,Number(m[1]),user.id,m[2],await parseJson(req));return fail(req,'Rota não encontrada',404)}catch(e){console.error(SLUG,e);return fail(req,'Erro interno',500)}})
