begin;

create extension if not exists pg_cron;
create extension if not exists pg_net;
create extension if not exists pgcrypto;

create table if not exists public.integration_product_mappings (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id) on delete cascade,
  brand_id bigint not null references public.brands(id) on delete cascade,
  provider varchar(40) not null,
  external_product_ref varchar(240) not null,
  external_name varchar(220),
  product_id bigint not null references public.products(id) on delete restrict,
  mapping_source varchar(24) not null default 'manual'
    check (mapping_source in ('manual','auto_shadow','imported')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists uq_integration_product_mapping
  on public.integration_product_mappings(business_id, brand_id, lower(provider), external_product_ref);
create index if not exists ix_integration_product_mapping_product
  on public.integration_product_mappings(product_id);

alter table public.integration_product_mappings enable row level security;

do $$
begin
  if exists(select 1 from pg_roles where rolname='anon') then
    execute 'revoke all privileges on table public.integration_product_mappings from anon';
  end if;
  if exists(select 1 from pg_roles where rolname='authenticated') then
    execute 'revoke all privileges on table public.integration_product_mappings from authenticated';
  end if;
end $$;

drop trigger if exists trg_integration_product_mappings_updated_at on public.integration_product_mappings;
create trigger trg_integration_product_mappings_updated_at
before update on public.integration_product_mappings
for each row execute function public.touch_updated_at();

comment on table public.integration_product_mappings is
  'Maps provider product references to canonical products. auto_shadow rows preserve order ingestion without inventing CMV.';

create or replace function public.c360_verify_worker_key(p_value text)
returns boolean
language sql
security definer
set search_path to 'public'
as $function$
  select coalesce(exists(
    select 1
      from vault.decrypted_secrets
     where name='c360_ifood_worker_key'
       and decrypted_secret = p_value
  ),false);
$function$;

revoke all on function public.c360_verify_worker_key(text) from public;
revoke all on function public.c360_verify_worker_key(text) from anon;
revoke all on function public.c360_verify_worker_key(text) from authenticated;
grant execute on function public.c360_verify_worker_key(text) to service_role;

do $$
begin
  if not exists(select 1 from vault.secrets where name='c360_ifood_worker_key') then
    perform vault.create_secret(encode(gen_random_bytes(32),'hex'),'c360_ifood_worker_key');
  end if;
end $$;

do $$
declare
  v_job_id bigint;
begin
  select jobid into v_job_id from cron.job where jobname='c360-ifood-poll-30s';
  if v_job_id is not null then
    perform cron.unschedule(v_job_id);
  end if;

  perform cron.schedule(
    'c360-ifood-poll-30s',
    '30 seconds',
    $cron$
      select net.http_post(
        url := 'https://npgheuzpnkwtxopswpqy.supabase.co/functions/v1/cozinha360-ifood-adapter-v55/poll',
        headers := jsonb_build_object(
          'Content-Type','application/json',
          'x-c360-worker-key',(
            select decrypted_secret
              from vault.decrypted_secrets
             where name='c360_ifood_worker_key'
             limit 1
          )
        ),
        body := '{}'::jsonb,
        timeout_milliseconds := 20000
      );
    $cron$
  );
end $$;

commit;
