begin;

create table if not exists public.integration_connections (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id) on delete cascade,
  provider varchar(40) not null,
  external_account_ref varchar(160),
  display_name varchar(160),
  mode varchar(20) not null default 'webhook' check (mode in ('webhook','polling','manual')),
  status varchar(20) not null default 'inactive' check (status in ('inactive','connecting','active','degraded','disabled')),
  last_event_at timestamptz,
  last_success_at timestamptz,
  last_error_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists uq_integration_connections_business_provider_account
  on public.integration_connections(business_id, lower(provider), coalesce(external_account_ref,''));
create index if not exists ix_integration_connections_business_status
  on public.integration_connections(business_id,status);

create table if not exists public.integration_events (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id) on delete cascade,
  connection_id bigint references public.integration_connections(id) on delete set null,
  provider varchar(40) not null,
  external_event_id varchar(200) not null,
  event_type varchar(120) not null,
  external_order_id varchar(200),
  occurred_at timestamptz,
  signature_verified boolean not null default false,
  payload_sha256 char(64) not null,
  payload_json text not null,
  canonical_event_type varchar(80),
  normalized_json text,
  canonical_order_id bigint references public.orders(id) on delete set null,
  status varchar(20) not null default 'received' check (status in ('received','processing','processed','ignored','failed','dead_letter')),
  attempts integer not null default 0 check (attempts >= 0),
  received_at timestamptz not null default now(),
  processing_started_at timestamptz,
  processed_at timestamptz,
  next_retry_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists uq_integration_events_business_provider_event
  on public.integration_events(business_id, lower(provider), external_event_id);
create index if not exists ix_integration_events_business_status_received
  on public.integration_events(business_id,status,received_at desc);
create index if not exists ix_integration_events_provider_external_order
  on public.integration_events(provider,external_order_id)
  where external_order_id is not null;
create index if not exists ix_integration_events_retry
  on public.integration_events(status,next_retry_at)
  where status in ('failed','dead_letter');

alter table public.integration_connections enable row level security;
alter table public.integration_events enable row level security;

do $$
begin
  if exists(select 1 from pg_roles where rolname='anon') then
    execute 'revoke all privileges on table public.integration_connections from anon';
    execute 'revoke all privileges on table public.integration_events from anon';
    execute 'revoke all privileges on sequence public.integration_connections_id_seq from anon';
    execute 'revoke all privileges on sequence public.integration_events_id_seq from anon';
  end if;
  if exists(select 1 from pg_roles where rolname='authenticated') then
    execute 'revoke all privileges on table public.integration_connections from authenticated';
    execute 'revoke all privileges on table public.integration_events from authenticated';
    execute 'revoke all privileges on sequence public.integration_connections_id_seq from authenticated';
    execute 'revoke all privileges on sequence public.integration_events_id_seq from authenticated';
  end if;
end $$;

drop trigger if exists trg_integration_connections_updated_at on public.integration_connections;
create trigger trg_integration_connections_updated_at
before update on public.integration_connections
for each row execute function public.touch_updated_at();

drop trigger if exists trg_integration_events_updated_at on public.integration_events;
create trigger trg_integration_events_updated_at
before update on public.integration_events
for each row execute function public.touch_updated_at();

create or replace function public.c360_ingest_integration_event(
  p_business_id bigint,
  p_provider text,
  p_external_event_id text,
  p_event_type text,
  p_external_order_id text,
  p_occurred_at timestamptz,
  p_payload_sha256 text,
  p_payload_json text,
  p_signature_verified boolean,
  p_connection_id bigint default null
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_existing public.integration_events%rowtype;
  v_event public.integration_events%rowtype;
  v_provider text := lower(trim(coalesce(p_provider,'')));
begin
  if v_provider = '' then raise exception 'PROVIDER_REQUIRED'; end if;
  if nullif(trim(coalesce(p_external_event_id,'')),'') is null then raise exception 'EXTERNAL_EVENT_ID_REQUIRED'; end if;
  if nullif(trim(coalesce(p_event_type,'')),'') is null then raise exception 'EVENT_TYPE_REQUIRED'; end if;
  if p_payload_sha256 !~ '^[0-9a-fA-F]{64}$' then raise exception 'PAYLOAD_SHA256_INVALID'; end if;
  if nullif(p_payload_json,'') is null then raise exception 'PAYLOAD_REQUIRED'; end if;

  if p_connection_id is not null and not exists(
    select 1 from public.integration_connections
     where id=p_connection_id and business_id=p_business_id and lower(provider)=v_provider
  ) then
    raise exception 'INTEGRATION_CONNECTION_NOT_FOUND';
  end if;

  perform pg_advisory_xact_lock(hashtextextended(p_business_id::text || ':' || v_provider || ':' || p_external_event_id,0));

  select * into v_existing
    from public.integration_events
   where business_id=p_business_id
     and lower(provider)=v_provider
     and external_event_id=p_external_event_id
   limit 1;

  if found then
    return jsonb_build_object(
      'id',v_existing.id,
      'status',v_existing.status,
      'signature_verified',v_existing.signature_verified,
      'idempotent_replay',true
    );
  end if;

  insert into public.integration_events(
    business_id,connection_id,provider,external_event_id,event_type,external_order_id,
    occurred_at,signature_verified,payload_sha256,payload_json,status
  ) values (
    p_business_id,p_connection_id,v_provider,p_external_event_id,trim(p_event_type),nullif(trim(coalesce(p_external_order_id,'')),''),
    p_occurred_at,coalesce(p_signature_verified,false),lower(p_payload_sha256),p_payload_json,'received'
  ) returning * into v_event;

  if p_connection_id is not null then
    update public.integration_connections
       set last_event_at=now(),
           status=case when status in ('inactive','connecting','degraded') then 'active' else status end
     where id=p_connection_id;
  end if;

  insert into public.outbox_events(business_id,topic,payload_json)
  values(p_business_id,'integration.event.received',jsonb_build_object(
    'integration_event_id',v_event.id,'provider',v_provider,'external_event_id',p_external_event_id,
    'event_type',p_event_type,'signature_verified',coalesce(p_signature_verified,false)
  )::text);

  return jsonb_build_object(
    'id',v_event.id,
    'status',v_event.status,
    'signature_verified',v_event.signature_verified,
    'idempotent_replay',false
  );
end;
$$;

create or replace function public.c360_mark_integration_event(
  p_event_id bigint,
  p_status text,
  p_canonical_event_type text default null,
  p_normalized_json text default null,
  p_canonical_order_id bigint default null,
  p_error text default null,
  p_next_retry_at timestamptz default null
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_event public.integration_events%rowtype;
  v_status text := lower(trim(coalesce(p_status,'')));
begin
  if v_status not in ('processing','processed','ignored','failed','dead_letter') then
    raise exception 'INTEGRATION_STATUS_INVALID';
  end if;

  select * into v_event from public.integration_events where id=p_event_id for update;
  if not found then raise exception 'INTEGRATION_EVENT_NOT_FOUND'; end if;

  update public.integration_events
     set status=v_status,
         attempts=case when v_status='processing' then attempts+1 else attempts end,
         processing_started_at=case when v_status='processing' then now() else processing_started_at end,
         processed_at=case when v_status in ('processed','ignored') then now() else processed_at end,
         canonical_event_type=coalesce(nullif(trim(coalesce(p_canonical_event_type,'')),''),canonical_event_type),
         normalized_json=coalesce(p_normalized_json,normalized_json),
         canonical_order_id=coalesce(p_canonical_order_id,canonical_order_id),
         last_error=case when v_status in ('failed','dead_letter') then nullif(p_error,'') else null end,
         next_retry_at=case when v_status='failed' then p_next_retry_at else null end
   where id=p_event_id
   returning * into v_event;

  update public.integration_connections c
     set last_success_at=case when v_status in ('processed','ignored') then now() else c.last_success_at end,
         last_error_at=case when v_status in ('failed','dead_letter') then now() else c.last_error_at end,
         last_error=case when v_status in ('failed','dead_letter') then nullif(p_error,'') else null end,
         status=case when v_status='dead_letter' then 'degraded' when v_status in ('processed','ignored') and c.status='degraded' then 'active' else c.status end
    from public.integration_events e
   where e.id=p_event_id and c.id=e.connection_id;

  insert into public.outbox_events(business_id,topic,payload_json)
  values(v_event.business_id,'integration.event.' || v_status,jsonb_build_object(
    'integration_event_id',v_event.id,'provider',v_event.provider,'status',v_status,
    'canonical_event_type',v_event.canonical_event_type,'canonical_order_id',v_event.canonical_order_id
  )::text);

  return jsonb_build_object('id',v_event.id,'status',v_event.status,'attempts',v_event.attempts);
end;
$$;

create or replace function public.c360_requeue_integration_event(p_event_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_event public.integration_events%rowtype;
begin
  select * into v_event from public.integration_events where id=p_event_id for update;
  if not found then raise exception 'INTEGRATION_EVENT_NOT_FOUND'; end if;
  if v_event.status not in ('failed','dead_letter') then raise exception 'INTEGRATION_EVENT_NOT_RETRYABLE'; end if;

  update public.integration_events
     set status='received',next_retry_at=null,last_error=null,processing_started_at=null,processed_at=null
   where id=p_event_id
   returning * into v_event;

  insert into public.outbox_events(business_id,topic,payload_json)
  values(v_event.business_id,'integration.event.requeued',jsonb_build_object('integration_event_id',v_event.id,'provider',v_event.provider)::text);

  return jsonb_build_object('id',v_event.id,'status',v_event.status,'attempts',v_event.attempts);
end;
$$;

revoke all on function public.c360_ingest_integration_event(bigint,text,text,text,text,timestamptz,text,text,boolean,bigint) from public;
revoke all on function public.c360_mark_integration_event(bigint,text,text,text,bigint,text,timestamptz) from public;
revoke all on function public.c360_requeue_integration_event(bigint) from public;

do $$
begin
  if exists(select 1 from pg_roles where rolname='anon') then
    execute 'revoke all on function public.c360_ingest_integration_event(bigint,text,text,text,text,timestamptz,text,text,boolean,bigint) from anon';
    execute 'revoke all on function public.c360_mark_integration_event(bigint,text,text,text,bigint,text,timestamptz) from anon';
    execute 'revoke all on function public.c360_requeue_integration_event(bigint) from anon';
  end if;
  if exists(select 1 from pg_roles where rolname='authenticated') then
    execute 'revoke all on function public.c360_ingest_integration_event(bigint,text,text,text,text,timestamptz,text,text,boolean,bigint) from authenticated';
    execute 'revoke all on function public.c360_mark_integration_event(bigint,text,text,text,bigint,text,timestamptz) from authenticated';
    execute 'revoke all on function public.c360_requeue_integration_event(bigint) from authenticated';
  end if;
  if exists(select 1 from pg_roles where rolname='service_role') then
    execute 'grant execute on function public.c360_ingest_integration_event(bigint,text,text,text,text,timestamptz,text,text,boolean,bigint) to service_role';
    execute 'grant execute on function public.c360_mark_integration_event(bigint,text,text,text,bigint,text,timestamptz) to service_role';
    execute 'grant execute on function public.c360_requeue_integration_event(bigint) to service_role';
  end if;
end $$;

commit;
