begin;

create table if not exists public.autopilot_runs (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id) on delete cascade,
  actor_user_id bigint references public.users(id) on delete set null,
  request_id uuid not null,
  horizon_days integer not null check (horizon_days between 1 and 14),
  buffer_bps integer not null default 0 check (buffer_bps between 0 and 5000),
  plan_hash varchar(64) not null,
  status varchar(24) not null default 'running' check (status in ('running','completed','partial','failed')),
  action_count integer not null default 0 check (action_count >= 0),
  result_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ux_autopilot_runs_business_request unique (business_id, request_id)
);

create index if not exists ix_autopilot_runs_business_created on public.autopilot_runs(business_id, created_at desc);
create index if not exists ix_autopilot_runs_business_status on public.autopilot_runs(business_id, status);

alter table public.autopilot_runs enable row level security;

do $$
begin
  if exists(select 1 from pg_roles where rolname='anon') then
    execute 'revoke all privileges on table public.autopilot_runs from anon';
    execute 'revoke all privileges on sequence public.autopilot_runs_id_seq from anon';
  end if;
  if exists(select 1 from pg_roles where rolname='authenticated') then
    execute 'revoke all privileges on table public.autopilot_runs from authenticated';
    execute 'revoke all privileges on sequence public.autopilot_runs_id_seq from authenticated';
  end if;
end $$;

comment on table public.autopilot_runs is 'Server-owned idempotency and audit ledger for Autopilot 360 bulk production actions.';
comment on column public.autopilot_runs.result_json is 'Sanitized orchestration result only; do not store provider secrets or raw auth tokens.';

commit;
