begin;

create table if not exists order_completion_snapshots (
  id bigint generated by default as identity primary key,
  business_id bigint not null references businesses(id) on delete cascade,
  order_id bigint not null references orders(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint uq_order_completion_snapshot_order unique(order_id)
);

create index if not exists ix_order_completion_snapshots_business on order_completion_snapshots(business_id);
create index if not exists ix_order_completion_snapshots_order on order_completion_snapshots(order_id);
create index if not exists ix_order_completion_snapshots_business_created on order_completion_snapshots(business_id, created_at desc);

create table if not exists order_recipe_snapshots (
  id bigint generated by default as identity primary key,
  business_id bigint not null references businesses(id) on delete cascade,
  order_id bigint not null references orders(id) on delete cascade,
  order_item_id bigint not null references order_items(id) on delete cascade,
  product_id bigint not null references products(id) on delete restrict,
  ingredient_id bigint not null references ingredients(id) on delete restrict,
  ordered_quantity integer not null check (ordered_quantity >= 0),
  qty_per_unit_milliunits integer not null check (qty_per_unit_milliunits >= 0),
  total_qty_milliunits integer not null check (total_qty_milliunits >= 0),
  created_at timestamptz not null default now(),
  constraint uq_order_recipe_snapshot_item_ingredient unique(order_item_id, ingredient_id)
);

create index if not exists ix_order_recipe_snapshots_business on order_recipe_snapshots(business_id);
create index if not exists ix_order_recipe_snapshots_order on order_recipe_snapshots(order_id);
create index if not exists ix_order_recipe_snapshots_order_item on order_recipe_snapshots(order_item_id);
create index if not exists ix_order_recipe_snapshots_product on order_recipe_snapshots(product_id);
create index if not exists ix_order_recipe_snapshots_ingredient on order_recipe_snapshots(ingredient_id);
create index if not exists ix_order_recipe_snapshots_business_order on order_recipe_snapshots(business_id, order_id);
create index if not exists ix_order_recipe_snapshots_order_ingredient on order_recipe_snapshots(order_id, ingredient_id);

alter table order_completion_snapshots enable row level security;
alter table order_recipe_snapshots enable row level security;

do $$
begin
  if exists (select 1 from pg_roles where rolname = 'anon') then
    revoke all privileges on table order_completion_snapshots from anon;
    revoke all privileges on table order_recipe_snapshots from anon;
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    revoke all privileges on table order_completion_snapshots from authenticated;
    revoke all privileges on table order_recipe_snapshots from authenticated;
  end if;
end $$;

commit;
