-- GCL v87: authenticated sales cockpit for real lead follow-up.
-- PII remains in the private sac schema and is returned only after an owner/admin check.

alter table sac.analysis_interest_leads
  add column if not exists assigned_to uuid references auth.users(id) on delete set null,
  add column if not exists follow_up_at timestamptz,
  add column if not exists last_contacted_at timestamptz;

create index if not exists analysis_interest_leads_follow_up_idx
  on sac.analysis_interest_leads(follow_up_at asc)
  where stage not in ('converted', 'lost') and follow_up_at is not null;

create table if not exists sac.analysis_interest_lead_events (
  id bigint generated by default as identity primary key,
  lead_id uuid not null references sac.analysis_interest_leads(id) on delete cascade,
  actor_user_id uuid not null references auth.users(id) on delete restrict,
  from_stage text not null,
  to_stage text not null,
  note text,
  created_at timestamptz not null default now(),
  constraint analysis_interest_lead_events_stage_check check (
    from_stage in ('checkout_interest','checkout_blocked','checkout_opened','contacted','qualified','converted','lost')
    and to_stage in ('contacted','qualified','converted','lost')
  ),
  constraint analysis_interest_lead_events_note_length check (note is null or length(note) <= 2000)
);

create index if not exists analysis_interest_lead_events_lead_idx
  on sac.analysis_interest_lead_events(lead_id, created_at desc);

alter table sac.analysis_interest_lead_events enable row level security;
revoke all on sac.analysis_interest_lead_events from public, anon, authenticated;
grant select, insert on sac.analysis_interest_lead_events to service_role;

create or replace function sac.is_gcl_sales_operator(p_user uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path to 'sac', 'public', 'auth'
as $$
  select p_user is not null and (
    exists (
      select 1
      from sac.gcl_staff_roles r
      where r.user_id = p_user and r.role in ('admin', 'owner')
    )
    or coalesce(
      (auth.jwt() -> 'app_metadata' ->> 'gcl_role') in ('admin', 'owner'),
      false
    )
  );
$$;

revoke execute on function sac.is_gcl_sales_operator(uuid)
from public, anon, authenticated, service_role;

create or replace function public.gcl_sales_lead_inbox(
  p_stage text default null,
  p_query text default null,
  p_limit integer default 50
)
returns jsonb
language plpgsql
stable
security definer
set search_path to 'public', 'sac', 'auth'
as $$
declare
  v_user uuid := auth.uid();
  v_stage text := lower(nullif(btrim(coalesce(p_stage, '')), ''));
  v_query text := lower(nullif(btrim(coalesce(p_query, '')), ''));
  v_rows jsonb;
  v_summary jsonb;
begin
  if not sac.is_gcl_sales_operator(v_user) then
    raise exception 'sales_operator_required' using errcode = '42501';
  end if;

  if v_stage is not null and v_stage not in (
    'active','all','checkout_interest','checkout_blocked','checkout_opened',
    'contacted','qualified','converted','lost'
  ) then
    raise exception 'invalid_lead_stage' using errcode = '22023';
  end if;

  if v_query is not null and length(v_query) > 120 then
    raise exception 'lead_query_too_long' using errcode = '22023';
  end if;

  select jsonb_build_object(
    'active', count(*) filter (where l.stage not in ('converted','lost')),
    'new', count(*) filter (where l.stage in ('checkout_interest','checkout_blocked','checkout_opened')),
    'contacted', count(*) filter (where l.stage = 'contacted'),
    'qualified', count(*) filter (where l.stage = 'qualified'),
    'converted', count(*) filter (where l.stage = 'converted'),
    'overdue', count(*) filter (
      where l.stage not in ('converted','lost') and l.follow_up_at < now()
    )
  )
  into v_summary
  from sac.analysis_interest_leads l;

  select coalesce(jsonb_agg(to_jsonb(x) order by x.priority asc, x.created_at desc), '[]'::jsonb)
  into v_rows
  from (
    select
      l.id,
      l.email,
      l.phone,
      l.company_name,
      l.role_title,
      l.stage,
      l.source_path,
      l.utm_source,
      l.utm_medium,
      l.utm_campaign,
      l.marketing_consent,
      l.first_seen_at,
      l.last_seen_at,
      l.created_at,
      l.updated_at,
      l.assigned_to,
      l.follow_up_at,
      l.last_contacted_at,
      i.normalized_domain,
      i.product_code,
      case
        when l.follow_up_at < now() then 0
        when l.stage = 'qualified' then 1
        when l.stage = 'contacted' then 2
        else 3
      end as priority,
      (select count(*)::int from sac.analysis_interest_lead_events e where e.lead_id = l.id) as event_count
    from sac.analysis_interest_leads l
    join sac.analysis_checkout_intents i on i.id = l.intent_id
    where (
      v_stage = 'all'
      or (coalesce(v_stage, 'active') = 'active' and l.stage not in ('converted','lost'))
      or l.stage = v_stage
    )
    and (
      v_query is null
      or lower(l.email) like '%' || v_query || '%'
      or lower(coalesce(l.company_name, '')) like '%' || v_query || '%'
      or lower(coalesce(i.normalized_domain, '')) like '%' || v_query || '%'
    )
    order by priority asc, l.created_at desc
    limit greatest(1, least(coalesce(p_limit, 50), 100))
  ) x;

  return jsonb_build_object(
    'access', 'sales_operator',
    'summary', coalesce(v_summary, '{}'::jsonb),
    'rows', v_rows
  );
end;
$$;

revoke execute on function public.gcl_sales_lead_inbox(text, text, integer)
from public, anon;
grant execute on function public.gcl_sales_lead_inbox(text, text, integer)
to authenticated, service_role;

create or replace function public.gcl_update_sales_lead(
  p_lead_id uuid,
  p_stage text,
  p_note text default null,
  p_follow_up_at timestamptz default null
)
returns jsonb
language plpgsql
security definer
set search_path to 'public', 'sac', 'auth'
as $$
declare
  v_user uuid := auth.uid();
  v_stage text := lower(btrim(coalesce(p_stage, '')));
  v_note text := nullif(btrim(coalesce(p_note, '')), '');
  v_lead sac.analysis_interest_leads%rowtype;
  v_rate jsonb;
begin
  if not sac.is_gcl_sales_operator(v_user) then
    raise exception 'sales_operator_required' using errcode = '42501';
  end if;

  if v_stage not in ('contacted','qualified','converted','lost') then
    raise exception 'invalid_lead_stage' using errcode = '22023';
  end if;

  if v_note is not null and length(v_note) > 2000 then
    raise exception 'lead_note_too_long' using errcode = '22023';
  end if;

  v_rate := sac.consume_rate_limit(
    'member:sales_lead_update',
    'user:' || v_user::text,
    60,
    60
  );
  if coalesce((v_rate ->> 'allowed')::boolean, false) is not true then
    raise exception 'rate_limited';
  end if;

  select * into v_lead
  from sac.analysis_interest_leads
  where id = p_lead_id
  for update;

  if not found then
    raise exception 'lead_not_found';
  end if;

  if v_lead.stage in ('converted','lost') and v_lead.stage <> v_stage then
    raise exception 'terminal_lead_stage';
  end if;

  update sac.analysis_interest_leads
  set
    stage = v_stage,
    assigned_to = v_user,
    follow_up_at = case when v_stage in ('converted','lost') then null else p_follow_up_at end,
    last_contacted_at = case when v_stage in ('contacted','qualified','converted') then now() else last_contacted_at end,
    updated_at = now()
  where id = p_lead_id;

  insert into sac.analysis_interest_lead_events(
    lead_id, actor_user_id, from_stage, to_stage, note
  ) values (
    p_lead_id, v_user, v_lead.stage, v_stage, v_note
  );

  return jsonb_build_object(
    'id', p_lead_id,
    'from_stage', v_lead.stage,
    'stage', v_stage,
    'assigned_to', v_user,
    'follow_up_at', case when v_stage in ('converted','lost') then null else p_follow_up_at end,
    'updated_at', now()
  );
end;
$$;

revoke execute on function public.gcl_update_sales_lead(uuid, text, text, timestamptz)
from public, anon;
grant execute on function public.gcl_update_sales_lead(uuid, text, text, timestamptz)
to authenticated, service_role;
