begin;

alter table public.brands
  add column if not exists slug varchar(90),
  add column if not exists primary_channel varchar(32) not null default 'direct',
  add column if not exists sort_order integer not null default 0;

create unique index if not exists uq_brands_business_slug_active
  on public.brands(business_id, lower(slug))
  where slug is not null and soft_deleted = false;

create table if not exists public.delivery_zones (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id) on delete cascade,
  brand_id bigint references public.brands(id) on delete cascade,
  name varchar(120) not null,
  zone_type varchar(24) not null default 'radius' check (zone_type in ('radius','neighborhood','cep')),
  match_value varchar(180) not null default '',
  fee_cents integer not null default 0 check (fee_cents >= 0),
  min_order_cents integer not null default 0 check (min_order_cents >= 0),
  eta_min integer not null default 45 check (eta_min between 5 and 360),
  active boolean not null default true,
  version integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists ix_delivery_zones_business on public.delivery_zones(business_id);
create index if not exists ix_delivery_zones_brand on public.delivery_zones(brand_id);

create table if not exists public.delivery_drivers (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id) on delete cascade,
  name varchar(120) not null,
  phone varchar(40) not null default '',
  vehicle varchar(20) not null default 'moto' check (vehicle in ('foot','bike','moto','car','utility')),
  status varchar(20) not null default 'offline' check (status in ('available','busy','offline')),
  active boolean not null default true,
  version integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists ix_delivery_drivers_business on public.delivery_drivers(business_id);

create table if not exists public.loyalty_programs (
  business_id bigint primary key references public.businesses(id) on delete cascade,
  mode varchar(20) not null default 'off' check (mode in ('off','points','cashback')),
  points_per_real numeric(8,2) not null default 1 check (points_per_real >= 0),
  cashback_bps integer not null default 0 check (cashback_bps between 0 and 5000),
  redeem_threshold integer not null default 0 check (redeem_threshold >= 0),
  active boolean not null default false,
  updated_by_user_id bigint references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.delivery_promos (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id) on delete cascade,
  brand_id bigint references public.brands(id) on delete cascade,
  code varchar(40) not null,
  discount_type varchar(24) not null check (discount_type in ('percent','fixed','free_delivery')),
  value integer not null default 0 check (value >= 0),
  min_order_cents integer not null default 0 check (min_order_cents >= 0),
  max_uses integer check (max_uses is null or max_uses > 0),
  used_count integer not null default 0 check (used_count >= 0),
  starts_at timestamptz,
  ends_at timestamptz,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (ends_at is null or starts_at is null or ends_at > starts_at)
);
create unique index if not exists uq_delivery_promos_business_code
  on public.delivery_promos(business_id, upper(code));
create index if not exists ix_delivery_promos_brand on public.delivery_promos(brand_id);

alter table public.delivery_zones enable row level security;
alter table public.delivery_drivers enable row level security;
alter table public.loyalty_programs enable row level security;
alter table public.delivery_promos enable row level security;

do $$
declare
  role_name text;
  table_name text;
begin
  foreach role_name in array array['anon','authenticated'] loop
    if exists(select 1 from pg_roles where rolname=role_name) then
      foreach table_name in array array['delivery_zones','delivery_drivers','loyalty_programs','delivery_promos'] loop
        execute format('revoke all privileges on table public.%I from %I',table_name,role_name);
      end loop;
      if to_regclass('public.delivery_zones_id_seq') is not null then execute format('revoke all privileges on sequence public.delivery_zones_id_seq from %I',role_name); end if;
      if to_regclass('public.delivery_drivers_id_seq') is not null then execute format('revoke all privileges on sequence public.delivery_drivers_id_seq from %I',role_name); end if;
      if to_regclass('public.delivery_promos_id_seq') is not null then execute format('revoke all privileges on sequence public.delivery_promos_id_seq from %I',role_name); end if;
    end if;
  end loop;
end $$;

drop trigger if exists trg_delivery_zones_updated_at on public.delivery_zones;
create trigger trg_delivery_zones_updated_at before update on public.delivery_zones for each row execute function public.touch_updated_at();
drop trigger if exists trg_delivery_drivers_updated_at on public.delivery_drivers;
create trigger trg_delivery_drivers_updated_at before update on public.delivery_drivers for each row execute function public.touch_updated_at();
drop trigger if exists trg_loyalty_programs_updated_at on public.loyalty_programs;
create trigger trg_loyalty_programs_updated_at before update on public.loyalty_programs for each row execute function public.touch_updated_at();
drop trigger if exists trg_delivery_promos_updated_at on public.delivery_promos;
create trigger trg_delivery_promos_updated_at before update on public.delivery_promos for each row execute function public.touch_updated_at();

commit;
