begin;

create table if not exists public.storefronts (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id) on delete cascade,
  brand_id bigint references public.brands(id) on delete set null,
  channel_id bigint not null references public.channels(id) on delete restrict,
  slug varchar(60) not null,
  display_name varchar(160) not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ck_storefront_slug check (slug ~ '^[a-z0-9][a-z0-9-]{2,59}$')
);
create unique index if not exists uq_storefronts_slug on public.storefronts(lower(slug));
create index if not exists ix_storefronts_business on public.storefronts(business_id,active);
create index if not exists ix_storefronts_brand on public.storefronts(brand_id) where brand_id is not null;

create table if not exists public.order_attributions (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id) on delete cascade,
  order_id bigint not null references public.orders(id) on delete cascade,
  storefront_id bigint references public.storefronts(id) on delete set null,
  session_key varchar(120),
  referrer varchar(500),
  utm_source varchar(120),
  utm_medium varchar(120),
  utm_campaign varchar(160),
  utm_content varchar(160),
  utm_term varchar(160),
  gclid varchar(220),
  fbclid varchar(220),
  ttclid varchar(220),
  media_cost_cents integer check (media_cost_cents is null or media_cost_cents >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(order_id)
);
create index if not exists ix_order_attributions_business_created on public.order_attributions(business_id,created_at desc);
create index if not exists ix_order_attributions_campaign on public.order_attributions(business_id,utm_source,utm_medium,utm_campaign);
create index if not exists ix_order_attributions_storefront on public.order_attributions(storefront_id) where storefront_id is not null;

create table if not exists public.conversion_events (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id) on delete cascade,
  order_id bigint not null references public.orders(id) on delete cascade,
  attribution_id bigint references public.order_attributions(id) on delete set null,
  event_name varchar(40) not null default 'purchase',
  event_id varchar(180) not null,
  occurred_at timestamptz not null default now(),
  revenue_cents integer not null default 0,
  variable_cost_cents integer not null default 0,
  channel_cost_cents integer not null default 0,
  media_cost_cents integer not null default 0,
  contribution_after_media_cents integer not null default 0,
  status varchar(20) not null default 'pending' check (status in ('pending','processing','sent','failed','dead_letter')),
  attempts integer not null default 0 check (attempts >= 0),
  last_error text,
  payload_json text not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(event_id),
  unique(order_id,event_name)
);
create index if not exists ix_conversion_events_business_created on public.conversion_events(business_id,occurred_at desc);
create index if not exists ix_conversion_events_delivery on public.conversion_events(status,created_at) where status in ('pending','failed');

alter table public.storefronts enable row level security;
alter table public.order_attributions enable row level security;
alter table public.conversion_events enable row level security;

do $$
begin
  if exists(select 1 from pg_roles where rolname='anon') then
    execute 'revoke all privileges on table public.storefronts from anon';
    execute 'revoke all privileges on table public.order_attributions from anon';
    execute 'revoke all privileges on table public.conversion_events from anon';
    execute 'revoke all privileges on sequence public.storefronts_id_seq from anon';
    execute 'revoke all privileges on sequence public.order_attributions_id_seq from anon';
    execute 'revoke all privileges on sequence public.conversion_events_id_seq from anon';
  end if;
  if exists(select 1 from pg_roles where rolname='authenticated') then
    execute 'revoke all privileges on table public.storefronts from authenticated';
    execute 'revoke all privileges on table public.order_attributions from authenticated';
    execute 'revoke all privileges on table public.conversion_events from authenticated';
    execute 'revoke all privileges on sequence public.storefronts_id_seq from authenticated';
    execute 'revoke all privileges on sequence public.order_attributions_id_seq from authenticated';
    execute 'revoke all privileges on sequence public.conversion_events_id_seq from authenticated';
  end if;
end $$;

drop trigger if exists trg_storefronts_updated_at on public.storefronts;
create trigger trg_storefronts_updated_at before update on public.storefronts
for each row execute function public.touch_updated_at();

drop trigger if exists trg_order_attributions_updated_at on public.order_attributions;
create trigger trg_order_attributions_updated_at before update on public.order_attributions
for each row execute function public.touch_updated_at();

drop trigger if exists trg_conversion_events_updated_at on public.conversion_events;
create trigger trg_conversion_events_updated_at before update on public.conversion_events
for each row execute function public.touch_updated_at();

create or replace function public.c360_create_direct_order(
  p_slug text,
  p_client_order_key text,
  p_items jsonb,
  p_customer_name text default '',
  p_phone text default '',
  p_email text default '',
  p_consent_marketing boolean default false,
  p_session_key text default null,
  p_referrer text default null,
  p_utm_source text default null,
  p_utm_medium text default null,
  p_utm_campaign text default null,
  p_utm_content text default null,
  p_utm_term text default null,
  p_gclid text default null,
  p_fbclid text default null,
  p_ttclid text default null
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_store public.storefronts%rowtype;
  v_existing public.orders%rowtype;
  v_order public.orders%rowtype;
  v_item jsonb;
  v_product public.products%rowtype;
  v_price public.product_channel_prices%rowtype;
  v_customer_id bigint;
  v_qty integer;
  v_unit_cost integer;
  v_total integer := 0;
  v_cost integer := 0;
  v_idempotency text;
  v_brand_id bigint;
  v_distinct_brands integer;
begin
  select * into v_store
    from public.storefronts
   where lower(slug)=lower(trim(coalesce(p_slug,''))) and active=true
   limit 1;
  if not found then raise exception 'STOREFRONT_NOT_FOUND'; end if;

  if p_client_order_key is null or length(trim(p_client_order_key)) < 8 or length(trim(p_client_order_key)) > 100 then
    raise exception 'CLIENT_ORDER_KEY_INVALID';
  end if;
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 or jsonb_array_length(p_items) > 20 then
    raise exception 'ORDER_ITEMS_INVALID';
  end if;

  v_idempotency := 'direct:' || lower(v_store.slug) || ':' || trim(p_client_order_key);
  perform pg_advisory_xact_lock(hashtextextended(v_store.business_id::text || ':' || v_idempotency,0));
  select * into v_existing from public.orders
   where business_id=v_store.business_id and idempotency_key=v_idempotency limit 1;
  if found then
    return jsonb_build_object(
      'id',v_existing.id,'status',v_existing.status,'total_cents',v_existing.total_cents,
      'contribution_cents',v_existing.contribution_cents,'idempotent_replay',true
    );
  end if;

  for v_item in select * from jsonb_array_elements(p_items)
  loop
    v_qty := coalesce((v_item->>'quantity')::integer,1);
    if v_qty < 1 or v_qty > 20 then raise exception 'ITEM_QUANTITY_INVALID'; end if;

    select * into v_product from public.products
     where id=(v_item->>'product_id')::bigint
       and business_id=v_store.business_id
       and soft_deleted=false and active=true;
    if not found then raise exception 'PRODUCT_NOT_FOUND'; end if;
    if v_store.brand_id is not null and v_product.brand_id is distinct from v_store.brand_id then
      raise exception 'PRODUCT_NOT_IN_STOREFRONT';
    end if;

    select * into v_price from public.product_channel_prices
     where product_id=v_product.id and channel_id=v_store.channel_id and business_id=v_store.business_id;
    if not found or v_price.sale_price_cents <= 0 then raise exception 'PRODUCT_PRICE_NOT_CONFIGURED'; end if;

    select greatest(0,round((
      coalesce(sum((i.last_purchase_price_cents::numeric * ri.qty_used_milliunits::numeric) / greatest(i.usable_qty_milliunits,1)),0)
      + v_product.energy_cents_per_batch
      + v_product.labor_cents_per_batch
      + v_product.packaging_cents_per_unit * greatest(v_product.units_per_batch,1)
    ) / greatest(v_product.units_per_batch,1))::integer)
      into v_unit_cost
      from public.recipe_items ri
      join public.ingredients i on i.id=ri.ingredient_id and i.business_id=v_store.business_id and i.soft_deleted=false
     where ri.product_id=v_product.id;

    v_total := v_total + v_price.sale_price_cents * v_qty;
    v_cost := v_cost + v_unit_cost * v_qty;
  end loop;

  if nullif(trim(coalesce(p_phone,'')),'') is not null then
    select id into v_customer_id from public.customers
     where business_id=v_store.business_id and phone=left(trim(p_phone),40) order by id limit 1;
  end if;
  if v_customer_id is null and nullif(trim(coalesce(p_email,'')),'') is not null then
    select id into v_customer_id from public.customers
     where business_id=v_store.business_id and lower(email)=lower(left(trim(p_email),320)) order by id limit 1;
  end if;

  if v_customer_id is null and (
    nullif(trim(coalesce(p_customer_name,'')),'') is not null or
    nullif(trim(coalesce(p_phone,'')),'') is not null or
    nullif(trim(coalesce(p_email,'')),'') is not null
  ) then
    insert into public.customers(business_id,name,phone,email,consent_marketing)
    values(
      v_store.business_id,
      left(coalesce(nullif(trim(p_customer_name),''),'Cliente pedido direto'),160),
      left(trim(coalesce(p_phone,'')),40),
      left(trim(coalesce(p_email,'')),320),
      coalesce(p_consent_marketing,false)
    ) returning id into v_customer_id;
  elsif v_customer_id is not null then
    update public.customers
       set name=case when nullif(trim(coalesce(p_customer_name,'')),'') is not null then left(trim(p_customer_name),160) else name end,
           phone=case when nullif(trim(coalesce(p_phone,'')),'') is not null then left(trim(p_phone),40) else phone end,
           email=case when nullif(trim(coalesce(p_email,'')),'') is not null then left(trim(p_email),320) else email end,
           consent_marketing=case when coalesce(p_consent_marketing,false) then true else consent_marketing end,
           opted_out_at=case when coalesce(p_consent_marketing,false) then null else opted_out_at end,
           updated_at=now()
     where id=v_customer_id;
  end if;

  select count(distinct p.brand_id), min(p.brand_id)
    into v_distinct_brands,v_brand_id
    from jsonb_array_elements(p_items) x
    join public.products p on p.id=(x->>'product_id')::bigint
   where p.brand_id is not null;
  if v_distinct_brands <> 1 or exists(
    select 1 from jsonb_array_elements(p_items) x join public.products p on p.id=(x->>'product_id')::bigint where p.brand_id is null
  ) then v_brand_id := null; end if;
  if v_store.brand_id is not null then v_brand_id := v_store.brand_id; end if;

  insert into public.orders(
    business_id,customer_id,channel_id,brand_id,status,source,total_cents,
    variable_cost_cents,contribution_cents,paid,idempotency_key
  ) values (
    v_store.business_id,v_customer_id,v_store.channel_id,v_brand_id,'new','direct:'||v_store.slug,
    v_total,v_cost,v_total-v_cost,false,v_idempotency
  ) returning * into v_order;

  for v_item in select * from jsonb_array_elements(p_items)
  loop
    v_qty := coalesce((v_item->>'quantity')::integer,1);
    select p.* into v_product from public.products p where p.id=(v_item->>'product_id')::bigint;
    select * into v_price from public.product_channel_prices
     where product_id=v_product.id and channel_id=v_store.channel_id and business_id=v_store.business_id;
    select greatest(0,round((
      coalesce(sum((i.last_purchase_price_cents::numeric * ri.qty_used_milliunits::numeric) / greatest(i.usable_qty_milliunits,1)),0)
      + v_product.energy_cents_per_batch
      + v_product.labor_cents_per_batch
      + v_product.packaging_cents_per_unit * greatest(v_product.units_per_batch,1)
    ) / greatest(v_product.units_per_batch,1))::integer)
      into v_unit_cost
      from public.recipe_items ri
      join public.ingredients i on i.id=ri.ingredient_id and i.business_id=v_store.business_id and i.soft_deleted=false
     where ri.product_id=v_product.id;
    insert into public.order_items(business_id,order_id,product_id,quantity,unit_price_cents,unit_variable_cost_cents)
    values(v_store.business_id,v_order.id,v_product.id,v_qty,v_price.sale_price_cents,v_unit_cost);
  end loop;

  insert into public.order_attributions(
    business_id,order_id,storefront_id,session_key,referrer,utm_source,utm_medium,utm_campaign,utm_content,utm_term,gclid,fbclid,ttclid
  ) values (
    v_store.business_id,v_order.id,v_store.id,
    left(nullif(trim(coalesce(p_session_key,'')),''),120),
    left(nullif(trim(coalesce(p_referrer,'')),''),500),
    left(nullif(trim(coalesce(p_utm_source,'')),''),120),
    left(nullif(trim(coalesce(p_utm_medium,'')),''),120),
    left(nullif(trim(coalesce(p_utm_campaign,'')),''),160),
    left(nullif(trim(coalesce(p_utm_content,'')),''),160),
    left(nullif(trim(coalesce(p_utm_term,'')),''),160),
    left(nullif(trim(coalesce(p_gclid,'')),''),220),
    left(nullif(trim(coalesce(p_fbclid,'')),''),220),
    left(nullif(trim(coalesce(p_ttclid,'')),''),220)
  );

  insert into public.outbox_events(business_id,topic,payload_json)
  values(v_store.business_id,'direct.order.created',jsonb_build_object(
    'order_id',v_order.id,'storefront_id',v_store.id,'slug',v_store.slug,'channel_id',v_store.channel_id
  )::text);

  return jsonb_build_object(
    'id',v_order.id,'status',v_order.status,'total_cents',v_order.total_cents,
    'contribution_cents',v_order.contribution_cents,'idempotent_replay',false
  );
end;
$$;

create or replace function public.c360_emit_purchase_conversion()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_attr public.order_attributions%rowtype;
  v_channel public.channels%rowtype;
  v_fee integer := 0;
  v_media integer := 0;
  v_channel_cost integer := 0;
  v_event public.conversion_events%rowtype;
begin
  if not ((coalesce(old.paid,false)=false and coalesce(new.paid,false)=true)
       or (old.status is distinct from 'completed' and new.status='completed')) then
    return new;
  end if;

  select * into v_attr from public.order_attributions where order_id=new.id limit 1;
  if not found then return new; end if;
  select * into v_channel from public.channels where id=new.channel_id and business_id=new.business_id;

  if found then
    v_fee := round(new.total_cents::numeric * coalesce(v_channel.fee_bps,0) / 10000)::integer;
    v_media := coalesce(v_attr.media_cost_cents,v_channel.media_cents,0);
    v_channel_cost := v_fee + coalesce(v_channel.fixed_fee_cents,0) + coalesce(v_channel.delivery_cents,0)
      + coalesce(v_channel.promo_cents,0) + v_media;
  else
    v_media := coalesce(v_attr.media_cost_cents,0);
    v_channel_cost := v_media;
  end if;

  insert into public.conversion_events(
    business_id,order_id,attribution_id,event_name,event_id,occurred_at,revenue_cents,
    variable_cost_cents,channel_cost_cents,media_cost_cents,contribution_after_media_cents,payload_json
  ) values (
    new.business_id,new.id,v_attr.id,'purchase','c360:order:'||new.id||':purchase',coalesce(new.completed_at,now()),
    new.total_cents,new.variable_cost_cents,v_channel_cost,v_media,new.contribution_cents-v_channel_cost,
    jsonb_build_object(
      'order_id',new.id,'source',new.source,'channel_id',new.channel_id,'storefront_id',v_attr.storefront_id,
      'utm_source',v_attr.utm_source,'utm_medium',v_attr.utm_medium,'utm_campaign',v_attr.utm_campaign
    )::text
  ) on conflict(order_id,event_name) do nothing
  returning * into v_event;

  if v_event.id is not null then
    insert into public.outbox_events(business_id,topic,payload_json)
    values(new.business_id,'conversion.purchase.ready',jsonb_build_object(
      'conversion_event_id',v_event.id,'event_id',v_event.event_id,'order_id',new.id
    )::text);
  end if;
  return new;
end;
$$;

drop trigger if exists trg_orders_purchase_conversion on public.orders;
create trigger trg_orders_purchase_conversion
after update of paid,status on public.orders
for each row execute function public.c360_emit_purchase_conversion();

create or replace function public.c360_campaign_attribution(
  p_business_id bigint,
  p_days integer default 30
) returns table(
  utm_source text,
  utm_medium text,
  utm_campaign text,
  orders bigint,
  revenue_cents bigint,
  variable_cost_cents bigint,
  channel_cost_cents bigint,
  media_cost_cents bigint,
  contribution_after_media_cents bigint,
  revenue_per_media numeric,
  contribution_per_media numeric
)
language sql
security definer
set search_path = public
as $$
  select
    coalesce(nullif(a.utm_source,''),'direct/unknown')::text,
    coalesce(nullif(a.utm_medium,''),'unknown')::text,
    coalesce(nullif(a.utm_campaign,''),'unattributed')::text,
    count(*)::bigint,
    sum(c.revenue_cents)::bigint,
    sum(c.variable_cost_cents)::bigint,
    sum(c.channel_cost_cents)::bigint,
    sum(c.media_cost_cents)::bigint,
    sum(c.contribution_after_media_cents)::bigint,
    case when sum(c.media_cost_cents)>0 then round(sum(c.revenue_cents)::numeric/sum(c.media_cost_cents),2) else null end,
    case when sum(c.media_cost_cents)>0 then round(sum(c.contribution_after_media_cents)::numeric/sum(c.media_cost_cents),2) else null end
  from public.conversion_events c
  join public.order_attributions a on a.id=c.attribution_id
  where c.business_id=p_business_id
    and c.event_name='purchase'
    and c.occurred_at >= now() - make_interval(days => greatest(1,least(coalesce(p_days,30),365)))
  group by 1,2,3
  order by sum(c.contribution_after_media_cents) desc, sum(c.revenue_cents) desc;
$$;

revoke all on function public.c360_create_direct_order(text,text,jsonb,text,text,text,boolean,text,text,text,text,text,text,text,text,text,text) from public;
revoke all on function public.c360_campaign_attribution(bigint,integer) from public;

do $$
begin
  if exists(select 1 from pg_roles where rolname='anon') then
    execute 'revoke all on function public.c360_create_direct_order(text,text,jsonb,text,text,text,boolean,text,text,text,text,text,text,text,text,text,text) from anon';
    execute 'revoke all on function public.c360_campaign_attribution(bigint,integer) from anon';
  end if;
  if exists(select 1 from pg_roles where rolname='authenticated') then
    execute 'revoke all on function public.c360_create_direct_order(text,text,jsonb,text,text,text,boolean,text,text,text,text,text,text,text,text,text,text) from authenticated';
    execute 'revoke all on function public.c360_campaign_attribution(bigint,integer) from authenticated';
  end if;
  if exists(select 1 from pg_roles where rolname='service_role') then
    execute 'grant execute on function public.c360_create_direct_order(text,text,jsonb,text,text,text,boolean,text,text,text,text,text,text,text,text,text,text) to service_role';
    execute 'grant execute on function public.c360_campaign_attribution(bigint,integer) to service_role';
  end if;
end $$;

commit;
