begin;

create table if not exists public.business_billing_accounts (
  business_id bigint primary key references public.businesses(id) on delete cascade,
  provider varchar(32) not null default 'none',
  provider_customer_ref text,
  provider_subscription_ref text,
  plan_key varchar(32) not null default 'candidate',
  status varchar(24) not null default 'candidate',
  current_period_end timestamptz,
  cancel_at_period_end boolean not null default false,
  metadata_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ck_business_billing_provider check (provider in ('none','stripe','manual')),
  constraint ck_business_billing_plan check (plan_key in ('candidate','free','pro')),
  constraint ck_business_billing_status check (status in ('candidate','free','trialing','active','past_due','canceled'))
);

create unique index if not exists ux_business_billing_provider_customer
  on public.business_billing_accounts(provider, provider_customer_ref)
  where provider_customer_ref is not null;

create unique index if not exists ux_business_billing_provider_subscription
  on public.business_billing_accounts(provider, provider_subscription_ref)
  where provider_subscription_ref is not null;

create table if not exists public.billing_events (
  id bigint generated by default as identity primary key,
  provider varchar(32) not null,
  provider_event_id text not null,
  event_type text not null,
  business_id bigint references public.businesses(id) on delete set null,
  payload_sha256 varchar(64),
  processing_status varchar(20) not null default 'received',
  processed_at timestamptz,
  error text,
  created_at timestamptz not null default now(),
  constraint ux_billing_events_provider_event unique(provider, provider_event_id),
  constraint ck_billing_event_status check (processing_status in ('received','processed','ignored','failed'))
);

create index if not exists ix_billing_events_business_created
  on public.billing_events(business_id, created_at desc);

alter table public.business_billing_accounts enable row level security;
alter table public.billing_events enable row level security;

do $$
begin
  if exists(select 1 from pg_roles where rolname='anon') then
    execute 'revoke all privileges on table public.business_billing_accounts from anon';
    execute 'revoke all privileges on table public.billing_events from anon';
  end if;
  if exists(select 1 from pg_roles where rolname='authenticated') then
    execute 'revoke all privileges on table public.business_billing_accounts from authenticated';
    execute 'revoke all privileges on table public.billing_events from authenticated';
  end if;
end $$;

drop trigger if exists trg_business_billing_accounts_updated_at on public.business_billing_accounts;
create trigger trg_business_billing_accounts_updated_at
before update on public.business_billing_accounts
for each row execute function public.touch_updated_at();

comment on table public.business_billing_accounts is
  'Server-controlled commercial entitlement state per business. Browser clients must consume a server API, never direct table grants.';
comment on table public.billing_events is
  'Provider event idempotency ledger. Store event identifiers and payload hashes, not raw payment payloads.';

commit;