begin;

alter table users add column if not exists auth_version integer not null default 1 check (auth_version >= 1);
alter table users add column if not exists failed_login_attempts integer not null default 0 check (failed_login_attempts >= 0);
alter table users add column if not exists locked_until timestamptz;

create table if not exists team_invites (
  id bigint generated by default as identity primary key,
  business_id bigint not null references businesses(id) on delete cascade,
  code varchar(80) not null unique,
  role varchar(20) not null default 'member' check (role in ('admin','member')),
  created_by_user_id bigint references users(id) on delete set null,
  expires_at timestamptz not null,
  max_uses integer not null default 1 check (max_uses between 1 and 100),
  uses integer not null default 0 check (uses >= 0),
  revoked boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists ix_team_invites_business on team_invites(business_id);
create index if not exists ix_team_invites_code on team_invites(code);
create index if not exists ix_team_invite_business_active on team_invites(business_id,revoked);

drop trigger if exists trg_team_invites_updated_at on team_invites;
create trigger trg_team_invites_updated_at before update on team_invites for each row execute function touch_updated_at();

commit;
