begin;

create table if not exists users (
  id bigint generated by default as identity primary key,
  email varchar(320) not null unique,
  password_hash varchar(255) not null,
  full_name varchar(120) not null default '',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists businesses (
  id bigint generated by default as identity primary key,
  name varchar(160) not null,
  city varchar(120) not null default '',
  timezone varchar(64) not null default 'America/Sao_Paulo',
  currency varchar(3) not null default 'BRL',
  min_contribution_cents integer not null default 1000 check (min_contribution_cents >= 0),
  safety_margin_bps integer not null default 2500 check (safety_margin_bps between 0 and 9000),
  price_alert_threshold_bps integer not null default 500 check (price_alert_threshold_bps between 0 and 10000),
  soft_deleted boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists memberships (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  business_id bigint not null references businesses(id) on delete cascade,
  role varchar(20) not null default 'member' check (role in ('owner','admin','member')),
  preferences_json text not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id,business_id)
);
create index if not exists ix_memberships_user on memberships(user_id);
create index if not exists ix_memberships_business on memberships(business_id);

create table if not exists ingredients (
  id bigint generated by default as identity primary key,
  business_id bigint not null references businesses(id) on delete cascade,
  name varchar(160) not null,
  unit varchar(20) not null default 'g',
  last_purchase_price_cents integer not null default 0 check (last_purchase_price_cents >= 0),
  last_purchase_qty_milliunits integer not null default 1000 check (last_purchase_qty_milliunits > 0),
  usable_qty_milliunits integer not null default 1000 check (usable_qty_milliunits > 0),
  soft_deleted boolean not null default false,
  version integer not null default 1 check (version >= 1),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(business_id,name)
);
create index if not exists ix_ingredients_business on ingredients(business_id);

create table if not exists suppliers (
  id bigint generated by default as identity primary key,
  business_id bigint not null references businesses(id) on delete cascade,
  name varchar(160) not null,
  cnpj varchar(20) not null default '',
  phone varchar(40) not null default '',
  backup_supplier boolean not null default false,
  notes text not null default '',
  soft_deleted boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists ix_suppliers_business on suppliers(business_id);

create table if not exists purchases (
  id bigint generated by default as identity primary key,
  business_id bigint not null references businesses(id) on delete cascade,
  ingredient_id bigint not null references ingredients(id) on delete restrict,
  supplier_id bigint references suppliers(id) on delete set null,
  quantity_milliunits integer not null check (quantity_milliunits > 0),
  total_cents integer not null check (total_cents >= 0),
  freight_cents integer not null default 0 check (freight_cents >= 0),
  tax_cents integer not null default 0 check (tax_cents >= 0),
  idempotency_key varchar(100) not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(business_id,idempotency_key)
);
create index if not exists ix_purchases_business on purchases(business_id);
create index if not exists ix_purchases_ingredient on purchases(ingredient_id);

create table if not exists products (
  id bigint generated by default as identity primary key,
  business_id bigint not null references businesses(id) on delete cascade,
  name varchar(160) not null,
  units_per_batch integer not null default 1 check (units_per_batch > 0),
  packaging_cents_per_unit integer not null default 0 check (packaging_cents_per_unit >= 0),
  energy_cents_per_batch integer not null default 0 check (energy_cents_per_batch >= 0),
  labor_cents_per_batch integer not null default 0 check (labor_cents_per_batch >= 0),
  soft_deleted boolean not null default false,
  version integer not null default 1 check (version >= 1),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists ix_products_business on products(business_id);

create table if not exists recipe_items (
  id bigint generated by default as identity primary key,
  product_id bigint not null references products(id) on delete cascade,
  ingredient_id bigint not null references ingredients(id) on delete restrict,
  qty_used_milliunits integer not null check (qty_used_milliunits > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(product_id,ingredient_id)
);

create table if not exists channels (
  id bigint generated by default as identity primary key,
  business_id bigint not null references businesses(id) on delete cascade,
  name varchar(120) not null,
  fee_bps integer not null default 0 check (fee_bps between 0 and 9999),
  fixed_fee_cents integer not null default 0 check (fixed_fee_cents >= 0),
  delivery_cents integer not null default 0 check (delivery_cents >= 0),
  promo_cents integer not null default 0 check (promo_cents >= 0),
  media_cents integer not null default 0 check (media_cents >= 0),
  traffic_active boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists ix_channels_business on channels(business_id);

create table if not exists product_channel_prices (
  id bigint generated by default as identity primary key,
  business_id bigint not null references businesses(id) on delete cascade,
  product_id bigint not null references products(id) on delete cascade,
  channel_id bigint not null references channels(id) on delete cascade,
  sale_price_cents integer not null check (sale_price_cents >= 0),
  desired_contribution_cents integer not null default 1000 check (desired_contribution_cents >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(product_id,channel_id)
);
create index if not exists ix_product_channel_prices_business on product_channel_prices(business_id);

create table if not exists customers (
  id bigint generated by default as identity primary key,
  business_id bigint not null references businesses(id) on delete cascade,
  name varchar(160) not null,
  phone varchar(40) not null default '',
  email varchar(320) not null default '',
  consent_marketing boolean not null default false,
  opted_out_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists ix_customers_business on customers(business_id);

create table if not exists orders (
  id bigint generated by default as identity primary key,
  business_id bigint not null references businesses(id) on delete cascade,
  customer_id bigint references customers(id) on delete set null,
  channel_id bigint references channels(id) on delete set null,
  status varchar(32) not null default 'new' check (status in ('new','confirmed','production','checking','awaiting_delivery','completed','cancelled')),
  source varchar(120) not null default 'manual',
  total_cents integer not null default 0 check (total_cents >= 0),
  variable_cost_cents integer not null default 0 check (variable_cost_cents >= 0),
  contribution_cents integer not null default 0,
  paid boolean not null default false,
  delayed boolean not null default false,
  error_flag boolean not null default false,
  idempotency_key varchar(100) not null,
  version integer not null default 1 check (version >= 1),
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(business_id,idempotency_key)
);
create index if not exists ix_orders_business on orders(business_id);
create index if not exists ix_orders_business_status on orders(business_id,status);

create table if not exists losses (
  id bigint generated by default as identity primary key,
  business_id bigint not null references businesses(id) on delete cascade,
  ingredient_id bigint references ingredients(id) on delete set null,
  reason varchar(120) not null,
  qty_milliunits integer not null default 0 check (qty_milliunits >= 0),
  estimated_cost_cents integer not null default 0 check (estimated_cost_cents >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists ix_losses_business on losses(business_id);

create table if not exists capacity_steps (
  id bigint generated by default as identity primary key,
  business_id bigint not null references businesses(id) on delete cascade,
  name varchar(120) not null,
  minutes_per_order integer not null check (minutes_per_order > 0),
  parallelism integer not null default 1 check (parallelism > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists ix_capacity_steps_business on capacity_steps(business_id);

create table if not exists audit_logs (
  id bigint generated by default as identity primary key,
  business_id bigint not null references businesses(id) on delete cascade,
  actor_user_id bigint references users(id) on delete set null,
  action varchar(120) not null,
  entity_type varchar(80) not null,
  entity_id varchar(80) not null default '',
  payload_json text not null default '{}',
  created_at timestamptz not null default now()
);
create index if not exists ix_audit_logs_business on audit_logs(business_id);

create table if not exists webhook_events (
  id bigint generated by default as identity primary key,
  provider varchar(64) not null,
  provider_event_id varchar(180) not null,
  payload_json text not null,
  status varchar(32) not null default 'received',
  attempts integer not null default 0 check (attempts >= 0),
  created_at timestamptz not null default now(),
  unique(provider,provider_event_id)
);
create index if not exists ix_webhook_provider on webhook_events(provider);

create table if not exists outbox_events (
  id bigint generated by default as identity primary key,
  business_id bigint references businesses(id) on delete cascade,
  topic varchar(120) not null,
  payload_json text not null,
  status varchar(32) not null default 'pending',
  attempts integer not null default 0 check (attempts >= 0),
  available_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);
create index if not exists ix_outbox_business on outbox_events(business_id);
create index if not exists ix_outbox_topic on outbox_events(topic);

create or replace function touch_updated_at() returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['users','businesses','memberships','ingredients','suppliers','purchases','products','recipe_items','channels','product_channel_prices','customers','orders','losses','capacity_steps']
  LOOP
    EXECUTE format('drop trigger if exists trg_%I_updated_at on %I', t, t);
    EXECUTE format('create trigger trg_%I_updated_at before update on %I for each row execute function touch_updated_at()', t, t);
  END LOOP;
END $$;

commit;
