begin;

create table if not exists inventory_counts (
  id bigint generated by default as identity primary key,
  business_id bigint not null references businesses(id) on delete cascade,
  ingredient_id bigint not null references ingredients(id) on delete restrict,
  counted_by_user_id bigint references users(id) on delete set null,
  counted_milliunits integer not null check (counted_milliunits >= 0),
  note varchar(500) not null default '',
  created_at timestamptz not null default now()
);

create index if not exists ix_inventory_counts_business on inventory_counts(business_id);
create index if not exists ix_inventory_counts_ingredient on inventory_counts(ingredient_id);
create index if not exists ix_inventory_counts_user on inventory_counts(counted_by_user_id);
create index if not exists ix_inventory_counts_business_ingredient_created on inventory_counts(business_id, ingredient_id, created_at desc);

alter table inventory_counts enable row level security;

do $$
begin
  if exists (select 1 from pg_roles where rolname = 'anon') then
    revoke all privileges on table inventory_counts from anon;
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    revoke all privileges on table inventory_counts from authenticated;
  end if;
end $$;

commit;
