begin;

create table if not exists public.deliveries (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id) on delete cascade,
  order_id bigint not null unique references public.orders(id) on delete cascade,
  driver_id bigint references public.delivery_drivers(id) on delete set null,
  zone_id bigint references public.delivery_zones(id) on delete set null,
  status varchar(24) not null default 'waiting' check (status in ('waiting','assigned','picked_up','delivered','failed','cancelled')),
  fee_cents integer not null default 0 check (fee_cents >= 0),
  promised_at timestamptz,
  picked_up_at timestamptz,
  delivered_at timestamptz,
  tracking_token uuid not null default gen_random_uuid() unique,
  notes text not null default '',
  version integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (delivered_at is null or picked_up_at is null or delivered_at >= picked_up_at)
);

create index if not exists ix_deliveries_business_status on public.deliveries(business_id,status);
create index if not exists ix_deliveries_driver_status on public.deliveries(driver_id,status) where driver_id is not null;
create index if not exists ix_deliveries_zone on public.deliveries(zone_id) where zone_id is not null;

alter table public.deliveries enable row level security;

do $$
declare role_name text;
begin
  foreach role_name in array array['anon','authenticated'] loop
    if exists(select 1 from pg_roles where rolname=role_name) then
      execute format('revoke all privileges on table public.deliveries from %I',role_name);
      if to_regclass('public.deliveries_id_seq') is not null then
        execute format('revoke all privileges on sequence public.deliveries_id_seq from %I',role_name);
      end if;
    end if;
  end loop;
end $$;

drop trigger if exists trg_deliveries_updated_at on public.deliveries;
create trigger trg_deliveries_updated_at before update on public.deliveries for each row execute function public.touch_updated_at();

commit;
