create unique index if not exists customers_business_phone_uq
  on public.customers (business_id, phone)
  where phone <> '';

create table if not exists public.integration_messages (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id) on delete cascade,
  connection_id bigint references public.integration_connections(id) on delete set null,
  customer_id bigint references public.customers(id) on delete set null,
  provider varchar(48) not null,
  external_message_id varchar(255) not null,
  direction varchar(16) not null check (direction in ('inbound','outbound')),
  message_type varchar(40) not null default 'text',
  sender_ref varchar(160),
  recipient_ref varchar(160),
  body_text text,
  status varchar(32) not null default 'received'
    check (status in ('received','queued','sent','delivered','read','failed','ignored')),
  provider_status varchar(64),
  integration_event_id bigint references public.integration_events(id) on delete set null,
  occurred_at timestamptz,
  raw_json text not null default '{}',
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(provider, external_message_id)
);

create index if not exists integration_messages_business_created_idx
  on public.integration_messages (business_id, created_at desc);
create index if not exists integration_messages_business_customer_idx
  on public.integration_messages (business_id, customer_id, created_at desc);
create index if not exists integration_messages_connection_idx
  on public.integration_messages (connection_id, created_at desc);

alter table public.integration_messages enable row level security;
revoke all on table public.integration_messages from anon, authenticated;
revoke all on sequence public.integration_messages_id_seq from anon, authenticated;
grant all on table public.integration_messages to service_role;
grant all on sequence public.integration_messages_id_seq to service_role;
