create table if not exists autopilot_runs (
  id bigint generated by default as identity primary key,
  business_id bigint not null references businesses(id) on delete cascade,
  actor_user_id bigint references users(id) on delete set null,
  request_id uuid not null,
  horizon_days integer not null check (horizon_days between 1 and 14),
  buffer_bps integer not null default 0 check (buffer_bps between 0 and 5000),
  plan_hash varchar(64) not null,
  status varchar(24) not null default 'running' check (status in ('running','completed','partial','failed')),
  action_count integer not null default 0 check (action_count >= 0),
  result_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (business_id, request_id)
);

create index if not exists ix_autopilot_runs_business_created on autopilot_runs(business_id, created_at desc);
create index if not exists ix_autopilot_runs_business_status on autopilot_runs(business_id, status);

alter table autopilot_runs enable row level security;
revoke all on table autopilot_runs from anon, authenticated;
revoke all on sequence autopilot_runs_id_seq from anon, authenticated;

comment on table autopilot_runs is 'Server-owned idempotency and audit ledger for Autopilot 360 bulk production actions.';
comment on column autopilot_runs.result_json is 'Sanitized orchestration result only; do not store provider secrets or raw auth tokens.';
