begin;

create table if not exists public.payment_intents (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id) on delete cascade,
  order_id bigint not null references public.orders(id) on delete cascade,
  connection_id bigint not null references public.integration_connections(id) on delete restrict,
  provider varchar(40) not null default 'mercadopago',
  method varchar(24) not null default 'pix',
  public_token uuid not null default gen_random_uuid(),
  idempotency_key uuid not null default gen_random_uuid(),
  external_reference varchar(160) not null,
  external_order_id varchar(160),
  status varchar(32) not null default 'created'
    check (status in ('created','action_required','processing','processed','failed','canceled','expired','refunded','charged_back')),
  status_detail varchar(80),
  amount_cents integer not null check (amount_cents > 0),
  qr_code text,
  qr_code_base64 text,
  ticket_url text,
  expires_at timestamptz,
  last_event_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (public_token),
  unique (idempotency_key),
  unique (external_reference),
  unique (business_id, order_id, provider, method)
);

create unique index if not exists uq_payment_intents_external_order
  on public.payment_intents(provider, external_order_id)
  where external_order_id is not null;
create index if not exists ix_payment_intents_business_status
  on public.payment_intents(business_id, status, updated_at desc);
create index if not exists ix_payment_intents_order
  on public.payment_intents(order_id);
create index if not exists ix_payment_intents_connection
  on public.payment_intents(connection_id);

alter table public.payment_intents enable row level security;

do $$
begin
  if exists(select 1 from pg_roles where rolname='anon') then
    execute 'revoke all privileges on table public.payment_intents from anon';
  end if;
  if exists(select 1 from pg_roles where rolname='authenticated') then
    execute 'revoke all privileges on table public.payment_intents from authenticated';
  end if;
end $$;

drop trigger if exists trg_payment_intents_updated_at on public.payment_intents;
create trigger trg_payment_intents_updated_at
before update on public.payment_intents
for each row execute function public.touch_updated_at();

comment on table public.payment_intents is
  'Canonical payment lifecycle. Provider credentials stay in integration_credentials; public_token exposes only safe checkout state.';
comment on column public.payment_intents.qr_code is
  'Single-use Pix copy-and-paste payload returned by the provider; never a provider credential.';

commit;
