begin;

alter table ingredients add column if not exists on_hand_milliunits integer not null default 0;
alter table ingredients add column if not exists par_level_milliunits integer not null default 0;
alter table ingredients add column if not exists reorder_target_milliunits integer not null default 0;

alter table products add column if not exists category varchar(80) not null default '';
alter table products add column if not exists active boolean not null default true;

alter table orders add column if not exists inventory_consumed boolean not null default false;

create table if not exists order_items (
  id bigint generated by default as identity primary key,
  business_id bigint not null references businesses(id) on delete cascade,
  order_id bigint not null references orders(id) on delete cascade,
  product_id bigint not null references products(id) on delete restrict,
  quantity integer not null default 1 check (quantity > 0),
  unit_price_cents integer not null default 0 check (unit_price_cents >= 0),
  unit_variable_cost_cents integer not null default 0 check (unit_variable_cost_cents >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists ix_order_items_business on order_items(business_id);
create index if not exists ix_order_items_order on order_items(order_id);
create index if not exists ix_order_items_product on order_items(product_id);

create table if not exists production_batches (
  id bigint generated by default as identity primary key,
  business_id bigint not null references businesses(id) on delete cascade,
  product_id bigint not null references products(id) on delete restrict,
  responsible_user_id bigint references users(id) on delete set null,
  status varchar(32) not null default 'planned' check (status in ('planned','in_progress','completed','cancelled')),
  planned_qty integer not null default 0 check (planned_qty >= 0),
  produced_qty integer not null default 0 check (produced_qty >= 0),
  waste_qty integer not null default 0 check (waste_qty >= 0),
  scheduled_for timestamptz,
  notes text not null default '',
  version integer not null default 1 check (version >= 1),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists ix_production_business on production_batches(business_id);
create index if not exists ix_production_product on production_batches(product_id);
create index if not exists ix_production_responsible on production_batches(responsible_user_id);
create index if not exists ix_production_business_status on production_batches(business_id,status);

drop trigger if exists trg_order_items_updated_at on order_items;
create trigger trg_order_items_updated_at before update on order_items for each row execute function touch_updated_at();
drop trigger if exists trg_production_batches_updated_at on production_batches;
create trigger trg_production_batches_updated_at before update on production_batches for each row execute function touch_updated_at();

commit;
