begin;

create table if not exists public.commercial_plans (
  plan_key varchar(24) primary key,
  display_name varchar(80) not null,
  monthly_cents integer not null check (monthly_cents >= 0),
  annual_cents integer not null check (annual_cents >= 0),
  online_order_limit integer,
  brand_limit integer not null check (brand_limit >= 1),
  driver_limit integer,
  route_quota integer,
  features_json jsonb not null default '{}'::jsonb,
  active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.commercial_plans(plan_key,display_name,monthly_cents,annual_cents,online_order_limit,brand_limit,driver_limit,route_quota,features_json,sort_order)
values
 ('free','Free',0,0,50,1,1,0,'{"direct_store":true,"kds":false,"crm":"basic","integrations":false,"autopilot":false}'::jsonb,0),
 ('start','Start',4990,49900,null,1,5,0,'{"direct_store":true,"kds":true,"crm":"basic","coupons":true,"integrations":"limited","autopilot":false}'::jsonb,10),
 ('pro','Pro',9990,99900,null,3,20,500,'{"direct_store":true,"kds":true,"crm":"brand","loyalty":true,"scheduled_orders":true,"dispatch":true,"integrations":true,"autopilot":false}'::jsonb,20),
 ('360','360',19990,199900,null,10,null,2000,'{"direct_store":true,"kds":true,"crm":"brand","loyalty":true,"scheduled_orders":true,"dispatch":true,"integrations":true,"autopilot":true,"api_webhooks":true}'::jsonb,30)
on conflict(plan_key) do update set
 display_name=excluded.display_name,monthly_cents=excluded.monthly_cents,annual_cents=excluded.annual_cents,
 online_order_limit=excluded.online_order_limit,brand_limit=excluded.brand_limit,driver_limit=excluded.driver_limit,
 route_quota=excluded.route_quota,features_json=excluded.features_json,active=true,sort_order=excluded.sort_order,updated_at=now();

create table if not exists public.delivery_settings (
  business_id bigint primary key references public.businesses(id) on delete cascade,
  scheduled_orders_enabled boolean not null default true,
  auto_accept_direct_orders boolean not null default false,
  route_provider varchar(24) not null default 'manual' check (route_provider in ('manual','google','mapbox','external')),
  route_optimization_enabled boolean not null default false,
  customer_tracking_enabled boolean not null default false,
  whatsapp_status_updates boolean not null default false,
  brand_crm_isolation boolean not null default true,
  prep_target_min integer not null default 25 check (prep_target_min between 5 and 240),
  default_eta_min integer not null default 45 check (default_eta_min between 10 and 360),
  sla_warning_minutes integer not null default 10 check (sla_warning_minutes between 1 and 120),
  max_scheduled_days integer not null default 7 check (max_scheduled_days between 0 and 60),
  updated_by_user_id bigint references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists ix_delivery_settings_updated_by on public.delivery_settings(updated_by_user_id) where updated_by_user_id is not null;

alter table public.delivery_zones
  add column if not exists center_lat numeric(9,6),
  add column if not exists center_lng numeric(9,6),
  add column if not exists radius_km numeric(7,2),
  add column if not exists free_delivery_over_cents integer not null default 0 check (free_delivery_over_cents >= 0);

alter table public.deliveries
  add column if not exists address_line varchar(300),
  add column if not exists neighborhood varchar(120),
  add column if not exists postal_code varchar(20),
  add column if not exists address_reference varchar(220),
  add column if not exists latitude numeric(9,6),
  add column if not exists longitude numeric(9,6),
  add column if not exists scheduled_for timestamptz,
  add column if not exists ready_at timestamptz,
  add column if not exists tracking_enabled boolean not null default false;
create index if not exists ix_deliveries_business_scheduled on public.deliveries(business_id,scheduled_for) where scheduled_for is not null;

create table if not exists public.customer_brand_profiles (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id) on delete cascade,
  brand_id bigint not null references public.brands(id) on delete cascade,
  customer_id bigint not null references public.customers(id) on delete cascade,
  consent_marketing boolean not null default false,
  opted_out_at timestamptz,
  first_order_at timestamptz,
  last_order_at timestamptz,
  order_count integer not null default 0 check (order_count >= 0),
  paid_order_count integer not null default 0 check (paid_order_count >= 0),
  revenue_cents bigint not null default 0,
  contribution_cents bigint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(business_id,brand_id,customer_id)
);
create index if not exists ix_customer_brand_profiles_brand_last on public.customer_brand_profiles(business_id,brand_id,last_order_at desc);
create index if not exists ix_customer_brand_profiles_customer on public.customer_brand_profiles(customer_id);

create table if not exists public.delivery_route_batches (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id) on delete cascade,
  zone_id bigint references public.delivery_zones(id) on delete set null,
  driver_id bigint references public.delivery_drivers(id) on delete set null,
  provider varchar(24) not null default 'manual' check (provider in ('manual','google','mapbox','external')),
  external_route_ref varchar(220),
  status varchar(24) not null default 'draft' check (status in ('draft','ready','dispatched','completed','cancelled')),
  distance_meters integer check (distance_meters is null or distance_meters >= 0),
  duration_seconds integer check (duration_seconds is null or duration_seconds >= 0),
  started_at timestamptz,
  completed_at timestamptz,
  version integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists ix_route_batches_business_status on public.delivery_route_batches(business_id,status,created_at desc);
create index if not exists ix_route_batches_driver on public.delivery_route_batches(driver_id,status) where driver_id is not null;

create table if not exists public.delivery_route_stops (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id) on delete cascade,
  route_batch_id bigint not null references public.delivery_route_batches(id) on delete cascade,
  delivery_id bigint not null references public.deliveries(id) on delete cascade,
  stop_order integer not null check (stop_order >= 1),
  status varchar(24) not null default 'pending' check (status in ('pending','arrived','completed','failed','skipped')),
  eta_at timestamptz,
  arrived_at timestamptz,
  completed_at timestamptz,
  address_snapshot varchar(300),
  latitude numeric(9,6),
  longitude numeric(9,6),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(route_batch_id,delivery_id),
  unique(route_batch_id,stop_order)
);
create index if not exists ix_route_stops_delivery on public.delivery_route_stops(delivery_id);

create table if not exists public.delivery_driver_ledger (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id) on delete cascade,
  driver_id bigint not null references public.delivery_drivers(id) on delete cascade,
  delivery_id bigint references public.deliveries(id) on delete set null,
  entry_type varchar(24) not null check (entry_type in ('delivery_fee','adjustment','payment')),
  amount_cents integer not null,
  note varchar(300) not null default '',
  created_by_user_id bigint references public.users(id) on delete set null,
  created_at timestamptz not null default now()
);
create index if not exists ix_driver_ledger_business_driver_created on public.delivery_driver_ledger(business_id,driver_id,created_at desc);
create index if not exists ix_driver_ledger_delivery on public.delivery_driver_ledger(delivery_id) where delivery_id is not null;
create index if not exists ix_driver_ledger_created_by on public.delivery_driver_ledger(created_by_user_id) where created_by_user_id is not null;

alter table public.commercial_plans enable row level security;
alter table public.delivery_settings enable row level security;
alter table public.customer_brand_profiles enable row level security;
alter table public.delivery_route_batches enable row level security;
alter table public.delivery_route_stops enable row level security;
alter table public.delivery_driver_ledger enable row level security;

do $$
declare role_name text; table_name text; seq_name text;
begin
  foreach role_name in array array['anon','authenticated'] loop
    if exists(select 1 from pg_roles where rolname=role_name) then
      foreach table_name in array array['commercial_plans','delivery_settings','customer_brand_profiles','delivery_route_batches','delivery_route_stops','delivery_driver_ledger'] loop
        execute format('revoke all privileges on table public.%I from %I',table_name,role_name);
      end loop;
      foreach seq_name in array array['customer_brand_profiles_id_seq','delivery_route_batches_id_seq','delivery_route_stops_id_seq','delivery_driver_ledger_id_seq'] loop
        if to_regclass('public.'||seq_name) is not null then execute format('revoke all privileges on sequence public.%I from %I',seq_name,role_name); end if;
      end loop;
    end if;
  end loop;
end $$;

drop trigger if exists trg_commercial_plans_updated_at on public.commercial_plans;
create trigger trg_commercial_plans_updated_at before update on public.commercial_plans for each row execute function public.touch_updated_at();
drop trigger if exists trg_delivery_settings_updated_at on public.delivery_settings;
create trigger trg_delivery_settings_updated_at before update on public.delivery_settings for each row execute function public.touch_updated_at();
drop trigger if exists trg_customer_brand_profiles_updated_at on public.customer_brand_profiles;
create trigger trg_customer_brand_profiles_updated_at before update on public.customer_brand_profiles for each row execute function public.touch_updated_at();
drop trigger if exists trg_route_batches_updated_at on public.delivery_route_batches;
create trigger trg_route_batches_updated_at before update on public.delivery_route_batches for each row execute function public.touch_updated_at();
drop trigger if exists trg_route_stops_updated_at on public.delivery_route_stops;
create trigger trg_route_stops_updated_at before update on public.delivery_route_stops for each row execute function public.touch_updated_at();

create or replace function public.c360_sync_customer_brand_profile() returns trigger
language plpgsql security definer set search_path=public as $$
declare paid_delta integer:=0; revenue_delta bigint:=0; contribution_delta bigint:=0;
begin
  if tg_op='INSERT' then
    if new.customer_id is null or new.brand_id is null then return new; end if;
    insert into public.customer_brand_profiles(business_id,brand_id,customer_id,first_order_at,last_order_at,order_count,paid_order_count,revenue_cents,contribution_cents)
    values(new.business_id,new.brand_id,new.customer_id,new.created_at,new.created_at,1,case when new.paid then 1 else 0 end,case when new.paid then new.total_cents else 0 end,case when new.paid then new.contribution_cents else 0 end)
    on conflict(business_id,brand_id,customer_id) do update set
      first_order_at=coalesce(public.customer_brand_profiles.first_order_at,excluded.first_order_at),
      last_order_at=greatest(coalesce(public.customer_brand_profiles.last_order_at,excluded.last_order_at),excluded.last_order_at),
      order_count=public.customer_brand_profiles.order_count+1,
      paid_order_count=public.customer_brand_profiles.paid_order_count+excluded.paid_order_count,
      revenue_cents=public.customer_brand_profiles.revenue_cents+excluded.revenue_cents,
      contribution_cents=public.customer_brand_profiles.contribution_cents+excluded.contribution_cents;
    return new;
  end if;

  if old.customer_id is distinct from new.customer_id or old.brand_id is distinct from new.brand_id then return new; end if;
  if new.customer_id is null or new.brand_id is null then return new; end if;
  if coalesce(old.paid,false)=false and coalesce(new.paid,false)=true then
    paid_delta:=1; revenue_delta:=new.total_cents; contribution_delta:=new.contribution_cents;
  elsif coalesce(old.paid,false)=true and coalesce(new.paid,false)=false then
    paid_delta:=-1; revenue_delta:=-old.total_cents; contribution_delta:=-old.contribution_cents;
  elsif coalesce(new.paid,false)=true then
    revenue_delta:=new.total_cents-old.total_cents; contribution_delta:=new.contribution_cents-old.contribution_cents;
  end if;
  if paid_delta<>0 or revenue_delta<>0 or contribution_delta<>0 then
    update public.customer_brand_profiles set
      paid_order_count=greatest(0,paid_order_count+paid_delta),
      revenue_cents=revenue_cents+revenue_delta,
      contribution_cents=contribution_cents+contribution_delta,
      last_order_at=greatest(coalesce(last_order_at,new.updated_at),new.updated_at)
    where business_id=new.business_id and brand_id=new.brand_id and customer_id=new.customer_id;
  end if;
  return new;
end $$;

revoke all on function public.c360_sync_customer_brand_profile() from public;
do $$ begin
  if exists(select 1 from pg_roles where rolname='anon') then revoke all on function public.c360_sync_customer_brand_profile() from anon; end if;
  if exists(select 1 from pg_roles where rolname='authenticated') then revoke all on function public.c360_sync_customer_brand_profile() from authenticated; end if;
end $$;

drop trigger if exists trg_orders_customer_brand_profile_insert on public.orders;
create trigger trg_orders_customer_brand_profile_insert after insert on public.orders for each row execute function public.c360_sync_customer_brand_profile();
drop trigger if exists trg_orders_customer_brand_profile_update on public.orders;
create trigger trg_orders_customer_brand_profile_update after update of paid,total_cents,contribution_cents on public.orders for each row execute function public.c360_sync_customer_brand_profile();

commit;
