begin;

create table if not exists public.brands (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id) on delete cascade,
  name varchar(120) not null,
  active boolean not null default true,
  soft_deleted boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists uq_brands_business_name_active
  on public.brands(business_id, lower(name))
  where soft_deleted = false;
create index if not exists ix_brands_business on public.brands(business_id);

alter table public.products
  add column if not exists brand_id bigint references public.brands(id) on delete set null;
create index if not exists ix_products_brand on public.products(brand_id);

alter table public.orders
  add column if not exists brand_id bigint references public.brands(id) on delete set null;
create index if not exists ix_orders_brand on public.orders(brand_id);

create unique index if not exists uq_channels_business_name
  on public.channels(business_id, lower(name));

-- Keep the server-only PostgREST posture used by the rest of the schema.
alter table public.brands enable row level security;
do $$
begin
  if exists(select 1 from pg_roles where rolname='anon') then
    execute 'revoke all privileges on table public.brands from anon';
    execute 'revoke all privileges on sequence public.brands_id_seq from anon';
  end if;
  if exists(select 1 from pg_roles where rolname='authenticated') then
    execute 'revoke all privileges on table public.brands from authenticated';
    execute 'revoke all privileges on sequence public.brands_id_seq from authenticated';
  end if;
end $$;

drop trigger if exists trg_brands_updated_at on public.brands;
create trigger trg_brands_updated_at
before update on public.brands
for each row execute function public.touch_updated_at();

-- Preserve the public RPC signature while deriving a single brand for the order
-- whenever every product in the order belongs to the same brand. Mixed-brand
-- baskets stay brand_id = null and remain fully traceable at item level.
create or replace function public.c360_create_order(
  p_business_id bigint,
  p_source text,
  p_paid boolean,
  p_customer_id bigint,
  p_channel_id bigint,
  p_items jsonb,
  p_idempotency_key text
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_existing public.orders%rowtype;
  v_order public.orders%rowtype;
  v_item jsonb;
  v_total integer := 0;
  v_cost integer := 0;
  v_qty integer;
  v_price integer;
  v_unit_cost integer;
  v_brand_id bigint;
  v_distinct_brands integer := 0;
begin
  if p_idempotency_key is not null and length(p_idempotency_key) > 0 then
    perform pg_advisory_xact_lock(hashtextextended(p_business_id::text || ':' || p_idempotency_key, 0));
    select * into v_existing
      from public.orders
     where business_id = p_business_id
       and idempotency_key = p_idempotency_key
     limit 1;
    if found then
      return jsonb_build_object(
        'id',v_existing.id,
        'version',v_existing.version,
        'brand_id',v_existing.brand_id,
        'idempotent_replay',true
      );
    end if;
  end if;

  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'ORDER_ITEMS_REQUIRED';
  end if;

  for v_item in select * from jsonb_array_elements(p_items)
  loop
    if not exists(
      select 1 from public.products
       where id = (v_item->>'product_id')::bigint
         and business_id = p_business_id
         and soft_deleted = false
    ) then
      raise exception 'PRODUCT_NOT_FOUND';
    end if;
    v_qty := greatest(coalesce((v_item->>'quantity')::integer,1),1);
    v_price := greatest(coalesce((v_item->>'unit_price_cents')::integer,0),0);
    v_unit_cost := greatest(coalesce((v_item->>'unit_variable_cost_cents')::integer,0),0);
    v_total := v_total + v_qty * v_price;
    v_cost := v_cost + v_qty * v_unit_cost;
  end loop;

  select count(distinct p.brand_id), min(p.brand_id)
    into v_distinct_brands, v_brand_id
    from jsonb_array_elements(p_items) x
    join public.products p on p.id = (x->>'product_id')::bigint
   where p.brand_id is not null;

  if v_distinct_brands <> 1 then
    v_brand_id := null;
  end if;

  -- A basket with branded + unbranded products is mixed and should not inherit a brand.
  if exists(
    select 1
      from jsonb_array_elements(p_items) x
      join public.products p on p.id = (x->>'product_id')::bigint
     where p.brand_id is null
  ) then
    v_brand_id := null;
  end if;

  insert into public.orders(
    business_id,customer_id,channel_id,brand_id,status,source,total_cents,
    variable_cost_cents,contribution_cents,paid,idempotency_key
  ) values (
    p_business_id,p_customer_id,p_channel_id,v_brand_id,'new',coalesce(nullif(p_source,''),'manual'),
    v_total,v_cost,v_total-v_cost,coalesce(p_paid,false),nullif(p_idempotency_key,'')
  ) returning * into v_order;

  for v_item in select * from jsonb_array_elements(p_items)
  loop
    insert into public.order_items(
      business_id,order_id,product_id,quantity,unit_price_cents,unit_variable_cost_cents
    ) values (
      p_business_id,
      v_order.id,
      (v_item->>'product_id')::bigint,
      greatest(coalesce((v_item->>'quantity')::integer,1),1),
      greatest(coalesce((v_item->>'unit_price_cents')::integer,0),0),
      greatest(coalesce((v_item->>'unit_variable_cost_cents')::integer,0),0)
    );
  end loop;

  insert into public.outbox_events(business_id,topic,payload_json)
  values(
    p_business_id,
    'order.created',
    jsonb_build_object('order_id',v_order.id,'brand_id',v_order.brand_id,'channel_id',v_order.channel_id)::text
  );

  return jsonb_build_object(
    'id',v_order.id,
    'version',v_order.version,
    'brand_id',v_order.brand_id,
    'channel_id',v_order.channel_id,
    'total_cents',v_total,
    'variable_cost_cents',v_cost,
    'contribution_cents',v_total-v_cost,
    'idempotent_replay',false
  );
end;
$$;

revoke all on function public.c360_create_order(bigint,text,boolean,bigint,bigint,jsonb,text) from public;
do $$
begin
  if exists(select 1 from pg_roles where rolname='anon') then
    execute 'revoke all on function public.c360_create_order(bigint,text,boolean,bigint,bigint,jsonb,text) from anon';
  end if;
  if exists(select 1 from pg_roles where rolname='authenticated') then
    execute 'revoke all on function public.c360_create_order(bigint,text,boolean,bigint,bigint,jsonb,text) from authenticated';
  end if;
  if exists(select 1 from pg_roles where rolname='service_role') then
    execute 'grant execute on function public.c360_create_order(bigint,text,boolean,bigint,bigint,jsonb,text) to service_role';
  end if;
end $$;

commit;
