begin;

alter table public.delivery_settings
  add column if not exists route_mode varchar(24) not null default 'manual';

do $$ begin
  if not exists (
    select 1 from pg_constraint
    where conname='ck_delivery_settings_route_mode'
      and conrelid='public.delivery_settings'::regclass
  ) then
    alter table public.delivery_settings
      add constraint ck_delivery_settings_route_mode
      check (route_mode in ('manual','assisted','intelligent'));
  end if;
end $$;

create table if not exists public.brand_integration_bindings (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id) on delete cascade,
  brand_id bigint not null references public.brands(id) on delete cascade,
  connection_id bigint not null references public.integration_connections(id) on delete cascade,
  channel_id bigint references public.channels(id) on delete set null,
  provider varchar(40) not null,
  external_store_ref varchar(180),
  order_import_enabled boolean not null default true,
  menu_sync_enabled boolean not null default false,
  price_sync_enabled boolean not null default false,
  availability_sync_enabled boolean not null default false,
  auto_accept_orders boolean not null default false,
  active boolean not null default true,
  last_sync_at timestamptz,
  last_success_at timestamptz,
  last_error_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(business_id,brand_id,provider)
);
create index if not exists ix_brand_integration_bindings_connection
  on public.brand_integration_bindings(connection_id);
create index if not exists ix_brand_integration_bindings_business_active
  on public.brand_integration_bindings(business_id,active,provider);
create index if not exists ix_brand_integration_bindings_channel
  on public.brand_integration_bindings(channel_id) where channel_id is not null;

create table if not exists public.brand_fiscal_profiles (
  brand_id bigint primary key references public.brands(id) on delete cascade,
  business_id bigint not null references public.businesses(id) on delete cascade,
  legal_name varchar(180),
  tax_id varchar(20),
  state_registration varchar(40),
  municipal_registration varchar(40),
  tax_regime varchar(24) not null default 'unconfigured'
    check (tax_regime in ('unconfigured','mei','simples','presumed','real','other')),
  fiscal_provider varchar(40),
  provider_profile_ref varchar(180),
  issuance_enabled boolean not null default false,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists ix_brand_fiscal_profiles_business
  on public.brand_fiscal_profiles(business_id,active);
create index if not exists ix_brand_fiscal_profiles_tax_id
  on public.brand_fiscal_profiles(business_id,tax_id) where tax_id is not null;

alter table public.brand_integration_bindings enable row level security;
alter table public.brand_fiscal_profiles enable row level security;

do $$
declare role_name text; seq_name text;
begin
  foreach role_name in array array['anon','authenticated'] loop
    if exists(select 1 from pg_roles where rolname=role_name) then
      execute format('revoke all privileges on table public.brand_integration_bindings from %I',role_name);
      execute format('revoke all privileges on table public.brand_fiscal_profiles from %I',role_name);
      seq_name := 'brand_integration_bindings_id_seq';
      if to_regclass('public.'||seq_name) is not null then
        execute format('revoke all privileges on sequence public.%I from %I',seq_name,role_name);
      end if;
    end if;
  end loop;
end $$;

drop trigger if exists trg_brand_integration_bindings_updated_at on public.brand_integration_bindings;
create trigger trg_brand_integration_bindings_updated_at
before update on public.brand_integration_bindings
for each row execute function public.touch_updated_at();

drop trigger if exists trg_brand_fiscal_profiles_updated_at on public.brand_fiscal_profiles;
create trigger trg_brand_fiscal_profiles_updated_at
before update on public.brand_fiscal_profiles
for each row execute function public.touch_updated_at();

create or replace function public.c360_validate_brand_integration_binding()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
declare
  v_brand_business bigint;
  v_connection_business bigint;
  v_connection_provider text;
  v_channel_business bigint;
begin
  select business_id into v_brand_business from public.brands where id=new.brand_id and soft_deleted=false;
  if v_brand_business is null or v_brand_business<>new.business_id then
    raise exception 'BRAND_BUSINESS_MISMATCH';
  end if;

  select business_id,provider into v_connection_business,v_connection_provider
    from public.integration_connections where id=new.connection_id;
  if v_connection_business is null or v_connection_business<>new.business_id then
    raise exception 'CONNECTION_BUSINESS_MISMATCH';
  end if;
  if lower(coalesce(v_connection_provider,''))<>lower(coalesce(new.provider,'')) then
    raise exception 'CONNECTION_PROVIDER_MISMATCH';
  end if;

  if new.channel_id is not null then
    select business_id into v_channel_business from public.channels where id=new.channel_id;
    if v_channel_business is null or v_channel_business<>new.business_id then
      raise exception 'CHANNEL_BUSINESS_MISMATCH';
    end if;
  end if;
  return new;
end;
$$;

create or replace function public.c360_validate_brand_fiscal_profile()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
declare v_brand_business bigint;
begin
  select business_id into v_brand_business from public.brands where id=new.brand_id and soft_deleted=false;
  if v_brand_business is null or v_brand_business<>new.business_id then
    raise exception 'BRAND_BUSINESS_MISMATCH';
  end if;
  if new.issuance_enabled and (nullif(trim(coalesce(new.fiscal_provider,'')),'') is null or nullif(trim(coalesce(new.provider_profile_ref,'')),'') is null) then
    raise exception 'FISCAL_PROVIDER_REQUIRED';
  end if;
  return new;
end;
$$;

revoke all on function public.c360_validate_brand_integration_binding() from public;
revoke all on function public.c360_validate_brand_fiscal_profile() from public;

drop trigger if exists trg_validate_brand_integration_binding on public.brand_integration_bindings;
create trigger trg_validate_brand_integration_binding
before insert or update on public.brand_integration_bindings
for each row execute function public.c360_validate_brand_integration_binding();

drop trigger if exists trg_validate_brand_fiscal_profile on public.brand_fiscal_profiles;
create trigger trg_validate_brand_fiscal_profile
before insert or update on public.brand_fiscal_profiles
for each row execute function public.c360_validate_brand_fiscal_profile();

commit;
