begin;

create table if not exists user_security_states (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  email_verified_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_user_security_state_user unique(user_id)
);

create index if not exists ix_user_security_states_user on user_security_states(user_id);

create table if not exists auth_action_tokens (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  purpose varchar(40) not null,
  token_hash varchar(64) not null,
  expires_at timestamptz not null,
  used_at timestamptz null,
  revoked_at timestamptz null,
  created_at timestamptz not null default now(),
  constraint uq_auth_action_token_hash unique(token_hash)
);

create index if not exists ix_auth_action_tokens_user on auth_action_tokens(user_id);
create index if not exists ix_auth_action_tokens_purpose on auth_action_tokens(purpose);
create index if not exists ix_auth_action_tokens_token_hash on auth_action_tokens(token_hash);
create index if not exists ix_auth_action_tokens_user_purpose_created on auth_action_tokens(user_id, purpose, created_at desc);
create index if not exists ix_auth_action_tokens_purpose_expires on auth_action_tokens(purpose, expires_at);

alter table user_security_states enable row level security;
alter table auth_action_tokens enable row level security;

do $$
begin
  if exists (select 1 from pg_roles where rolname = 'anon') then
    revoke all privileges on table user_security_states from anon;
    revoke all privileges on table auth_action_tokens from anon;
  end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then
    revoke all privileges on table user_security_states from authenticated;
    revoke all privileges on table auth_action_tokens from authenticated;
  end if;
end $$;

commit;
