begin;

create table if not exists public.business_memories (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id) on delete cascade,
  namespace varchar(48) not null,
  data_json text not null default '{}',
  version integer not null default 1 check (version >= 1),
  updated_by_user_id bigint references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_business_memory_namespace unique (business_id, namespace)
);

create index if not exists ix_business_memories_business_updated
  on public.business_memories (business_id, updated_at desc);

create table if not exists public.business_memory_revisions (
  id bigint generated by default as identity primary key,
  memory_id bigint not null references public.business_memories(id) on delete cascade,
  business_id bigint not null references public.businesses(id) on delete cascade,
  namespace varchar(48) not null,
  version integer not null check (version >= 1),
  data_json text not null,
  actor_user_id bigint references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint uq_business_memory_revision_version unique (memory_id, version)
);

create index if not exists ix_business_memory_revisions_business_namespace
  on public.business_memory_revisions (business_id, namespace, version desc);

create or replace function public.touch_business_memory_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_business_memories_touch on public.business_memories;
create trigger trg_business_memories_touch
before update on public.business_memories
for each row execute function public.touch_business_memory_updated_at();

alter table public.business_memories enable row level security;
alter table public.business_memory_revisions enable row level security;

DO $$
DECLARE
  has_anon boolean := exists(select 1 from pg_roles where rolname='anon');
  has_authenticated boolean := exists(select 1 from pg_roles where rolname='authenticated');
BEGIN
  IF has_anon THEN
    revoke all privileges on table public.business_memories from anon;
    revoke all privileges on table public.business_memory_revisions from anon;
    revoke all privileges on all sequences in schema public from anon;
  END IF;
  IF has_authenticated THEN
    revoke all privileges on table public.business_memories from authenticated;
    revoke all privileges on table public.business_memory_revisions from authenticated;
    revoke all privileges on all sequences in schema public from authenticated;
  END IF;
END $$;

commit;
